(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var n=ca(this);function p(a,b){if(b)a:{var c=n;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
p("Symbol",function(a){function b(k){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(k||"")+"_"+e++,k)}function c(k,g){this.g=k;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
p("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=n[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});function da(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function r(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ea="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var ka=fa;function la(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.I=b.prototype}function ma(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function na(){this.m=!1;this.j=null;this.u=void 0;this.g=1;this.l=this.i=0;this.o=this.h=null}
function oa(a){if(a.m)throw new TypeError("Generator is already running");a.m=!0}f=na.prototype;f.K=function(a){this.u=a};function pa(a,b){a.h={R:b,S:!0};a.g=a.i||a.l}f.return=function(a){this.h={return:a};this.g=this.l};f.Ed=function(a){this.h={D:a};this.g=this.l};function qa(a,b,c){a.g=c;return{value:b}}f.rf=function(a,b){a=r(a);var c=a.next();ma(c);if(c.done)this.u=c.value,this.g=b;else return this.j=a,qa(this,c.value,b)};f.D=function(a){this.g=a};f.Fd=function(){this.g=0};
f.Td=function(a){this.i=0;this.l=a||0};function ra(a,b){a.g=b;a.i=0}function sa(a){a.i=0;var b=a.h.R;a.h=null;return b}f.Ic=function(a,b,c){c?this.o[c]=this.h:this.o=[this.h];this.i=a||0;this.l=b||0};f.Gd=function(a,b){b=this.o.splice(b||0)[0];(b=this.h=this.h||b)?b.S?this.g=this.i||this.l:void 0!=b.D&&this.l<b.D?(this.g=b.D,this.h=null):this.g=this.l:this.g=a};f.Lc=function(a){return new ta(a)};function ta(a){this.h=a;this.g=[];for(var b in a)this.g.push(b);this.g.reverse()}
ta.prototype.i=function(){for(;0<this.g.length;){var a=this.g.pop();if(a in this.h)return a}return null};function ua(a){this.g=new na;this.h=a}function va(a,b){oa(a.g);var c=a.g.j;if(c)return wa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return xa(a)}function wa(a,b,c,d){try{var e=b.call(a.g.j,c);ma(e);if(!e.done)return a.g.m=!1,e;var k=e.value}catch(g){return a.g.j=null,pa(a.g,g),xa(a)}a.g.j=null;d.call(a.g,k);return xa(a)}
function xa(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.m=!1,{value:b.value,done:!1}}catch(c){a.g.u=void 0,pa(a.g,c)}a.g.m=!1;if(a.g.h){b=a.g.h;a.g.h=null;if(b.S)throw b.R;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ya(a){this.next=function(b){oa(a.g);a.g.j?b=wa(a,a.g.j.next,b,a.g.K):(a.g.K(b),b=xa(a));return b};this.throw=function(b){oa(a.g);a.g.j?b=wa(a,a.g.j["throw"],b,a.g.K):(pa(a.g,b),b=xa(a));return b};this.return=function(b){return va(a,b)};this[Symbol.iterator]=function(){return this}}function za(a,b){b=new ya(new ua(b));ka&&a.prototype&&ka(b,a.prototype);return b}function t(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
p("WeakMap",function(a){function b(l){this.g=(h+=Math.random()+1).toString();if(l){l=r(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function e(l){if(!t(l,g)){var m=new c;ba(l,g,{value:m})}}function k(l){var m=Object[l];m&&(Object[l]=function(q){if(q instanceof c)return q;Object.isExtensible(q)&&e(q);return m(q)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),
q=new a([[l,2],[m,3]]);if(2!=q.get(l)||3!=q.get(m))return!1;q.delete(l);q.set(m,4);return!q.has(l)&&4==q.get(m)}catch(u){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();k("freeze");k("preventExtensions");k("seal");var h=0;b.prototype.set=function(l,m){if(!d(l))throw Error("Invalid WeakMap key");e(l);if(!t(l,g))throw Error("WeakMap key fail: "+l);l[g][this.g]=m;return this};b.prototype.get=function(l){return d(l)&&t(l,g)?l[g][this.g]:void 0};b.prototype.has=function(l){return d(l)&&t(l,
g)&&t(l[g],this.g)};b.prototype.delete=function(l){return d(l)&&t(l,g)&&t(l[g],this.g)?delete l[g][this.g]:!1};return b});
p("Map",function(a){function b(){var h={};return h.B=h.next=h.head=h}function c(h,l){var m=h.g;return da(function(){if(m){for(;m.head!=h.g;)m=m.B;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})}function d(h,l){var m=l&&typeof l;"object"==m||"function"==m?k.has(l)?m=k.get(l):(m=""+ ++g,k.set(l,m)):m="p_"+l;var q=h.h[m];if(q&&t(h.h,m))for(h=0;h<q.length;h++){var u=q[h];if(l!==l&&u.key!==u.key||l===u.key)return{id:m,list:q,index:h,v:u}}return{id:m,list:q,
index:-1,v:void 0}}function e(h){this.h={};this.g=b();this.size=0;if(h){h=r(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),l=new a(r([[h,"s"]]));if("s"!=l.get(h)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),q=m.next();if(q.done||q.value[0]!=h||"s"!=q.value[1])return!1;q=m.next();return q.done||4!=q.value[0].x||
"t"!=q.value[1]||!m.next().done?!1:!0}catch(u){return!1}}())return a;var k=new WeakMap;e.prototype.set=function(h,l){h=0===h?0:h;var m=d(this,h);m.list||(m.list=this.h[m.id]=[]);m.v?m.v.value=l:(m.v={next:this.g,B:this.g.B,head:this.g,key:h,value:l},m.list.push(m.v),this.g.B.next=m.v,this.g.B=m.v,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.v&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.h[h.id],h.v.B.next=h.v.next,h.v.next.B=h.v.B,h.v.head=null,this.size--,
!0):!1};e.prototype.clear=function(){this.h={};this.g=this.g.B=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).v};e.prototype.get=function(h){return(h=d(this,h).v)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,l){for(var m=this.entries(),q;!(q=m.next()).done;)q=q.value,
h.call(l,q[1],q[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});function Aa(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
p("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=Aa(this,b,"endsWith");void 0===c&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;0<e&&0<c;)if(d[--c]!=b[--e])return!1;return 0>=e}});function Ba(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var k=c++;return{value:b(k,a[k]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}
p("Array.prototype.entries",function(a){return a?a:function(){return Ba(this,function(b,c){return[b,c]})}});
p("Promise",function(a){function b(g){this.h=0;this.i=void 0;this.g=[];this.o=!1;var h=this.j();try{g(h.resolve,h.reject)}catch(l){h.reject(l)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.h=function(g){if(null==this.g){this.g=[];var h=this;this.i(function(){h.l()})}this.g.push(g)};var e=n.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var l=
g[h];g[h]=null;try{l()}catch(m){this.j(m)}}}this.g=null};c.prototype.j=function(g){this.i(function(){throw g;})};b.prototype.j=function(){function g(m){return function(q){l||(l=!0,m.call(h,q))}}var h=this,l=!1;return{resolve:g(this.O),reject:g(this.l)}};b.prototype.O=function(g){if(g===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.T(g);else{a:switch(typeof g){case "object":var h=null!=g;break a;case "function":h=!0;break a;default:h=!1}h?this.J(g):this.m(g)}};
b.prototype.J=function(g){var h=void 0;try{h=g.then}catch(l){this.l(l);return}"function"==typeof h?this.U(h,g):this.m(g)};b.prototype.l=function(g){this.u(2,g)};b.prototype.m=function(g){this.u(1,g)};b.prototype.u=function(g,h){if(0!=this.h)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.h);this.h=g;this.i=h;2===this.h&&this.P();this.F()};b.prototype.P=function(){var g=this;e(function(){if(g.N()){var h=n.console;"undefined"!==typeof h&&h.error(g.i)}},1)};b.prototype.N=
function(){if(this.o)return!1;var g=n.CustomEvent,h=n.Event,l=n.dispatchEvent;if("undefined"===typeof l)return!0;"function"===typeof g?g=new g("unhandledrejection",{cancelable:!0}):"function"===typeof h?g=new h("unhandledrejection",{cancelable:!0}):(g=n.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return l(g)};b.prototype.F=function(){if(null!=this.g){for(var g=0;g<this.g.length;++g)k.h(this.g[g]);this.g=null}};var k=new c;b.prototype.T=
function(g){var h=this.j();g.H(h.resolve,h.reject)};b.prototype.U=function(g,h){var l=this.j();try{g.call(h,l.resolve,l.reject)}catch(m){l.reject(m)}};b.prototype.then=function(g,h){function l(H,K){return"function"==typeof H?function($a){try{m(H($a))}catch(ab){q(ab)}}:K}var m,q,u=new b(function(H,K){m=H;q=K});this.H(l(g,m),l(h,q));return u};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.H=function(g,h){function l(){switch(m.h){case 1:g(m.i);break;case 2:h(m.i);break;default:throw Error("Unexpected state: "+
m.h);}}var m=this;null==this.g?k.h(l):this.g.push(l);this.o=!0};b.resolve=d;b.reject=function(g){return new b(function(h,l){l(g)})};b.race=function(g){return new b(function(h,l){for(var m=r(g),q=m.next();!q.done;q=m.next())d(q.value).H(h,l)})};b.all=function(g){var h=r(g),l=h.next();return l.done?d([]):new b(function(m,q){function u($a){return function(ab){H[$a]=ab;K--;0==K&&m(H)}}var H=[],K=0;do H.push(void 0),K++,d(l.value).H(u(H.length-1),q),l=h.next();while(!l.done)})};return b});
p("Array.prototype.keys",function(a){return a?a:function(){return Ba(this,function(b){return b})}});p("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],k="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof k){b=k.call(b);for(var g=0;!(k=b.next()).done;)e.push(c.call(d,k.value,g++))}else for(k=b.length,g=0;g<k;g++)e.push(c.call(d,b[g],g));return e}});
p("Array.prototype.values",function(a){return a?a:function(){return Ba(this,function(b,c){return c})}});p("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});p("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var k=d[c];if(k===b||Object.is(k,b))return!0}return!1}});
p("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==Aa(this,b,"includes").indexOf(b,c||0)}});var v=this||self;function Ca(){}function Da(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length}function Ea(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}
function w(a,b){a=a.split(".");var c=v;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}function Fa(a,b){function c(){}c.prototype=b.prototype;a.I=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.zc=function(d,e,k){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}}function Ga(a){return a};var x=new Map([]);x.set("devsite-a11y-announce",{src:"/js/devsite_devsite_a11y_announce_module.js"});x.set("devsite-analytics",{src:"/js/devsite_devsite_analytics_module.js"});x.set("devsite-analytics-scope",{src:"/js/devsite_devsite_analytics_scope_module.js"});x.set("devsite-anselm",{src:"/js/devsite_devsite_anselm_module.js"});x.set("devsite-api-getstarted",{src:"/js/devsite_devsite_api_getstarted_module.js"});x.set("devsite-apix",{src:"/js/devsite_devsite_apix_module.js"});
x.set("devsite-apix-index",{src:"/js/devsite_devsite_apix_index_module.js"});x.set("devsite-apix-snippets",{src:"/js/devsite_devsite_apix_snippets_module.js"});x.set("devsite-badger",{src:"/js/devsite_devsite_badger_module.js"});x.set("devsite-badge-awarded",{src:"/js/devsite_devsite_badge_awarded_module.js"});x.set("devsite-badge-awarder",{src:"/js/devsite_devsite_badge_awarder_module.js"});x.set("devsite-badge-redeemer",{src:"/js/devsite_devsite_badge_redeemer_module.js"});
x.set("devsite-book-nav",{src:"/js/devsite_devsite_book_nav_module.js"});x.set("devsite-bookmark",{src:"/js/devsite_devsite_bookmark_module.js"});x.set("devsite-chart",{src:"/js/devsite_devsite_chart_module.js"});x.set("devsite-catalog",{src:"/js/devsite_devsite_catalog_module.js"});x.set("devsite-code",{src:"/js/devsite_devsite_code_module.js"});x.set("devsite-content",{src:"/js/devsite_devsite_content_module.js"});x.set("devsite-codelab-catalog",{src:"/js/devsite_devsite_codelab_catalog_module.js"});
x.set("devsite-product-catalog",{src:"/js/devsite_devsite_product_catalog_module.js"});x.set("devsite-credentials-dialog",{src:"/js/devsite_devsite_credentials_dialog_module.js"});x.set("devsite-cse",{src:"/js/devsite_devsite_cse_module.js"});x.set("devsite-panel",{src:"/js/devsite_devsite_panel_module.js"});x.set("devsite-device",{src:"/js/devsite_devsite_device_module.js"});x.set("devsite-devprofile",{src:"/js/devsite_devsite_devprofile_module.js"});x.set("devsite-dialog",{src:"/js/devsite_devsite_dialog_module.js"});
x.set("devsite-dynamic-content",{src:"/js/devsite_devsite_dynamic_content_module.js"});x.set("devsite-expandable",{src:"/js/devsite_devsite_expandable_module.js"});x.set("devsite-expandable-nav",{src:"/js/devsite_devsite_expandable_nav_module.js"});x.set("devsite-extradory",{src:"/js/devsite_devsite_extradory_module.js"});x.set("devsite-feedback",{src:"/js/devsite_devsite_feedback_module.js"});x.set("devsite-filter",{src:"/js/devsite_devsite_filter_module.js"});x.set("devsite-footer-linkboxes",{src:"/js/devsite_devsite_footer_linkboxes_module.js"});
x.set("devsite-footer-promos",{src:"/js/devsite_devsite_footer_promos_module.js"});x.set("devsite-footer-utility",{src:"/js/devsite_devsite_footer_utility_module.js"});x.set("devsite-google-survey",{src:"/js/devsite_devsite_google_survey_module.js"});x.set("devsite-googler-buttons",{src:"/js/devsite_devsite_googler_buttons_module.js"});x.set("devsite-hats-survey",{src:"/js/devsite_devsite_hats_survey_module.js"});x.set("devsite-header",{src:"/js/devsite_devsite_header_module.js"});
x.set("devsite-heading-link",{src:"/js/devsite_devsite_heading_link_module.js"});x.set("devsite-iframe",{src:"/js/devsite_devsite_iframe_module.js"});x.set("devsite-jump-to",{src:"/js/devsite_devsite_jump_to_module.js"});x.set("devsite-jsfiddle-button",{src:"/js/devsite_devsite_jsfiddle_button_module.js"});x.set("devsite-language-selector",{src:"/js/devsite_devsite_language_selector_module.js"});x.set("devsite-lightbox",{src:"/js/devsite_devsite_lightbox_module.js"});x.set("devsite-mathjax",{src:"/js/devsite_devsite_mathjax_module.js"});
x.set("devsite-mdc",{src:"/js/devsite_devsite_mdc_module.js"});x.set("devsite-multiple-choice",{src:"/js/devsite_devsite_multiple_choice_module.js"});x.set("devsite-nav-buttons",{src:"/js/devsite_devsite_nav_buttons_module.js"});x.set("devsite-playlist",{src:"/js/devsite_devsite_playlist_module.js"});x.set("devsite-playlist-earnable-badges",{src:"/js/devsite_devsite_playlist_earnable_badges_module.js"});x.set("devsite-playlist-summary",{src:"/js/devsite_devsite_playlist_summary_module.js"});
x.set("devsite-pagination",{src:"/js/devsite_devsite_pagination_module.js"});x.set("devsite-progress",{src:"/js/devsite_devsite_progress_module.js"});x.set("devsite-quiz",{src:"/js/devsite_devsite_quiz_module.js"});x.set("devsite-recommendations",{src:"/js/devsite_devsite_recommendations_module.js"});x.set("devsite-recommendations-dropdown",{src:"/js/devsite_devsite_recommendations_dropdown_module.js"});x.set("devsite-recommendations-sidebar",{src:"/js/devsite_devsite_recommendations_sidebar_module.js"});
x.set("devsite-reference-results",{src:"/js/devsite_devsite_reference_results_module.js"});x.set("devsite-search",{src:"/js/devsite_devsite_search_module.js"});x.set("devsite-select",{src:"/js/devsite_devsite_select_module.js"});x.set("devsite-selector",{src:"/js/devsite_devsite_selector_module.js"});x.set("devsite-shell",{src:"/js/devsite_devsite_shell_module.js"});x.set("devsite-shell-activate-button",{src:"/js/devsite_devsite_shell_activate_button_module.js"});x.set("devsite-sitemask",{src:"/js/devsite_devsite_sitemask_module.js"});
x.set("devsite-snackbar",{src:"/js/devsite_devsite_snackbar_module.js"});x.set("devsite-sort",{src:"/js/devsite_devsite_sort_module.js"});x.set("devsite-spinner",{src:"/js/devsite_devsite_spinner_module.js"});x.set("devsite-support-form",{src:"/js/devsite_devsite_support_form_module.js"});x.set("devsite-tabs",{src:"/js/devsite_devsite_tabs_module.js"});x.set("devsite-theme-selector",{src:"/js/devsite_devsite_theme_selector_module.js"});x.set("devsite-thumb-rating",{src:"/js/devsite_devsite_thumb_rating_module.js"});
x.set("devsite-toc",{src:"/js/devsite_devsite_toc_module.js"});x.set("devsite-topic",{src:"/js/devsite_devsite_topic_module.js"});x.set("devsite-tooltip",{src:"/js/devsite_devsite_tooltip_module.js"});x.set("devsite-tracking-question",{src:"/js/devsite_devsite_tracking_question_module.js"});x.set("devsite-user",{src:"/js/devsite_devsite_user_module.js"});x.set("devsite-var",{src:"/js/devsite_devsite_var_module.js"});x.set("devsite-version-selector",{src:"/js/devsite_devsite_version_selector_module.js"});
x.set("devsite-visibility-analytics",{src:"/js/devsite_devsite_visibility_analytics_module.js"});x.set("devsite-vplus",{src:"/js/devsite_devsite_vplus_module.js"});x.set("devsite-wall-acknowledgement",{src:"/js/devsite_devsite_wall_acknowledgement_module.js"});x.set("devsite-youtube",{src:"/js/devsite_devsite_youtube_module.js"});x.set("google-codelab",{src:"/js/devsite_google_codelab_module.js"});x.set("google-codelab-about",{src:"/js/devsite_google_codelab_about_module.js"});
x.set("google-codelab-analytics",{src:"/js/devsite_google_codelab_analytics_module.js"});x.set("google-codelab-step",{src:"/js/devsite_google_codelab_step_module.js"});x.set("google-codelab-survey",{src:"/js/devsite_google_codelab_survey_module.js"});w("DevsiteAppAuthorizedElements",x);w("DevsiteAppTenantCustomized",!1);var Ha={uc:0,tc:1,$b:6,Yb:8,dc:12,ec:14,fc:17,jc:18,lc:21,nc:25,wa:37,oc:38,Ga:40,eb:45,ma:47,Z:50,ga:52,ea:62,Sa:63,xb:66,pb:70,$:73,jb:74,oa:75,ub:76,Oa:77,Qa:80,fa:81,ab:82,Ma:83,ob:85,qa:87,Ia:89,rb:90,Ja:91,Pa:92,ka:93,rc:94,La:95,ja:96,yb:97,aa:98,ca:99,mc:100,Fa:101,Na:102,tb:103,qc:104,sa:105,la:106,Da:107,ua:108,nb:109,ra:110,Ca:111,pc:112,vb:113,va:114,ia:115,xa:116,bb:117,$a:118,Ka:119,qb:120,bc:121,wb:122,hc:123,Zb:124,Xa:125,kb:126,Ea:127,cc:128,gb:129,hb:130,Aa:131,Wa:132,ba:133,Ta:134,
Ha:135,cb:136,da:137,sc:138,lb:139,ac:140,Xb:141,fb:142,Za:143,mb:144,ha:145,ib:146,Ua:147,Ya:148,sb:149,ta:150,pa:151,Va:152,Ba:153,za:154,na:155,kc:156,ic:157,Ra:158,ya:159};var Ia,Ja="undefined"!==typeof TextEncoder;var Ka=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},La=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,k=0;k<c;k++)k in e&&(d[k]=b.call(void 0,e[k],k,a));return d};function Ma(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};var Na;function Oa(a,b){this.g=b===Pa?a:""}f=Oa.prototype;f.ad=!0;f.Xc=function(){return this.g.toString()};f.$c=!0;f.Pc=function(){return 1};f.Fc=function(a,b){var c=Qa.exec(Ra(this).toString()),d=c[3]||"";return Sa(c[1]+Ta("?",c[2]||"",a)+Ta("#",d,b))};f.toString=function(){return this.g+""};function Ra(a){return a instanceof Oa&&a.constructor===Oa?a.g:"type_error:TrustedResourceUrl"}var Qa=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,Pa={};
function Sa(a){if(void 0===Na){var b=null;var c=v.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:Ga,createScript:Ga,createScriptURL:Ga})}catch(d){v.console&&v.console.error(d.message)}Na=b}else Na=b}a=(b=Na)?b.createScriptURL(a):a;return new Oa(a,Pa)}
function Ta(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c)if(Object.prototype.hasOwnProperty.call(c,d)){var e=c[d];e=Array.isArray(e)?e:[e];for(var k=0;k<e.length;k++){var g=e[k];null!=g&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(g)))}}return b};var Ua;a:{var Va=v.navigator;if(Va){var Wa=Va.userAgent;if(Wa){Ua=Wa;break a}}Ua=""}function y(a){return-1!=Ua.indexOf(a)};function Xa(){}function Ya(){return(y("Chrome")||y("CriOS"))&&!y("Edge")};var Za="function"===typeof Uint8Array.prototype.slice,z=0,A=0;function bb(a){var b=a>>>0;a=Math.floor((a-b)/4294967296)>>>0;z=b;A=a}function B(a){var b=0>a;a=Math.abs(a);var c=a>>>0;a=Math.floor((a-c)/4294967296);a>>>=0;b&&(a=~a>>>0,c=(~c>>>0)+1,4294967295<c&&(c=0,a++,4294967295<a&&(a=0)));z=c;A=a}function cb(a){var b=0>a;a=2*Math.abs(a);bb(a);a=z;var c=A;b&&(0==a?0==c?c=a=4294967295:(c--,a=4294967295):a--);z=a;A=c}
function db(a){var b=0>a?1:0;a=b?-a:a;if(0===a)0<1/a?z=A=0:(A=0,z=2147483648);else if(isNaN(a))A=0,z=2147483647;else if(3.4028234663852886E38<a)A=0,z=(b<<31|2139095040)>>>0;else if(1.1754943508222875E-38>a)a=Math.round(a/Math.pow(2,-149)),A=0,z=(b<<31|a)>>>0;else{var c=Math.floor(Math.log(a)/Math.LN2);a*=Math.pow(2,-c);a=Math.round(8388608*a)&8388607;A=0;z=(b<<31|c+127<<23|a)>>>0}}
function eb(a){var b=r(a);a=b.next().value;var c=b.next().value,d=b.next().value,e=b.next().value,k=b.next().value,g=b.next().value,h=b.next().value;b=b.next().value;z=a+(c<<8)+(d<<16)+(e<<24)>>>0;A=k+(g<<8)+(h<<16)+(b<<24)>>>0}function fb(a,b,c){var d=b>>31;c(a<<1^d,(b<<1|a>>>31)^d)}
function gb(a){function b(g,h){for(var l=0;8>l&&(1!==g||0<h);l++)h=g*e[l]+h,e[l]=h&255,h>>>=8}function c(){for(var g=0;8>g;g++)e[g]=~e[g]&255}var d=!1;"-"===a[0]&&(d=!0,a=a.slice(1));for(var e=[0,0,0,0,0,0,0,0],k=0;k<a.length;k++)b(10,a.charCodeAt(k)-48);d&&(c(),b(1,1));return e}
function hb(a){return a.constructor===Uint8Array?a:a.constructor===ArrayBuffer?new Uint8Array(a):a.constructor===Array?new Uint8Array(a):a.constructor===String?ib(a):a instanceof Uint8Array?new Uint8Array(a.buffer,a.byteOffset,a.byteLength):new Uint8Array(0)};function C(a,b){this.g=a;this.h=b}function jb(a){return new C((a.g>>>1|(a.h&1)<<31)>>>0,a.h>>>1>>>0)}function kb(a){return new C(a.g<<1>>>0,(a.h<<1|a.g>>>31)>>>0)}f=C.prototype;f.Hd=function(){return!!(this.g&1)};f.add=function(a){return new C((this.g+a.g&4294967295)>>>0>>>0,((this.h+a.h&4294967295)>>>0)+(4294967296<=this.g+a.g?1:0)>>>0)};f.sub=function(a){return new C((this.g-a.g&4294967295)>>>0>>>0,((this.h-a.h&4294967295)>>>0)-(0>this.g-a.g?1:0)>>>0)};
function lb(a){var b=a&65535,c=a>>>16;a=10*b+65536*(0*b&65535)+65536*(10*c&65535);for(b=0*c+(0*b>>>16)+(10*c>>>16);4294967296<=a;)a-=4294967296,b+=1;return new C(a>>>0,b>>>0)}f.toString=function(){for(var a="",b=this;0!=b.g||0!=b.h;){var c=new C(0,0);b=new C(b.g,b.h);for(var d=new C(10,0),e=new C(1,0);!(d.h&2147483648);)d=kb(d),e=kb(e);for(;0!=e.g||0!=e.h;)0>=(d.h<b.h||d.h==b.h&&d.g<b.g?-1:d.h==b.h&&d.g==b.g?0:1)&&(c=c.add(e),b=b.sub(d)),d=jb(d),e=jb(e);c=[c,b];b=c[0];a=c[1].g+a}""==a&&(a="0");return a};
function mb(a){for(var b=new C(0,0),c=new C(0,0),d=0;d<a.length;d++){if("0">a[d]||"9"<a[d])return null;c.g=parseInt(a[d],10);var e=lb(b.g);b=lb(b.h);b.h=b.g;b.g=0;b=e.add(b).add(c)}return b}f.zb=function(){return new C(this.g,this.h)};function D(a,b){this.g=a;this.h=b}D.prototype.add=function(a){return new D((this.g+a.g&4294967295)>>>0>>>0,((this.h+a.h&4294967295)>>>0)+(4294967296<=this.g+a.g?1:0)>>>0)};
D.prototype.sub=function(a){return new D((this.g-a.g&4294967295)>>>0>>>0,((this.h-a.h&4294967295)>>>0)-(0>this.g-a.g?1:0)>>>0)};D.prototype.i=function(){return new D(this.g,this.h)};D.prototype.toString=function(){var a=0!=(this.h&2147483648),b=new C(this.g,this.h);a&&(b=(new C(0,0)).sub(b));return(a?"-":"")+b.toString()};function nb(a){var b=0<a.length&&"-"==a[0];b&&(a=a.substring(1));a=mb(a);if(null===a)return null;b&&(a=(new C(0,0)).sub(a));return new D(a.g,a.h)};function ob(){this.h=new Uint8Array(64);this.g=0}function pb(a,b){if(!(a.g+b<a.h.length)){var c=a.h;a.h=new Uint8Array(Math.ceil(b+2*a.h.length));a.h.set(c)}}f=ob.prototype;f.push=function(a){pb(this,1);this.h[this.g++]=a};f.Ab=function(a){pb(this,a.length);this.h.set(a,this.g);this.g+=a.length};f.length=function(){return this.g};f.end=function(){var a=this.h,b=this.g;this.g=0;return Za?a.slice(0,b):new Uint8Array(a.subarray(0,b))};
function E(a,b,c){for(;0<c||127<b;)a.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.push(b)}function F(a,b,c){G(a,b);G(a,c)}function qb(a,b,c){fb(b,c,function(d,e){E(a,d>>>0,e>>>0)})}function I(a,b){for(;127<b;)a.push(b&127|128),b>>>=7;a.push(b)}function rb(a,b){if(0<=b)I(a,b);else{for(var c=0;9>c;c++)a.push(b&127|128),b>>=7;a.push(1)}}function sb(a,b){I(a,(b<<1^b>>31)>>>0)}function tb(a,b){eb(gb(b));fb(z,A,function(c,d){E(a,c>>>0,d>>>0)})}f.qf=function(a){this.push(a>>>0&255)};
f.pf=function(a){this.push(a>>>0&255);this.push(a>>>8&255)};function G(a,b){a.push(b>>>0&255);a.push(b>>>8&255);a.push(b>>>16&255);a.push(b>>>24&255)}function ub(a,b){bb(b);G(a,z);G(a,A)}f.pe=function(a){this.push(a>>>0&255)};f.oe=function(a){this.push(a>>>0&255);this.push(a>>>8&255)};function vb(a,b){a.push(b>>>0&255);a.push(b>>>8&255);a.push(b>>>16&255);a.push(b>>>24&255)}
function wb(a,b){var c=b;c=(b=0>c?1:0)?-c:c;if(0===c)A=0<1/c?0:2147483648,z=0;else if(isNaN(c))A=2147483647,z=4294967295;else if(1.7976931348623157E308<c)A=(b<<31|2146435072)>>>0,z=0;else if(2.2250738585072014E-308>c){var d=c/Math.pow(2,-1074);A=(b<<31|d/4294967296)>>>0;z=d>>>0}else{var e=c;d=0;if(2<=e)for(;2<=e&&1023>d;)d++,e/=2;else for(;1>e&&-1022<d;)e*=2,d--;c*=Math.pow(2,-d);A=(b<<31|d+1023<<20|1048576*c&1048575)>>>0;z=4503599627370496*c>>>0}G(a,z);G(a,A)};function xb(a){xb[" "](a);return a}xb[" "]=Ca;var yb=y("Gecko")&&!(-1!=Ua.toLowerCase().indexOf("webkit")&&!y("Edge"))&&!(y("Trident")||y("MSIE"))&&!y("Edge"),zb=-1!=Ua.toLowerCase().indexOf("webkit")&&!y("Edge"),Ab=y("Macintosh");Xa();!y("Android")||Ya()||Xa();Ya();!y("Safari")||Ya()||y("Coast")||y("Opera")||y("Edge")||y("Edg/")||y("OPR")||Xa();var Bb={},Cb=null;function Db(a,b){void 0===b&&(b=0);Eb();b=Bb[b];for(var c=Array(Math.floor(a.length/3)),d=b[64]||"",e=0,k=0;e<a.length-2;e+=3){var g=a[e],h=a[e+1],l=a[e+2],m=b[g>>2];g=b[(g&3)<<4|h>>4];h=b[(h&15)<<2|l>>6];l=b[l&63];c[k++]=m+g+h+l}m=0;l=d;switch(a.length-e){case 2:m=a[e+1],l=b[(m&15)<<2]||d;case 1:a=a[e],c[k]=b[a>>2]+b[(a&3)<<4|m>>4]+l+d}return c.join("")}
function ib(a){var b=a.length,c=3*b/4;c%3?c=Math.floor(c):-1!="=.".indexOf(a[b-1])&&(c=-1!="=.".indexOf(a[b-2])?c-2:c-1);var d=new Uint8Array(c),e=0;Fb(a,function(k){d[e++]=k});return d.subarray(0,e)}
function Fb(a,b){function c(l){for(;d<a.length;){var m=a.charAt(d++),q=Cb[m];if(null!=q)return q;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return l}Eb();for(var d=0;;){var e=c(-1),k=c(0),g=c(64),h=c(64);if(64===h&&-1===e)break;b(e<<2|k>>4);64!=g&&(b(k<<4&240|g>>2),64!=h&&b(g<<6&192|h))}}
function Eb(){if(!Cb){Cb={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));Bb[c]=d;for(var e=0;e<d.length;e++){var k=d[e];void 0===Cb[k]&&(Cb[k]=e)}}}};function Gb(){this.i=[];this.h=0;this.g=new ob}function Hb(a,b){var c=a.g.end();a.i.push(c);a.i.push(b);a.h+=c.length+b.length}function J(a,b){L(a,b,2);b=a.g.end();a.i.push(b);a.h+=b.length;return{X:a.h,V:a.i.length-1}}function M(a,b){var c=a.g.end();a.i.push(c);a.h+=c.length;I(a.g,a.h+a.g.length()-b.X);c=a.g.end();a.h+=c.length;a.i.splice(1+b.V,0,c)}f=Gb.prototype;f.Kd=function(a,b,c){null!=a&&null!=b&&null!=c&&Hb(this,a.subarray(b,c))};
function Ib(a){var b=a.h+a.g.length();if(0===b)return new Uint8Array(0);b=new Uint8Array(b);for(var c=a.i,d=c.length,e=0,k=0;k<d;k++){var g=c[k];0!==g.length&&(b.set(g,e),e+=g.length)}c=a.g;d=c.g;0!==d&&(b.set(c.h.subarray(0,d),e),c.g=0);a.i=[b];return b}f.Wc=function(a){return Db(Ib(this),a)};function L(a,b,c){I(a.g,8*b+c)}
f.me=function(a,b,c){switch(a){case 1:null!=c&&(L(this,b,1),wb(this.g,c));break;case 2:null!=c&&(L(this,b,5),a=this.g,db(c),G(a,z));break;case 3:null!=c&&null!=c&&(L(this,b,0),a=this.g,B(c),E(a,z,A));break;case 4:null!=c&&null!=c&&(L(this,b,0),a=this.g,B(c),E(a,z,A));break;case 5:null!=c&&null!=c&&(L(this,b,0),rb(this.g,c));break;case 6:null!=c&&(L(this,b,1),ub(this.g,c));break;case 7:null!=c&&(L(this,b,5),G(this.g,c));break;case 8:Jb(this,b,c);break;case 9:N(this,b,c);break;case 12:null!=c&&Kb(this,
b,hb(c));break;case 13:null!=c&&null!=c&&(L(this,b,0),I(this.g,c));break;case 14:Lb(this,b,c);break;case 15:null!=c&&(L(this,b,5),vb(this.g,c));break;case 16:null!=c&&(L(this,b,1),a=this.g,B(c),F(a,z,A));break;case 17:null!=c&&null!=c&&(L(this,b,0),sb(this.g,c));break;case 18:null!=c&&null!=c&&(L(this,b,0),a=this.g,cb(c),E(a,z,A))}};f.nf=function(a,b){null!=b&&null!=b&&(L(this,a,0),tb(this.g,b))};function Jb(a,b,c){null!=c&&(L(a,b,0),a.g.push(c?1:0))}
function Lb(a,b,c){null!=c&&(c=parseInt(c,10),L(a,b,0),rb(a.g,c))}
function N(a,b,c){if(null!=c){if(Ja)c=(Ia||(Ia=new TextEncoder)).encode(c);else{var d=void 0;d=void 0===d?!1:d;for(var e=0,k=new Uint8Array(3*c.length),g=0;g<c.length;g++){var h=c.charCodeAt(g);if(128>h)k[e++]=h;else{if(2048>h)k[e++]=h>>6|192;else{if(55296<=h&&57343>=h){if(56319>=h&&g<c.length){var l=c.charCodeAt(++g);if(56320<=l&&57343>=l){h=1024*(h-55296)+l-56320+65536;k[e++]=h>>18|240;k[e++]=h>>12&63|128;k[e++]=h>>6&63|128;k[e++]=h&63|128;continue}else g--}if(d)throw Error("Found an unpaired surrogate");
h=65533}k[e++]=h>>12|224;k[e++]=h>>6&63|128}k[e++]=h&63|128}}c=k.subarray(0,e)}Kb(a,b,c)}}function Kb(a,b,c){L(a,b,2);I(a.g,c.length);Hb(a,c)}f.qe=function(a,b,c){null!=b&&(a=J(this,a),c(b,this),M(this,a))};f.re=function(a,b,c){null!=b&&(L(this,1,3),L(this,2,0),rb(this.g,a),a=J(this,3),c(b,this),M(this,a),L(this,1,4))};f.ne=function(a,b,c){null!=b&&(L(this,a,3),c(b,this),L(this,a,4))};f.Xe=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,0),rb(this.g,d))}};
f.Ye=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){L(this,a,0);var e=this.g;B(d);E(e,z,A)}}};f.gf=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var k=c(b[e]),g=d(b[e]);L(this,a,1);F(this.g,k,g)}};f.hf=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var k=c(b[e]),g=d(b[e]);L(this,a,0);E(this.g,k,g)}};f.jf=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var k=c(b[e]),g=d(b[e]);L(this,a,0);qb(this.g,k>>>0,g>>>0)}};
f.Ze=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=nb(e),L(this,d,0),E(this.g,e.g,e.h))}};f.kf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,0),I(this.g,d))}};f.lf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){L(this,a,0);var e=this.g;B(d);E(e,z,A)}}};f.mf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=mb(e),L(this,d,0),E(this.g,e.g,e.h))}};
f.df=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,0),sb(this.g,d))}};f.ef=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){L(this,a,0);var e=this.g;cb(d);E(e,z,A)}}};f.ff=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,0),tb(this.g,d))}};f.Se=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,5),G(this.g,d))}};
f.Te=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,1),ub(this.g,d))}};f.Ue=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=mb(e),L(this,d,1),F(this.g,e.g,e.h))}};f.af=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,5),vb(this.g,d))}};f.bf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){L(this,a,1);var e=this.g;B(d);F(e,z,A)}}};
f.cf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=nb(e),L(this,d,1),F(this.g,e.g,e.h))}};f.Ve=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){L(this,a,5);var e=this.g;db(d);G(e,z)}}};f.Qe=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,1),wb(this.g,d))}};f.Oe=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Jb(this,a,b[c])};f.Re=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Lb(this,a,b[c])};
function Mb(a,b,c){if(null!=c)for(var d=0;d<c.length;d++)N(a,b,c[d])}f.Pe=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Kb(this,a,hb(d))}};f.$e=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++){var e=J(this,a);c(b[d],this);M(this,e)}};f.We=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++)L(this,a,3),c(b[d],this),L(this,a,4)};f.ye=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)rb(this.g,b[c]);M(this,a)}};
f.ze=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)rb(this.g,parseInt(b[c],10));M(this,a)}};f.Ae=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++){var d=this.g;B(b[c]);E(d,z,A)}M(this,a)}};f.Ie=function(a,b,c,d){if(null!=b){a=J(this,a);for(var e=0;e<b.length;e++)F(this.g,c(b[e]),d(b[e]));M(this,a)}};f.Je=function(a,b,c,d){if(null!=b){a=J(this,a);for(var e=0;e<b.length;e++)E(this.g,c(b[e]),d(b[e]));M(this,a)}};
f.Ke=function(a,b,c,d){if(null!=b){a=J(this,a);for(var e=this.g,k=0;k<b.length;k++)qb(e,c(b[k]),d(b[k]));M(this,a)}};f.Be=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++){var d=nb(b[c]);E(this.g,d.g,d.h)}M(this,a)}};f.Le=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)I(this.g,b[c]);M(this,a)}};f.Me=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++){var d=this.g;B(b[c]);E(d,z,A)}M(this,a)}};
f.Ne=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++){var d=mb(b[c]);E(this.g,d.g,d.h)}M(this,a)}};f.Fe=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)sb(this.g,b[c]);M(this,a)}};f.Ge=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++){var d=this.g;cb(b[c]);E(d,z,A)}M(this,a)}};f.He=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)tb(this.g,b[c]);M(this,a)}};
f.ue=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,4*b.length),a=0;a<b.length;a++)G(this.g,b[a])};f.ve=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,8*b.length),a=0;a<b.length;a++)ub(this.g,b[a])};f.we=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,8*b.length),a=0;a<b.length;a++){var c=mb(b[a]);F(this.g,c.g,c.h)}};f.Ce=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,4*b.length),a=0;a<b.length;a++)vb(this.g,b[a])};
f.De=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,8*b.length),a=0;a<b.length;a++){var c=this.g;B(b[a]);F(c,z,A)}};f.Ee=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,8*b.length),a=0;a<b.length;a++){var c=this.g;eb(gb(b[a]));F(c,z,A)}};f.xe=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,4*b.length),a=0;a<b.length;a++){var c=this.g;db(b[a]);G(c,z)}};f.te=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,8*b.length),a=0;a<b.length;a++)wb(this.g,b[a])};
f.se=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,b.length),a=0;a<b.length;a++)this.g.push(b[a]?1:0)};var Nb="function"===typeof Uint8Array;function Ob(a){return Pb(a,function(b){return b},function(b){return new Uint8Array(b)})}function Qb(a,b,c){return"object"===typeof a?Nb&&!Array.isArray(a)&&a instanceof Uint8Array?c(a):Pb(a,b,c):b(a)}function Pb(a,b,c){if(Array.isArray(a)){for(var d=Array(a.length),e=0;e<a.length;e++){var k=a[e];null!=k&&(d[e]=Qb(k,b,c))}Array.isArray(a)&&a.W&&O(d);return d}d={};for(e in a)k=a[e],null!=k&&(d[e]=Qb(k,b,c));return d}
function Rb(a){return Pb(a,function(b){return"number"===typeof b?isFinite(b)?b:String(b):b},function(b){return Db(b)})}function Sb(a){return Pb(a,function(b){return b},function(b){return new Uint8Array(b)})}var Tb={W:{value:!0,configurable:!0}};function O(a){Array.isArray(a)&&!Object.isFrozen(a)&&Object.defineProperties(a,Tb);return a}var Ub;function Vb(a,b){this.i=a;this.j=b;this.g={};this.h=!0;this.l=null;if(0<this.i.length){for(a=0;a<this.i.length;a++){b=this.i[a];var c=b[0];this.g[c.toString()]=new Wb(c,b[1])}this.h=!0}}f=Vb.prototype;f.isFrozen=function(){return!1};f.Bc=function(){};f.toJSON=function(){var a=this.s(!1);return Ub?a:Rb(a)};f.Cb=function(){return this.toJSON()};
f.s=function(a){if(this.h){if(this.j){var b=this.g,c;for(c in b)if(Object.prototype.hasOwnProperty.call(b,c)){var d=b[c].g;d&&d.s(a)}}}else{this.i.length=0;b=Xb(this);b.sort();for(c=0;c<b.length;c++){d=this.g[b[c]];var e=d.g;e&&e.s(a);this.i.push([d.key,d.value])}this.h=!0}return this.i};f.Sc=function(){return Xb(this).length};f.Bb=function(){this.g={};this.h=!1};f.Gc=function(a){a=a.toString();var b=this.g.hasOwnProperty(a);delete this.g[a];this.h=!1;return b};
f.Qc=function(){var a=[],b=Xb(this);b.sort();for(var c=0;c<b.length;c++){var d=this.g[b[c]];a.push([d.key,d.value])}return a};f.entries=function(){var a=[],b=Xb(this);b.sort();for(var c=0;c<b.length;c++){var d=this.g[b[c]];a.push([d.key,Yb(this,d)])}return new Zb(a)};f.keys=function(){var a=[],b=Xb(this);b.sort();for(var c=0;c<b.length;c++)a.push(this.g[b[c]].key);return new Zb(a)};f.values=function(){var a=[],b=Xb(this);b.sort();for(var c=0;c<b.length;c++)a.push(Yb(this,this.g[b[c]]));return new Zb(a)};
f.forEach=function(a,b){var c=Xb(this);c.sort();for(var d=0;d<c.length;d++){var e=this.g[c[d]];a.call(b,Yb(this,e),e.key,this)}};f.set=function(a,b){var c=new Wb(a);this.j?(c.g=b,c.value=b.s(!1)):c.value=b;this.g[a.toString()]=c;this.h=!1;return this};f.be=function(a,b){this.g[a.toString()]=new Wb(a,b);this.h=!1};function Yb(a,b){return a.j?(b.g||(b.g=new a.j(b.value),a.isFrozen()&&null(b.g)),b.g):b.value}f.get=function(a){if(a=this.g[a.toString()])return Yb(this,a)};
f.has=function(a){return a.toString()in this.g};function Xb(a){a=a.g;var b=[],c;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b}Vb.prototype[Symbol.iterator]=function(){return this.entries()};function Wb(a,b){this.key=a;this.value=b;this.g=void 0}function Zb(a){this.i=0;this.h=a}Zb.prototype.next=function(){return this.i<this.h.length?{done:!1,value:this.h[this.i++]}:{done:!0,value:void 0}};Zb.prototype[Symbol.iterator]=function(){return this};var $b;function ac(a,b){$b=b;a=new a(b);$b=null;return a};function bc(a,b,c){var d=$b;$b=null;a||(a=d);d=this.constructor.Ld;a||(a=d?[d]:[]);this.l=d?0:-1;this.j=this.g=null;this.i=a;a:{d=this.i.length;a=d-1;if(d&&(d=this.i[a],!(null===d||"object"!=typeof d||Array.isArray(d)||Nb&&d instanceof Uint8Array))){this.m=a-this.l;this.h=d;break a}void 0!==b&&-1<b?(this.m=Math.max(b,a+1-this.l),this.h=null):this.m=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)a=c[b],a<this.m?(a+=this.l,(d=this.i[a])?O(d):this.i[a]=cc):(dc(this),(d=this.h[a])?O(d):this.h[a]=cc)}
var cc=Object.freeze(O([]));function dc(a){var b=a.m+a.l;a.i[b]||(a.h=a.i[b]={})}function P(a,b){if(-1===b)return null;if(b<a.m){b+=a.l;var c=a.i[b];return c!==cc?c:a.i[b]=O([])}if(a.h)return c=a.h[b],c!==cc?c:a.h[b]=O([])}f=bc.prototype;f.td=function(a){return null!=P(this,a)};f.ud=function(a,b){return ec(this,b)===a};function fc(a,b){a=P(a,b);return null==a?a:+a}function gc(a,b){a=P(a,b);return null==a?a:!!a}
f.sd=function(a){var b=P(this,a);this.j||(this.j={});if(!this.j[a]){for(var c=0;c<b.length;c++)b[c]=+b[c];this.j[a]=!0}return b};f.rd=function(a){var b=P(this,a);this.j||(this.j={});if(!this.j[a]){for(var c=0;c<b.length;c++)b[c]=!!b[c];this.j[a]=!0}return b};function hc(a,b,c){a=P(a,b);return null==a?c:a}function ic(a,b,c){c=void 0===c?!1:c;a=gc(a,b);return null==a?c:a}
f.fd=function(a,b,c){this.g||(this.g={});if(a in this.g)return this.g[a];var d=P(this,a);if(!d){if(b)return;d=O([]);Q(this,a,d)}b=new Vb(d,c);return this.g[a]=b};function Q(a,b,c){b<a.m?a.i[b+a.l]=c:(dc(a),a.h[b]=c);return a}f.ed=function(a){this.g||(this.g={});this.g[a]=void 0;return Q(this,a,void 0)};f.dd=function(a){var b=[];this.g||(this.g={});b=b||[];for(var c=O([]),d=0;d<b.length;d++)c[d]=b[d].s(!1);this.g[a]=b;return Q(this,a,c)};function R(a,b,c,d){c!==d?Q(a,b,c):Q(a,b,void 0);return a}
function jc(a,b,c,d){b=P(a,b);void 0!=d?b.splice(d,0,c):b.push(c);return a}function ec(a,b){for(var c=0,d=0;d<b.length;d++){var e=b[d];null!=P(a,e)&&(0!==c&&Q(a,c,void 0),c=e)}return c}f.vd=function(a,b,c){this.g||(this.g={});var d=c?c.s(!1):c;this.g[a]=c;(b=ec(this,b))&&b!==a&&null!=d&&(this.g&&b in this.g&&(this.g[b]=void 0),Q(this,b,void 0));return Q(this,a,d)};
f.cd=function(a,b,c,d){this.g||(this.g={});if(!this.g[a]){var e=P(this,a);for(var k=[],g=0;g<e.length;g++)k[g]=new c(e[g]);this.g[a]=k}e=this.g[a];b=b?b:new c;a=P(this,a);void 0!=d?(e.splice(d,0,b),a.splice(d,0,b.s(!1))):(e.push(b),a.push(b.s(!1)));return b};f.Fb=function(){return this.toJSON()};f.je=function(){return this.toJSON()};f.toJSON=function(){var a=this.s(!1);return Ub?a:Rb(a)};f.ke=function(){return Sb(this.s(!1))};
f.s=function(a){if(this.g)for(var b in this.g){var c=this.g[b];if(Array.isArray(c))for(var d=0;d<c.length;d++)c[d]&&c[d].s(a);else c&&c.s(a)}return this.i};function kc(){var a=S.g;Ub=!0;try{return JSON.stringify(a.toJSON(),lc)}finally{Ub=!1}}function lc(a,b){switch(typeof b){case "number":return isFinite(b)?b:String(b);case "object":if(Nb&&null!=b&&b instanceof Uint8Array)return Db(b)}return b}f.toString=function(){return this.s(!1).toString()};
f.Eb=function(a){dc(this);this.g||(this.g={});var b=a.i;return a.j?a.g()?(this.g[b]||(this.g[b]=La(this.h[b]||[],function(c){return new a.h(c)})),this.g[b]):this.h[b]=this.h[b]||O([]):a.g()?(!this.g[b]&&this.h[b]&&(this.g[b]=new a.h(this.h[b])),this.g[b]):this.h[b]};f.Rd=function(a,b){this.g||(this.g={});dc(this);var c=a.i;a.j?(b=b||[],a.g()?(this.g[c]=b,this.h[c]=O(La(b,function(d){return d.s(!1)}))):this.h[c]=O(b)):a.g()?(this.g[c]=b,this.h[c]=b?b.s(!1):b):this.h[c]=b;return this};
f.Db=function(){var a=this.constructor,b=Ob(this.s(!1));return ac(a,b)};function T(a,b,c){return ec(a,b)===c?c:-1}function U(a,b,c){return hc(a,b,void 0===c?"":c)}f.kd=function(a,b,c){return hc(this,T(this,b,a),c)};f.hd=function(a,b,c){return ic(this,T(this,b,a),c)};f.nd=function(a,b,c){a=T(this,b,a);return hc(this,a,void 0===c?0:c)};f.od=function(a,b,c){a=T(this,b,a);return hc(this,a,void 0===c?"0":c)};f.md=function(a,b,c){a=T(this,b,a);c=void 0===c?0:c;a=fc(this,a);return null==a?c:a};
f.pd=function(a,b,c){return U(this,T(this,b,a),c)};f.jd=function(a,b){return P(this,T(this,b,a))};f.gd=function(a,b){return gc(this,T(this,b,a))};f.ld=function(a,b){return fc(this,T(this,b,a))};f.qd=function(a,b,c){b=T(this,c,b);-1===b?a=null:(this.g||(this.g={}),this.g[b]||(c=P(this,b))&&(this.g[b]=new a(c)),a=this.g[b]);return a};f.yd=function(a,b){return R(this,a,b,0)};f.xd=function(a,b){return R(this,a,b,0)};f.zd=function(a,b){null!=b&&0!==+b?Q(this,a,b):Q(this,a,void 0);return this};
f.wd=function(a,b){null!=b&&0!==b.length?Q(this,a,b):Q(this,a,void 0);return this};function mc(a){bc.call(this,a,-1,nc)}la(mc,bc);f=mc.prototype;f.getTenantId=function(){return hc(this,1,0)};f.ee=function(a){return R(this,1,a,0)};f.getLocale=function(){return U(this,2)};f.Od=function(a){return R(this,4,a,"")};f.Ud=function(a){return R(this,5,a,"")};f.fe=function(a){return R(this,6,a,"")};f.getInsecureHost=function(){return U(this,7)};f.Vd=function(a){return R(this,7,a,"")};f.Rc=function(){return ic(this,8)};f.Xd=function(a){return R(this,8,a,!1)};
f.Wd=function(a){return R(this,9,a,!1)};f.Mc=function(){return P(this,10)};f.Pd=function(a){return Q(this,10,O(a||[]))};f.vc=function(a,b){return jc(this,10,a,b)};f.Cc=function(){return Q(this,10,O([]))};f.Yd=function(a){return R(this,11,a,!1)};f.de=function(a){return Q(this,12,O(a||[]))};f.xc=function(a,b){return jc(this,12,a,b)};f.Ec=function(){return Q(this,12,O([]))};f.Sd=function(a){return Q(this,13,O(a||[]))};f.wc=function(a,b){return jc(this,13,a,b)};f.Dc=function(){return Q(this,13,O([]))};
f.Oc=function(){return U(this,14)};f.Qd=function(a){return R(this,14,a,"")};f.Uc=function(){return U(this,15)};f.Zd=function(a){return R(this,15,a,"")};
f.Nd=function(){var a=new Gb;Lb(a,1,P(this,1));N(a,2,P(this,2));N(a,4,P(this,4));N(a,5,P(this,5));N(a,6,P(this,6));N(a,7,P(this,7));Jb(a,8,P(this,8));Jb(a,9,P(this,9));Mb(a,10,P(this,10));Jb(a,11,P(this,11));Mb(a,12,P(this,12));var b=P(this,13);if(null!=b&&b.length){for(var c=J(a,13),d=0;d<b.length;d++)rb(a.g,b[d]);M(a,c)}N(a,14,P(this,14));N(a,15,P(this,15));return Ib(a)};function oc(){var a=GoogleDevelopersObject;return ac(mc,a?JSON.parse(a):null)}var nc=[10,12,13];
mc.prototype.o=function(a){if(null!=this){var b,c={he:hc(this,1,0),locale:U(this,2),yc:U(this,4),Yc:U(this,5),ie:U(this,6),bd:U(this,7),Bd:ic(this,8),Ad:ic(this,9),Ac:null==(b=P(this,10))?void 0:b,Cd:ic(this,11),ge:null==(b=P(this,12))?void 0:b,Jc:null==(b=P(this,13))?void 0:b,Hc:U(this,14),Jd:U(this,15)};a&&(c.Y=this);a=c}else a=void 0;return a};function pc(a){var b=qc,c=void 0;return new (c||(c=Promise))(function(d,e){function k(l){try{h(a.next(l))}catch(m){e(m)}}function g(l){try{h(a["throw"](l))}catch(m){e(m)}}function h(l){l.done?d(l.value):(new c(function(m){m(l.value)})).then(k,g)}h((a=a.apply(b,void 0)).next())})};function rc(a,b){this.h=a[v.Symbol.iterator]();this.i=b;this.j=0}rc.prototype[Symbol.iterator]=function(){return this};rc.prototype.next=function(){var a=this.h.next();return{value:a.done?void 0:this.i.call(void 0,a.value,this.j++),done:a.done}};function sc(a,b){return new rc(a,b)};var tc="StopIteration"in v?v.StopIteration:{message:"StopIteration",stack:""};function uc(){}uc.prototype.next=function(){return uc.prototype.g.call(this)};uc.prototype.g=function(){throw tc;};uc.prototype.G=function(){return this};function vc(a){if(a instanceof V||a instanceof W||a instanceof wc)return a;if("function"==typeof a.next)return new V(function(){return xc(a)});if("function"==typeof a[Symbol.iterator])return new V(function(){return a[Symbol.iterator]()});if("function"==typeof a.G)return new V(function(){return xc(a.G())});throw Error("Not an iterator or iterable.");}
function xc(a){if(!(a instanceof uc))return a;var b=!1;return{next:function(){for(var c;!b;)try{c=a.g();break}catch(d){if(d!==tc)throw d;b=!0}return{value:c,done:b}}}}function V(a){this.h=a}V.prototype.G=function(){return new W(this.h())};V.prototype.l=function(){return new W(this.h())};V.prototype[Symbol.iterator]=function(){return new wc(this.h())};V.prototype.i=function(){return new wc(this.h())};function W(a){this.h=a}la(W,uc);W.prototype.g=function(){var a=this.h.next();if(a.done)throw tc;return a.value};
W.prototype.next=function(){return W.prototype.g.call(this)};W.prototype.l=function(){return this};W.prototype[Symbol.iterator]=function(){return new wc(this.h)};W.prototype.i=function(){return new wc(this.h)};function wc(a){V.call(this,function(){return a});this.j=a}la(wc,V);wc.prototype.next=function(){return this.j.next()};function yc(a,b){this.h={};this.g=[];this.i=this.size=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof yc)for(c=a.C(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}f=yc.prototype;f.A=function(){zc(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.h[this.g[b]]);return a};f.C=function(){zc(this);return this.g.concat()};
f.has=function(a){return Ac(this.h,a)};f.Hb=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if(Ac(this.h,c)&&this.h[c]==a)return!0}return!1};f.Ib=function(a,b){if(this===a)return!0;if(this.size!=a.size)return!1;b=b||Bc;zc(this);for(var c,d=0;c=this.g[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function Bc(a,b){return a===b}f.Jb=function(){return 0==this.size};f.Gb=function(){this.h={};this.i=this.size=this.g.length=0};
function zc(a){if(a.size!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];Ac(a.h,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.size!=a.g.length){var e={};for(c=b=0;b<a.g.length;)d=a.g[b],Ac(e,d)||(a.g[c++]=d,e[d]=1),b++;a.g.length=c}}f.get=function(a,b){return Ac(this.h,a)?this.h[a]:b};f.set=function(a,b){Ac(this.h,a)||(this.size+=1,this.g.push(a),this.i++);this.h[a]=b};f.forEach=function(a,b){for(var c=this.C(),d=0;d<c.length;d++){var e=c[d],k=this.get(e);a.call(b,k,e,this)}};
f.le=function(){for(var a=new yc,b=0;b<this.g.length;b++){var c=this.g[b];a.set(this.h[c],c)}return a};f.Kb=function(){zc(this);for(var a={},b=0;b<this.g.length;b++){var c=this.g[b];a[c]=this.h[c]}return a};f.keys=function(){return vc(this.G(!0)).i()};f.values=function(){return vc(this.G(!1)).i()};f.entries=function(){var a=this;return sc(this.keys(),function(b){return[b,a.get(b)]})};
f.G=function(a){zc(this);var b=0,c=this.i,d=this,e=new uc;e.g=function(){if(c!=d.i)throw Error("The map has changed since the iterator was created");if(b>=d.g.length)throw tc;var k=d.g[b++];return a?k:d.h[k]};e.next=e.g.bind(e);return e};function Ac(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Cc(a){if(a.A&&"function"==typeof a.A)return a.A();if("undefined"!==typeof Map&&a instanceof Map||"undefined"!==typeof Set&&a instanceof Set)return Array.from(a.values());if("string"===typeof a)return a.split("");if(Da(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function Dc(a){if(a.C&&"function"==typeof a.C)return a.C();if(!a.A||"function"!=typeof a.A){if("undefined"!==typeof Map&&a instanceof Map)return Array.from(a.keys());if(!("undefined"!==typeof Set&&a instanceof Set)){if(Da(a)||"string"===typeof a){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}b=[];c=0;for(var d in a)b[c++]=d;return b}}}
function Ec(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(Da(a)||"string"===typeof a)Array.prototype.forEach.call(a,b,c);else for(var d=Dc(a),e=Cc(a),k=e.length,g=0;g<k;g++)b.call(c,e[g],d&&d[g],a)};var Fc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Gc(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var k=a[c].substring(0,d);e=a[c].substring(d+1)}else k=a[c];b(k,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function Hc(a,b){this.h=this.u=this.m="";this.j=null;this.o=this.i="";this.l=this.F=!1;if(a instanceof Hc){this.l=void 0!==b?b:a.l;Ic(this,a.m);var c=a.u;X(this);this.u=c;c=a.h;X(this);this.h=c;Jc(this,a.j);c=a.i;X(this);this.i=c;Kc(this,Lc(a.g));a=a.o;X(this);this.o=a}else a&&(c=String(a).match(Fc))?(this.l=!!b,Ic(this,c[1]||"",!0),a=c[2]||"",X(this),this.u=Mc(a),a=c[3]||"",X(this),this.h=Mc(a,!0),Jc(this,c[4]),a=c[5]||"",X(this),this.i=Mc(a,!0),Kc(this,c[6]||"",!0),a=c[7]||"",X(this),this.o=Mc(a)):
(this.l=!!b,this.g=new Nc(null,this.l))}f=Hc.prototype;f.toString=function(){var a=[],b=this.m;b&&a.push(Oc(b,Pc,!0),":");var c=this.h;if(c||"file"==b)a.push("//"),(b=this.u)&&a.push(Oc(b,Pc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.j,null!=c&&a.push(":",String(c));if(c=this.i)this.h&&"/"!=c.charAt(0)&&a.push("/"),a.push(Oc(c,"/"==c.charAt(0)?Qc:Rc,!0));(c=this.g.toString())&&a.push("?",c);(c=this.o)&&a.push("#",Oc(c,Sc));return a.join("")};
f.resolve=function(a){var b=new Hc(this),c=!!a.m;c?Ic(b,a.m):c=!!a.u;if(c){var d=a.u;X(b);b.u=d}else c=!!a.h;c?(d=a.h,X(b),b.h=d):c=null!=a.j;d=a.i;if(c)Jc(b,a.j);else if(c=!!a.i){if("/"!=d.charAt(0))if(this.h&&!this.i)d="/"+d;else{var e=b.i.lastIndexOf("/");-1!=e&&(d=b.i.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var k=[],g=0;g<e.length;){var h=e[g++];"."==h?d&&g==e.length&&k.push(""):".."==h?((1<k.length||
1==k.length&&""!=k[0])&&k.pop(),d&&g==e.length&&k.push("")):(k.push(h),d=!0)}d=k.join("/")}else d=e}c?(X(b),b.i=d):c=""!==a.g.toString();c?Kc(b,Lc(a.g)):c=!!a.o;c&&(a=a.o,X(b),b.o=a);return b};function Ic(a,b,c){X(a);a.m=c?Mc(b,!0):b;a.m&&(a.m=a.m.replace(/:$/,""))}function Jc(a,b){X(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.j=b}else a.j=null}function Kc(a,b,c){X(a);b instanceof Nc?(a.g=b,Tc(a.g,a.l)):(c||(b=Oc(b,Uc)),a.g=new Nc(b,a.l));return a}
f.ae=function(a,b){return Kc(this,a,b)};f.Nc=function(){return Mc(this.g.toString())};f.Lb=function(){return this.g.toString()};f.$d=function(a,b){X(this);Array.isArray(b)||(b=[String(b)]);Vc(this.g,a,b);return this};f.Vc=function(a){return this.g.A(a)};f.Zc=function(a){return(!this.h&&!a.h||this.h==a.h)&&(null==this.j&&null==a.j||this.j==a.j)};
f.Id=function(){X(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Date.now()).toString(36);X(this);this.g.set("zx",a);return this};f.Mb=function(a){X(this);Wc(this.g,a);return this};f.ce=function(a){this.F=a;return this};f.Dd=function(){return this.F};function X(a){if(a.F)throw Error("Tried to modify a read-only Uri");}f.Nb=function(a){this.l=a;this.g&&Tc(this.g,a);return this};
function Xc(a){return a instanceof Hc?new Hc(a):new Hc(a,void 0)}function Mc(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function Oc(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Yc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function Yc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Pc=/[#\/\?@]/g,Rc=/[#\?:]/g,Qc=/[#\?]/g,Uc=/[#\?@]/g,Sc=/#/g;function Nc(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b}
function Y(a){a.g||(a.g=new yc,a.h=0,a.i&&Gc(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}f=Nc.prototype;f.Rb=function(){Y(this);return this.h};f.add=function(a,b){Y(this);this.i=null;a=Zc(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};function Wc(a,b){Y(a);b=Zc(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a=a.g,Ac(a.h,b)&&(delete a.h[b],--a.size,a.i++,a.g.length>2*a.size&&zc(a)))}f.Ob=function(){this.g=this.i=null;this.h=0};
f.Sb=function(){Y(this);return 0==this.h};function $c(a,b){Y(a);b=Zc(a,b);return a.g.has(b)}f.Pb=function(a){var b=this.A();return 0<=Ka(b,a)};f.forEach=function(a,b){Y(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};f.C=function(){Y(this);for(var a=this.g.A(),b=this.g.C(),c=[],d=0;d<b.length;d++)for(var e=a[d],k=0;k<e.length;k++)c.push(b[d]);return c};
f.A=function(a){Y(this);var b=[];if("string"===typeof a)$c(this,a)&&(b=b.concat(this.g.get(Zc(this,a))));else{a=this.g.A();for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};f.set=function(a,b){Y(this);this.i=null;a=Zc(this,a);$c(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};f.get=function(a,b){if(!a)return b;a=this.A(a);return 0<a.length?String(a[0]):b};
function Vc(a,b,c){Wc(a,b);if(0<c.length){a.i=null;var d=a.g,e=d.set;b=Zc(a,b);var k=c.length;if(0<k){for(var g=Array(k),h=0;h<k;h++)g[h]=c[h];k=g}else k=[];e.call(d,b,k);a.h+=c.length}}f.toString=function(){if(this.i)return this.i;if(!this.g)return"";for(var a=[],b=this.g.C(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.A(d);for(var k=0;k<d.length;k++){var g=e;""!==d[k]&&(g+="="+encodeURIComponent(String(d[k])));a.push(g)}}return this.i=a.join("&")};
f.Kc=function(a){Y(this);this.g.forEach(function(b,c){0<=Ka(a,c)||Wc(this,c)},this);return this};function Lc(a){var b=new Nc;b.i=a.i;a.g&&(b.g=new yc(a.g),b.h=a.h);return b}function Zc(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b}function Tc(a,b){b&&!a.j&&(Y(a),a.i=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Wc(this,d),Vc(this,e,c))},a));a.j=b}f.Qb=function(a){for(var b=0;b<arguments.length;b++)Ec(arguments[b],function(c,d){this.add(d,c)},this)};var ad={};function bd(a,b){var c=ad[a];if(void 0!==c&&(!c.M||Date.now()<=c.M+3E5))return c.p;c=new Promise(function(e,k){b.onload=function(){return e(b)};b.onerror=function(g){b.parentNode&&b.parentNode.removeChild(b);k(g)};document.head.appendChild(b)});var d={M:0,p:c};c.catch(function(){return d.M=+new Date});ad[a]=d;return c}
function cd(a){var b=void 0===b?null:b;a=Xc(a);var c=document.createElement("script"),d=Sa(a.toString());c.src=Ra(d);var e;d=(c.ownerDocument&&c.ownerDocument.defaultView||window).document;var k=null===(e=d.querySelector)||void 0===e?void 0:e.call(d,"script[nonce]");(e=k?k.nonce||k.getAttribute("nonce")||"":"")&&c.setAttribute("nonce",e);b&&(c.type=b);return bd(a.toString(),c)};function dd(a,b){this.type=a;this.i=this.target=b;this.m=this.l=!1}dd.prototype.O=function(){return this.l};dd.prototype.j=function(){this.l=!0};dd.prototype.h=function(){this.m=!0};var ed=function(){if(!v.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{v.addEventListener("test",Ca,b),v.removeEventListener("test",Ca,b)}catch(c){}return a}();function Z(a,b){dd.call(this,a?a.type:"");this.relatedTarget=this.i=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.N=this.F=0;this.key="";this.o=this.u=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.J=!1;this.pointerId=0;this.pointerType="";this.g=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.i=b;if(b=a.relatedTarget){if(yb){a:{try{xb(b.nodeName);
var e=!0;break a}catch(k){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.F=zb||void 0!==a.offsetX?a.offsetX:a.layerX,this.N=zb||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.u=a.keyCode||0;this.key=a.key||"";this.o=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.J=Ab?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:fd[a.pointerType]||"";this.state=a.state;this.g=a;a.defaultPrevented&&Z.I.h.call(this)}}Fa(Z,dd);var fd={2:"touch",3:"pen",4:"mouse"};
Z.prototype.P=function(){return 0==this.g.button&&!(Ab&&this.ctrlKey)};Z.prototype.j=function(){Z.I.j.call(this);this.g.stopPropagation?this.g.stopPropagation():this.g.cancelBubble=!0};Z.prototype.h=function(){Z.I.h.call(this);var a=this.g;a.preventDefault?a.preventDefault():a.returnValue=!1};var gd="closure_listenable_"+(1E6*Math.random()|0);var hd=0;function id(a,b,c,d,e){this.listener=a;this.g=null;this.src=b;this.type=c;this.capture=!!d;this.i=e;this.key=++hd;this.h=this.L=!1}function jd(a){a.h=!0;a.listener=null;a.g=null;a.src=null;a.i=null};function kd(a){this.src=a;this.g={};this.h=0}f=kd.prototype;f.Tc=function(){var a=0,b;for(b in this.g)a+=this.g[b].length;return a};f.add=function(a,b,c,d,e){var k=a.toString();a=this.g[k];a||(a=this.g[k]=[],this.h++);var g=ld(a,b,d,e);-1<g?(b=a[g],c||(b.L=!1)):(b=new id(b,this.src,k,!!d,e),b.L=c,a.push(b));return b};
f.Wb=function(a,b,c,d){a=a.toString();if(!(a in this.g))return!1;var e=this.g[a];b=ld(e,b,c,d);return-1<b?(jd(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.g[a],this.h--),!0):!1};f.Md=function(a){a=a&&a.toString();var b=0,c;for(c in this.g)if(!a||c==a){for(var d=this.g[c],e=0;e<d.length;e++)++b,jd(d[e]);delete this.g[c];this.h--}return b};f.Ub=function(a,b){a=this.g[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
f.Tb=function(a,b,c,d){a=this.g[a.toString()];var e=-1;a&&(e=ld(a,b,c,d));return-1<e?a[e]:null};f.Vb=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Ma(this.g,function(k){for(var g=0;g<k.length;++g)if(!(c&&k[g].type!=d||e&&k[g].capture!=b))return!0;return!1})};function ld(a,b,c,d){for(var e=0;e<a.length;++e){var k=a[e];if(!k.h&&k.listener==b&&k.capture==!!c&&k.i==d)return e}return-1};var md="closure_lm_"+(1E6*Math.random()|0),nd={},od=0;function pd(a,b,c,d,e){if(d&&d.once)return qd(a,b,c,d,e);if(Array.isArray(b)){for(var k=0;k<b.length;k++)pd(a,b[k],c,d,e);return null}c=rd(c);return a&&a[gd]?a.g(b,c,Ea(d)?!!d.capture:!!d,e):sd(a,b,c,!1,d,e)}
function sd(a,b,c,d,e,k){if(!b)throw Error("Invalid event type");var g=Ea(e)?!!e.capture:!!e,h=td(a);h||(a[md]=h=new kd(a));c=h.add(b,c,d,g,k);if(c.g)return c;d=ud();c.g=d;d.src=a;d.listener=c;if(a.addEventListener)ed||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(vd(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");od++;return c}
function ud(){function a(c){return b.call(a.src,a.listener,c)}var b=wd;return a}function qd(a,b,c,d,e){if(Array.isArray(b)){for(var k=0;k<b.length;k++)qd(a,b[k],c,d,e);return null}c=rd(c);return a&&a[gd]?a.h(b,c,Ea(d)?!!d.capture:!!d,e):sd(a,b,c,!0,d,e)}
function xd(a){if("number"!==typeof a&&a&&!a.h){var b=a.src;if(b&&b[gd])b.i(a);else{var c=a.type,d=a.g;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(vd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);od--;if(c=td(b)){d=a.type;if(d in c.g){var e=c.g[d],k=Ka(e,a),g;(g=0<=k)&&Array.prototype.splice.call(e,k,1);g&&(jd(a),0==c.g[d].length&&(delete c.g[d],c.h--))}0==c.h&&(c.src=null,b[md]=null)}else jd(a)}}}
function vd(a){return a in nd?nd[a]:nd[a]="on"+a}function wd(a,b){if(a.h)a=!0;else{b=new Z(b,this);var c=a.listener,d=a.i||a.src;a.L&&xd(a);a=c.call(d,b)}return a}function td(a){a=a[md];return a instanceof kd?a:null}var yd="__closure_events_fn_"+(1E9*Math.random()>>>0);function rd(a){if("function"===typeof a)return a;a[yd]||(a[yd]=function(b){return a.handleEvent(b)});return a[yd]};function zd(){var a=this;this.promise=new Promise(function(b,c){a.resolve=b;a.reject=c})};function Ad(){var a=this;this.h=null;this.g=new mc;this.j=[];this.l=this.i=null;if(v.__globalAppLoader)return v.__globalAppLoader;try{this.g=oc()}catch(b){Bd("GoogleDevelopersObject missing or invalid")}GoogleDevelopersObject=null;w("__globalAppLoader",this);w("DevsiteApp.hasFlagAccess",function(b){return a.hasFlagAccess(b)})}Ad.prototype.m=function(){v.__globalAppLoader=null;xd(this.i);xd(this.l)};
function Cd(a){var b=[];b.push(cd("https://www.gstatic.com/external_hosted/polymer/v2/webcomponents-lite.js"));"fetch"in window&&"URL"in window||b.push(cd(U(a.g,5)+"/js/polyfills.js"));return Promise.all(b)}function Dd(a){var b=a.g.getLocale();a=U(a.g,4);return b&&"en"!==b?a.replace(/\.js$/,"__"+b.toLowerCase().replace("-","_")+".js"):a}
Ad.prototype.getEnv=function(){if(ic(this.g,11))return"PROD";var a=document.location.hostname;return a.endsWith("test.devsite.corp.google.com")||a.endsWith("test.devsite-v2-staging.googleplex.com")?"TEST":a.endsWith(".devsite.corp.google.com")||a.endsWith("devsite-v2-staging.googleplex.com")?"STAGE":"DEV"};
Ad.prototype.hasFlagAccess=function(a){a:{var b=this.getEnv(),c=P(this.g,13),d=new URL(document.location.toString());d=new Hc(d.href);var e=Object.keys(Ha);if("PROD"!==b)for(b=r(e),e=b.next();!e.done;e=b.next())if(e=e.value,Ha[e]===a&&(e=d.g.get(e),void 0!==e)){if("true"===e){a=!0;break a}if("false"===e){a=!1;break a}}a=Array.from(c).includes(a)}return a};
function Ed(){return pc(function b(){var c=this,d,e,k,g,h,l,m,q;return za(b,function(u){switch(u.g){case 1:return u.i=2,qa(u,Cd(c),4);case 4:ra(u,3);break;case 2:d=sa(u),Bd("Failed to load Devsite App dependencies: "+d.message);case 3:e=new zd;w("__devsiteAppReadyResolver",e.resolve);w("__devsiteAppReadyPromise",e.promise);w("DevsiteApp.whenReady",function(){return e.promise});if(!P(c.g,12).length){u.D(5);break}u.i=6;return qa(u,Promise.all(P(c.g,12).map(function(H){H=Xc(H);var K=document.createElement("link");
K.setAttribute("rel","stylesheet");K.setAttribute("type","text/css");K.setAttribute("href",H.toString());return bd(H.toString(),K)})),8);case 8:ra(u,5);break;case 6:k=sa(u),Bd("Failed to load Devsite App dependencies: "+k.message);case 5:return g=v.DevsiteAppTenantCustomized?U(c.g,6):U(c.g,5),u.i=9,qa(u,cd(g+Dd(c)),11);case 11:ra(u,10);break;case 9:h=sa(u);if("en"===c.g.getLocale()){Bd("Failed to load Devsite App binary: "+h.message);u.D(10);break}R(c.g,2,"en","");u.i=13;return qa(u,cd(g+U(c.g,4)),
15);case 15:ra(u,10);break;case 13:l=sa(u),Bd("Failed to load Devsite App binary: "+l.message);case 10:if(m=document,"complete"===m.readyState||"interactive"===m.readyState)u.D(0);else return q=new zd,m.addEventListener("readystatechange",function(){"interactive"!==m.readyState&&"complete"!==m.readyState||q.resolve()}),qa(u,q.promise,0)}})})}function Bd(a){throw Error(void 0===a?"Devsite has failed to load.":a);};var S=new Ad;(function(){var a=document.querySelector("devsite-content");a&&(S.i=pd(window,"message",function(b){S.j.push(b)}),S.l=qd(a,"devsite-content-updated",function(){xd(S.i);for(var b=r(S.j),c=b.next();!c.done;c=b.next())(c=c.value.g)&&window.dispatchEvent(c);S.j=[];xd(S.l)}))})();var Fd;var qc=S,Gd=window;"WeakMap"in Gd&&"performance"in Gd&&"now"in Gd.performance?(qc.h||(qc.h=Ed()),Fd=qc.h):Fd=Promise.resolve();
Fd.then(function(){v.DevsiteAppInit||Bd("Failed to load Devsite App binary");ic(S.g,9)?DevsiteAppFrameboxInit(kc(),v.DevsiteAppAuthorizedElements):DevsiteAppInit(kc(),v.DevsiteAppAuthorizedElements)});}).call(this);
