(function(_ds){var window=this;'use strict';var P0=function(a){var b=a.Kq,c=a.Lb,d=a.wn;a=a.ep;var e='<ul class="devsite-nav-list"><li class="devsite-nav-item devsite-nav-heading devsite-toc-toggle" role="heading" aria-level="2"><span class="devsite-nav-title"><span class="devsite-nav-text">Table of contents</span></span>';c&&(e=e+'<button type="button" title="'+_ds.rj("Expand/collapse contents"),e+='" class="devsite-nav-show-all button-transparent material-icons"></button>');e+="</li>";for(var g=b.length,h=0;h<g;h++){var k=b[h];
e+='<li class="devsite-nav-item"'+(c&&k.index<a?" visible":"")+'><a href="#'+_ds.W(k.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.W(h)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.W(h)+'" track-metadata-link-destination="#'+_ds.W(k.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.V(k.text)+"</span></a>";if(_ds.lj(k.children).length){e+=
'<ul class="devsite-nav-list">';k=k.children;for(var l=k.length,m=0;m<l;m++){var p=k[m];e+='<li class="devsite-nav-item"'+(c&&p.index<a?" visible":"")+'><a href="#'+_ds.W(p.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.W(h)+"."+_ds.W(m)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.W(h)+"."+_ds.W(m)+'" track-metadata-link-destination="#'+
_ds.W(p.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.V(p.text)+"</span></a></li>"}e+="</ul>"}e+="</li>"}d&&(e=c?e+'<li class="devsite-nav-item devsite-apix-link"><a href="#try-it" class="devsite-nav-title"><span class="devsite-nav-text" tooltip>Try it</span></a></li>':e+'<button type="button" class="devsite-show-apix button-primary">Try it!</button>');c&&(e=e+'<li class="devsite-toc-toggle"><button type="button" class="button-flat devsite-nav-more-items material-icons" track-type="navigation" track-name="embeddedNavExpand" title="'+
_ds.rj("Expand/collapse contents"),e+='"></button></li>');return(0,_ds.T)(e+"</ul>")},Y0=function(){var a=_ds.R.call(this)||this;a.eventHandler=new _ds.zl;a.K=new _ds.Gn;a.D=new Set;a.F=new Map;a.N=new _ds.Dn(function(){return void Q0(a)},16);a.L=new _ds.Dn(function(){return void R0(a)},33);a.o=null;a.m=null;a.j=[];a.G=!1;a.C=null;a.Lb=!1;a.J=[];a.O(_ds.Jh(S0),_ds.Jh(T0),_ds.Jh(U0),_ds.Jh(V0),_ds.Jh(W0),_ds.Jh(X0));return a},Z0=function(a){a.Lb||a.eventHandler.listen(document.body,"devsite-content-updated devsite-element-hidden devsite-element-visible devsite-page-loaded devsite-sticky-resize devsite-sticky-scroll".split(" "),
function(){a.L.xa()});a.eventHandler.listen(document.body,"devsite-content-updated",function(){Q0(a)})},$0=function(a){_ds.Q(a,function c(){var d=this,e,g,h,k;return _ds.D(c,function(l){switch(l.h){case 1:e=d;if(!("IntersectionObserver"in _ds.uk())){l.H(2);break}d.C&&d.C.disconnect();g=document.querySelector("devsite-header");h=152;if(!g){l.H(3);break}return _ds.x(l,window.customElements.whenDefined("devsite-header"),4);case 4:(k=Number(g.getAttribute("top-row--height"))+Number(g.getAttribute("bottom-row--height")))&&
(h=k);case 3:d.C=new IntersectionObserver(function(m){m=_ds.r(m);for(var p=m.next();!p.done;p=m.next())p=p.value,p.isIntersecting?e.D.add(p.target):e.D.delete(p.target);e.L.xa()},{rootMargin:h+"px 0px 0px 0px",threshold:[0,1]});case 2:d.K.resolve(),_ds.y(l)}})})},R0=function(a){return _ds.Q(a,function c(){var d=this;return _ds.D(c,function(e){if(1==e.h)return _ds.x(e,a1(d),2);if(d.m){var g="#"+d.m.id,h=encodeURI(g);g=d.F.get(g)||d.F.get(h);d.o!==g&&(d.o&&d.o.classList.remove("devsite-nav-active"),
g&&(g.classList.add("devsite-nav-active"),d.o=g))}_ds.y(e)})})},Q0=function(a){if(!a.hasAttribute("disabled")){var b=document.querySelector("devsite-content .devsite-article-body");b?(a.Lb?a.classList.add("devsite-toc-embedded"):a.classList.add("devsite-toc"),b1(a,b),a.G=!0):a.pb()}},b1=function(a,b){var c=[],d=!1,e="";switch(a.getAttribute("depth")){case "1":e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents)";break;default:e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents), h3:not(.hide-from-toc):not(#contents):not(#table-of-contents)"}a.j=
[].concat(_ds.ya(b.querySelectorAll(e))).filter(function(h){return h.id&&h.dataset.text}).filter(function(h){return c1(h)});b=_ds.r(a.j.entries());for(e=b.next();!e.done;e=b.next()){var g=_ds.r(e.value);e=g.next().value;g=g.next().value;e={id:g.id,level:g.tagName.toLowerCase(),text:g.dataset.text,children:[],index:e};"h2"===e.level?(c.push(e),d=!0):d?c[c.length-1].children.push(e):c.push(e)}_ds.Sb(a.J,c,a.Xi.bind(a))&&a.G||(c.length?(d1(a,c),a.show(),a.Lb||e1(a)):a.pb(),a.J=c)},a1=function(a){return _ds.Q(a,
function c(){var d=this,e,g,h,k,l,m,p,q;return _ds.D(c,function(t){switch(t.h){case 1:e=d;g=0;h=document.querySelector("devsite-header");if(!h){t.H(2);break}return _ds.x(t,window.customElements.whenDefined("devsite-header"),3);case 3:g=h.Fg();case 2:k=d.j.findIndex(function(u){return e.D.has(u)&&u.getBoundingClientRect().top>=g});l=d.j[k];if(!l){d.m&&d.m.getBoundingClientRect().top>window.innerHeight&&(m=d.j.indexOf(d.m),0<m&&(d.m=d.j[m-1]));t.H(0);break}return _ds.x(t,f1(d),5);case 5:p=t.j,q=l.getBoundingClientRect().top-
g,d.m=q>p&&0<k?d.j[k-1]:l,_ds.y(t)}})})},f1=function(a){return _ds.Q(a,function c(){var d,e,g,h;return _ds.D(c,function(k){if(1==k.h)return e=d=0,(g=document.querySelector("devsite-header"))?_ds.x(k,window.customElements.whenDefined("devsite-header"),3):k.H(2);2!=k.h&&(d=g.Fg(),e=g.mo());h=window.innerHeight-d;return k.return(Math.max(e-d,Math.floor(h/5)))})})},e1=function(a){_ds.Q(a,function c(){var d=this,e,g,h;return _ds.D(c,function(k){if(1==k.h)return _ds.x(k,d.K.promise,2);if(!d.C)return k.return();
d.C.disconnect();d.D.clear();d.o&&d.o.classList.remove("devsite-nav-active");d.o=null;e=_ds.r(d.j);for(g=e.next();!g.done;g=e.next())h=g.value,d.C.observe(h);_ds.y(k)})})},c1=function(a){return _ds.UJ.find(function(b){return!!_ds.il(a,b,6)})||_ds.hl(a,"devsite-selector",null,6)||_ds.il(a,"devsite-dialog",3)?!1:!0},d1=function(a,b){var c=_ds.ol(P0,{Kq:b,Lb:a.Lb,wn:!!document.body.querySelector("devsite-apix, .devsite-apix"),ep:5});b=_ds.r(c.querySelectorAll("a.devsite-nav-title"));for(var d=b.next();!d.done;d=
b.next()){d=d.value;var e=d.hash,g=encodeURI(d.hash);a.F.set(e,d);a.F.set(g,d)}_ds.Bk(a);a.Lb&&_ds.Zh(a,"hidden","",c);a.appendChild(c);if(a.Lb){if(8<=a.getElementsByClassName("devsite-nav-item").length){b=_ds.r(a.querySelectorAll(".devsite-nav-show-all, .devsite-nav-more-items"));for(d=b.next();!d.done;d=b.next())a.eventHandler.listen(d.value,"click",function(){a.hasAttribute("expanded")?a.removeAttribute("expanded"):_ds.Zh(a,"expanded","")});_ds.Zh(a,"expandable","")}setTimeout(function(){c.removeAttribute("hidden")},
0)}};var S0=_ds.xa(["disabled"]),T0=_ds.xa(["has-toc"]),U0=_ds.xa(["hidden"]),V0=_ds.xa(["expandable"]),W0=_ds.xa(["expanded"]),X0=_ds.xa(["visible"]);_ds.v(Y0,_ds.R);_ds.f=Y0.prototype;_ds.f.connectedCallback=function(){this.Lb=this.hasAttribute("devsite-toc-embedded");Q0(this);Z0(this)};_ds.f.disconnectedCallback=function(){this.pb();this.G=!1;_ds.Fl(this.eventHandler)};
_ds.f.uh=function(a){a=a&&"false"===a.toLowerCase();this.J=[];_ds.Bk(this);a?(_ds.Zh(this,"disabled",""),this.pb()):(this.removeAttribute("disabled"),this.show(),this.N.xa())};_ds.f.pb=function(){_ds.Bk(this);this.dispatchEvent(new CustomEvent("devsite-element-hidden",{bubbles:!0}));this.removeAttribute("visible");_ds.Zh(this,"hidden","");if(!this.Lb){var a=document.querySelector(".devsite-main-content");a&&a.removeAttribute("has-toc")}};
_ds.f.show=function(){this.dispatchEvent(new CustomEvent("devsite-element-visible",{bubbles:!0}));this.removeAttribute("hidden");_ds.Zh(this,"visible","");if(!this.Lb){var a=document.querySelector(".devsite-main-content");a&&_ds.Zh(this,"has-toc","",a);$0(this)}};_ds.f.Xi=function(a,b){var c=!0;if(a.children.length||b.children.length)c=_ds.Sb(a.children,b.children,this.Xi.bind(this));return c&&a.id===b.id&&a.text===b.text};
_ds.n.Object.defineProperties(Y0,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["max-height","offset"]}}});Y0.prototype.renderUpdatedContent=Y0.prototype.uh;Y0.prototype.disconnectedCallback=Y0.prototype.disconnectedCallback;Y0.prototype.connectedCallback=Y0.prototype.connectedCallback;try{window.customElements.define("devsite-toc",Y0)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteToc",a)};})(_ds_www);
