(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var PU=function(a,b){MU()&&(b=NU()?"translate3d("+b+"px,0px,0px)":"translate("+b+"px,0px)",_ds.Jn(a,OU(),b))},SU=function(){var a=_ds.R.call(this)||this;a.N=-1;a.o=new _ds.zl;a.J=new _ds.zl;a.F=0;a.K=new MutationObserver(function(){return QU(a)});a.V=new _ds.Dn(function(){QU(a);RU(a)},15);a.C=0;a.j=0;a.D=0;a.m=0;a.G=!1;return a},UU=function(a){a.o.listen(a,"devsite-search-toggle",function(b){b=b.ma;_ds.il(b.target,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",
""):a.removeAttribute("search-active"))});a.o.listen(document.body,"devsite-sitemask-hidden",function(){return document.body.removeAttribute("devsite-book-nav--open")});a.o.listen(window,"resize",function(){return TU(a)});a.o.listen(document.body,["devsite-page-loaded","devsite-content-updated"],function(){TU(a)});a.o.listen(a,"click",function(b){b.defaultPrevented||"devsite-hamburger-menu"!=b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",
""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})))})},TU=function(a){window.requestAnimationFrame(function(){return a.V.xa()})},VU=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},QU=function(a){a.C=VU(a,".devsite-top-logo-row-wrapper-wrapper");a.j=VU(a,".devsite-collapsible-section");a.D=VU(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",a.C);a.setAttribute("bottom-row--height",a.j);a.setAttribute("bottom-tabs--height",a.D);document.body.style.setProperty("--devsite-js-header-top-row-height",
a.C+"px");document.body.style.setProperty("--devsite-js-header-lower-section-height",a.j+"px");document.body.style.setProperty("--devsite-js-header-lower-tabs-height",a.D+"px");document.body.style.setProperty("--devsite-js-header-height",a.Fg()+"px");WU(a)},XU=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){var b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity=1;a.appendChild(b)}},WU=function(a){var b=
a.querySelector(".devsite-collapsible-section");a.m>=a.j&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.m<a.j-a.D&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.m!==a.N&&(document.body.style.setProperty("--devsite-js-header-lower-tabs-offset",a.m+"px"),_ds.Jn(b,"transform","translate3d(0, -"+a.m+"px, 0)"),RU(a),a.N=a.m)},YU=function(a){var b=a.querySelector(".devsite-top-logo-row-middle"),c=a.querySelector("devsite-search"),d=
a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.Fl(a.J);a.F&&window.cancelAnimationFrame(a.F);c.removeAttribute("transition");a.removeAttribute("search-expanded");var e=new _ds.ak(b.offsetWidth,b.offsetHeight);b=new _ds.ak(c.offsetWidth,c.offsetHeight);var g=_ds.$n(c,"margin"),h="rtl"===document.documentElement.getAttribute("dir")?1:-1,k=(e.width-g.left-g.right)/b.width;e=(e.width-(b.width+g.left+g.right))*h;var l=(g=a.hasAttribute("search-active"))?e:0,m=g?k:1;_ds.Jn(d,{opacity:1,width:b.width+
"px",height:b.height+"px"});PU(c,a.hasAttribute("search-active")?0:e);_ds.Dl(a.J,d,_ds.Wl,function(){var p=a.querySelector("devsite-search"),q=a.querySelector(".devsite-search-background");q&&(q.style.opacity=0);p&&(p.removeAttribute("transition"),PU(p,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.F=window.requestAnimationFrame(function(){c.setAttribute("transition","");if(MU()){var p=NU()?"scale3d("+m+",1,1)":"scale("+m+",1)";_ds.Jn(d,
OU(),p)}PU(c,l)})}},ZU=function(a,b){var c,d,e,g;_ds.cb(function(h){if(1==h.h){if(!a.hasAttribute("billboard"))return h.return();c=a.querySelector("devsite-search");d=a.querySelector("devsite-search input.devsite-search-query");e=a.querySelector(".devsite-header-billboard-search devsite-search");g=e.querySelector("input.devsite-search-query");if(!b)return e.removeAttribute("disabled"),document.activeElement===d&&g.focus(),c.setAttribute("disabled",""),h.H(0);c.removeAttribute("disabled");return document.activeElement!==
g?h.H(3):_ds.x(h,_ds.wm(),4)}3!=h.h&&d.focus();e.setAttribute("disabled","");_ds.y(h)})},RU=function(a){0===a.j?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},$U=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},
aV=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.G=!0,_ds.$h(a,c,b))};var MU=_ds.Gb(function(){return!_ds.rk||0<=_ds.Gc(_ds.lL,9)}),NU=_ds.Gb(function(){return _ds.tk||_ds.FB||_ds.Ln&&0<=_ds.Gc(_ds.lL,10)||_ds.rk&&0<=_ds.Gc(_ds.lL,10)}),OU=_ds.Gb(function(){return _ds.rk&&9==_ds.Rn?"-ms-transform":"transform"});_ds.v(SU,_ds.R);_ds.f=SU.prototype;_ds.f.attributeChangedCallback=function(a,b,c){switch(a){case "offset":this.m=parseFloat(this.getAttribute("offset"))||0;WU(this);break;case "search-active":YU(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),ZU(this,a)}};
_ds.f.connectedCallback=function(){UU(this);XU(this);RU(this);QU(this);this.K.observe(this,{childList:!0,subtree:!0});WU(this);var a=_ds.em();this.L=_ds.Wi(_ds.Yi(a.href),"authuser")};_ds.f.disconnectedCallback=function(){_ds.Fl(this.o);this.K.disconnect()};_ds.f.Fg=function(){return this.C+this.j-this.m};_ds.f.mo=function(){return this.C+this.j};
_ds.f.Ta=function(a){this.G=!1;if(a){aV(this,a,".devsite-header-upper-tabs");aV(this,a,".devsite-collapsible-section");aV(this,a,".devsite-product-name-wrapper");aV(this,a,"devsite-language-selector");aV(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&$U(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&($U(c,b),c=_ds.em(),c=_ds.Wi(_ds.Yi(c.href),"authuser"),c!==this.L&&(this.L=c,b.refresh()));
_ds.$h(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));_ds.$h(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.G&&a&&(_ds.Bk(this),this.appendChild(a));XU(this);TU(this)};_ds.n.Object.defineProperties(SU,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["offset","search-active","bottom-row--hidden"]}}});
SU.prototype.updateContent=SU.prototype.Ta;SU.prototype.disconnectedCallback=SU.prototype.disconnectedCallback;SU.prototype.connectedCallback=SU.prototype.connectedCallback;SU.prototype.attributeChangedCallback=SU.prototype.attributeChangedCallback;try{window.customElements.define("devsite-header",SU)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
