(function(_ds){var window=this;'use strict';var mO=function(a,b){a.href=_ds.Vh(b)},nO=function(){return(0,_ds.T)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},oO=function(){return(0,_ds.T)('<div class="devsite-book-nav-blur"></div>')},qO=function(){var a=_ds.R.call(this)||this;a.o=!1;a.m=null;a.eventHandler=new _ds.zl;a.G=function(){};a.C=new Set;a.J=!1;a.background=document.createElement("div");a.background.classList.add("devsite-book-nav-bg");
a.j=_ds.ol(nO);a.D=_ds.ol(oO);a.K=new Promise(function(b){a.G=b});a.F=new _ds.Dn(function(){a.o&&pO(a)},20);return a},sO=function(a,b,c){c=void 0===c?!0:c;b=Array.from((void 0===b?a:b).querySelectorAll(".devsite-nav-title"));a.C=new Set(b);if(!_ds.em().hash&&c)rO(a,a.C);else for(c=new _ds.sE,a=_ds.r(a.C),b=a.next();!b.done;b=a.next())_ds.uE(c,b.value)},rO=function(a,b){_ds.Q(a,function d(){var e=this,g,h,k,l,m,p,q;return _ds.D(d,function(t){if(1==t.h)return g=e,e.o?_ds.x(t,(0,_ds.tp)(),2):t.return();
h=t.j;k=new _ds.sE;l=function(u){u=u.target;_ds.uE(k,u);g.C.delete(u);h.unregisterIntersectionForElement(u)};m=_ds.r(b);for(p=m.next();!p.done;p=m.next()){q=p.value;try{h.registerIntersectionForElement(q,l)}catch(u){l({target:q})}}_ds.y(t)})})},pO=function(a){var b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.Zh(a,"visually-hidden","",c))},xO=function(a){a.eventHandler.listen(a,"click",function(b){var c;
if(!b.defaultPrevented){var d=b.target;"devsite-close-nav"===d.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.Zh(a,"top-level-nav",""));if(d.hasAttribute("menu")){var e=d.getAttribute("menu");e&&tO(a,e)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}if(!(d.classList.contains("devsite-nav-toggle")||d.classList.contains("devsite-nav-title-no-path")||
(null===(c=d.parentElement)||void 0===c?0:c.classList.contains("devsite-nav-title-no-path")))){a.m&&(b=a.m.querySelector("[menu=_book]"))&&b.contains(d)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}));var g;d instanceof Element&&d.matches("a.devsite-nav-title")?g=d:g=_ds.hl(d,"a","devsite-nav-title");g&&!g.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}))}}});a.eventHandler.listen(a,[uO,"focusin"],function(b){return void vO(a,
b)});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",function(){a.m&&(tO(a,"_book")?a.removeAttribute("top-level-nav"):_ds.Zh(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",function(){return void a.F.xa()});a.eventHandler.listen(a,"devsite-content-updated",function(){a.F.xa()});a.eventHandler.listen(a,"scroll",function(){_ds.Zh(a,"user-scrolled","")});a.eventHandler.listen(a.j,"click",function(){wO(a)})},tO=function(a,b){var c=!1;if(a.m)for(var d=
_ds.r(a.m.querySelectorAll("[menu]")),e=d.next();!e.done;e=d.next())e=e.value,e.getAttribute("menu")===b?(e.removeAttribute("hidden"),c=!0):_ds.Zh(a,"hidden","",e);return c},vO=function(a,b){b.defaultPrevented||(b=_ds.gl(b.target,function(c){return c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a},!0),b!==a&&mO(b,_ds.So(_ds.lm(b.href).href)))},zO=function(a){return _ds.Q(a,function c(){var d=this;return _ds.D(c,function(e){switch(e.h){case 1:if(!d.o)return e.return();d.removeAttribute("user-scrolled");
return _ds.x(e,_ds.wm(),2);case 2:return _ds.x(e,yO(d),3);case 3:return _ds.x(e,d.K,4);case 4:return _ds.x(e,(0,_ds.tp)(),5);case 5:return _ds.x(e,_ds.wm(),6);case 6:return _ds.x(e,yO(d),0)}})})},AO=function(a,b){(b=void 0===b?a:b)||(b=a);var c=_ds.r(b.querySelectorAll(".devsite-nav-active"));for(a=c.next();!a.done;a=c.next())a.value.classList.remove("devsite-nav-active");a=_ds.Bm(_ds.em().pathname);a='[href="'+_ds.lm(a).href+'"], [href="'+a+'"],\n        [alt-paths~="'+a+'"]';b=_ds.r(b.querySelectorAll(a));
for(a=b.next();!a.done;a=b.next())a.value.classList.add("devsite-nav-active")},BO=function(a,b){(b=void 0===b?a:b)||(b=a);var c=b.querySelector(".devsite-mobile-nav-bottom");if(c)for(var d=c.querySelector(".devsite-nav-active");d&&d.parentElement&&d.parentElement!==b;)d.hasAttribute("collapsed")&&(d.removeAttribute("animatable"),_ds.Dl(a.eventHandler,d,"devsite-expandable-nav-transition-end",function(){d&&_ds.Zh(a,"animatable","",d)}),d.removeAttribute("collapsed")),d=d.parentElement},yO=function(a){return _ds.Q(a,
function c(){var d=this,e;return _ds.D(c,function(g){if(1==g.h)return d.o&&d.m?_ds.x(g,(0,_ds.tp)(),2):g.return();if(4!=g.h)return(e=d.m.querySelector(".devsite-nav-active"))?d.hasAttribute("user-scrolled")?g.H(4):_ds.x(g,CO(d,e),4):g.H(0);_ds.Zh(d,"animatable","");_ds.y(g)})})},CO=function(a,b){return _ds.Q(a,function d(){var e=this,g,h;return _ds.D(d,function(k){if(1==k.h){if(!e.o)return k.return();g=e.hasAttribute("user-scrolled");h=_ds.Tn(b,e,!0);e.scrollTop=h.y;return _ds.x(k,_ds.wm(),2)}g&&
_ds.Zh(e,"user-scrolled","");_ds.y(k)})})},DO=function(a){return _ds.Q(a,function c(){var d,e=this,g,h,k;return _ds.D(c,function(l){if(1==l.h)return _ds.x(l,(0,_ds.tp)(),2);d=l.j;g=_ds.r(e.C);for(h=g.next();!h.done;h=g.next())k=h.value,d.unregisterIntersectionForElement(k);_ds.y(l)})})},wO=function(a){_ds.Q(a,function c(){var d,e,g=this;return _ds.D(c,function(h){if(1==h.h)return e=(d=document.documentElement.scrollHeight-document.documentElement.clientHeight)?document.documentElement.scrollTop/d:
0,g.hasAttribute("collapsed")?(_ds.Zh(g,"aria-expanded","true",g.j),_ds.Zh(g,"aria-label","Hide side navigation",g.j),_ds.Zh(g,"data-title","Hide side navigation",g.j),g.removeAttribute("collapsed"),EO(g,"Expanded book nav")):(g.j.removeAttribute("aria-expanded"),_ds.Zh(g,"aria-label","Show side navigation",g.j),_ds.Zh(g,"data-title","Show side navigation",g.j),_ds.Zh(g,"collapsed",""),EO(g,"Collapsed book nav")),_ds.x(h,_ds.wm(),2);d=document.documentElement.scrollHeight-document.documentElement.clientHeight;
document.documentElement.scrollTop=Math.round(e*d);_ds.y(h)})})},EO=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))};var FO=_ds.xa(["animatable"]),GO=_ds.xa(["aria-expanded"]),HO=_ds.xa(["aria-label"]),IO=_ds.xa(["collapsed"]),JO=_ds.xa(["data-title"]),KO=_ds.xa(["fixed"]),LO=_ds.xa(["has-book-nav"]),MO=_ds.xa(["hidden"]),NO=_ds.xa(["role"]),OO=_ds.xa(["top-level-nav"]),PO=_ds.xa(["user-scrolled"]),QO=_ds.xa(["visually-hidden"]),uO="onpointerover"in window?"pointerover":"mouseover";_ds.v(qO,_ds.R);_ds.f=qO.prototype;
_ds.f.connectedCallback=function(){var a,b;return _ds.Q(this,function d(){var e=this,g;return _ds.D(d,function(h){if(1==h.h)return e.o=!0,e.O(e.h(FO),e.h(GO),e.h(HO),e.h(IO),e.h(JO),e.h(KO),e.h(LO),e.h(MO),e.h(NO),e.h(OO),e.h(PO),e.h(QO)),_ds.Zh(e,"role","menu"),_ds.Ck(e.background,e),e.hasAttribute("hidden")&&(_ds.Zh(e,"hidden","",e.j),_ds.Zh(e,"hidden","",e.D)),_ds.x(h,(0,_ds.tp)(),2);if(3!=h.h)return g=h.j,e.J=g.hasFlagAccess(150),e.J&&(null===(a=e.parentElement)||void 0===a?void 0:a.insertBefore(e.j,
e.nextSibling),_ds.Zh(e,"aria-label","Hide side navigation",e.j),_ds.Zh(e,"data-title","Hide side navigation",e.j),_ds.Zh(e,"aria-expanded","true",e.j),null===(b=e.parentElement)||void 0===b?void 0:b.insertBefore(e.D,e.nextSibling)),pO(e),xO(e),_ds.x(h,e.init(),3);sO(e);_ds.y(h)})})};
_ds.f.disconnectedCallback=function(){this.o=!1;_ds.Fl(this.eventHandler);DO(this);this.C.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.Zh(this,"visually-hidden","",a);a=_ds.r([this.background,this.j,this.D]);for(var b=a.next();!b.done;b=a.next())(b=b.value)&&_ds.Fk(b);this.removeAttribute("animatable");document.body.style.removeProperty("--devsite-js-book-nav-scrollbar-width")};
_ds.f.attributeChangedCallback=function(a){"hidden"===a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.Zh(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);for(var c=_ds.r([this.background,
this.j,this.D]),d=c.next();!d.done;d=c.next())(d=d.value)&&(b?_ds.Zh(this,a,"",d):d.removeAttribute(a))}"fixed"===a&&this.G()};
_ds.f.init=function(a){a=void 0===a?!0:a;return _ds.Q(this,function c(){var d=this,e,g,h;return _ds.D(c,function(k){if(1==k.h){if(!d.o)return k.return();document.body.style.setProperty("--devsite-js-book-nav-scrollbar-width",d.offsetWidth-d.clientWidth+"px");d.m=d.querySelector(".devsite-mobile-nav-bottom");!d.hasAttribute("hidden")&&d.m&&d.m.querySelector(".devsite-nav-active")||_ds.Zh(d,"animatable","");_ds.Zh(d,"top-level-nav","");d.m&&d.m.querySelector("[menu=_book]")&&d.removeAttribute("top-level-nav");
0===d.children.length&&_ds.Zh(d,"hidden","");if(d.background)for(e=_ds.r(["hidden","fixed"]),g=e.next();!g.done;g=e.next())h=g.value,d.hasAttribute(h)&&_ds.Zh(d,h,"",d.background);return!d.hasAttribute("hidden")&&a?(AO(d),BO(d),_ds.x(k,zO(d),0)):_ds.x(k,_ds.wm(),4)}return _ds.x(k,yO(d),0)})})};
_ds.f.Ta=function(a){return _ds.Q(this,function c(){var d=this,e;return _ds.D(c,function(g){switch(g.h){case 1:if(!a){_ds.Bk(d);g.H(2);break}d.removeAttribute("animatable");e=a.querySelector("nav")||null;AO(d,e);BO(d,e);if(!e){g.H(3);break}return _ds.x(g,DO(d),4);case 4:d.C.clear(),sO(d,e,!1);case 3:_ds.$h(d,d.querySelector("nav"),e);case 2:return _ds.x(g,_ds.wm(),5);case 5:return _ds.x(g,d.init(!1),0)}})})};
_ds.n.Object.defineProperties(qO,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["collapsed","fixed","hidden"]}}});qO.prototype.updateContent=qO.prototype.Ta;qO.prototype.attributeChangedCallback=qO.prototype.attributeChangedCallback;qO.prototype.disconnectedCallback=qO.prototype.disconnectedCallback;qO.prototype.connectedCallback=qO.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",qO)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
