(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var vV=function(){var a=_ds.R.call(this)||this;a.m=new _ds.ro;a.j=new _ds.zl;tV().then(function(){uV(a)});return a},uV=function(a){var b;return _ds.cb(function(c){return(b=_ds.$J.get("django_language"))?_ds.x(c,a.m.set("language_preference",b),0):c.H(0)})},xV=function(a){_ds.Fl(a.j);var b=a.querySelector(".devsite-language-selector-select");b&&a.j.listen(b,"change",function(c){wV(a,c)})},wV=function(a,b){var c,d;_ds.cb(function(e){switch(e.h){case 1:return _ds.x(e,DevsiteApp.whenReady(),
2);case 2:return _ds.$J.remove("django_language"),c=b.target,_ds.$J.set("django_language",c.value,{Cb:15552E3,path:"/"}),d=document.documentElement.getAttribute("lang"),_ds.x(e,yV(a,d,c.value),3);case 3:return _ds.x(e,uV(a),4);case 4:var g=_ds.So(_ds.Xi(new _ds.Ii(_ds.uk().location.href),"hl").toString());_ds.uk().location.assign(_ds.Vh(g));_ds.y(e)}})},yV=function(a,b,c){var d,e;return _ds.cb(function(g){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",
label:"Language Selector",action:b+" to "+c},bubbles:!0}));d={name:"change",type:"languageSelector",metadata:{"selected-language":c,"original-language":b}};e={eventData:JSON.stringify(d)};a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:e,bubbles:!0}));_ds.y(g)})},tV=function(){return _ds.cb(function(a){if(1==a.h)return _ds.$J.get("django_language")?a.H(0):_ds.x(a,DevsiteApp.whenReady(),3);_ds.$J.set("django_language",DevsiteApp.getLocale()||"en",{Cb:15552E3,path:"/"});
_ds.y(a)})};_ds.v(vV,_ds.R);vV.prototype.connectedCallback=function(){xV(this)};vV.prototype.disconnectedCallback=function(){_ds.Fl(this.j)};vV.prototype.Ta=function(a){a&&(_ds.$h(this,this.querySelector(".devsite-language-selector-menu"),a.querySelector(".devsite-language-selector-menu")),xV(this))};vV.prototype.updateContent=vV.prototype.Ta;vV.prototype.disconnectedCallback=vV.prototype.disconnectedCallback;vV.prototype.connectedCallback=vV.prototype.connectedCallback;try{window.customElements.define("devsite-language-selector",vV)}catch(a){console.warn("devsite.app.customElement.DevsiteLanguageSelector",a)};})(_ds_www);
