(function(_ds){var window=this;'use strict';var C_=function(a){var b=a.Hh;a=a.vn;for(var c='<div class="dropdown-tabbed-menu"><ul class="dropdown-tabbed-menu-list">',d=a.length,e=0;e<d;e++){var g=a[e];c+='<li class="dropdown-tabbed-menu-list-item"><a href="#" column-id="'+_ds.W(g.un)+'" tabindex="0" track-type="nav" track-name="'+_ds.W(g.text)+'" track-metadata-eventdetail="#" track-metadata-position="nav - '+_ds.W(b)+'" track-metadata-module="secondary nav">'+_ds.V(g.text)+"</a></li>"}return(0,_ds.T)(c+"</ul></div>")},D_=function(a){var b=
a.Hh,c=a.href;a=a.text;return(0,_ds.T)('<div class="dropdown-tabbed-menu-button"><a href="'+_ds.W(_ds.Nj(c))+'" track-type="nav" track-name="'+_ds.W(a)+'" track-metadata-eventdetail="'+_ds.W(c)+'" track-metadata-position="nav - '+_ds.W(b)+'" track-metadata-module="secondary nav">'+_ds.V(a)+"</a></div>")},V_=function(){var a=_ds.R.call(this)||this;a.V=20;a.eventHandler=new _ds.zl;a.m=new _ds.zl;a.K=new _ds.Dn(function(){E_(a)},a.V);a.L=null;a.D=null;a.J=!1;a.G=0;a.j=null;a.F=null;a.N=0;a.o=[];a.C=
null;a.O(a.h(F_),a.h(G_),a.h(H_),a.h(I_),a.h(J_),a.h(K_),a.h(L_),a.h(M_),a.h(N_),a.h(O_),a.h(P_),a.h(Q_),a.h(R_),a.h(S_),a.h(T_),a.h(U_));return a},d0=function(a){a.eventHandler.listen(document.body,"devsite-sticky-resize",function(){return a.K.xa()});a.eventHandler.listen(a,"click",function(e){if(!(e.shiftKey||e.ctrlKey||e.metaKey||e.altKey)){var g=e.target,h=W_(a,g);if(h)if(a.D&&a.D(e))e.preventDefault(),e.stopPropagation();else if(h===a.j)X_(a,e);else if(Y_(a),g.classList.contains("devsite-tabs-dropdown-toggle"))e.preventDefault(),
e.stopPropagation(),h.hasAttribute("dropdown--open")?Z_(a):$_(a,h);else{var k;"A"===g.tagName?k=g:k=_ds.hl(g,"A");var l=h.querySelector(".devsite-tabs-dropdown");if(l&&l.contains(g))k&&k.hasAttribute("href")||(e.preventDefault(),e.stopPropagation());else{if(e=a.L||a.querySelector("[active]"))e.removeAttribute("active"),_ds.Zh(a,"aria-selected","false",e);_ds.Zh(a,"active","",h);_ds.Zh(a,"aria-selected","true",h);a.L=h;k&&k&&"#"!==k.href||a.K.xa()}}}});if(a.querySelector("tab[dropdown]")||a.querySelector("tab[overflow-tab]")){var b=
"onpointermove"in window?"pointerover":"mouseover",c="onpointermove"in window?"pointerleave":"mouseleave",d=a.querySelectorAll("tab[clickable]");if(d.length){b=_ds.r(d);for(c=b.next();!c.done;c=b.next())a.eventHandler.listen(c.value,"click",function(e){var g,h=e.target,k=W_(a,h),l=null===k||void 0===k?void 0:k.querySelector(".devsite-tabs-dropdown");!l||(null===(g=a.j)||void 0===g?0:g.contains(h))||l.contains(h)||(e.preventDefault(),e.stopPropagation(),(null===k||void 0===k?0:k.hasAttribute("dropdown--open"))?
Z_(a):a0(a,e))});a.eventHandler.listen(document.body,"click",function(e){a.C&&!a.C.contains(e.target)&&Z_(a)})}else a.eventHandler.listen(a,b,function(e){return void b0(a,e)}),a.eventHandler.listen(a,c,function(){return void c0(a)})}b=[].concat(_ds.ya(a.querySelectorAll(".devsite-tabs-close-button")));b=_ds.r(b);for(c=b.next();!c.done;c=b.next())a.eventHandler.listen(c.value,"click",function(){return Z_(a)})},c0=function(a){return _ds.Q(a,function c(){var d,e=this;return _ds.D(c,function(g){if(1==
g.h)return _ds.x(g,(0,_ds.tp)(),2);d=g.j;if(d.isTouchEnabled())return g.return();Z_(e,300);_ds.y(g)})})},b0=function(a,b){return _ds.Q(a,function d(){var e,g=this;return _ds.D(d,function(h){if(1==h.h)return _ds.x(h,(0,_ds.tp)(),2);e=h.j;if(e.isTouchEnabled())return h.return();a0(g,b);_ds.y(h)})})},a0=function(a,b){var c,d=b.target,e=W_(a,d);e&&(e===a.j||(null===(c=a.j)||void 0===c?0:c.contains(d))?X_(a,b):$_(a,e))},Z_=function(a,b){b=void 0===b?0:b;_ds.Fl(a.m);window.clearTimeout(a.G);var c=a.querySelector("tab[dropdown--open]");
if(c){var d=c.querySelector(".devsite-tabs-dropdown");_ds.Zh(a,"dropdown-transition","",d);_ds.Dl(a.m,d,_ds.Wl,function(){null===d||void 0===d?void 0:d.removeAttribute("dropdown-transition");a.removeAttribute("dropdown--open");_ds.Zh(a,"hidden","",d)});a.G=window.setTimeout(function(){c.removeAttribute("dropdown--open");e0(a,c)},b)}else a.removeAttribute("dropdown--open");Y_(a)},$_=function(a,b){_ds.Q(a,function d(){var e=this,g,h,k,l,m,p,q,t,u,w,z,J;return _ds.D(d,function(M){if(1==M.h){g=e;Y_(e);
if(!b.hasAttribute("dropdown"))return Z_(e),M.return();_ds.Fl(e.m);window.clearTimeout(e.G);return b.hasAttribute("dropdown--open")?M.return():_ds.x(M,(0,_ds.tp)(),2)}h=M.j;h.isTouchEnabled()&&_ds.Dl(e.m,document.body,"click",function(L){g.contains(L.target)||Z_(g)});k=e.querySelector("tab[dropdown--open]");l=b.querySelector(".devsite-tabs-dropdown");if(!l)return k&&(k.removeAttribute("dropdown--open"),e0(e,k)),M.return();l.removeAttribute("hidden");_ds.Jn(l,"left","");m=_ds.pk(window||window);p=
Array.from(l.querySelectorAll(".devsite-tabs-dropdown-column"));!b.hasAttribute("dropdown-full")&&1<p.length&&(q=[],p.forEach(function(L){q.push(L.scrollWidth)}),t=Math.max.apply(null,q),u=t*p.length,u<m.width?p.forEach(function(L){_ds.Jn(L,"width",t+"px")}):_ds.Zh(e,"dropdown-full","",b));w=l.getBoundingClientRect();b.hasAttribute("dropdown-full")?_ds.Jn(l,"left","-"+w.left+"px"):(z=Math.min(w.left,w.left+w.width-m.width),0<z&&_ds.Jn(l,"left","-"+z+"px"));k?(k.removeAttribute("dropdown--open"),e0(e,
k),J=k.querySelector(".devsite-tabs-dropdown"),null===J||void 0===J?void 0:J.removeAttribute("dropdown-transition"),_ds.Zh(e,"hidden","",J)):(_ds.Zh(e,"dropdown-transition","",l),_ds.Dl(e.m,l,_ds.Wl,function(){return l.removeAttribute("dropdown-transition")}));window.requestAnimationFrame(function(){_ds.Zh(g,"dropdown--open","");_ds.Zh(g,"dropdown--open","",b);e0(g,b)});_ds.y(M)})})},W_=function(a,b){for(;b&&b!==a;){if("TAB"===b.tagName.toUpperCase())return b;b=b.parentElement}return null},X_=function(a,
b){var c;_ds.Q(a,function e(){var g=this,h,k,l;return _ds.D(e,function(m){switch(m.h){case 1:return h=g,b.preventDefault(),b.stopPropagation(),document.body.dispatchEvent(new CustomEvent("devsite-close-overflow-tabs")),_ds.x(m,_ds.wm(),2);case 2:return g.hasAttribute("overflow-menu--open")?m.return():_ds.x(m,(0,_ds.tp)(),3);case 3:return k=m.j,_ds.x(m,k.whenReady(),4);case 4:k.isTouchEnabled()&&(l=function(p){h.contains(p.target)||Y_(h);_ds.El(h.m,document.body,["devsite-close-overflow-tabs","click"],
l)},g.m.listen(document.body,["devsite-close-overflow-tabs","click"],l)),null===(c=g.F)||void 0===c?void 0:c.removeAttribute("hidden"),_ds.Zh(g,"overflow-menu--open",""),_ds.y(m)}})})},Y_=function(a){_ds.Zh(a,"hidden","",a.F);a.removeAttribute("overflow-menu--open")},E_=function(a){var b,c,d;_ds.Zh(a,"hidden","",a.j);if(!(a.o&&3>a.o.length)){var e=f0(a,a);if(0!==e){var g=(null===(b=a.o)||void 0===b?void 0:b.slice())||[],h=0,k;g.forEach(function(t){t.parentNode!==a.C&&(k?_ds.Dk(t,k):_ds.Ek(a.C,t,0));
k=t;h+=f0(a,t)});if(!(h<=e)){var l=a.N;null===(c=a.j)||void 0===c?void 0:c.removeAttribute("hidden");var m=a.querySelector("[active]");for(m&&(l+=f0(a,m));null===g||void 0===g?0:g.length;){var p=g.shift();if(p!==m){var q=f0(a,p||null);l+q<=e?l+=q:null===(d=a.F)||void 0===d?void 0:d.appendChild(p)}}}}}},g0=function(a){var b;a.o=Array.from(a.querySelectorAll("tab"));var c=a.querySelector(".devsite-tabs-wrapper");c||(c=a.ownerDocument.createElement("div"),c.classList.add("devsite-tabs-wrapper"),a.appendChild(c),
null===(b=a.o)||void 0===b?void 0:b.forEach(function(g){return null===c||void 0===c?void 0:c.appendChild(g)}));a.C=c;a.appendChild(c);if(!a.hasAttribute("no-overflow")){var d=a.ownerDocument.createElement("tab");_ds.Zh(a,"overflow-tab","",d);var e=a.ownerDocument.createElement("a");_ds.Id(e,"#");e.textContent="More";e.classList.add("devsite-icon");e.classList.add("devsite-icon-arrow-drop-down");d.appendChild(e);a.j=d;e=a.ownerDocument.createElement("div");e.classList.add("devsite-tabs-overflow-menu");
_ds.Zh(a,"scrollbars","",e);_ds.Zh(a,"hidden","",e);a.F=e;d.appendChild(e);c.appendChild(d)}},f0=function(a,b){if(!b)return 0;for(var c=[],d=b;d.parentElement&&0===d.offsetWidth;)c.push(d),_ds.Zh(a,"render-hidden","",d),d=d.parentElement;a=_ds.Un(b).width;c=_ds.r(c);for(b=c.next();!b.done;b=c.next())b.value.removeAttribute("render-hidden");return a},e0=function(a,b){_ds.Zh(a,"aria-expanded",""+b.hasAttribute("dropdown--open"),b.querySelector(".devsite-tabs-dropdown-toggle"))},h0=function(a,b){return _ds.Q(a,
function d(){var e;return _ds.D(d,function(g){if(1==g.h)return _ds.x(g,(0,_ds.tp)(),2);e=g.j;return e.isTouchEnabled()||!b.hasAttribute("generated-tab-menu")?g.return(!1):g.return(!0)})})},k0=function(a){var b;null===(b=a.o)||void 0===b?void 0:b.forEach(function(c,d){return _ds.Q(a,function g(){var h=this,k,l,m,p,q,t,u,w,z;return _ds.D(g,function(J){if(1==J.h)return k=h,_ds.x(J,h0(h,c),2);l=J.j;if(!l)return J.return();m=Array.from(c.querySelectorAll(".devsite-tabs-dropdown-column"));p=c.querySelector(".devsite-tabs-dropdown");
q=c.querySelector("a");m.forEach(function(M,L){_ds.Zh(k,"column-id","tab-"+d+"-column-"+L,M)});t=m.map(function(M){var L=M.querySelector(".devsite-nav-title")||M.querySelector(".devsite-nav-item-title");return{un:M.getAttribute("column-id"),text:null===L||void 0===L?void 0:L.textContent}});q&&(u=_ds.ol(C_,{Hh:(q.textContent||"").toLowerCase().trim(),vn:t}),p&&(w=c.querySelector(".devsite-tabs-dropdown-content")))&&(p.insertBefore(u,w),z=c.querySelector(".dropdown-tabbed-menu a"),i0(c),h.eventHandler.listen(u,
"click",function(M){M.preventDefault();var L=c.querySelector(".dropdown-tabbed-menu-button");M=M.target;L&&M.tagName&&"a"===M.tagName.toLowerCase()&&!L.contains(M)&&j0(k,c,(null===M||void 0===M?void 0:M.getAttribute("column-id"))||"")}),z&&j0(h,c,z.getAttribute("column-id")||""));_ds.y(J)})})})},j0=function(a,b,c){var d=Array.from(b.querySelectorAll(".devsite-tabs-dropdown-column"));b=Array.from(b.querySelectorAll(".dropdown-tabbed-menu a"));b.forEach(function(e){return e.removeAttribute("active")});
d.forEach(function(e){return _ds.Zh(a,"hidden","",e)});b=b.find(function(e){return e.getAttribute("column-id")===c});d=d.find(function(e){return e.getAttribute("column-id")===c});b&&d&&(_ds.Zh(a,"active","",b),d.removeAttribute("hidden"))},i0=function(a){var b=a.querySelector(".dropdown-tabbed-menu-button-target");if(!a.querySelector(".dropdown-tabbed-menu-button")&&b){var c=a.querySelector("a");c&&(c=c.textContent,b=b.querySelector(".devsite-nav-item a"),a=a.querySelector(".dropdown-tabbed-menu"),
b&&(c=_ds.ol(D_,{Hh:(c||"").toLowerCase().trim(),href:b.getAttribute("href")||"",text:b.textContent||""}),null===a||void 0===a?void 0:a.appendChild(c)))}};var F_=_ds.xa(["active"]),G_=_ds.xa(["aria-expanded"]),H_=_ds.xa(["aria-selected"]),I_=_ds.xa(["collapsed"]),J_=_ds.xa(["column-id"]),K_=_ds.xa(["connected"]),L_=_ds.xa(["dropdown"]),M_=_ds.xa(["dropdown-full"]),N_=_ds.xa(["dropdown--open"]),O_=_ds.xa(["dropdown-transition"]),P_=_ds.xa(["hidden"]),Q_=_ds.xa(["no-overflow"]),R_=_ds.xa(["overflow-menu--open"]),S_=_ds.xa(["overflow-tab"]),T_=_ds.xa(["render-hidden"]),U_=_ds.xa(["scrollbars"]);_ds.v(V_,_ds.R);
V_.prototype.disconnectedCallback=function(){_ds.Fl(this.eventHandler);_ds.Fl(this.m)};V_.prototype.connectedCallback=function(){this.J||(g0(this),this.J=!0);_ds.Zh(this,"connected","");var a;this.hasAttribute("no-overflow")||(_ds.Zh(this,"collapsed","",this.j),this.N=f0(this,this.j),null===(a=this.j)||void 0===a?void 0:a.removeAttribute("collapsed"),d0(this),E_(this));k0(this)};V_.prototype.R=function(a){this.D=a};V_.prototype.Y=function(){this.D=null};V_.prototype.connectedCallback=V_.prototype.connectedCallback;
V_.prototype.disconnectedCallback=V_.prototype.disconnectedCallback;try{window.customElements.define("devsite-tabs",V_)}catch(a){console.warn("devsite.app.customElement.DevsiteTabs",a)};})(_ds_www);
