(function(_ds){var window=this;'use strict';var AR=function(){var a=void 0===a?_ds.nK.length:a;return _ds.nK.slice(0,a)},BR=function(a){var b=a.projectName,c=a.Rp,d=a.Sp,e=a.Zn,g=a.Jn,h=a.Fq;a='<devsite-dialog class="devsite-feedback"><div class="devsite-dialog-contents"><h3 class="no-link">Send feedback about...</h3><div class="devsite-feedback-items"><a href="#" class="devsite-feedback-item" feedback-type="documentation" data-label="Docs Feedback Image" track-type="feedback" track-name="feedbackDocIcon"><div class="devsite-feedback-item-icon-container devsite-feedback-item-icon-color"><div class="devsite-feedback-item-icon material-icons" aria-hidden="true">description</div></div><div>This page</div><div class="devsite-feedback-item-type">Documentation feedback</div></a>';
g||(c=d?'<div class="devsite-feedback-item-icon material-icons" aria-hidden="true">'+_ds.V(d)+"</div>":c?'<img src="'+_ds.W(_ds.Pj(c))+'" loading="lazy" alt="">':"",a+="<a"+(e?' href="'+_ds.W(_ds.Nj(e))+'"':' href="#"')+' class="devsite-feedback-item" feedback-type="product" data-label="Product Feedback Image" track-type="feedback" track-name="feedbackProductIcon"><div class="devsite-feedback-item-icon-container '+(d?"devsite-feedback-item-icon-color devsite-theme-primary":"devsite-feedback-item-icon-img")+
'">'+c+"</div><div>"+_ds.V(b)+'</div><div class="devsite-feedback-item-type">',a+="Product feedback</div></a>");a+='</div><div class="devsite-feedback-notice">We appreciate your feedback! Please note that we cannot respond.</div>';h&&(a+='<div class="devsite-feedback-support"><span class="devsite-feedback-support-icon material-icons" aria-hidden="true">help</span><span>',b='Need help? Visit our <a href="'+(_ds.W(_ds.Nj(h))+'">support page</a>.'),a=a+b+"</span></div>");return(0,_ds.T)(a+'<div class="devsite-feedback-buttons"><button class="button-white" tabindex="1" data-label="Cancel Feedback Button" track-type="feedback" track-name="cancelFeedbackButton" feedback-cancel>Close</button></div></div></devsite-dialog>')},
LR=function(){var a=_ds.R.call(this,["devsite-dialog"])||this;a.eventHandler=new _ds.zl;a.j=null;a.m=!1;a.O(_ds.Jh(CR),_ds.Jh(DR),_ds.Jh(ER),_ds.Jh(FR),_ds.Jh(GR),_ds.Jh(HR),_ds.Jh(IR),_ds.Jh(JR),_ds.Jh(KR));return a},RR=function(a){var b;a.eventHandler.listen(a,"click",function(e){if("A"===e.target.tagName||"BUTTON"===e.target.tagName)e.preventDefault(),e.stopPropagation(),a.j&&(document.body.appendChild(a.j),_ds.no.Fb([_ds.Jh(MR)],a.j,"open",""),e={action:"click",category:a.getAttribute("data-category")||
"Site-Wide Custom Events",label:a.getAttribute("data-label")},NR(a,e))});if(a.j){var c=Array.from(a.j.querySelectorAll("[feedback-type]"));c=_ds.r(c);for(var d=c.next();!d.done;d=c.next())a.eventHandler.listen(d.value,"click",function(e){OR(a,e)});(c=null===(b=a.j)||void 0===b?void 0:b.querySelector("button[feedback-cancel]"))&&a.eventHandler.listen(c,"click",function(){QR(a);var e,g=null===(e=a.j)||void 0===e?void 0:e.querySelector("button[feedback-cancel]");e={action:"click",label:null===g||void 0===
g?void 0:g.getAttribute("data-label"),category:(null===g||void 0===g?void 0:g.getAttribute("data-category"))||"Site-Wide Custom Events"};NR(a,e)});a.eventHandler.listen(a.j,"devsite-dialog-hide",function(){_ds.Fk(a.j)})}},OR=function(a,b){var c=b.uc,d=c.getAttribute("feedback-type"),e="#"===c.getAttribute("href");d={context:a.getAttribute("context"),type:d};var g=AR();g.length&&(d.errorStack=g);a.hasAttribute("rating-type")&&(d.ratingType=a.getAttribute("rating-type"));a.hasAttribute("rating-category")&&
(d.ratingCategory=a.getAttribute("rating-category"));g={productId:a.getAttribute("product-id"),locale:DevsiteApp.getLocale(),bucket:a.getAttribute("bucket"),productVersion:a.getAttribute("version"),callback:function(){return void SR()},onLoadCallback:function(){return void QR(a)}};c={action:"click",label:c.getAttribute("data-label"),category:c.getAttribute("data-category")||"Site-Wide Custom Events"};NR(a,c);e&&(b.preventDefault(),b.stopPropagation(),_ds.MC(g,d))},QR=function(a){var b;null===(b=a.j)||
void 0===b?void 0:b.removeAttribute("open");_ds.Fk(a.j)},SR=function(){Array.from(document.querySelectorAll('script[src*="www.google.com/tools/feedback/"]')).forEach(function(a){return _ds.Fk(a)})},NR=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:b,bubbles:!0}))};var CR=_ds.xa(["bucket"]),DR=_ds.xa(["context"]),ER=_ds.xa(["product-id"]),FR=_ds.xa(["data-label"]),GR=_ds.xa(["track-metadata-position"]),HR=_ds.xa(["track-name"]),IR=_ds.xa(["track-type"]),JR=_ds.xa(["disable"]),KR=_ds.xa(["project-"]),MR=_ds.xa(["open"]);_ds.v(LR,_ds.R);
LR.prototype.connectedCallback=function(){if(!this.m){var a=this.querySelector(".google-feedback"),b=new Map([["data-b","bucket"],["data-context","context"],["data-p","product-id"]]),c=new Map([["data-label","Send Feedback Button"],["track-metadata-position","content"],["track-name","sendFeedbackLink"],["track-type","feedback"]]);if(a){b=_ds.r(b.entries());for(var d=b.next();!d.done;d=b.next()){var e=_ds.r(d.value);d=e.next().value;e=e.next().value;if(a.hasAttribute(d)){var g=a.getAttribute(d)||"";
_ds.Zh(this,e,g);a.removeAttribute(d)}}c=_ds.r(c.entries());for(b=c.next();!b.done;b=c.next())d=_ds.r(b.value),b=d.next().value,d=d.next().value,a.hasAttribute(b)?(d=a.getAttribute(b)||"",_ds.Zh(this,b,d),a.removeAttribute(b)):_ds.Zh(this,b,d);a.classList.remove("google-feedback")}!this.hasAttribute("project-name")&&(a=document.querySelector('meta[property="og:site_name"]'))&&(a=a.getAttribute("content")||"",_ds.Zh(this,"project-name",a));this.hasAttribute("project-icon")?_ds.Zh(this,"project-icon",
_ds.lm(this.getAttribute("project-icon")||"").href||""):(a=document.querySelector('link[rel="apple-touch-icon"]'))&&_ds.Zh(this,"project-icon",a.getAttribute("href")||"");this.j=_ds.ol(BR,{Jn:this.hasAttribute("disable-product-feedback"),Zn:this.getAttribute("project-feedback-url"),Rp:this.getAttribute("project-icon"),Sp:this.getAttribute("project-icon-name"),projectName:this.getAttribute("project-name")||"",Fq:this.getAttribute("project-support-url")});this.m=!0}RR(this)};
LR.prototype.disconnectedCallback=function(){_ds.Fl(this.eventHandler)};LR.prototype.disconnectedCallback=LR.prototype.disconnectedCallback;LR.prototype.connectedCallback=LR.prototype.connectedCallback;try{window.customElements.define("devsite-feedback",LR)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteFeedback",a)};})(_ds_www);
