(function(_ds){var window=this;'use strict';var aQ=function(){var a=_ds.R.call(this)||this;a.C=new _ds.zl;a.D=new _ds.zl;a.m=new Set;a.j=null;"IntersectionObserver"in window&&(a.j=new IntersectionObserver(function(b){b=_ds.r(b);for(var c=b.next();!c.done;c=b.next())c=c.value,c.isIntersecting&&(c=c.target,_ds.uE(new _ds.sE,c),a.m.delete(c),a.j.unobserve(c))},{rootMargin:"100%"}));return a},bQ=function(a){Array.from(a.getElementsByTagName("table")).forEach(function(b){if(!b.parentNode.classList.contains("devsite-table-wrapper")){var c=
document.createElement("div");c.classList.add("devsite-table-wrapper");b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));_ds.Ck(c,b);c.appendChild(b)}})},jQ=function(a,b){var c,d,e,g,h,k,l;return _ds.cb(function(m){if(1==m.h)return _ds.x(m,DevsiteApp.whenReady(),2);c=_ds.em();d=DevsiteApp.getInsecureHost();e=b.ma;if(e.origin!==c.origin&&d&&e.origin!==d)return m.return();try{g=_ds.Gg(_ds.so,e.data)}catch(p){return m.return()}h=_ds.ng(g,
1,0);if(4===h)return cQ(a,e),m.return();k=g.getName();if(!k)return m.return();if(l=a.querySelector('devsite-iframe iframe[name="'+k+'"]'))switch(h){case 5:dQ(g,l);break;case 8:eQ(e,g,c);break;case 1:fQ(e,g,c);break;case 6:case 7:gQ(h,c,g);break;case 9:hQ(a,g);break;case 10:iQ(g,c)}_ds.y(m)})},dQ=function(a,b){var c,d,e,g;_ds.cb(function(h){c=_ds.sk(document).y;d=_ds.Kg(a,4);e=_ds.Kg(a,3);g=_ds.Sk(b);d&&g.setAttribute("width",d+"px");e&&g.setAttribute("height",e+"px");window.requestAnimationFrame(function(){window.scrollTo(_ds.sk(document).x,
c)});_ds.y(h)})},cQ=function(a,b){var c,d,e;_ds.cb(function(g){if(c=kQ(a,b.source)){d="goog_"+_ds.Eo++;c.setAttribute("name",d);var h=_ds.to(3);e=_ds.P(h,2,d);(h=b.source)&&h.postMessage(_ds.Fg(e),"*")}_ds.y(g)})},eQ=function(a,b,c){var d;_ds.cb(function(e){var g=_ds.uo(_ds.to(8),_ds.O(b,8));d=_ds.P(g,6,c.toString());(g=a.source)&&g.postMessage(_ds.Fg(d),"*");_ds.y(e)})},fQ=function(a,b,c){var d;_ds.cb(function(e){var g=_ds.uo(_ds.to(2),_ds.O(b,8));d=_ds.P(g,7,c.search+c.hash);(g=a.source)&&g.postMessage(_ds.Fg(d),
"*");_ds.y(e)})},gQ=function(a,b,c){var d,e,g;_ds.cb(function(h){d=c.Ha();e=new URL(c.getUrl(),b.origin);g=window.location.origin+window.location.pathname+e.search+e.hash;6===a?window.history.pushState({},d,g):window.history.replaceState({},d,g);_ds.y(h)})},hQ=function(a,b){var c,d,e,g;_ds.cb(function(h){c=_ds.O(b,9);d=JSON.parse(_ds.O(b,10));"cloudtrackEvent"===c&&d?(e=d,g={eventData:e},a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:g,bubbles:!0}))):"devsite-apix"===
c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",{detail:d,bubbles:!0}));_ds.y(h)})},iQ=function(a,b){var c,d;_ds.cb(function(e){if(c=a.getUrl())d=new URL(c,b.origin),c.startsWith("#")||b.origin===d.origin&&b.pathname===d.pathname&&b.search===d.search?DevsiteApp.scrollToAnchor(d.hash,!0):DevsiteApp.fetchPage(d.href);_ds.y(e)})},kQ=function(a,b){var c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(function(d){_ds.Wk(d)===b&&(c=d)});return c},nQ=function(a){a.o=a.querySelector(".devsite-article-body");
a.o&&lQ(a);a.j&&a.j.disconnect();a.m.clear();bQ(a);var b=Array.from(a.querySelectorAll(".devsite-nav-title, .devsite-page-title, td > code, th > code"));if("docs"===document.body.getAttribute("layout")&&a.o){var c=Array.from(a.o.querySelectorAll("h1, h2, h3, h4, h5, h6"));b.push.apply(b,_ds.ya(c))}a.m.clear();a.m=new Set(b);if(_ds.em().hash){b=new _ds.sE;c=_ds.r(a.m);for(var d=c.next();!d.done;d=c.next())_ds.uE(b,d.value)}else mQ(a,a.m);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},
lQ=function(a){"full"===document.body.getAttribute("layout")&&(a=a.o.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&Array.from(a).forEach(function(b){b.removeAttribute("tabindex")})},mQ=function(a,b){a.j&&b.forEach(function(c){a.j.observe(c)})};_ds.v(aQ,_ds.R);aQ.prototype.connectedCallback=function(){var a=this;this.C.listen(window,"message",function(b){return jQ(a,b)});nQ(this)};
aQ.prototype.disconnectedCallback=function(){this.j&&this.j.disconnect();this.m.clear();_ds.Fl(this.C);_ds.Fl(this.D)};aQ.prototype.Ta=function(a){var b=this;a&&([".devsite-article",".devsite-content-data","devsite-content-footer","devsite-google-survey"].forEach(function(c){_ds.$h(b,b.querySelector(c),a.querySelector(c))}),nQ(this))};aQ.prototype.updateContent=aQ.prototype.Ta;aQ.prototype.disconnectedCallback=aQ.prototype.disconnectedCallback;aQ.prototype.connectedCallback=aQ.prototype.connectedCallback;try{window.customElements.define("devsite-content",aQ)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
