(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var m=ca(this);function q(a,b){if(b)a:{var c=m;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
q("Symbol",function(a){function b(k){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(k||"")+"_"+e++,k)}function c(k,g){this.g=k;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=m[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});function da(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function r(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ea="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var ka=fa;function la(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function ma(){this.m=!1;this.j=null;this.s=void 0;this.g=1;this.l=this.i=0;this.o=this.h=null}function na(a){if(a.m)throw new TypeError("Generator is already running");a.m=!0}f=ma.prototype;f.J=function(a){this.s=a};function oa(a,b){a.h={R:b,S:!0};a.g=a.i||a.l}f.return=function(a){this.h={return:a};this.g=this.l};f.Ed=function(a){this.h={C:a};this.g=this.l};
function pa(a,b,c){a.g=c;return{value:b}}f.qf=function(a,b){a=r(a);var c=a.next();la(c);if(c.done)this.s=c.value,this.g=b;else return this.j=a,pa(this,c.value,b)};f.C=function(a){this.g=a};f.Fd=function(){this.g=0};f.Td=function(a){this.i=0;this.l=a||0};function qa(a,b){a.g=b;a.i=0}function ra(a){a.i=0;var b=a.h.R;a.h=null;return b}f.Hc=function(a,b,c){c?this.o[c]=this.h:this.o=[this.h];this.i=a||0;this.l=b||0};
f.Gd=function(a,b){b=this.o.splice(b||0)[0];(b=this.h=this.h||b)?b.S?this.g=this.i||this.l:void 0!=b.C&&this.l<b.C?(this.g=b.C,this.h=null):this.g=this.l:this.g=a};f.Kc=function(a){return new sa(a)};function sa(a){this.h=a;this.g=[];for(var b in a)this.g.push(b);this.g.reverse()}sa.prototype.i=function(){for(;0<this.g.length;){var a=this.g.pop();if(a in this.h)return a}return null};function ta(a){this.g=new ma;this.h=a}
function ua(a,b){na(a.g);var c=a.g.j;if(c)return va(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return wa(a)}function va(a,b,c,d){try{var e=b.call(a.g.j,c);la(e);if(!e.done)return a.g.m=!1,e;var k=e.value}catch(g){return a.g.j=null,oa(a.g,g),wa(a)}a.g.j=null;d.call(a.g,k);return wa(a)}
function wa(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.m=!1,{value:b.value,done:!1}}catch(c){a.g.s=void 0,oa(a.g,c)}a.g.m=!1;if(a.g.h){b=a.g.h;a.g.h=null;if(b.S)throw b.R;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function xa(a){this.next=function(b){na(a.g);a.g.j?b=va(a,a.g.j.next,b,a.g.J):(a.g.J(b),b=wa(a));return b};this.throw=function(b){na(a.g);a.g.j?b=va(a,a.g.j["throw"],b,a.g.J):(oa(a.g,b),b=wa(a));return b};this.return=function(b){return ua(a,b)};this[Symbol.iterator]=function(){return this}}function ya(a,b){b=new xa(new ta(b));ka&&a.prototype&&ka(b,a.prototype);return b}function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
q("WeakMap",function(a){function b(l){this.g=(h+=Math.random()+1).toString();if(l){l=r(l);for(var n;!(n=l.next()).done;)n=n.value,this.set(n[0],n[1])}}function c(){}function d(l){var n=typeof l;return"object"===n&&null!==l||"function"===n}function e(l){if(!u(l,g)){var n=new c;ba(l,g,{value:n})}}function k(l){var n=Object[l];n&&(Object[l]=function(p){if(p instanceof c)return p;Object.isExtensible(p)&&e(p);return n(p)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),n=Object.seal({}),
p=new a([[l,2],[n,3]]);if(2!=p.get(l)||3!=p.get(n))return!1;p.delete(l);p.set(n,4);return!p.has(l)&&4==p.get(n)}catch(t){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();k("freeze");k("preventExtensions");k("seal");var h=0;b.prototype.set=function(l,n){if(!d(l))throw Error("Invalid WeakMap key");e(l);if(!u(l,g))throw Error("WeakMap key fail: "+l);l[g][this.g]=n;return this};b.prototype.get=function(l){return d(l)&&u(l,g)?l[g][this.g]:void 0};b.prototype.has=function(l){return d(l)&&u(l,
g)&&u(l[g],this.g)};b.prototype.delete=function(l){return d(l)&&u(l,g)&&u(l[g],this.g)?delete l[g][this.g]:!1};return b});
q("Map",function(a){function b(){var h={};return h.B=h.next=h.head=h}function c(h,l){var n=h.g;return da(function(){if(n){for(;n.head!=h.g;)n=n.B;for(;n.next!=n.head;)return n=n.next,{done:!1,value:l(n)};n=null}return{done:!0,value:void 0}})}function d(h,l){var n=l&&typeof l;"object"==n||"function"==n?k.has(l)?n=k.get(l):(n=""+ ++g,k.set(l,n)):n="p_"+l;var p=h.h[n];if(p&&u(h.h,n))for(h=0;h<p.length;h++){var t=p[h];if(l!==l&&t.key!==t.key||l===t.key)return{id:n,list:p,index:h,v:t}}return{id:n,list:p,
index:-1,v:void 0}}function e(h){this.h={};this.g=b();this.size=0;if(h){h=r(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),l=new a(r([[h,"s"]]));if("s"!=l.get(h)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var n=l.entries(),p=n.next();if(p.done||p.value[0]!=h||"s"!=p.value[1])return!1;p=n.next();return p.done||4!=p.value[0].x||
"t"!=p.value[1]||!n.next().done?!1:!0}catch(t){return!1}}())return a;var k=new WeakMap;e.prototype.set=function(h,l){h=0===h?0:h;var n=d(this,h);n.list||(n.list=this.h[n.id]=[]);n.v?n.v.value=l:(n.v={next:this.g,B:this.g.B,head:this.g,key:h,value:l},n.list.push(n.v),this.g.B.next=n.v,this.g.B=n.v,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.v&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.h[h.id],h.v.B.next=h.v.next,h.v.next.B=h.v.B,h.v.head=null,this.size--,
!0):!1};e.prototype.clear=function(){this.h={};this.g=this.g.B=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).v};e.prototype.get=function(h){return(h=d(this,h).v)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,l){for(var n=this.entries(),p;!(p=n.next()).done;)p=p.value,
h.call(l,p[1],p[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});function za(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var k=c++;return{value:b(k,a[k]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}q("Array.prototype.entries",function(a){return a?a:function(){return za(this,function(b,c){return[b,c]})}});
q("Promise",function(a){function b(g){this.h=0;this.i=void 0;this.g=[];this.o=!1;var h=this.j();try{g(h.resolve,h.reject)}catch(l){h.reject(l)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.h=function(g){if(null==this.g){this.g=[];var h=this;this.i(function(){h.l()})}this.g.push(g)};var e=m.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var l=
g[h];g[h]=null;try{l()}catch(n){this.j(n)}}}this.g=null};c.prototype.j=function(g){this.i(function(){throw g;})};b.prototype.j=function(){function g(n){return function(p){l||(l=!0,n.call(h,p))}}var h=this,l=!1;return{resolve:g(this.O),reject:g(this.l)}};b.prototype.O=function(g){if(g===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.T(g);else{a:switch(typeof g){case "object":var h=null!=g;break a;case "function":h=!0;break a;default:h=!1}h?this.I(g):this.m(g)}};
b.prototype.I=function(g){var h=void 0;try{h=g.then}catch(l){this.l(l);return}"function"==typeof h?this.U(h,g):this.m(g)};b.prototype.l=function(g){this.s(2,g)};b.prototype.m=function(g){this.s(1,g)};b.prototype.s=function(g,h){if(0!=this.h)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.h);this.h=g;this.i=h;2===this.h&&this.P();this.D()};b.prototype.P=function(){var g=this;e(function(){if(g.N()){var h=m.console;"undefined"!==typeof h&&h.error(g.i)}},1)};b.prototype.N=
function(){if(this.o)return!1;var g=m.CustomEvent,h=m.Event,l=m.dispatchEvent;if("undefined"===typeof l)return!0;"function"===typeof g?g=new g("unhandledrejection",{cancelable:!0}):"function"===typeof h?g=new h("unhandledrejection",{cancelable:!0}):(g=m.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return l(g)};b.prototype.D=function(){if(null!=this.g){for(var g=0;g<this.g.length;++g)k.h(this.g[g]);this.g=null}};var k=new c;b.prototype.T=
function(g){var h=this.j();g.F(h.resolve,h.reject)};b.prototype.U=function(g,h){var l=this.j();try{g.call(h,l.resolve,l.reject)}catch(n){l.reject(n)}};b.prototype.then=function(g,h){function l(G,J){return"function"==typeof G?function($a){try{n(G($a))}catch(ab){p(ab)}}:J}var n,p,t=new b(function(G,J){n=G;p=J});this.F(l(g,n),l(h,p));return t};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.F=function(g,h){function l(){switch(n.h){case 1:g(n.i);break;case 2:h(n.i);break;default:throw Error("Unexpected state: "+
n.h);}}var n=this;null==this.g?k.h(l):this.g.push(l);this.o=!0};b.resolve=d;b.reject=function(g){return new b(function(h,l){l(g)})};b.race=function(g){return new b(function(h,l){for(var n=r(g),p=n.next();!p.done;p=n.next())d(p.value).F(h,l)})};b.all=function(g){var h=r(g),l=h.next();return l.done?d([]):new b(function(n,p){function t($a){return function(ab){G[$a]=ab;J--;0==J&&n(G)}}var G=[],J=0;do G.push(void 0),J++,d(l.value).F(t(G.length-1),p),l=h.next();while(!l.done)})};return b});
function Aa(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}q("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=Aa(this,b,"endsWith");void 0===c&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;0<e&&0<c;)if(d[--c]!=b[--e])return!1;return 0>=e}});
q("Array.prototype.values",function(a){return a?a:function(){return za(this,function(b,c){return c})}});q("Array.prototype.keys",function(a){return a?a:function(){return za(this,function(b){return b})}});
q("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],k="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof k){b=k.call(b);for(var g=0;!(k=b.next()).done;)e.push(c.call(d,k.value,g++))}else for(k=b.length,g=0;g<k;g++)e.push(c.call(d,b[g],g));return e}});q("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
q("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var k=d[c];if(k===b||Object.is(k,b))return!0}return!1}});q("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==Aa(this,b,"includes").indexOf(b,c||0)}});var v=this||self;function Ba(){}
function Ca(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length}function Da(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function Ea(a,b){a=a.split(".");var c=v;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}
function Fa(a,b){function c(){}c.prototype=b.prototype;a.G=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.yc=function(d,e,k){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}}function Ga(a){return a};var w=new Map([]);w.set("devsite-a11y-announce",{src:"/cloud/js/devsite_devsite_a11y_announce_module.js"});w.set("devsite-analytics",{src:"/cloud/js/devsite_devsite_analytics_module.js"});w.set("devsite-analytics-scope",{src:"/cloud/js/devsite_devsite_analytics_scope_module.js"});w.set("devsite-anselm",{src:"/cloud/js/devsite_devsite_anselm_module.js"});w.set("devsite-api-getstarted",{src:"/cloud/js/devsite_devsite_api_getstarted_module.js"});w.set("devsite-apix",{src:"/cloud/js/devsite_devsite_apix_module.js"});
w.set("devsite-apix-index",{src:"/cloud/js/devsite_devsite_apix_index_module.js"});w.set("devsite-apix-snippets",{src:"/cloud/js/devsite_devsite_apix_snippets_module.js"});w.set("devsite-badger",{src:"/cloud/js/devsite_devsite_badger_module.js"});w.set("devsite-badge-awarded",{src:"/cloud/js/devsite_devsite_badge_awarded_module.js"});w.set("devsite-badge-awarder",{src:"/cloud/js/devsite_devsite_badge_awarder_module.js"});w.set("devsite-badge-redeemer",{src:"/cloud/js/devsite_devsite_badge_redeemer_module.js"});
w.set("devsite-book-nav",{src:"/cloud/js/devsite_devsite_book_nav_module.js"});w.set("devsite-chart",{src:"/cloud/js/devsite_devsite_chart_module.js"});w.set("devsite-catalog",{src:"/cloud/js/devsite_devsite_catalog_module.js"});w.set("devsite-code",{src:"/cloud/js/devsite_devsite_code_module.js"});w.set("devsite-content",{src:"/cloud/js/devsite_devsite_content_module.js"});w.set("devsite-codelab-catalog",{src:"/cloud/js/devsite_devsite_codelab_catalog_module.js"});
w.set("devsite-product-catalog",{src:"/cloud/js/devsite_devsite_product_catalog_module.js"});w.set("devsite-credentials-dialog",{src:"/cloud/js/devsite_devsite_credentials_dialog_module.js"});w.set("devsite-cse",{src:"/cloud/js/devsite_devsite_cse_module.js"});w.set("devsite-panel",{src:"/cloud/js/devsite_devsite_panel_module.js"});w.set("devsite-device",{src:"/cloud/js/devsite_devsite_device_module.js"});w.set("devsite-devprofile",{src:"/cloud/js/devsite_devsite_devprofile_module.js"});
w.set("devsite-dialog",{src:"/cloud/js/devsite_devsite_dialog_module.js"});w.set("devsite-dynamic-content",{src:"/cloud/js/devsite_devsite_dynamic_content_module.js"});w.set("devsite-expandable",{src:"/cloud/js/devsite_devsite_expandable_module.js"});w.set("devsite-expandable-nav",{src:"/cloud/js/devsite_devsite_expandable_nav_module.js"});w.set("devsite-extradory",{src:"/cloud/js/devsite_devsite_extradory_module.js"});w.set("devsite-feedback",{src:"/cloud/js/devsite_devsite_feedback_module.js"});
w.set("devsite-filter",{src:"/cloud/js/devsite_devsite_filter_module.js"});w.set("devsite-footer-linkboxes",{src:"/cloud/js/devsite_devsite_footer_linkboxes_module.js"});w.set("devsite-footer-promos",{src:"/cloud/js/devsite_devsite_footer_promos_module.js"});w.set("devsite-footer-utility",{src:"/cloud/js/devsite_devsite_footer_utility_module.js"});w.set("devsite-google-survey",{src:"/cloud/js/devsite_devsite_google_survey_module.js"});w.set("devsite-googler-buttons",{src:"/cloud/js/devsite_devsite_googler_buttons_module.js"});
w.set("devsite-hats-survey",{src:"/cloud/js/devsite_devsite_hats_survey_module.js"});w.set("devsite-heading-link",{src:"/cloud/js/devsite_devsite_heading_link_module.js"});w.set("devsite-iframe",{src:"/cloud/js/devsite_devsite_iframe_module.js"});w.set("devsite-info-popout",{src:"/cloud/js/devsite_devsite_info_popout_module.js"});w.set("devsite-jump-to",{src:"/cloud/js/devsite_devsite_jump_to_module.js"});w.set("devsite-jsfiddle-button",{src:"/cloud/js/devsite_devsite_jsfiddle_button_module.js"});
w.set("devsite-language-selector",{src:"/cloud/js/devsite_devsite_language_selector_module.js"});w.set("devsite-lightbox",{src:"/cloud/js/devsite_devsite_lightbox_module.js"});w.set("devsite-mathjax",{src:"/cloud/js/devsite_devsite_mathjax_module.js"});w.set("devsite-mdc",{src:"/cloud/js/devsite_devsite_mdc_module.js"});w.set("devsite-multiple-choice",{src:"/cloud/js/devsite_devsite_multiple_choice_module.js"});w.set("devsite-nav-buttons",{src:"/cloud/js/devsite_devsite_nav_buttons_module.js"});
w.set("devsite-playlist",{src:"/cloud/js/devsite_devsite_playlist_module.js"});w.set("devsite-playlist-earnable-badges",{src:"/cloud/js/devsite_devsite_playlist_earnable_badges_module.js"});w.set("devsite-playlist-summary",{src:"/cloud/js/devsite_devsite_playlist_summary_module.js"});w.set("devsite-pagination",{src:"/cloud/js/devsite_devsite_pagination_module.js"});w.set("devsite-profile-card",{src:"/cloud/js/devsite_devsite_profile_card_module.js"});w.set("devsite-progress",{src:"/cloud/js/devsite_devsite_progress_module.js"});
w.set("devsite-quiz",{src:"/cloud/js/devsite_devsite_quiz_module.js"});w.set("devsite-recommendations",{src:"/cloud/js/devsite_devsite_recommendations_module.js"});w.set("devsite-recommendations-dropdown",{src:"/cloud/js/devsite_devsite_recommendations_dropdown_module.js"});w.set("devsite-recommendations-sidebar",{src:"/cloud/js/devsite_devsite_recommendations_sidebar_module.js"});w.set("devsite-reference-results",{src:"/cloud/js/devsite_devsite_reference_results_module.js"});
w.set("devsite-search",{src:"/cloud/js/devsite_devsite_search_module.js"});w.set("devsite-select",{src:"/cloud/js/devsite_devsite_select_module.js"});w.set("devsite-selector",{src:"/cloud/js/devsite_devsite_selector_module.js"});w.set("devsite-shell",{src:"/cloud/js/devsite_devsite_shell_module.js"});w.set("devsite-shell-activate-button",{src:"/cloud/js/devsite_devsite_shell_activate_button_module.js"});w.set("devsite-sitemask",{src:"/cloud/js/devsite_devsite_sitemask_module.js"});
w.set("devsite-snackbar",{src:"/cloud/js/devsite_devsite_snackbar_module.js"});w.set("devsite-sort",{src:"/cloud/js/devsite_devsite_sort_module.js"});w.set("devsite-spinner",{src:"/cloud/js/devsite_devsite_spinner_module.js"});w.set("devsite-support-form",{src:"/cloud/js/devsite_devsite_support_form_module.js"});w.set("devsite-tabs",{src:"/cloud/js/devsite_devsite_tabs_module.js"});w.set("devsite-theme-selector",{src:"/cloud/js/devsite_devsite_theme_selector_module.js"});w.set("devsite-toc",{src:"/cloud/js/devsite_devsite_toc_module.js"});
w.set("devsite-topic",{src:"/cloud/js/devsite_devsite_topic_module.js"});w.set("devsite-tooltip",{src:"/cloud/js/devsite_devsite_tooltip_module.js"});w.set("devsite-tracking-question",{src:"/cloud/js/devsite_devsite_tracking_question_module.js"});w.set("devsite-user",{src:"/cloud/js/devsite_devsite_user_module.js"});w.set("devsite-var",{src:"/cloud/js/devsite_devsite_var_module.js"});w.set("devsite-version-selector",{src:"/cloud/js/devsite_devsite_version_selector_module.js"});
w.set("devsite-visibility-analytics",{src:"/cloud/js/devsite_devsite_visibility_analytics_module.js"});w.set("devsite-vplus",{src:"/cloud/js/devsite_devsite_vplus_module.js"});w.set("devsite-wall-acknowledgement",{src:"/cloud/js/devsite_devsite_wall_acknowledgement_module.js"});w.set("devsite-youtube",{src:"/cloud/js/devsite_devsite_youtube_module.js"});w.set("google-codelab",{src:"/cloud/js/devsite_google_codelab_module.js"});w.set("google-codelab-about",{src:"/cloud/js/devsite_google_codelab_about_module.js"});
w.set("google-codelab-analytics",{src:"/cloud/js/devsite_google_codelab_analytics_module.js"});w.set("google-codelab-step",{src:"/cloud/js/devsite_google_codelab_step_module.js"});w.set("google-codelab-survey",{src:"/cloud/js/devsite_google_codelab_survey_module.js"});w.set("cloud-shell-button",{src:"/cloud/js/devsite_cloud_shell_button_module.js"});w.set("cloud-shell-pane",{src:"/cloud/js/devsite_cloud_shell_pane_module.js"});w.set("cloudx-additional-tabs",{src:"/cloud/js/devsite_cloudx_additional_tabs_module.js"});
w.set("cloudx-button-code",{src:"/cloud/js/devsite_cloudx_button_code_module.js"});w.set("cloudx-carousel",{src:"/cloud/js/devsite_cloudx_carousel_module.js"});w.set("cloudx-chat",{src:"/cloud/js/devsite_cloudx_chat_module.js"});w.set("cloudx-chrome-policies",{src:"/cloud/js/devsite_cloudx_chrome_policies_module.js"});w.set("cloudx-collapse",{src:"/cloud/js/devsite_cloudx_collapse_module.js"});w.set("cloudx-compliance",{src:"/cloud/js/devsite_cloudx_compliance_module.js"});w.set("cloudx-demo",{src:"/cloud/js/devsite_cloudx_demo_module.js"});
w.set("cloudx-dynamic-content",{src:"/cloud/js/devsite_cloudx_dynamic_content_module.js"});w.set("cloudx-experiments",{src:"/cloud/js/devsite_cloudx_experiments_module.js"});w.set("cloudx-form",{src:"/cloud/js/devsite_cloudx_form_module.js"});w.set("cloudx-free-trial-eligible-content",{src:"/cloud/js/devsite_cloudx_free_trial_eligible_content_module.js"});w.set("cloudx-gallery",{src:"/cloud/js/devsite_cloudx_gallery_module.js"});w.set("cloudx-jump-menu",{src:"/cloud/js/devsite_cloudx_jump_menu_module.js"});
w.set("cloudx-maps-platform",{src:"/cloud/js/devsite_cloudx_maps_platform_module.js"});w.set("cloudx-popup",{src:"/cloud/js/devsite_cloudx_popup_module.js"});w.set("cloudx-pricing-instance",{src:"/cloud/js/devsite_cloudx_pricing_instance_module.js"});w.set("cloudx-pricing-socket",{src:"/cloud/js/devsite_cloudx_pricing_socket_module.js"});w.set("cloudx-pricing-table",{src:"/cloud/js/devsite_cloudx_pricing_table_module.js"});w.set("cloudx-print",{src:"/cloud/js/devsite_cloudx_print_module.js"});
w.set("cloudx-recaptcha",{src:"/cloud/js/devsite_cloudx_recaptcha_module.js"});w.set("cloudx-select-dropdown",{src:"/cloud/js/devsite_cloudx_select_dropdown_module.js"});w.set("cloudx-share-links",{src:"/cloud/js/devsite_cloudx_share_links_module.js"});w.set("cloudx-table",{src:"/cloud/js/devsite_cloudx_table_module.js"});w.set("cloudx-tabs",{src:"/cloud/js/devsite_cloudx_tabs_module.js"});w.set("cloudx-tabs-nav",{src:"/cloud/js/devsite_cloudx_tabs_nav_module.js"});w.set("cloudx-tags",{src:"/cloud/js/devsite_cloudx_tags_module.js"});
w.set("cloudx-track",{src:"/cloud/js/devsite_cloudx_track_module.js"});w.set("cloudx-user",{src:"/cloud/js/devsite_cloudx_user_module.js"});w.set("cloudx-utils-init",{src:"/cloud/js/devsite_cloudx_utils_init_module.js"});w.set("devsite-bookmark",{src:"/cloud/js/devsite_devsite_bookmark_module.js"});w.set("devsite-header",{src:"/cloud/js/devsite_devsite_header_module.js"});w.set("devsite-thumb-rating",{src:"/cloud/js/devsite_devsite_thumb_rating_module.js"});w.set("goog-split-pane",{src:"/cloud/js/devsite_goog_split_pane_module.js"});
Ea("DevsiteAppAuthorizedElements",w);Ea("DevsiteAppTenantCustomized",!0);var Ha={tc:0,sc:1,Yb:6,Wb:8,cc:12,dc:14,ec:17,ic:18,kc:21,mc:25,Aa:37,nc:38,La:40,jb:45,na:47,Z:50,ha:52,ea:62,Xa:63,Db:66,ub:70,$:73,ob:74,pa:75,Ab:76,Ta:77,Va:80,fa:81,gb:82,Ra:83,tb:85,ta:87,Na:89,wb:90,Oa:91,Ua:92,la:93,qc:94,Qa:95,ka:96,Eb:97,aa:98,ca:99,lc:100,Ka:101,Sa:102,zb:103,pc:104,va:105,ma:106,Ia:107,ya:108,sb:109,ua:110,Ha:111,oc:112,Bb:113,za:114,ja:115,Ca:116,hb:117,fb:118,Pa:119,vb:120,ac:121,Cb:122,fc:123,Xb:124,bb:125,pb:126,Ja:127,bc:128,lb:129,mb:130,Fa:131,ab:132,ba:133,Ya:134,
Ma:135,ib:136,da:137,rc:138,qb:139,Zb:140,Vb:141,kb:142,eb:143,rb:144,ia:145,nb:146,Za:147,cb:148,xb:149,xa:150,sa:151,$a:152,Ga:153,Ea:154,oa:155,jc:156,hc:157,Wa:158,Da:159,ga:160,qa:161,wa:162,$b:163,yb:164,Ba:165,ra:166,Fb:167};var Ia,Ja="undefined"!==typeof TextEncoder;var Ka=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var La;a:{var Ma=v.navigator;if(Ma){var Na=Ma.userAgent;if(Na){La=Na;break a}}La=""}function Oa(a){return-1!=La.indexOf(a)};function Pa(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};function Qa(a){Qa[" "](a);return a}Qa[" "]=Ba;var Ra=Oa("Gecko")&&!(-1!=La.toLowerCase().indexOf("webkit")&&!Oa("Edge"))&&!(Oa("Trident")||Oa("MSIE"))&&!Oa("Edge"),Sa=-1!=La.toLowerCase().indexOf("webkit")&&!Oa("Edge"),Ta=Oa("Macintosh");var Ua={},Va=null;function Wa(a,b){void 0===b&&(b=0);Xa();b=Ua[b];for(var c=Array(Math.floor(a.length/3)),d=b[64]||"",e=0,k=0;e<a.length-2;e+=3){var g=a[e],h=a[e+1],l=a[e+2],n=b[g>>2];g=b[(g&3)<<4|h>>4];h=b[(h&15)<<2|l>>6];l=b[l&63];c[k++]=n+g+h+l}n=0;l=d;switch(a.length-e){case 2:n=a[e+1],l=b[(n&15)<<2]||d;case 1:a=a[e],c[k]=b[a>>2]+b[(a&3)<<4|n>>4]+l+d}return c.join("")}
function Ya(a){var b=a.length,c=3*b/4;c%3?c=Math.floor(c):-1!="=.".indexOf(a[b-1])&&(c=-1!="=.".indexOf(a[b-2])?c-2:c-1);var d=new Uint8Array(c),e=0;Za(a,function(k){d[e++]=k});return d.subarray(0,e)}
function Za(a,b){function c(l){for(;d<a.length;){var n=a.charAt(d++),p=Va[n];if(null!=p)return p;if(!/^[\s\xa0]*$/.test(n))throw Error("Unknown base64 encoding at char: "+n);}return l}Xa();for(var d=0;;){var e=c(-1),k=c(0),g=c(64),h=c(64);if(64===h&&-1===e)break;b(e<<2|k>>4);64!=g&&(b(k<<4&240|g>>2),64!=h&&b(g<<6&192|h))}}
function Xa(){if(!Va){Va={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));Ua[c]=d;for(var e=0;e<d.length;e++){var k=d[e];void 0===Va[k]&&(Va[k]=e)}}}};var bb="function"===typeof Uint8Array.prototype.slice,cb,x=0,y=0;function db(a){var b=a>>>0;a=Math.floor((a-b)/4294967296)>>>0;x=b;y=a}function z(a){var b=0>a;a=Math.abs(a);var c=a>>>0;a=Math.floor((a-c)/4294967296);a>>>=0;b&&(a=~a>>>0,c=(~c>>>0)+1,4294967295<c&&(c=0,a++,4294967295<a&&(a=0)));x=c;y=a}function eb(a){var b=0>a;a=2*Math.abs(a);db(a);a=x;var c=y;b&&(0==a?0==c?c=a=4294967295:(c--,a=4294967295):a--);x=a;y=c}
function fb(a){var b=0>a?1:0;a=b?-a:a;if(0===a)0<1/a?x=y=0:(y=0,x=2147483648);else if(isNaN(a))y=0,x=2147483647;else if(3.4028234663852886E38<a)y=0,x=(b<<31|2139095040)>>>0;else if(1.1754943508222875E-38>a)a=Math.round(a/Math.pow(2,-149)),y=0,x=(b<<31|a)>>>0;else{var c=Math.floor(Math.log(a)/Math.LN2);a*=Math.pow(2,-c);a=Math.round(8388608*a)&8388607;y=0;x=(b<<31|c+127<<23|a)>>>0}}
function gb(a){var b=r(a);a=b.next().value;var c=b.next().value,d=b.next().value,e=b.next().value,k=b.next().value,g=b.next().value,h=b.next().value;b=b.next().value;x=a+(c<<8)+(d<<16)+(e<<24)>>>0;y=k+(g<<8)+(h<<16)+(b<<24)>>>0}function hb(a,b,c){var d=b>>31;c(a<<1^d,(b<<1|a>>>31)^d)}
function ib(a){function b(g,h){for(var l=0;8>l&&(1!==g||0<h);l++)h=g*e[l]+h,e[l]=h&255,h>>>=8}function c(){for(var g=0;8>g;g++)e[g]=~e[g]&255}var d=!1;"-"===a[0]&&(d=!0,a=a.slice(1));for(var e=[0,0,0,0,0,0,0,0],k=0;k<a.length;k++)b(10,a.charCodeAt(k)-48);d&&(c(),b(1,1));return e}
function jb(a){return a.constructor===Uint8Array?a:a.constructor===ArrayBuffer?new Uint8Array(a):a.constructor===Array?new Uint8Array(a):a.constructor===String?Ya(a):a instanceof Uint8Array?new Uint8Array(a.buffer,a.byteOffset,a.byteLength):new Uint8Array(0)};function A(a,b){this.g=a;this.h=b}function kb(a){return new A((a.g>>>1|(a.h&1)<<31)>>>0,a.h>>>1>>>0)}function lb(a){return new A(a.g<<1>>>0,(a.h<<1|a.g>>>31)>>>0)}f=A.prototype;f.Hd=function(){return!!(this.g&1)};f.add=function(a){return new A((this.g+a.g&4294967295)>>>0>>>0,((this.h+a.h&4294967295)>>>0)+(4294967296<=this.g+a.g?1:0)>>>0)};f.sub=function(a){return new A((this.g-a.g&4294967295)>>>0>>>0,((this.h-a.h&4294967295)>>>0)-(0>this.g-a.g?1:0)>>>0)};
function mb(a){var b=a&65535,c=a>>>16;a=10*b+65536*(0*b&65535)+65536*(10*c&65535);for(b=0*c+(0*b>>>16)+(10*c>>>16);4294967296<=a;)a-=4294967296,b+=1;return new A(a>>>0,b>>>0)}f.toString=function(){for(var a="",b=this;0!=b.g||0!=b.h;){var c=new A(0,0);b=new A(b.g,b.h);for(var d=new A(10,0),e=new A(1,0);!(d.h&2147483648);)d=lb(d),e=lb(e);for(;0!=e.g||0!=e.h;)0>=(d.h<b.h||d.h==b.h&&d.g<b.g?-1:d.h==b.h&&d.g==b.g?0:1)&&(c=c.add(e),b=b.sub(d)),d=kb(d),e=kb(e);c=[c,b];b=c[0];a=c[1].g+a}""==a&&(a="0");return a};
function nb(a){for(var b=new A(0,0),c=new A(0,0),d=0;d<a.length;d++){if("0">a[d]||"9"<a[d])return null;c.g=parseInt(a[d],10);var e=mb(b.g);b=mb(b.h);b.h=b.g;b.g=0;b=e.add(b).add(c)}return b}f.Gb=function(){return new A(this.g,this.h)};function B(a,b){this.g=a;this.h=b}B.prototype.add=function(a){return new B((this.g+a.g&4294967295)>>>0>>>0,((this.h+a.h&4294967295)>>>0)+(4294967296<=this.g+a.g?1:0)>>>0)};
B.prototype.sub=function(a){return new B((this.g-a.g&4294967295)>>>0>>>0,((this.h-a.h&4294967295)>>>0)-(0>this.g-a.g?1:0)>>>0)};B.prototype.i=function(){return new B(this.g,this.h)};B.prototype.toString=function(){var a=0!=(this.h&2147483648),b=new A(this.g,this.h);a&&(b=(new A(0,0)).sub(b));return(a?"-":"")+b.toString()};function ob(a){var b=0<a.length&&"-"==a[0];b&&(a=a.substring(1));a=nb(a);if(null===a)return null;b&&(a=(new A(0,0)).sub(a));return new B(a.g,a.h)};function pb(){this.h=new Uint8Array(64);this.g=0}function qb(a,b){if(!(a.g+b<a.h.length)){var c=a.h;a.h=new Uint8Array(Math.ceil(b+2*a.h.length));a.h.set(c)}}function C(a,b){qb(a,1);a.h[a.g++]=b}f=pb.prototype;f.Hb=function(a){qb(this,a.length);this.h.set(a,this.g);this.g+=a.length};f.length=function(){return this.g};f.end=function(){var a=this.h,b=this.g;this.g=0;return 0===b?cb||(cb=new Uint8Array(0)):bb?a.slice(0,b):new Uint8Array(a.subarray(0,b))};
function D(a,b,c){for(;0<c||127<b;)C(a,b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;C(a,b)}function E(a,b,c){F(a,b);F(a,c)}function rb(a,b,c){hb(b,c,function(d,e){D(a,d>>>0,e>>>0)})}function H(a,b){for(;127<b;)C(a,b&127|128),b>>>=7;C(a,b)}function sb(a,b){if(0<=b)H(a,b);else{for(var c=0;9>c;c++)C(a,b&127|128),b>>=7;C(a,1)}}function tb(a,b){H(a,(b<<1^b>>31)>>>0)}function ub(a,b){gb(ib(b));hb(x,y,function(c,d){D(a,c>>>0,d>>>0)})}f.pf=function(a){C(this,a>>>0&255)};
f.nf=function(a){C(this,a>>>0&255);C(this,a>>>8&255)};function F(a,b){C(a,b>>>0&255);C(a,b>>>8&255);C(a,b>>>16&255);C(a,b>>>24&255)}function vb(a,b){db(b);F(a,x);F(a,y)}f.oe=function(a){C(this,a>>>0&255)};f.ne=function(a){C(this,a>>>0&255);C(this,a>>>8&255)};function wb(a,b){C(a,b>>>0&255);C(a,b>>>8&255);C(a,b>>>16&255);C(a,b>>>24&255)}
function xb(a,b){var c=b;c=(b=0>c?1:0)?-c:c;if(0===c)y=0<1/c?0:2147483648,x=0;else if(isNaN(c))y=2147483647,x=4294967295;else if(1.7976931348623157E308<c)y=(b<<31|2146435072)>>>0,x=0;else if(2.2250738585072014E-308>c){var d=c/Math.pow(2,-1074);y=(b<<31|d/4294967296)>>>0;x=d>>>0}else{var e=c;d=0;if(2<=e)for(;2<=e&&1023>d;)d++,e/=2;else for(;1>e&&-1022<d;)e*=2,d--;c*=Math.pow(2,-d);y=(b<<31|d+1023<<20|1048576*c&1048575)>>>0;x=4503599627370496*c>>>0}F(a,x);F(a,y)};function yb(){this.i=[];this.h=0;this.g=new pb}function zb(a,b){0!==b.length&&(a.i.push(b),a.h+=b.length)}function Ab(a){zb(a,a.g.end())}function I(a,b){K(a,b,2);Ab(a);return{X:a.h,V:a.i.length-1}}function L(a,b){Ab(a);H(a.g,a.h+a.g.length()-b.X);var c=a.g.end();a.h+=c.length;a.i.splice(1+b.V,0,c)}f=yb.prototype;f.Kd=function(a,b,c){null!=a&&null!=b&&null!=c&&(a=a.subarray(b,c),Ab(this),zb(this,a))};
function Bb(a){var b=a.h+a.g.length();if(0===b)return new Uint8Array(0);b=new Uint8Array(b);for(var c=a.i,d=c.length,e=0,k=0;k<d;k++){var g=c[k];0!==g.length&&(b.set(g,e),e+=g.length)}c=a.g;d=c.g;0!==d&&(b.set(c.h.subarray(0,d),e),c.g=0);a.i=[b];return b}f.Wc=function(a){return Wa(Bb(this),a)};function K(a,b,c){H(a.g,8*b+c)}
f.le=function(a,b,c){switch(a){case 1:null!=c&&(K(this,b,1),xb(this.g,c));break;case 2:null!=c&&(K(this,b,5),a=this.g,fb(c),F(a,x));break;case 3:null!=c&&null!=c&&(K(this,b,0),a=this.g,z(c),D(a,x,y));break;case 4:null!=c&&null!=c&&(K(this,b,0),a=this.g,z(c),D(a,x,y));break;case 5:null!=c&&null!=c&&(K(this,b,0),sb(this.g,c));break;case 6:null!=c&&(K(this,b,1),vb(this.g,c));break;case 7:null!=c&&(K(this,b,5),F(this.g,c));break;case 8:Cb(this,b,c);break;case 9:M(this,b,c);break;case 12:null!=c&&Db(this,
b,jb(c));break;case 13:null!=c&&null!=c&&(K(this,b,0),H(this.g,c));break;case 14:Eb(this,b,c);break;case 15:null!=c&&(K(this,b,5),wb(this.g,c));break;case 16:null!=c&&(K(this,b,1),a=this.g,z(c),E(a,x,y));break;case 17:null!=c&&null!=c&&(K(this,b,0),tb(this.g,c));break;case 18:null!=c&&null!=c&&(K(this,b,0),a=this.g,eb(c),D(a,x,y))}};f.mf=function(a,b){null!=b&&null!=b&&(K(this,a,0),ub(this.g,b))};function Cb(a,b,c){null!=c&&(K(a,b,0),C(a.g,c?1:0))}
function Eb(a,b,c){null!=c&&(c=parseInt(c,10),K(a,b,0),sb(a.g,c))}
function M(a,b,c){if(null!=c){if(Ja)c=(Ia||(Ia=new TextEncoder)).encode(c);else{var d=void 0;d=void 0===d?!1:d;for(var e=0,k=new Uint8Array(3*c.length),g=0;g<c.length;g++){var h=c.charCodeAt(g);if(128>h)k[e++]=h;else{if(2048>h)k[e++]=h>>6|192;else{if(55296<=h&&57343>=h){if(56319>=h&&g<c.length){var l=c.charCodeAt(++g);if(56320<=l&&57343>=l){h=1024*(h-55296)+l-56320+65536;k[e++]=h>>18|240;k[e++]=h>>12&63|128;k[e++]=h>>6&63|128;k[e++]=h&63|128;continue}else g--}if(d)throw Error("Found an unpaired surrogate");
h=65533}k[e++]=h>>12|224;k[e++]=h>>6&63|128}k[e++]=h&63|128}}c=k.subarray(0,e)}Db(a,b,c)}}function Db(a,b,c){K(a,b,2);H(a.g,c.length);Ab(a);zb(a,c)}f.pe=function(a,b,c){null!=b&&(a=I(this,a),c(b,this),L(this,a))};f.qe=function(a,b,c){null!=b&&(K(this,1,3),K(this,2,0),sb(this.g,a),a=I(this,3),c(b,this),L(this,a),K(this,1,4))};f.me=function(a,b,c){null!=b&&(K(this,a,3),c(b,this),K(this,a,4))};f.We=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,0),sb(this.g,d))}};
f.Xe=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){K(this,a,0);var e=this.g;z(d);D(e,x,y)}}};f.ff=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var k=c(b[e]),g=d(b[e]);K(this,a,1);E(this.g,k,g)}};f.gf=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var k=c(b[e]),g=d(b[e]);K(this,a,0);D(this.g,k,g)}};f.hf=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var k=c(b[e]),g=d(b[e]);K(this,a,0);rb(this.g,k>>>0,g>>>0)}};
f.Ye=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=ob(e),K(this,d,0),D(this.g,e.g,e.h))}};f.jf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,0),H(this.g,d))}};f.kf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){K(this,a,0);var e=this.g;z(d);D(e,x,y)}}};f.lf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=nb(e),K(this,d,0),D(this.g,e.g,e.h))}};
f.cf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,0),tb(this.g,d))}};f.df=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){K(this,a,0);var e=this.g;eb(d);D(e,x,y)}}};f.ef=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,0),ub(this.g,d))}};f.Re=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,5),F(this.g,d))}};
f.Se=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,1),vb(this.g,d))}};f.Te=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=nb(e),K(this,d,1),E(this.g,e.g,e.h))}};f.$e=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,5),wb(this.g,d))}};f.af=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){K(this,a,1);var e=this.g;z(d);E(e,x,y)}}};
f.bf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=ob(e),K(this,d,1),E(this.g,e.g,e.h))}};f.Ue=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){K(this,a,5);var e=this.g;fb(d);F(e,x)}}};f.Pe=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(K(this,a,1),xb(this.g,d))}};f.Ne=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Cb(this,a,b[c])};f.Qe=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Eb(this,a,b[c])};
function Fb(a,b,c){if(null!=c)for(var d=0;d<c.length;d++)M(a,b,c[d])}f.Oe=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Db(this,a,jb(d))}};f.Ze=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++){var e=I(this,a);c(b[d],this);L(this,e)}};f.Ve=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++)K(this,a,3),c(b[d],this),K(this,a,4)};f.xe=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++)sb(this.g,b[c]);L(this,a)}};
f.ye=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++)sb(this.g,parseInt(b[c],10));L(this,a)}};f.ze=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++){var d=this.g;z(b[c]);D(d,x,y)}L(this,a)}};f.He=function(a,b,c,d){if(null!=b){a=I(this,a);for(var e=0;e<b.length;e++)E(this.g,c(b[e]),d(b[e]));L(this,a)}};f.Ie=function(a,b,c,d){if(null!=b){a=I(this,a);for(var e=0;e<b.length;e++)D(this.g,c(b[e]),d(b[e]));L(this,a)}};
f.Je=function(a,b,c,d){if(null!=b){a=I(this,a);for(var e=this.g,k=0;k<b.length;k++)rb(e,c(b[k]),d(b[k]));L(this,a)}};f.Ae=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++){var d=ob(b[c]);D(this.g,d.g,d.h)}L(this,a)}};f.Ke=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++)H(this.g,b[c]);L(this,a)}};f.Le=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++){var d=this.g;z(b[c]);D(d,x,y)}L(this,a)}};
f.Me=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++){var d=nb(b[c]);D(this.g,d.g,d.h)}L(this,a)}};f.Ee=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++)tb(this.g,b[c]);L(this,a)}};f.Fe=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++){var d=this.g;eb(b[c]);D(d,x,y)}L(this,a)}};f.Ge=function(a,b){if(null!=b&&b.length){a=I(this,a);for(var c=0;c<b.length;c++)ub(this.g,b[c]);L(this,a)}};
f.te=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,4*b.length),a=0;a<b.length;a++)F(this.g,b[a])};f.ue=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,8*b.length),a=0;a<b.length;a++)vb(this.g,b[a])};f.ve=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,8*b.length),a=0;a<b.length;a++){var c=nb(b[a]);E(this.g,c.g,c.h)}};f.Be=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,4*b.length),a=0;a<b.length;a++)wb(this.g,b[a])};
f.Ce=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,8*b.length),a=0;a<b.length;a++){var c=this.g;z(b[a]);E(c,x,y)}};f.De=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,8*b.length),a=0;a<b.length;a++){var c=this.g;gb(ib(b[a]));E(c,x,y)}};f.we=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,4*b.length),a=0;a<b.length;a++){var c=this.g;fb(b[a]);F(c,x)}};f.se=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,8*b.length),a=0;a<b.length;a++)xb(this.g,b[a])};
f.re=function(a,b){if(null!=b&&b.length)for(K(this,a,2),H(this.g,b.length),a=0;a<b.length;a++)C(this.g,b[a]?1:0)};var Gb="function"===typeof Uint8Array;function Hb(a,b,c){if(null!=a)return"object"===typeof a?Gb&&a instanceof Uint8Array?c(a):Ib(a,b,c):b(a)}function Ib(a,b,c){if(Array.isArray(a)){for(var d=Array(a.length),e=0;e<a.length;e++)d[e]=Hb(a[e],b,c);Array.isArray(a)&&a.W&&N(d);return d}d={};for(e in a)d[e]=Hb(a[e],b,c);return d}function Jb(a){return"number"===typeof a?isFinite(a)?a:String(a):a}function Kb(a){return new Uint8Array(a)}function Lb(a){return a}var Mb={W:{value:!0,configurable:!0}};
function N(a){Array.isArray(a)&&!Object.isFrozen(a)&&Object.defineProperties(a,Mb);return a}var Nb;function Ob(a,b){this.i=a;this.j=b;this.g={};this.h=!0;this.l=null;if(0<this.i.length){for(a=0;a<this.i.length;a++){b=this.i[a];var c=b[0];this.g[c.toString()]=new Pb(c,b[1])}this.h=!0}}f=Ob.prototype;f.isFrozen=function(){return!1};f.toJSON=function(){var a=this.u(!1);return Nb?a:Ib(a,Jb,Wa)};f.Jb=function(){return this.toJSON()};
f.u=function(a){if(this.h){if(this.j){var b=this.g,c;for(c in b)if(Object.prototype.hasOwnProperty.call(b,c)){var d=b[c].g;d&&d.u(a)}}}else{this.i.length=0;b=Qb(this);b.sort();for(c=0;c<b.length;c++){d=this.g[b[c]];var e=d.g;e&&e.u(a);this.i.push([d.key,d.value])}this.h=!0}return this.i};f.Sc=function(){return Qb(this).length};f.Ib=function(){this.g={};this.h=!1};f.Fc=function(a){a=a.toString();var b=this.g.hasOwnProperty(a);delete this.g[a];this.h=!1;return b};
f.Qc=function(){var a=[],b=Qb(this);b.sort();for(var c=0;c<b.length;c++){var d=this.g[b[c]];a.push([d.key,d.value])}return a};f.entries=function(){var a=[],b=Qb(this);b.sort();for(var c=0;c<b.length;c++){var d=this.g[b[c]];a.push([d.key,Rb(this,d)])}return new Sb(a)};f.keys=function(){var a=[],b=Qb(this);b.sort();for(var c=0;c<b.length;c++)a.push(this.g[b[c]].key);return new Sb(a)};f.values=function(){var a=[],b=Qb(this);b.sort();for(var c=0;c<b.length;c++)a.push(Rb(this,this.g[b[c]]));return new Sb(a)};
f.forEach=function(a,b){var c=Qb(this);c.sort();for(var d=0;d<c.length;d++){var e=this.g[c[d]];a.call(b,Rb(this,e),e.key,this)}};f.set=function(a,b){var c=new Pb(a);this.j?(c.g=b,c.value=b.u(!1)):c.value=b;this.g[a.toString()]=c;this.h=!1;return this};f.be=function(a,b){this.g[a.toString()]=new Pb(a,b);this.h=!1};function Rb(a,b){return a.j?(b.g||(b.g=new a.j(b.value),a.isFrozen()&&null(b.g)),b.g):b.value}f.get=function(a){if(a=this.g[a.toString()])return Rb(this,a)};
f.has=function(a){return a.toString()in this.g};function Qb(a){a=a.g;var b=[],c;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b}Ob.prototype[Symbol.iterator]=function(){return this.entries()};function Pb(a,b){this.key=a;this.value=b;this.g=void 0}function Sb(a){this.h=0;this.g=a}Sb.prototype.next=function(){return this.h<this.g.length?{done:!1,value:this.g[this.h++]}:{done:!0,value:void 0}};Sb.prototype[Symbol.iterator]=function(){return this};var Tb;function Ub(a,b){Tb=b;a=new a(b);Tb=null;return a};function O(a,b,c){var d=Tb;Tb=null;a||(a=d);d=this.constructor.Ld;a||(a=d?[d]:[]);this.l=d?0:-1;this.i=this.g=null;this.h=a;a:{d=this.h.length;a=d-1;if(d&&(d=this.h[a],null!==d&&"object"===typeof d&&d.constructor===Object)){this.m=a-this.l;this.j=d;break a}void 0!==b&&-1<b?(this.m=Math.max(b,a+1-this.l),this.j=null):this.m=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)a=c[b],a<this.m?(a+=this.l,(d=this.h[a])?N(d):this.h[a]=P):(Vb(this),(d=this.j[a])?N(d):this.j[a]=P)}var P=Object.freeze(N([]));
function Vb(a){var b=a.m+a.l;a.h[b]||(a.j=a.h[b]={})}function Q(a,b,c){return-1===b?null:(void 0===c?0:c)||b>=a.m?a.j?a.j[b]:void 0:a.h[b+a.l]}f=O.prototype;f.sd=function(a){return null!=Q(this,a)};f.td=function(a,b){return Wb(this,b)===a};function R(a,b){var c=void 0===c?!1:c;var d=Q(a,b,c);null==d&&(d=P);d===P&&(d=N([]),S(a,b,d,c));return d}function Xb(a,b){a=Q(a,b);return null==a?a:+a}function Yb(a,b){a=Q(a,b);return null==a?a:!!a}
f.rd=function(a){var b=R(this,a);this.i||(this.i={});if(!this.i[a]){for(var c=0;c<b.length;c++)b[c]=+b[c];this.i[a]=!0}return b};f.qd=function(a){var b=R(this,a);this.i||(this.i={});if(!this.i[a]){for(var c=0;c<b.length;c++)b[c]=!!b[c];this.i[a]=!0}return b};function Zb(a,b,c){a=Q(a,b);return null==a?c:a}function $b(a,b,c){a=Yb(a,b);return null==a?void 0===c?!1:c:a}function ac(a,b,c){a.g||(a.g={});if(b in a.g)return a.g[b];var d=Q(a,b);d||(d=N([]),S(a,b,d));c=new Ob(d,c);return a.g[b]=c}
function S(a,b,c,d){(void 0===d?0:d)||b>=a.m?(Vb(a),a.j[b]=c):a.h[b+a.l]=c;return a}function bc(a,b,c,d){d=void 0===d?!1:d;return S(a,b,N(c||[]),d)}f.ed=function(a){return cc(this,a,void 0)};f.dd=function(a){return dc(this,a,void 0)};function T(a,b,c,d){c!==d?S(a,b,c):S(a,b,void 0);return a}function ec(a,b,c,d){b=R(a,b);void 0!=d?b.splice(d,0,c):b.push(c);return a}function Wb(a,b){for(var c=0,d=0;d<b.length;d++){var e=b[d];null!=Q(a,e)&&(0!==c&&S(a,c,void 0),c=e)}return c}
function fc(a,b,c,d,e){if(-1===c)return null;a.g||(a.g={});!a.g[c]&&(e=Q(a,c,void 0===e?!1:e),d||e)&&(a.g[c]=new b(e));return a.g[c]}function gc(a,b,c){a.g||(a.g={});var d=a.g[c];if(!d){var e=R(a,c);d=[];for(var k=0;k<e.length;k++)d[k]=new b(e[k]);a.g[c]=d}return d}function cc(a,b,c,d){d=void 0===d?!1:d;a.g||(a.g={});var e=c?c.u(!1):c;a.g[b]=c;return S(a,b,e,d)}
f.ud=function(a,b,c){this.g||(this.g={});var d=c?c.u(!1):c;this.g[a]=c;(b=Wb(this,b))&&b!==a&&null!=d&&(this.g&&b in this.g&&(this.g[b]=void 0),S(this,b,void 0));return S(this,a,d)};function dc(a,b,c,d){d=void 0===d?!1:d;if(c){var e=N([]);for(var k=0;k<c.length;k++)e[k]=c[k].u(!1);a.g||(a.g={});a.g[b]=c}else a.g&&(a.g[b]=void 0),e=P;return S(a,b,e,d)}f.cd=function(a,b,c,d){var e=gc(this,c,a);b=b?b:new c;a=R(this,a);void 0!=d?(e.splice(d,0,b),a.splice(d,0,b.u(!1))):(e.push(b),a.push(b.u(!1)));return b};
f.Lb=function(){return this.toJSON()};f.je=function(){return this.toJSON()};f.toJSON=function(){var a=this.u(!1);return Nb?a:Ib(a,Jb,Wa)};f.ke=function(){return Ib(this.u(!1),Lb,Kb)};f.u=function(a){if(this.g)for(var b in this.g){var c=this.g[b];if(Array.isArray(c))for(var d=0;d<c.length;d++)c[d]&&c[d].u(a);else c&&c.u(a)}return this.h};function hc(){var a=U.g;Nb=!0;try{return JSON.stringify(a.toJSON(),ic)}finally{Nb=!1}}
function ic(a,b){switch(typeof b){case "number":return isFinite(b)?b:String(b);case "object":if(Gb&&null!=b&&b instanceof Uint8Array)return Wa(b)}return b}f.toString=function(){return this.u(!1).toString()};f.Rd=function(a,b){var c=a.h,d=a.g;return a.i?d?dc(this,c,b,!0):bc(this,c,b,!0):d?cc(this,c,b,!0):S(this,c,b,!0)};f.Kb=function(){var a=this.constructor,b=Ib(this.u(!1),Lb,Kb);a=Ub(a,b);jc(a,this);return a};
function jc(a,b){b.o&&(a.o=b.o.slice());var c=b.g;if(c){b=b.j;var d={},e;for(e in c){var k=c[e];if(k){var g=!(!b||!b[e]),h=+e;if(Array.isArray(k)){if(k.length)for(g=gc(a,k[0].constructor,h),h=0;h<Math.min(g.length,k.length);h++)jc(g[h],k[h])}else k instanceof Ob?k.j&&(d.H=ac(a,h,k.j),k.forEach(function(l){return function(n,p){return jc(l.H.get(p),n)}}(d))):(g=fc(a,k.constructor,h,0,g))&&jc(g,k)}d={H:d.H}}}}function V(a,b,c){return Wb(a,b)===c?c:-1}
function W(a,b,c){return Zb(a,b,void 0===c?"":c)}f.jd=function(a,b,c){return Zb(this,V(this,b,a),c)};f.gd=function(a,b,c){return $b(this,V(this,b,a),c)};f.md=function(a,b,c){a=V(this,b,a);return Zb(this,a,void 0===c?0:c)};f.nd=function(a,b,c){a=V(this,b,a);return Zb(this,a,void 0===c?"0":c)};f.ld=function(a,b,c){a=V(this,b,a);a=Xb(this,a);return null==a?void 0===c?0:c:a};f.od=function(a,b,c){return W(this,V(this,b,a),c)};f.hd=function(a,b){return Q(this,V(this,b,a))};
f.fd=function(a,b){return Yb(this,V(this,b,a))};f.kd=function(a,b){return Xb(this,V(this,b,a))};f.pd=function(a,b,c){return fc(this,a,V(this,c,b))};f.xd=function(a,b){return T(this,a,b,0)};f.wd=function(a,b){return T(this,a,b,0)};f.yd=function(a,b){null!=b&&0!==+b?S(this,a,b):S(this,a,void 0);return this};f.vd=function(a,b){null!=b&&0!==b.length?S(this,a,b):S(this,a,void 0);return this};function X(a){O.call(this,a,-1,kc)}X.prototype=ea(O.prototype);X.prototype.constructor=X;if(ka)ka(X,O);else for(var lc in O)if("prototype"!=lc)if(Object.defineProperties){var mc=Object.getOwnPropertyDescriptor(O,lc);mc&&Object.defineProperty(X,lc,mc)}else X[lc]=O[lc];X.G=O.prototype;f=X.prototype;f.getTenantId=function(){return Zb(this,1,0)};f.ee=function(a){return T(this,1,a,0)};f.getLocale=function(){return W(this,2)};f.Od=function(a){return T(this,4,a,"")};f.Ud=function(a){return T(this,5,a,"")};
f.fe=function(a){return T(this,6,a,"")};f.getInsecureHost=function(){return W(this,7)};f.Vd=function(a){return T(this,7,a,"")};f.Rc=function(){return $b(this,8)};f.Xd=function(a){return T(this,8,a,!1)};f.Wd=function(a){return T(this,9,a,!1)};f.Lc=function(){return R(this,10)};f.Pd=function(a){return bc(this,10,a)};f.uc=function(a,b){return ec(this,10,a,b)};f.Ac=function(){return S(this,10,P)};f.Yd=function(a){return T(this,11,a,!1)};f.de=function(a){return bc(this,12,a)};
f.wc=function(a,b){return ec(this,12,a,b)};f.Cc=function(){return S(this,12,P)};f.Sd=function(a){return bc(this,13,a)};f.vc=function(a,b){return ec(this,13,a,b)};f.Bc=function(){return S(this,13,P)};f.Oc=function(){return W(this,14)};f.Qd=function(a){return T(this,14,a,"")};f.Uc=function(){return W(this,15)};f.Zd=function(a){return T(this,15,a,"")};
f.Nd=function(){var a=new yb;Eb(a,1,Q(this,1));M(a,2,Q(this,2));M(a,4,Q(this,4));M(a,5,Q(this,5));M(a,6,Q(this,6));M(a,7,Q(this,7));Cb(a,8,Q(this,8));Cb(a,9,Q(this,9));Fb(a,10,Q(this,10));Cb(a,11,Q(this,11));Fb(a,12,Q(this,12));var b=Q(this,13);if(null!=b&&b.length){for(var c=I(a,13),d=0;d<b.length;d++)sb(a.g,b[d]);L(a,c)}M(a,14,Q(this,14));M(a,15,Q(this,15));if(b=this.o)for(Ab(a),c=0;c<b.length;c++)zb(a,b[c]);return Bb(a)};
function nc(){var a=GoogleDevelopersObject;return Ub(X,a?JSON.parse(a):null)}var kc=[10,12,13];X.prototype.s=function(a){if(null!=this){var b,c={he:Zb(this,1,0),locale:W(this,2),xc:W(this,4),Yc:W(this,5),ie:W(this,6),bd:W(this,7),Bd:$b(this,8),Ad:$b(this,9),zc:null==(b=R(this,10))?void 0:b,Cd:$b(this,11),ge:null==(b=R(this,12))?void 0:b,Ic:null==(b=R(this,13))?void 0:b,Gc:W(this,14),Jd:W(this,15)};a&&(c.Y=this);a=c}else a=void 0;return a};function oc(a){var b=pc,c=void 0;return new (c||(c=Promise))(function(d,e){function k(l){try{h(a.next(l))}catch(n){e(n)}}function g(l){try{h(a["throw"](l))}catch(n){e(n)}}function h(l){l.done?d(l.value):(new c(function(n){n(l.value)})).then(k,g)}h((a=a.apply(b,void 0)).next())})};var qc;function rc(a,b){this.g=b===sc?a:""}f=rc.prototype;f.ad=!0;f.Xc=function(){return this.g.toString()};f.$c=!0;f.Pc=function(){return 1};f.Dc=function(a,b){var c=tc.exec(uc(this).toString()),d=c[3]||"";return vc(c[1]+wc("?",c[2]||"",a)+wc("#",d,b))};f.toString=function(){return this.g+""};function uc(a){return a instanceof rc&&a.constructor===rc?a.g:"type_error:TrustedResourceUrl"}var tc=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,sc={};
function vc(a){if(void 0===qc){var b=null;var c=v.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:Ga,createScript:Ga,createScriptURL:Ga})}catch(d){v.console&&v.console.error(d.message)}qc=b}else qc=b}a=(b=qc)?b.createScriptURL(a):a;return new rc(a,sc)}
function wc(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c)if(Object.prototype.hasOwnProperty.call(c,d)){var e=c[d];e=Array.isArray(e)?e:[e];for(var k=0;k<e.length;k++){var g=e[k];null!=g&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(g)))}}return b};/*

 Copyright 2021 The Safevalues Authors
 SPDX-License-Identifier: Apache-2.0
*/
function xc(a){if(a.A&&"function"==typeof a.A)return a.A();if("undefined"!==typeof Map&&a instanceof Map||"undefined"!==typeof Set&&a instanceof Set)return Array.from(a.values());if("string"===typeof a)return a.split("");if(Ca(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function yc(a){if(a.L&&"function"==typeof a.L)return a.L();if(!a.A||"function"!=typeof a.A){if("undefined"!==typeof Map&&a instanceof Map)return Array.from(a.keys());if(!("undefined"!==typeof Set&&a instanceof Set)){if(Ca(a)||"string"===typeof a){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}b=[];c=0;for(var d in a)b[c++]=d;return b}}}
function zc(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(Ca(a)||"string"===typeof a)Array.prototype.forEach.call(a,b,c);else for(var d=yc(a),e=xc(a),k=e.length,g=0;g<k;g++)b.call(c,e[g],d&&d[g],a)};var Ac=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Bc(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var k=a[c].substring(0,d);e=a[c].substring(d+1)}else k=a[c];b(k,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function Cc(a,b){this.h=this.s=this.m="";this.j=null;this.o=this.i="";this.l=this.D=!1;if(a instanceof Cc){this.l=void 0!==b?b:a.l;Dc(this,a.m);var c=a.s;Y(this);this.s=c;c=a.h;Y(this);this.h=c;Ec(this,a.j);c=a.i;Y(this);this.i=c;Fc(this,Gc(a.g));a=a.o;Y(this);this.o=a}else a&&(c=String(a).match(Ac))?(this.l=!!b,Dc(this,c[1]||"",!0),a=c[2]||"",Y(this),this.s=Hc(a),a=c[3]||"",Y(this),this.h=Hc(a,!0),Ec(this,c[4]),a=c[5]||"",Y(this),this.i=Hc(a,!0),Fc(this,c[6]||"",!0),a=c[7]||"",Y(this),this.o=Hc(a)):
(this.l=!!b,this.g=new Ic(null,this.l))}f=Cc.prototype;f.toString=function(){var a=[],b=this.m;b&&a.push(Jc(b,Kc,!0),":");var c=this.h;if(c||"file"==b)a.push("//"),(b=this.s)&&a.push(Jc(b,Kc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.j,null!=c&&a.push(":",String(c));if(c=this.i)this.h&&"/"!=c.charAt(0)&&a.push("/"),a.push(Jc(c,"/"==c.charAt(0)?Lc:Mc,!0));(c=this.g.toString())&&a.push("?",c);(c=this.o)&&a.push("#",Jc(c,Nc));return a.join("")};
f.resolve=function(a){var b=new Cc(this),c=!!a.m;c?Dc(b,a.m):c=!!a.s;if(c){var d=a.s;Y(b);b.s=d}else c=!!a.h;c?(d=a.h,Y(b),b.h=d):c=null!=a.j;d=a.i;if(c)Ec(b,a.j);else if(c=!!a.i){if("/"!=d.charAt(0))if(this.h&&!this.i)d="/"+d;else{var e=b.i.lastIndexOf("/");-1!=e&&(d=b.i.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var k=[],g=0;g<e.length;){var h=e[g++];"."==h?d&&g==e.length&&k.push(""):".."==h?((1<k.length||
1==k.length&&""!=k[0])&&k.pop(),d&&g==e.length&&k.push("")):(k.push(h),d=!0)}d=k.join("/")}else d=e}c?(Y(b),b.i=d):c=""!==a.g.toString();c?Fc(b,Gc(a.g)):c=!!a.o;c&&(a=a.o,Y(b),b.o=a);return b};function Dc(a,b,c){Y(a);a.m=c?Hc(b,!0):b;a.m&&(a.m=a.m.replace(/:$/,""))}function Ec(a,b){Y(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.j=b}else a.j=null}function Fc(a,b,c){Y(a);b instanceof Ic?(a.g=b,Oc(a.g,a.l)):(c||(b=Jc(b,Pc)),a.g=new Ic(b,a.l));return a}
f.ae=function(a,b){return Fc(this,a,b)};f.Nc=function(){return Hc(this.g.toString())};f.Mb=function(){return this.g.toString()};f.$d=function(a,b){Y(this);Array.isArray(b)||(b=[String(b)]);Qc(this.g,a,b);return this};f.Vc=function(a){return this.g.A(a)};f.Zc=function(a){return(!this.h&&!a.h||this.h==a.h)&&(null==this.j&&null==a.j||this.j==a.j)};
f.Id=function(){Y(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Date.now()).toString(36);Y(this);this.g.set("zx",a);return this};f.Nb=function(a){Y(this);Rc(this.g,a);return this};f.ce=function(a){this.D=a;return this};f.Dd=function(){return this.D};function Y(a){if(a.D)throw Error("Tried to modify a read-only Uri");}f.Ob=function(a){this.l=a;this.g&&Oc(this.g,a);return this};
function Sc(a){return a instanceof Cc?new Cc(a):new Cc(a,void 0)}function Hc(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function Jc(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Tc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function Tc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Kc=/[#\/\?@]/g,Mc=/[#\?:]/g,Lc=/[#\?]/g,Pc=/[#\?@]/g,Nc=/#/g;function Ic(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b}
function Z(a){a.g||(a.g=new Map,a.h=0,a.i&&Bc(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}f=Ic.prototype;f.Mc=function(){Z(this);return this.h};f.add=function(a,b){Z(this);this.i=null;a=Uc(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};function Rc(a,b){Z(a);b=Uc(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a.g.delete(b))}f.Pb=function(){this.g=this.i=null;this.h=0};f.zd=function(){Z(this);return 0==this.h};
function Vc(a,b){Z(a);b=Uc(a,b);return a.g.has(b)}f.Ec=function(a){var b=this.A();return 0<=Ka(b,a)};f.forEach=function(a,b){Z(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};f.L=function(){Z(this);for(var a=Array.from(this.g.values()),b=Array.from(this.g.keys()),c=[],d=0;d<b.length;d++)for(var e=a[d],k=0;k<e.length;k++)c.push(b[d]);return c};
f.A=function(a){Z(this);var b=[];if("string"===typeof a)Vc(this,a)&&(b=b.concat(this.g.get(Uc(this,a))));else{a=Array.from(this.g.values());for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};f.set=function(a,b){Z(this);this.i=null;a=Uc(this,a);Vc(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};f.get=function(a,b){if(!a)return b;a=this.A(a);return 0<a.length?String(a[0]):b};
function Qc(a,b,c){Rc(a,b);if(0<c.length){a.i=null;var d=a.g,e=d.set;b=Uc(a,b);var k=c.length;if(0<k){for(var g=Array(k),h=0;h<k;h++)g[h]=c[h];k=g}else k=[];e.call(d,b,k);a.h+=c.length}}f.toString=function(){if(this.i)return this.i;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.A(d);for(var k=0;k<d.length;k++){var g=e;""!==d[k]&&(g+="="+encodeURIComponent(String(d[k])));a.push(g)}}return this.i=a.join("&")};
f.Jc=function(a){Z(this);this.g.forEach(function(b,c){0<=Ka(a,c)||Rc(this,c)},this);return this};function Gc(a){var b=new Ic;b.i=a.i;a.g&&(b.g=new Map(a.g),b.h=a.h);return b}function Uc(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b}function Oc(a,b){b&&!a.j&&(Z(a),a.i=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Rc(this,d),Qc(this,e,c))},a));a.j=b}f.Qb=function(a){for(var b=0;b<arguments.length;b++)zc(arguments[b],function(c,d){this.add(d,c)},this)};var Wc={};function Xc(a,b){var c=Wc[a];if(void 0!==c&&(!c.M||Date.now()<=c.M+3E5))return c.p;c=new Promise(function(e,k){b.onload=function(){return e(b)};b.onerror=function(g){b.parentNode&&b.parentNode.removeChild(b);k(g)};document.head.appendChild(b)});var d={M:0,p:c};c.catch(function(){return d.M=+new Date});Wc[a]=d;return c}
function Yc(a){var b=void 0===b?null:b;a=Sc(a);var c=document.createElement("script"),d=vc(a.toString());c.src=uc(d);var e;d=(c.ownerDocument&&c.ownerDocument.defaultView||window).document;var k=null===(e=d.querySelector)||void 0===e?void 0:e.call(d,"script[nonce]");(e=k?k.nonce||k.getAttribute("nonce")||"":"")&&c.setAttribute("nonce",e);b&&(c.type=b);return Xc(a.toString(),c)};function Zc(a,b){this.type=a;this.i=this.target=b;this.m=this.l=!1}Zc.prototype.O=function(){return this.l};Zc.prototype.j=function(){this.l=!0};Zc.prototype.h=function(){this.m=!0};var $c=function(){if(!v.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{v.addEventListener("test",Ba,b),v.removeEventListener("test",Ba,b)}catch(c){}return a}();function ad(a,b){Zc.call(this,a?a.type:"");this.relatedTarget=this.i=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.N=this.D=0;this.key="";this.o=this.s=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.I=!1;this.pointerId=0;this.pointerType="";this.g=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.i=b;if(b=a.relatedTarget){if(Ra){a:{try{Qa(b.nodeName);
var e=!0;break a}catch(k){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.D=Sa||void 0!==a.offsetX?a.offsetX:a.layerX,this.N=Sa||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.s=a.keyCode||0;this.key=a.key||"";this.o=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.I=Ta?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:bd[a.pointerType]||"";this.state=a.state;this.g=a;a.defaultPrevented&&ad.G.h.call(this)}}Fa(ad,Zc);var bd={2:"touch",3:"pen",4:"mouse"};
ad.prototype.P=function(){return 0==this.g.button&&!(Ta&&this.ctrlKey)};ad.prototype.j=function(){ad.G.j.call(this);this.g.stopPropagation?this.g.stopPropagation():this.g.cancelBubble=!0};ad.prototype.h=function(){ad.G.h.call(this);var a=this.g;a.preventDefault?a.preventDefault():a.returnValue=!1};var cd="closure_listenable_"+(1E6*Math.random()|0);var dd=0;function ed(a,b,c,d,e){this.listener=a;this.g=null;this.src=b;this.type=c;this.capture=!!d;this.i=e;this.key=++dd;this.h=this.K=!1}function fd(a){a.h=!0;a.listener=null;a.g=null;a.src=null;a.i=null};function gd(a){this.src=a;this.g={};this.h=0}f=gd.prototype;f.Tc=function(){var a=0,b;for(b in this.g)a+=this.g[b].length;return a};f.add=function(a,b,c,d,e){var k=a.toString();a=this.g[k];a||(a=this.g[k]=[],this.h++);var g=hd(a,b,d,e);-1<g?(b=a[g],c||(b.K=!1)):(b=new ed(b,this.src,k,!!d,e),b.K=c,a.push(b));return b};
f.Ub=function(a,b,c,d){a=a.toString();if(!(a in this.g))return!1;var e=this.g[a];b=hd(e,b,c,d);return-1<b?(fd(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.g[a],this.h--),!0):!1};f.Md=function(a){a=a&&a.toString();var b=0,c;for(c in this.g)if(!a||c==a){for(var d=this.g[c],e=0;e<d.length;e++)++b,fd(d[e]);delete this.g[c];this.h--}return b};f.Sb=function(a,b){a=this.g[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
f.Rb=function(a,b,c,d){a=this.g[a.toString()];var e=-1;a&&(e=hd(a,b,c,d));return-1<e?a[e]:null};f.Tb=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Pa(this.g,function(k){for(var g=0;g<k.length;++g)if(!(c&&k[g].type!=d||e&&k[g].capture!=b))return!0;return!1})};function hd(a,b,c,d){for(var e=0;e<a.length;++e){var k=a[e];if(!k.h&&k.listener==b&&k.capture==!!c&&k.i==d)return e}return-1};var id="closure_lm_"+(1E6*Math.random()|0),jd={},kd=0;function ld(a,b,c,d,e){if(d&&d.once)return md(a,b,c,d,e);if(Array.isArray(b)){for(var k=0;k<b.length;k++)ld(a,b[k],c,d,e);return null}c=nd(c);return a&&a[cd]?a.g(b,c,Da(d)?!!d.capture:!!d,e):od(a,b,c,!1,d,e)}
function od(a,b,c,d,e,k){if(!b)throw Error("Invalid event type");var g=Da(e)?!!e.capture:!!e,h=pd(a);h||(a[id]=h=new gd(a));c=h.add(b,c,d,g,k);if(c.g)return c;d=qd();c.g=d;d.src=a;d.listener=c;if(a.addEventListener)$c||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(rd(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");kd++;return c}
function qd(){function a(c){return b.call(a.src,a.listener,c)}var b=sd;return a}function md(a,b,c,d,e){if(Array.isArray(b)){for(var k=0;k<b.length;k++)md(a,b[k],c,d,e);return null}c=nd(c);return a&&a[cd]?a.h(b,c,Da(d)?!!d.capture:!!d,e):od(a,b,c,!0,d,e)}
function td(a){if("number"!==typeof a&&a&&!a.h){var b=a.src;if(b&&b[cd])b.i(a);else{var c=a.type,d=a.g;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(rd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);kd--;if(c=pd(b)){d=a.type;if(d in c.g){var e=c.g[d],k=Ka(e,a),g;(g=0<=k)&&Array.prototype.splice.call(e,k,1);g&&(fd(a),0==c.g[d].length&&(delete c.g[d],c.h--))}0==c.h&&(c.src=null,b[id]=null)}else fd(a)}}}
function rd(a){return a in jd?jd[a]:jd[a]="on"+a}function sd(a,b){if(a.h)a=!0;else{b=new ad(b,this);var c=a.listener,d=a.i||a.src;a.K&&td(a);a=c.call(d,b)}return a}function pd(a){a=a[id];return a instanceof gd?a:null}var ud="__closure_events_fn_"+(1E9*Math.random()>>>0);function nd(a){if("function"===typeof a)return a;a[ud]||(a[ud]=function(b){return a.handleEvent(b)});return a[ud]};function vd(){var a=this;this.promise=new Promise(function(b,c){a.resolve=b;a.reject=c})};function wd(){var a=this;this.h=null;this.g=new X;this.j=[];this.l=this.i=null;if(v.__globalAppLoader)return v.__globalAppLoader;try{this.g=nc()}catch(b){xd("GoogleDevelopersObject missing or invalid")}GoogleDevelopersObject=null;Ea("__globalAppLoader",this);Ea("DevsiteApp.hasFlagAccess",function(b){return a.hasFlagAccess(b)})}wd.prototype.m=function(){v.__globalAppLoader=null;td(this.i);td(this.l)};
function yd(a){var b=[];b.push(Yc("https://www.gstatic.com/external_hosted/polymer/v2/webcomponents-lite.js"));"fetch"in window&&"URL"in window||b.push(Yc(W(a.g,5)+"/js/polyfills.js"));return Promise.all(b)}function zd(a){var b=a.g.getLocale();a=W(a.g,4);return b&&"en"!==b?a.replace(/\.js$/,"__"+b.toLowerCase().replace("-","_")+".js"):a}
wd.prototype.getEnv=function(){if($b(this.g,11))return"PROD";var a=document.location.hostname;return a.endsWith("test.devsite.corp.google.com")||a.endsWith("test.devsite-v2-staging.googleplex.com")?"TEST":a.endsWith(".devsite.corp.google.com")||a.endsWith("devsite-v2-staging.googleplex.com")?"STAGE":"DEV"};
wd.prototype.hasFlagAccess=function(a){a:{var b=this.getEnv(),c=R(this.g,13),d=new URL(document.location.toString());d=new Cc(d.href);var e=Object.keys(Ha);if("PROD"!==b)for(b=r(e),e=b.next();!e.done;e=b.next())if(e=e.value,Ha[e]===a&&(e=d.g.get(e),void 0!==e)){if("true"===e){a=!0;break a}if("false"===e){a=!1;break a}}a=Array.from(c).includes(a)}return a};
function Ad(){return oc(function b(){var c=this,d,e,k,g,h,l,n,p;return ya(b,function(t){switch(t.g){case 1:return t.i=2,pa(t,yd(c),4);case 4:qa(t,3);break;case 2:d=ra(t),xd("Failed to load Devsite App dependencies: "+d.message);case 3:e=new vd;Ea("__devsiteAppReadyResolver",e.resolve);Ea("__devsiteAppReadyPromise",e.promise);Ea("DevsiteApp.whenReady",function(){return e.promise});if(!R(c.g,12).length){t.C(5);break}t.i=6;return pa(t,Promise.all(R(c.g,12).map(function(G){G=Sc(G);var J=document.createElement("link");
J.setAttribute("rel","stylesheet");J.setAttribute("type","text/css");J.setAttribute("href",G.toString());return Xc(G.toString(),J)})),8);case 8:qa(t,5);break;case 6:k=ra(t),xd("Failed to load Devsite App dependencies: "+k.message);case 5:return g=v.DevsiteAppTenantCustomized?W(c.g,6):W(c.g,5),t.i=9,pa(t,Yc(g+zd(c)),11);case 11:qa(t,10);break;case 9:h=ra(t);if("en"===c.g.getLocale()){xd("Failed to load Devsite App binary: "+h.message);t.C(10);break}T(c.g,2,"en","");t.i=13;return pa(t,Yc(g+W(c.g,4)),
15);case 15:qa(t,10);break;case 13:l=ra(t),xd("Failed to load Devsite App binary: "+l.message);case 10:if(n=document,"complete"===n.readyState||"interactive"===n.readyState)t.C(0);else return p=new vd,n.addEventListener("readystatechange",function(){"interactive"!==n.readyState&&"complete"!==n.readyState||p.resolve()}),pa(t,p.promise,0)}})})}function xd(a){throw Error(void 0===a?"Devsite has failed to load.":a);};var U=new wd;(function(){var a=document.querySelector("devsite-content");a&&(U.i=ld(window,"message",function(b){U.j.push(b)}),U.l=md(a,"devsite-content-updated",function(){td(U.i);for(var b=r(U.j),c=b.next();!c.done;c=b.next())(c=c.value.g)&&window.dispatchEvent(c);U.j=[];td(U.l)}))})();var Bd;var pc=U,Cd=window;"WeakMap"in Cd&&"performance"in Cd&&"now"in Cd.performance?(pc.h||(pc.h=Ad()),Bd=pc.h):Bd=Promise.resolve();
Bd.then(function(){v.DevsiteAppInit||xd("Failed to load Devsite App binary");$b(U.g,9)?DevsiteAppFrameboxInit(hc(),v.DevsiteAppAuthorizedElements):DevsiteAppInit(hc(),v.DevsiteAppAuthorizedElements)});}).call(this);
