(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var m,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},p=ca(this),q=function(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}};
q("Symbol",function(a){if(a)return a;var b=function(f,g){this.bb=f;ba(this,"description",{configurable:!0,writable:!0,value:g})};b.prototype.toString=function(){return this.bb};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=p[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});
var da=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},r=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},ea=function(a){if(!(a instanceof Array)){a=r(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a},fa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ha;
if("function"==typeof Object.setPrototypeOf)ha=Object.setPrototypeOf;else{var ia;a:{var ja={a:!0},ka={};try{ka.__proto__=ja;ia=ka.a;break a}catch(a){}ia=!1}ha=ia?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var la=ha,t=function(a,b){a.prototype=fa(b.prototype);a.prototype.constructor=a;if(la)la(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.zb=b.prototype},ma=function(){this.na=!1;this.S=null;this.o=void 0;this.g=1;this.Pa=this.xa=0;this.aa=null},na=function(a){if(a.na)throw new TypeError("Generator is already running");a.na=!0};ma.prototype.oa=function(a){this.o=a};
ma.prototype.qa=function(a){this.aa={gb:a,mb:!0};this.g=this.xa||this.Pa};ma.prototype.return=function(a){this.aa={return:a};this.g=this.Pa};var u=function(a,b,c){a.g=c;return{value:b}},oa=function(a){a.xa=0;a.aa=null},pa=function(a){this.h=new ma;this.rb=a};pa.prototype.oa=function(a){na(this.h);if(this.h.S)return qa(this,this.h.S.next,a,this.h.oa);this.h.oa(a);return ra(this)};
var sa=function(a,b){na(a.h);var c=a.h.S;if(c)return qa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.h.return);a.h.return(b);return ra(a)};pa.prototype.qa=function(a){na(this.h);if(this.h.S)return qa(this,this.h.S["throw"],a,this.h.oa);this.h.qa(a);return ra(this)};
var qa=function(a,b,c,d){try{var e=b.call(a.h.S,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.h.na=!1,e;var f=e.value}catch(g){return a.h.S=null,a.h.qa(g),ra(a)}a.h.S=null;d.call(a.h,f);return ra(a)},ra=function(a){for(;a.h.g;)try{var b=a.rb(a.h);if(b)return a.h.na=!1,{value:b.value,done:!1}}catch(c){a.h.o=void 0,a.h.qa(c)}a.h.na=!1;if(a.h.aa){b=a.h.aa;a.h.aa=null;if(b.mb)throw b.gb;return{value:b.return,done:!0}}return{value:void 0,
done:!0}},ta=function(a){this.next=function(b){return a.oa(b)};this.throw=function(b){return a.qa(b)};this.return=function(b){return sa(a,b)};this[Symbol.iterator]=function(){return this}},v=function(a,b){b=new ta(new pa(b));la&&a.prototype&&la(b,a.prototype);return b},w=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},ua="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)w(d,e)&&(a[e]=d[e])}return a};
q("Object.assign",function(a){return a||ua});
q("Promise",function(a){function b(){this.N=null}function c(g){return g instanceof e?g:new e(function(h){h(g)})}if(a)return a;b.prototype.Ma=function(g){if(null==this.N){this.N=[];var h=this;this.Na(function(){h.hb()})}this.N.push(g)};var d=p.setTimeout;b.prototype.Na=function(g){d(g,0)};b.prototype.hb=function(){for(;this.N&&this.N.length;){var g=this.N;this.N=[];for(var h=0;h<g.length;++h){var k=g[h];g[h]=null;try{k()}catch(l){this.eb(l)}}}this.N=null};b.prototype.eb=function(g){this.Na(function(){throw g;
})};var e=function(g){this.j=0;this.P=void 0;this.ea=[];this.Ua=!1;var h=this.za();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}};e.prototype.za=function(){function g(l){return function(n){k||(k=!0,l.call(h,n))}}var h=this,k=!1;return{resolve:g(this.ub),reject:g(this.Ha)}};e.prototype.ub=function(g){if(g===this)this.Ha(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof e)this.wb(g);else{a:switch(typeof g){case "object":var h=null!=g;break a;case "function":h=!0;break a;default:h=
!1}h?this.tb(g):this.Qa(g)}};e.prototype.tb=function(g){var h=void 0;try{h=g.then}catch(k){this.Ha(k);return}"function"==typeof h?this.xb(h,g):this.Qa(g)};e.prototype.Ha=function(g){this.Ya(2,g)};e.prototype.Qa=function(g){this.Ya(1,g)};e.prototype.Ya=function(g,h){if(0!=this.j)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.j);this.j=g;this.P=h;2===this.j&&this.vb();this.jb()};e.prototype.vb=function(){var g=this;d(function(){if(g.qb()){var h=p.console;"undefined"!==
typeof h&&h.error(g.P)}},1)};e.prototype.qb=function(){if(this.Ua)return!1;var g=p.CustomEvent,h=p.Event,k=p.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof g?g=new g("unhandledrejection",{cancelable:!0}):"function"===typeof h?g=new h("unhandledrejection",{cancelable:!0}):(g=p.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.P;return k(g)};e.prototype.jb=function(){if(null!=this.ea){for(var g=0;g<this.ea.length;++g)f.Ma(this.ea[g]);
this.ea=null}};var f=new b;e.prototype.wb=function(g){var h=this.za();g.sa(h.resolve,h.reject)};e.prototype.xb=function(g,h){var k=this.za();try{g.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};e.prototype.then=function(g,h){function k(z,O){return"function"==typeof z?function(Ya){try{l(z(Ya))}catch(Za){n(Za)}}:O}var l,n,y=new e(function(z,O){l=z;n=O});this.sa(k(g,l),k(h,n));return y};e.prototype.catch=function(g){return this.then(void 0,g)};e.prototype.sa=function(g,h){function k(){switch(l.j){case 1:g(l.P);
break;case 2:h(l.P);break;default:throw Error("Unexpected state: "+l.j);}}var l=this;null==this.ea?f.Ma(k):this.ea.push(k);this.Ua=!0};e.resolve=c;e.reject=function(g){return new e(function(h,k){k(g)})};e.race=function(g){return new e(function(h,k){for(var l=r(g),n=l.next();!n.done;n=l.next())c(n.value).sa(h,k)})};e.all=function(g){var h=r(g),k=h.next();return k.done?c([]):new e(function(l,n){function y(Ya){return function(Za){z[Ya]=Za;O--;0==O&&l(z)}}var z=[],O=0;do z.push(void 0),O++,c(k.value).sa(y(z.length-
1),n),k=h.next();while(!k.done)})};return e});q("String.prototype.startsWith",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var d=this+"";b+="";var e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var g=0;g<f&&c<e;)if(d[c++]!=b[g++])return!1;return g>=f}});
q("WeakMap",function(a){function b(){}function c(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function d(k){if(!w(k,f)){var l=new b;ba(k,f,{value:l})}}function e(k){var l=Object[k];l&&(Object[k]=function(n){if(n instanceof b)return n;Object.isExtensible(n)&&d(n);return l(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),n=new a([[k,2],[l,3]]);if(2!=n.get(k)||3!=n.get(l))return!1;n.delete(k);n.set(l,4);return!n.has(k)&&4==n.get(l)}catch(y){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var g=0,h=function(k){this.ma=(g+=Math.random()+1).toString();if(k){k=r(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};h.prototype.set=function(k,l){if(!c(k))throw Error("Invalid WeakMap key");d(k);if(!w(k,f))throw Error("WeakMap key fail: "+k);k[f][this.ma]=l;return this};h.prototype.get=function(k){return c(k)&&w(k,f)?k[f][this.ma]:void 0};h.prototype.has=function(k){return c(k)&&w(k,f)&&w(k[f],
this.ma)};h.prototype.delete=function(k){return c(k)&&w(k,f)&&w(k[f],this.ma)?delete k[f][this.ma]:!1};return h});
q("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),k=new a(r([[h,"s"]]));if("s"!=k.get(h)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),n=l.next();if(n.done||n.value[0]!=h||"s"!=n.value[1])return!1;n=l.next();return n.done||4!=n.value[0].x||"t"!=n.value[1]||!l.next().done?!1:!0}catch(y){return!1}}())return a;var b=new WeakMap,c=function(h){this.la={};this.v=
f();this.size=0;if(h){h=r(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}};c.prototype.set=function(h,k){h=0===h?0:h;var l=d(this,h);l.list||(l.list=this.la[l.id]=[]);l.s?l.s.value=k:(l.s={next:this.v,M:this.v.M,head:this.v,key:h,value:k},l.list.push(l.s),this.v.M.next=l.s,this.v.M=l.s,this.size++);return this};c.prototype.delete=function(h){h=d(this,h);return h.s&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.la[h.id],h.s.M.next=h.s.next,h.s.next.M=h.s.M,h.s.head=null,
this.size--,!0):!1};c.prototype.clear=function(){this.la={};this.v=this.v.M=f();this.size=0};c.prototype.has=function(h){return!!d(this,h).s};c.prototype.get=function(h){return(h=d(this,h).s)&&h.value};c.prototype.entries=function(){return e(this,function(h){return[h.key,h.value]})};c.prototype.keys=function(){return e(this,function(h){return h.key})};c.prototype.values=function(){return e(this,function(h){return h.value})};c.prototype.forEach=function(h,k){for(var l=this.entries(),n;!(n=l.next()).done;)n=
n.value,h.call(k,n[1],n[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(h,k){var l=k&&typeof k;"object"==l||"function"==l?b.has(k)?l=b.get(k):(l=""+ ++g,b.set(k,l)):l="p_"+k;var n=h.la[l];if(n&&w(h.la,l))for(h=0;h<n.length;h++){var y=n[h];if(k!==k&&y.key!==y.key||k===y.key)return{id:l,list:n,index:h,s:y}}return{id:l,list:n,index:-1,s:void 0}},e=function(h,k){var l=h.v;return da(function(){if(l){for(;l.head!=h.v;)l=l.M;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};
l=null}return{done:!0,value:void 0}})},f=function(){var h={};return h.M=h.next=h.head=h},g=0;return c});var va=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};q("Array.prototype.values",function(a){return a?a:function(){return va(this,function(b,c){return c})}});
q("Array.prototype.keys",function(a){return a?a:function(){return va(this,function(b){return b})}});q("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});
q("Array.prototype.entries",function(a){return a?a:function(){return va(this,function(b,c){return[b,c]})}});q("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)w(b,d)&&c.push(b[d]);return c}});
var x=this||self,wa=function(a,b){a=a.split(".");var c=x;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b},xa=function(){},ya=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},za=function(a){var b=ya(a);return"array"==b||"object"==b&&"number"==typeof a.length},Aa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},Ba=
function(a,b,c){return a.call.apply(a.bind,arguments)},Ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},Da=function(a,b,c){Da=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?Ba:Ca;return Da.apply(null,arguments)},Ea=function(a,b){function c(){}
c.prototype=b.prototype;a.zb=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Nb=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}},Fa=function(a){return a};var A=function(a,b){var c=void 0;return new (c||(c=Promise))(function(d,e){function f(k){try{h(b.next(k))}catch(l){e(l)}}function g(k){try{h(b["throw"](k))}catch(l){e(l)}}function h(k){k.done?d(k.value):(new c(function(l){l(k.value)})).then(f,g)}h((b=b.apply(a,void 0)).next())})};function B(a){if(Error.captureStackTrace)Error.captureStackTrace(this,B);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}Ea(B,Error);B.prototype.name="CustomError";var Ga;var Ha=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");B.call(this,c+a[d])};Ea(Ha,B);Ha.prototype.name="AssertionError";
var Ia=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new Ha(""+e,f||[]);},C=function(a,b,c){a||Ia("",null,b,Array.prototype.slice.call(arguments,2));return a},Ja=function(a,b){throw new Ha("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},D=function(a,b,c){"number"!==typeof a&&Ia("Expected number but got %s: %s.",[ya(a),a],b,Array.prototype.slice.call(arguments,2));return a},Ka=function(a,b,c){"function"!==typeof a&&Ia("Expected function but got %s: %s.",
[ya(a),a],b,Array.prototype.slice.call(arguments,2))},E=function(a,b,c,d){a instanceof b||Ia("Expected instanceof %s but got %s.",[La(b),La(a)],c,Array.prototype.slice.call(arguments,3));return a},La=function(a){return a instanceof Function?a.displayName||a.name||"unknown type name":a instanceof Object?a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a):null===a?"null":typeof a};var Ma=Array.prototype.forEach?function(a,b){C(null!=a.length);Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};function Na(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Oa;var Ra=function(a,b){this.$a=a===Pa&&b||"";this.cb=Qa};Ra.prototype.toString=function(){return"Const{"+this.$a+"}"};var Qa={},Pa={};var Ta=function(a,b){this.Wa=b===Sa?a:""};Ta.prototype.toString=function(){return this.Wa+""};
var Ua=function(a){if(a instanceof Ta&&a.constructor===Ta)return a.Wa;Ja("expected object of type TrustedResourceUrl, got '"+a+"' of type "+ya(a));return"type_error:TrustedResourceUrl"},Sa={},Va=function(a){if(void 0===Oa){var b=null;var c=x.trustedTypes;if(c&&c.createPolicy)try{b=c.createPolicy("goog#html",{createHTML:Fa,createScript:Fa,createScriptURL:Fa})}catch(d){x.console&&x.console.error(d.message)}Oa=b}a=(b=Oa)?b.createScriptURL(a):a;return new Ta(a,Sa)};var F;a:{var Wa=x.navigator;if(Wa){var Xa=Wa.userAgent;if(Xa){F=Xa;break a}}F=""};var $a=/^[\w+/_-]+[=]{0,2}$/;var ab=function(a){if(a.V&&"function"==typeof a.V)return a.V();if("undefined"!==typeof Map&&a instanceof Map||"undefined"!==typeof Set&&a instanceof Set)return Array.from(a.values());if("string"===typeof a)return a.split("");if(za(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b},bb=function(a){if(a.Fa&&"function"==typeof a.Fa)return a.Fa();if(!a.V||"function"!=typeof a.V){if("undefined"!==typeof Map&&a instanceof Map)return Array.from(a.keys());
if(!("undefined"!==typeof Set&&a instanceof Set)){if(za(a)||"string"===typeof a){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}b=[];c=0;for(var d in a)b[c++]=d;return b}}},cb=function(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(za(a)||"string"===typeof a)Array.prototype.forEach.call(a,b,c);else for(var d=bb(a),e=ab(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)};var db=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),eb=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var G=function(a){this.K=this.Y=this.R="";this.ga=null;this.U=this.G="";this.F=this.nb=!1;if(a instanceof G){this.F=a.F;fb(this,a.R);var b=a.Y;H(this);this.Y=b;b=a.K;H(this);this.K=b;gb(this,a.ga);b=a.G;H(this);this.G=b;hb(this,a.C.clone());a=a.U;H(this);this.U=a}else a&&(b=String(a).match(db))?(this.F=!1,fb(this,b[1]||"",!0),a=b[2]||"",H(this),this.Y=ib(a),a=b[3]||"",H(this),this.K=ib(a,!0),gb(this,b[4]),a=b[5]||"",H(this),this.G=ib(a,!0),hb(this,b[6]||"",!0),a=b[7]||"",H(this),this.U=ib(a)):(this.F=
!1,this.C=new I(null,this.F))};G.prototype.toString=function(){var a=[],b=this.R;b&&a.push(jb(b,kb,!0),":");var c=this.K;if(c||"file"==b)a.push("//"),(b=this.Y)&&a.push(jb(b,kb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.ga,null!=c&&a.push(":",String(c));if(c=this.G)this.K&&"/"!=c.charAt(0)&&a.push("/"),a.push(jb(c,"/"==c.charAt(0)?lb:mb,!0));(c=this.C.toString())&&a.push("?",c);(c=this.U)&&a.push("#",jb(c,nb));return a.join("")};
G.prototype.resolve=function(a){var b=this.clone(),c=!!a.R;c?fb(b,a.R):c=!!a.Y;if(c){var d=a.Y;H(b);b.Y=d}else c=!!a.K;c?(d=a.K,H(b),b.K=d):c=null!=a.ga;d=a.G;if(c)gb(b,a.ga);else if(c=!!a.G){if("/"!=d.charAt(0))if(this.K&&!this.G)d="/"+d;else{var e=b.G.lastIndexOf("/");-1!=e&&(d=b.G.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],g=0;g<e.length;){var h=e[g++];"."==h?d&&g==e.length&&f.push(""):".."==
h?((1<f.length||1==f.length&&""!=f[0])&&f.pop(),d&&g==e.length&&f.push("")):(f.push(h),d=!0)}d=f.join("/")}else d=e}c?(H(b),b.G=d):c=""!==a.C.toString();c?hb(b,a.C.clone()):c=!!a.U;c&&(a=a.U,H(b),b.U=a);return b};G.prototype.clone=function(){return new G(this)};
var fb=function(a,b,c){H(a);a.R=c?ib(b,!0):b;a.R&&(a.R=a.R.replace(/:$/,""))},gb=function(a,b){H(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.ga=b}else a.ga=null},hb=function(a,b,c){H(a);b instanceof I?(a.C=b,a.C.Ja(a.F)):(c||(b=jb(b,ob)),a.C=new I(b,a.F))};G.prototype.getQuery=function(){return this.C.toString()};var J=function(a,b,c){H(a);a.C.set(b,c);return a};G.prototype.removeParameter=function(a){H(this);this.C.remove(a);return this};
var H=function(a){if(a.nb)throw Error("Tried to modify a read-only Uri");};G.prototype.Ja=function(a){this.F=a;this.C&&this.C.Ja(a)};
var ib=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},jb=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,pb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},pb=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},kb=/[#\/\?@]/g,mb=/[#\?:]/g,lb=/[#\?]/g,ob=/[#\?@]/g,nb=/#/g,I=function(a,b){this.u=this.i=null;this.A=a||null;this.F=!!b},K=function(a){a.i||(a.i=new Map,a.u=0,a.A&&eb(a.A,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g,
" ")),c)}))};I.prototype.add=function(a,b){K(this);this.A=null;a=L(this,a);var c=this.i.get(a);c||this.i.set(a,c=[]);c.push(b);this.u=D(this.u)+1;return this};I.prototype.remove=function(a){K(this);a=L(this,a);return this.i.has(a)?(this.A=null,this.u=D(this.u)-this.i.get(a).length,this.i.delete(a)):!1};I.prototype.clear=function(){this.i=this.A=null;this.u=0};var qb=function(a,b){K(a);b=L(a,b);return a.i.has(b)};m=I.prototype;
m.forEach=function(a,b){K(this);this.i.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};m.Fa=function(){K(this);for(var a=Array.from(this.i.values()),b=Array.from(this.i.keys()),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};m.V=function(a){K(this);var b=[];if("string"===typeof a)qb(this,a)&&(b=b.concat(this.i.get(L(this,a))));else{a=Array.from(this.i.values());for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};
m.set=function(a,b){K(this);this.A=null;a=L(this,a);qb(this,a)&&(this.u=D(this.u)-this.i.get(a).length);this.i.set(a,[b]);this.u=D(this.u)+1;return this};m.get=function(a,b){if(!a)return b;a=this.V(a);return 0<a.length?String(a[0]):b};
m.toString=function(){if(this.A)return this.A;if(!this.i)return"";for(var a=[],b=Array.from(this.i.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.V(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.A=a.join("&")};m.clone=function(){var a=new I;a.A=this.A;this.i&&(a.i=new Map(this.i),a.u=this.u);return a};var L=function(a,b){b=String(b);a.F&&(b=b.toLowerCase());return b};
I.prototype.Ja=function(a){a&&!this.F&&(K(this),this.A=null,this.i.forEach(function(b,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.remove(d),0<b.length&&(this.A=null,this.i.set(L(this,d),Na(b)),this.u=D(this.u)+b.length))},this));this.F=a};I.prototype.extend=function(a){for(var b=0;b<arguments.length;b++)cb(arguments[b],function(c,d){this.add(d,c)},this)};C(!0);var rb=-1!=F.toLowerCase().indexOf("webkit")&&-1==F.indexOf("Edge");var sb={},tb=null,ub=function(a){var b;C(za(a),"encodeByteArray takes an array as a parameter");void 0===b&&(b=0);if(!tb){tb={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));sb[e]=f;for(var g=0;g<f.length;g++){var h=f[g],k=tb[h];void 0===k?tb[h]=g:C(k===g)}}}b=sb[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){k=a[f];var l=a[f+1];h=a[f+2];g=b[k>>2];k=b[(k&
3)<<4|l>>4];l=b[(l&15)<<2|h>>6];h=b[h&63];c[e++]=""+g+k+l+h}g=0;h=d;switch(a.length-f){case 2:g=a[f+1],h=b[(g&15)<<2]||d;case 1:a=a[f],c[e]=""+b[a>>2]+b[(a&3)<<4|g>>4]+h+d}return c.join("")};var vb="function"===typeof Uint8Array;function wb(a){return xb(a,function(b){return b},function(b){return new Uint8Array(b)})}function yb(a,b,c){return"object"===typeof a?vb&&!Array.isArray(a)&&a instanceof Uint8Array?c(a):xb(C(a),b,c):b(a)}function xb(a,b,c){if(Array.isArray(a)){for(var d=Array(a.length),e=0;e<a.length;e++){var f=a[e];null!=f&&(d[e]=yb(f,b,c))}Array.isArray(a)&&a.ob&&M(d);return d}d={};for(e in a)f=a[e],null!=f&&(d[e]=yb(f,b,c));return d}
function zb(a){return xb(a,function(b){return"number"===typeof b?isFinite(b)?b:String(b):b},function(b){return ub(b)})}var Ab={ob:{value:!0,configurable:!0}},M=function(a){Array.isArray(a)&&!Object.isFrozen(a)&&Object.defineProperties(a,Ab);return a},Bb,Cb=Symbol("exempted jspb subclass"),Db=Symbol("generated by jspb");var N=function(a,b){this.I=a;this.ja=b;this.map={};this.ka=!0;this.Va=null;if(0<this.I.length){for(a=0;a<this.I.length;a++){b=this.I[a];var c=b[0];this.map[c.toString()]=new Eb(c,b[1])}this.ka=!0}};m=N.prototype;m.isFrozen=function(){return!1};m.toJSON=function(){var a=this.H(!1);return Bb?a:zb(a)};
m.H=function(a){if(this.ka){if(this.ja){var b=this.map,c;for(c in b)if(Object.prototype.hasOwnProperty.call(b,c)){var d=b[c].Z;d&&d.H(a)}}}else{this.I.length=0;b=Fb(this);b.sort();for(c=0;c<b.length;c++){d=this.map[b[c]];var e=d.Z;e&&e.H(a);this.I.push([d.key,d.value])}this.ka=!0}return this.I};m.clear=function(){this.map={};this.ka=!1};m.entries=function(){var a=[],b=Fb(this);b.sort();for(var c=0;c<b.length;c++){var d=this.map[b[c]];a.push([d.key,Gb(this,d)])}return new Hb(a)};
m.keys=function(){var a=[],b=Fb(this);b.sort();for(var c=0;c<b.length;c++)a.push(this.map[b[c]].key);return new Hb(a)};m.values=function(){var a=[],b=Fb(this);b.sort();for(var c=0;c<b.length;c++)a.push(Gb(this,this.map[b[c]]));return new Hb(a)};m.forEach=function(a,b){var c=Fb(this);c.sort();for(var d=0;d<c.length;d++){var e=this.map[c[d]];a.call(b,Gb(this,e),e.key,this)}};m.set=function(a,b){var c=new Eb(a);this.ja?(c.Z=b,c.value=b.H(!1)):c.value=b;this.map[a.toString()]=c;this.ka=!1;return this};
var Gb=function(a,b){return a.ja?(b.Z||(b.Z=new a.ja(b.value),a.isFrozen()&&(C(null!=a.Va),a.Va(b.Z))),b.Z):b.value};N.prototype.get=function(a){if(a=this.map[a.toString()])return Gb(this,a)};N.prototype.has=function(a){return a.toString()in this.map};var Fb=function(a){a=a.map;var b=[],c;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b};N.prototype[Symbol.iterator]=function(){return this.entries()};
var Eb=function(a,b){this.key=a;this.value=b;this.Z=void 0},Hb=function(a){this.Sa=0;this.I=a};Hb.prototype.next=function(){return this.Sa<this.I.length?{done:!1,value:this.I[this.Sa++]}:{done:!0,value:void 0}};Hb.prototype[Symbol.iterator]=function(){return this};var Ib;function Jb(a,b){Ib=b;a=new a(b);Ib=null;return a};var P=function(a,b,c){E(this,P,"The message constructor should only be used by subclasses");C(this.constructor!==P,"Message is an abstract class and cannot be directly constructed");if(!0!==this[Cb]){C(!0===this[Db],"Message can only be subclassed by proto gencode.");var d=Object.getPrototypeOf(C(Object.getPrototypeOf(this)));C(d.hasOwnProperty(Db),"Generated jspb classes should not be extended")}d=Ib;Ib=null;a||(a=d);d=this.constructor.Sb;a||(a=d?[d]:[]);this.ba=d?0:-1;this.m=null;this.L=a;a:{d=
this.L.length;a=d-1;if(d&&(d=this.L[a],!(null===d||"object"!=typeof d||Array.isArray(d)||vb&&d instanceof Uint8Array))){this.fa=a-this.ba;this.O=d;break a}void 0!==b&&-1<b?(this.fa=Math.max(b,a+1-this.ba),this.O=null):this.fa=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)a=c[b],a<this.fa?(a+=this.ba,(d=this.L[a])?M(d):this.L[a]=Kb):(Lb(this),(d=this.O[a])?M(d):this.O[a]=Kb)},Kb=Object.freeze(M([])),Lb=function(a){var b=a.fa+a.ba;a.L[b]||(a.O=a.L[b]={})},Q=function(a,b,c){return-1===b?null:(void 0===
c?0:c)||b>=a.fa?a.O?a.O[b]:void 0:a.L[b+a.ba]},Nb=function(a,b){var c=void 0===c?!1:c;var d=Q(a,b,c);null==d&&(d=Kb);d===Kb&&(d=M([]),Mb(a,b,d,c));return d},Ob=function(a,b,c,d){a.m||(a.m={});if(b in a.m)return a.m[b];var e=Q(a,b);if(!e){if(c)return;e=M([]);Mb(a,b,e)}c=new N(e,d);return a.m[b]=c},Mb=function(a,b,c,d){(void 0===d?0:d)||b>=a.fa?(Lb(a),a.O[b]=c):a.L[b+a.ba]=c};function R(a,b,c,d){E(a,P);c!==d?Mb(a,b,c):Mb(a,b,void 0);return a}
var Pb=function(a,b,c,d,e){if(-1===c)return null;a.m||(a.m={});!a.m[c]&&(e=Q(a,c,void 0===e?!1:e),d||e)&&(a.m[c]=new b(e));return a.m[c]},Qb=function(a,b,c){a.m||(a.m={});var d=a.m[c];if(!d){var e=Nb(a,c);d=[];for(var f=0;f<e.length;f++)d[f]=new b(e[f]);a.m[c]=d}return d};P.prototype.toJSON=function(){var a=this.H(!1);return Bb?a:zb(a)};P.prototype.H=function(a){if(this.m)for(var b in this.m){var c=this.m[b];if(Array.isArray(c))for(var d=0;d<c.length;d++)c[d]&&c[d].H(a);else c&&c.H(a)}return this.L};
var S=function(a){Bb=!0;try{return JSON.stringify(a.toJSON(),Rb)}finally{Bb=!1}},Rb=function(a,b){switch(typeof b){case "number":return isFinite(b)?b:String(b);case "object":if(vb&&null!=b&&b instanceof Uint8Array)return ub(b)}return b},T=function(a,b){a=Jb(a,b?JSON.parse(b):null);E(a,P);return a};P.prototype.toString=function(){return this.H(!1).toString()};P.prototype.getExtension=function(a){var b=a.Pb,c=a.Ob;return a.Rb?c?Qb(this,c,b):Nb(this,b):c?Pb(this,c,b,0,!0):Q(this,b,!0)};
P.prototype.clone=function(){var a=E(this,P),b=a.constructor,c=wb(a.H(!1));b=Jb(b,c);Sb(b,a);return b};
function Sb(a,b){C(a,"expected `to` to be non-null");C(b,"expected `from` to be non-null");b.Ta&&(a.Ta=b.Ta.slice());var c=b.m;if(c){b=b.O;var d={},e;for(e in c){var f=c[e];if(f){var g=!(!b||!b[e]),h=+e;if(Array.isArray(f)){if(f.length)for(g=Qb(a,f[0].constructor,h),h=0;h<Math.min(g.length,f.length);h++)Sb(g[h],E(f[h],P))}else f instanceof N?f.ja&&(d.wa=Ob(a,h,!1,f.ja),f.forEach(function(k){return function(l,n){return Sb(k.wa.get(n),l)}}(d))):(E(f,P),(g=Pb(a,f.constructor,h,0,g))&&Sb(g,f))}d={wa:d.wa}}}}
var Tb=function(a,b){a=Q(a,b);return null==a?0:a},Ub=function(a,b){a=Q(a,b);return null==a?"":a};var U=function(){P.apply(this,arguments)};t(U,P);U.prototype[Db]=!0;var Vb=function(a){U.call(this,a)};t(Vb,U);var Wb=function(a){U.call(this,a)};t(Wb,U);var Xb=function(a){U.call(this,a)};t(Xb,U);Xb.prototype.setProjectId=function(a){return R(this,1,a,"")};var Yb=function(a){U.call(this,a)};t(Yb,U);var Zb=function(a){U.call(this,a)};t(Zb,U);var $b=function(a){U.call(this,a)};t($b,U);$b.prototype.Xa=function(a){return R(this,1,a,"")};$b.prototype.getItem=function(){return Ub(this,2)};$b.prototype.setItem=function(a){return R(this,2,a,"")};var ac=function(a){U.call(this,a)};t(ac,U);var bc=function(a){U.call(this,a)};t(bc,U);/*

 Copyright 2021 The Safevalues Authors
 SPDX-License-Identifier: Apache-2.0
*/
function cc(a){var b,c=(a.ownerDocument&&a.ownerDocument.defaultView||window).document,d=null===(b=c.querySelector)||void 0===b?void 0:b.call(c,"script[nonce]");(b=d?d.nonce||d.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",b)};try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};var V=function(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0};m=V.prototype;m.clone=function(){return new V(this.x,this.y)};m.toString=function(){return"("+this.x+", "+this.y+")"};m.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};m.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};m.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
m.translate=function(a,b){a instanceof V?(this.x+=a.x,this.y+=a.y):(this.x+=Number(a),"number"===typeof b&&(this.y+=b));return this};m.scale=function(a,b){this.x*=a;this.y*="number"===typeof b?b:a;return this};var dc=function(a,b){this.width=a;this.height=b};m=dc.prototype;m.clone=function(){return new dc(this.width,this.height)};m.toString=function(){return"("+this.width+" x "+this.height+")"};m.aspectRatio=function(){return this.width/this.height};m.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};m.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
m.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};m.scale=function(a,b){this.width*=a;this.height*="number"===typeof b?b:a;return this};var ec=function(a,b,c){function d(h){h&&b.appendChild("string"===typeof h?a.createTextNode(h):h)}for(var e=1;e<c.length;e++){var f=c[e];if(!za(f)||Aa(f)&&0<f.nodeType)d(f);else{a:{if(f&&"number"==typeof f.length){if(Aa(f)){var g="function"==typeof f.item||"string"==typeof f.item;break a}if("function"===typeof f){g="function"==typeof f.item;break a}}g=!1}Ma(g?Na(f):f,d)}}},fc=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)},gc=function(a){return a&&
a.parentNode?a.parentNode.removeChild(a):null},hc=function(a){C(a,"Node cannot be null or undefined.");return 9==a.nodeType?a:a.ownerDocument||a.document},ic=function(a){this.Aa=a||x.document||document};m=ic.prototype;m.getElementsByTagName=function(a,b){return(b||this.Aa).getElementsByTagName(String(a))};m.createElement=function(a){return fc(this.Aa,a)};m.createTextNode=function(a){return this.Aa.createTextNode(String(a))};
m.appendChild=function(a,b){C(null!=a&&null!=b,"goog.dom.appendChild expects non-null arguments");a.appendChild(b)};m.append=function(a,b){ec(hc(a),a,arguments)};m.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
m.removeNode=gc;m.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var jc=function(a,b){this.pb=100;this.fb=a;this.sb=b;this.ua=0;this.v=null};jc.prototype.get=function(){if(0<this.ua){this.ua--;var a=this.v;this.v=a.next;a.next=null}else a=this.fb();return a};jc.prototype.put=function(a){this.sb(a);this.ua<this.pb&&(this.ua++,a.next=this.v,this.v=a)};var kc,lc=function(){var a=x.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&-1==F.indexOf("Presto")&&(a=function(){var e=fc(document,"IFRAME");e.style.display="none";document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.close();var g="callImmediate"+Math.random(),h="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;e=Da(function(k){if(("*"==h||k.origin==h)&&k.data==g)this.port1.onmessage()},
this);f.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(g,h)}}});if("undefined"!==typeof a&&-1==F.indexOf("Trident")&&-1==F.indexOf("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var e=c.Oa;c.Oa=null;e()}};return function(e){d.next={Oa:e};d=d.next;b.port2.postMessage(0)}}return function(e){x.setTimeout(e,0)}};function mc(a){x.setTimeout(function(){throw a;},0)};var nc=function(){this.va=this.$=null};nc.prototype.add=function(a,b){var c=oc.get();c.set(a,b);this.va?this.va.next=c:(C(!this.$),this.$=c);this.va=c};nc.prototype.remove=function(){var a=null;this.$&&(a=this.$,this.$=this.$.next,this.$||(this.va=null),a.next=null);return a};var oc=new jc(function(){return new pc},function(a){return a.reset()}),pc=function(){this.next=this.scope=this.Da=null};pc.prototype.set=function(a,b){this.Da=a;this.scope=b;this.next=null};
pc.prototype.reset=function(){this.next=this.scope=this.Da=null};var uc=function(a,b){qc||rc();sc||(qc(),sc=!0);tc.add(a,b)},qc,rc=function(){if(x.Promise&&x.Promise.resolve){var a=x.Promise.resolve(void 0);qc=function(){a.then(vc)}}else qc=function(){var b=vc;"function"!==typeof x.setImmediate||x.Window&&x.Window.prototype&&-1==F.indexOf("Edge")&&x.Window.prototype.setImmediate==x.setImmediate?(kc||(kc=lc()),kc(b)):x.setImmediate(b)}},sc=!1,tc=new nc,vc=function(){for(var a;a=tc.remove();){try{a.Da.call(a.scope)}catch(b){mc(b)}oc.put(a)}sc=!1};var W=function(a){this.j=0;this.P=void 0;this.ca=this.J=this.X=null;this.ta=this.Ca=!1;if(a!=xa)try{var b=this;a.call(void 0,function(c){wc(b,2,c)},function(c){if(!(c instanceof xc))try{if(c instanceof Error)throw c;throw Error("Promise rejected.");}catch(d){}wc(b,3,c)})}catch(c){wc(this,3,c)}},yc=function(){this.next=this.context=this.da=this.W=this.T=null;this.ra=!1};yc.prototype.reset=function(){this.context=this.da=this.W=this.T=null;this.ra=!1};
var zc=new jc(function(){return new yc},function(a){a.reset()}),Ac=function(a,b,c){var d=zc.get();d.W=a;d.da=b;d.context=c;return d};W.prototype.then=function(a,b,c){null!=a&&Ka(a,"opt_onFulfilled should be a function.");null!=b&&Ka(b,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");return Bc(this,"function"===typeof a?a:null,"function"===typeof b?b:null,c)};W.prototype.$goog_Thenable=!0;var Cc=function(a,b){return Bc(a,null,b,void 0)};
W.prototype.cancel=function(a){if(0==this.j){var b=new xc(a);uc(function(){Dc(this,b)},this)}};
var Dc=function(a,b){if(0==a.j)if(a.X){var c=a.X;if(c.J){for(var d=0,e=null,f=null,g=c.J;g&&(g.ra||(d++,g.T==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.j&&1==d?Dc(c,b):(f?(d=f,C(c.J),C(null!=d),d.next==c.ca&&(c.ca=d),d.next=d.next.next):Ec(c),Fc(c,e,3,b)))}a.X=null}else wc(a,3,b)},Hc=function(a,b){a.J||2!=a.j&&3!=a.j||Gc(a);C(null!=b.W);a.ca?a.ca.next=b:a.J=b;a.ca=b},Bc=function(a,b,c,d){var e=Ac(null,null,null);e.T=new W(function(f,g){e.W=b?function(h){try{var k=b.call(d,h);f(k)}catch(l){g(l)}}:
f;e.da=c?function(h){try{var k=c.call(d,h);void 0===k&&h instanceof xc?g(h):f(k)}catch(l){g(l)}}:g});e.T.X=a;Hc(a,e);return e.T};W.prototype.Ab=function(a){C(1==this.j);this.j=0;wc(this,2,a)};W.prototype.Bb=function(a){C(1==this.j);this.j=0;wc(this,3,a)};
var wc=function(a,b,c){if(0==a.j){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.j=1;a:{var d=c,e=a.Ab,f=a.Bb;if(d instanceof W){null!=e&&Ka(e,"opt_onFulfilled should be a function.");null!=f&&Ka(f,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");Hc(d,Ac(e||xa,f||null,a));var g=!0}else{if(d)try{var h=!!d.$goog_Thenable}catch(l){h=!1}else h=!1;if(h)d.then(e,f,a),g=!0;else{if(Aa(d))try{var k=d.then;if("function"===typeof k){Ic(d,
k,e,f,a);g=!0;break a}}catch(l){f.call(a,l);g=!0;break a}g=!1}}}g||(a.P=c,a.j=b,a.X=null,Gc(a),3!=b||c instanceof xc||Jc(a,c))}},Ic=function(a,b,c,d,e){var f=!1,g=function(k){f||(f=!0,c.call(e,k))},h=function(k){f||(f=!0,d.call(e,k))};try{b.call(a,g,h)}catch(k){h(k)}},Gc=function(a){a.Ca||(a.Ca=!0,uc(a.ib,a))},Ec=function(a){var b=null;a.J&&(b=a.J,a.J=b.next,b.next=null);a.J||(a.ca=null);null!=b&&C(null!=b.W);return b};
W.prototype.ib=function(){for(var a;a=Ec(this);)Fc(this,a,this.j,this.P);this.Ca=!1};var Fc=function(a,b,c,d){if(3==c&&b.da&&!b.ra)for(;a&&a.ta;a=a.X)a.ta=!1;if(b.T)b.T.X=null,Kc(b,c,d);else try{b.ra?b.W.call(b.context):Kc(b,c,d)}catch(e){Lc.call(null,e)}zc.put(b)},Kc=function(a,b,c){2==b?a.W.call(a.context,c):a.da&&a.da.call(a.context,c)},Jc=function(a,b){a.ta=!0;uc(function(){a.ta&&Lc.call(null,b)})},Lc=mc,xc=function(a){B.call(this,a)};Ea(xc,B);xc.prototype.name="cancel";var Mc=function(a,b){if("function"!==typeof a)if(a&&"function"==typeof a.handleEvent)a=Da(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:x.setTimeout(a,b||0)},Nc=function(a,b){var c=null;return Cc(new W(function(d,e){c=Mc(function(){d(b)},a);-1==c&&e(Error("Failed to schedule timer."))}),function(d){x.clearTimeout(c);throw d;})};var Oc;var Pc=new Ra(Pa,"https://apis.google.com/js/client.js");Pc instanceof Ra&&Pc.constructor===Ra&&Pc.cb===Qa?Oc=Pc.$a:(Ja("expected object of type Const, got '"+Pc+"'"),Oc="type_error:Const");var Qc=Va(Oc),Rc=!1;function Sc(){return A(this,function b(){var c;return v(b,function(d){Rc||x.gapi||(c=fc(document,"SCRIPT"),c.src=Ua(Qc),cc(c),c.type="text/javascript",c.async=!0,c.onerror=function(){gc(c);Rc=!1},document.body.appendChild(c),Rc=!0);return d.return(Tc())})})}
function Tc(){return A(this,function b(){var c;return v(b,function(d){return 1==d.g?(c=x.gapi)?u(d,new Promise(function(e,f){c.load("gapi.iframes",{callback:function(){e()},timeout:3E4,ontimeout:function(){f(Error("Timeout while trying to load GAPI frames library."))},onerror:function(g){f(Error(g?g.message:"Error while trying to load GAPI frames library."))}})}),0):u(d,Nc(100),4):d.return(Tc())})})};var Uc=function(){this.messageHandlers=new Map};Uc.prototype.register=function(a,b){if(this.messageHandlers.has(a))throw Error("Handler for "+a+" already exists.");this.messageHandlers.set(a,b);this.iframe&&this.iframe.register(a,b,gapi.iframes.CROSS_ORIGIN_IFRAMES_FILTER)};Uc.prototype.unregister=function(a){this.messageHandlers.delete(a);this.iframe&&this.iframe.unregister(a)};
Uc.prototype.send=function(a,b,c){if(!this.iframe)throw Error("Iframe is not open. Tried to send '"+a+"'");this.iframe.send(a,b,c,gapi.iframes.CROSS_ORIGIN_IFRAMES_FILTER)};var Vc=function(a){if(!a.iframe)throw Error("Iframe is not ready");for(var b=r(a.messageHandlers.keys()),c=b.next();!c.done;c=b.next())a.iframe.unregister(c.value)},Wc=function(a){this.messageHandlers=new Map;this.Ea=a;this.Ga=!1};t(Wc,Uc);
Wc.prototype.open=function(){return A(this,function b(){var c=this;return v(b,function(d){if(1==d.g)return u(d,Sc(),2);if(3!=d.g){if(c.isOpen)throw Error("App is already open.");c.Ga=!0;return u(d,gapi.iframes.getContext().open(Object.assign({},c.Ea)),3)}c.iframe=d.o;if(!c.iframe)throw Error("Iframe is not ready");for(var e=r(c.messageHandlers),f=e.next();!f.done;f=e.next()){var g=r(f.value);f=g.next().value;g=g.next().value;c.iframe.register(f,g,gapi.iframes.CROSS_ORIGIN_IFRAMES_FILTER)}d.g=0})})};
Wc.prototype.close=function(){return A(this,function b(){var c=this,d;return v(b,function(e){d=c;if(!c.isOpen)throw Error("App is not open.");return e.return(new Promise(function(f,g){d.iframe?(Vc(d),d.iframe.close({},function(){f()}),d.iframe=void 0,d.Ga=!1):g("Iframe is not open.")}))})})};Wc.prototype.ping=function(){var a;return A(this,function c(){var d=this;return v(c,function(e){d.iframe?e=u(e,null===(a=d.iframe)||void 0===a?void 0:a.ping(),0):(e.g=0,e=void 0);return e})})};
p.Object.defineProperties(Wc.prototype,{isOpen:{configurable:!0,enumerable:!0,get:function(){return this.Ga}}});var Xc=function(a){this.messageHandlers=new Map;this.iframe=a||void 0},Yc;t(Xc,Uc);
var Zc=function(){return A(this,function b(){var c,d,e;return v(b,function(f){switch(f.g){case 1:return Yc?f.return(Yc):u(f,Sc(),2);case 2:c=gapi.iframes.getContext().getParentIframe();d=null;if(!c){f.g=3;break}return u(f,Promise.race([c.ping().then(function(){return c}),Nc(1E4,null)]),4);case 4:d=f.o;case 3:if(Yc)return f.return(Yc);e=new Xc(d);d&&(Yc=e);return f.return(e)}})})};var X=function(a){this.name=a};X.prototype.l=function(a){return A(this,function c(){var d,e=this;return v(c,function(f){if(1==f.g)return u(f,Zc(),2);d=f.o;d.register(e.name,a);f.g=0})})};X.prototype.removeListener=function(){return A(this,function b(){var c,d=this;return v(b,function(e){if(1==e.g)return u(e,Zc(),2);c=e.o;c.unregister(d.name);e.g=0})})};X.prototype.send=function(a,b){var c=this;return new Promise(function(d,e){try{a.iframe.send(c.name,b,function(f){f=r(f).next().value;d(f)})}catch(f){e(f)}})};
var bd=function(){var a=$c;this.pa=ad;this.ha=a;this.B=new X("cloud_shell_bounds_for_element")};bd.prototype.l=function(a){var b=this;return this.B.l(function(c){return A(b,function e(){var f=this,g,h;return v(e,function(k){if(1==k.g)return g=T(f.pa,c),u(k,a(g),2);h=k.o;return k.return(S(h))})})})};bd.prototype.removeListener=function(){return A(this,function b(){var c=this;return v(b,function(d){return u(d,c.B.removeListener(),0)})})};
bd.prototype.send=function(a,b){return A(this,function d(){var e=this,f;return v(d,function(g){if(1==g.g)return u(g,e.B.send(a,S(b)),2);f=g.o;return g.return(T(e.ha,f))})})};var Y=function(a){this.name=a};Y.prototype.l=function(a,b){a.iframe.register(this.name,b)};Y.prototype.removeListener=function(a){a.iframe.unregister(this.name)};Y.prototype.send=function(a){return A(this,function c(){var d=this,e,f;return v(c,function(g){if(1==g.g)return e=d,u(g,Zc(),2);f=g.o;return g.return(new Promise(function(h,k){try{f.send(e.name,a,function(l){l=r(l).next().value;h(l)})}catch(l){k(l)}}))})})};
var dd=function(){var a=cd;this.name="cloud_shell_feedback_start";this.pa=ac;this.ha=a;this.B=new Y(this.name)};dd.prototype.l=function(a,b){var c=this;this.B.l(a,function(d){return A(c,function f(){var g=this,h,k;return v(f,function(l){if(1==l.g)return h=T(g.pa,d),u(l,b(h),2);k=l.o;return l.return(S(k))})})})};dd.prototype.removeListener=function(a){this.B.removeListener(a)};
dd.prototype.send=function(a){return A(this,function c(){var d=this,e;return v(c,function(f){if(1==f.g)return u(f,d.B.send(S(a)),2);e=f.o;return f.return(T(d.ha,e))})})};var ed=function(a,b){this.name=a;this.kb=void 0===b?!1:b;this.Za=new Y(this.name);this.Ka=new X(this.name)};m=ed.prototype;m.l=function(a){return A(this,function c(){var d=this;return v(c,function(e){return u(e,d.Ka.l(a),0)})})};m.removeListener=function(){return A(this,function b(){var c=this;return v(b,function(d){return u(d,c.Ka.removeListener(),0)})})};m.send=function(a){return A(this,function c(){var d=this;return v(c,function(e){return e.return(d.Za.send(a))})})};
m.Ia=function(a,b){return A(this,function d(){var e=this;return v(d,function(f){1==f.g?!e.kb||a.isOpen?(f.g=2,f=void 0):f=u(f,a.open(),2):f=f.return(e.Ka.send(a,b));return f})})};m.Ba=function(a,b){var c=this;this.Za.l(a,function(d){return c.Ia(b,d)})};var fd=function(a,b,c){this.pa=b;this.ha=c;this.B=new ed(a,!1)};m=fd.prototype;
m.l=function(a){return A(this,function c(){var d=this,e;return v(c,function(f){e=d;return u(f,d.B.l(function(g){return A(e,function k(){var l=this,n,y;return v(k,function(z){if(1==z.g)return n=T(l.pa,g),u(z,a(n),2);y=z.o;return z.return(S(y))})})}),0)})})};m.removeListener=function(){return A(this,function b(){var c=this;return v(b,function(d){return u(d,c.B.removeListener(),0)})})};
m.send=function(a){return A(this,function c(){var d=this,e;return v(c,function(f){if(1==f.g)return u(f,d.B.send(S(a)),2);e=f.o;return f.return(T(d.ha,e))})})};m.Ia=function(a,b){return A(this,function d(){var e=this,f;return v(d,function(g){if(1==g.g)return u(g,e.B.Ia(a,S(b)),2);f=g.o;return g.return(T(e.ha,f))})})};m.Ba=function(a,b){this.B.Ba(a,b)};var ad=function(a){U.call(this,a)};t(ad,U);ad.prototype.Xa=function(a){return R(this,1,a,"")};var gd=function(a){U.call(this,a)};t(gd,U);var $c=function(a){U.call(this,a,-1,hd)};t($c,U);var hd=[1];var cd=function(a){U.call(this,a)};t(cd,U);var id=new Y("close"),jd=new X("host_enter_shell_command"),kd=new Y("get_project"),ld=new Y("resize"),md=new dd,nd=new X("expect_regex"),od=new bd,pd=new X("cloud_shell_focus_element"),qd=new Y("cloud_shell_clear_spotlights"),rd=new Y("editor_loaded"),sd=new Y("first_prompt"),td=new X("get_web_preview_address"),ud=new Y("maximize"),vd=new Y("is_maximized"),wd=new X("set_project"),xd=[new ed("enter_shell_command",!0),new ed("open-cloud-shell",!0),new fd("cloud-shell-status",Xb,Wb),new fd("editor-spotlight",
$b,cd),new ed("editor-open-file"),new fd("editor-select-line",Yb,cd),new fd("editor-select-regex",Zb,cd)];var yd={Cb:"cloudshell_context",Db:"cloudshell_create_custom_image",Eb:"cloudshell_working_dir",Fb:"cloudshell_git_branch",Gb:"cloudshell_git_repo",Hb:"cloudshell_go_get_repo",Ib:"cloudshell_image",Jb:"cloudshell_open_in_editor",Kb:"cloudshell_print",Mb:"cloudshell_workspace",Lb:"cloudshell_tutorial"};var zd={element:{D:Element},environmentDeployment:{D:"string",optional:!0},language:{D:"string",optional:!0},mode:{D:"string",optional:!0},onClose:{D:"function",optional:!0},onEditorLoad:{D:"function",optional:!0},onTerminalReady:{D:"function",optional:!0},onOpen:{D:"function",optional:!0},parseQueryParams:{D:"boolean",optional:!0},projectIdProvider:{D:"function",optional:!0},resizer:{D:"function",optional:!0},concordWindowId:{D:"string",optional:!0},maximization:{D:"object",optional:!0}};
function Ad(a){var b=[];Object.keys(zd).forEach(function(c){var d=a[c],e=zd[c],f=e.D;e.optional||void 0!==d?(void 0!==d&&"string"===typeof f&&typeof d!==f||void 0!==d&&"function"===typeof f&&!(d instanceof f))&&b.push("Option '"+c+"' requires type '"+f+"'.'"):b.push("Missing required option: '"+c+"'")});return b};var Bd=function(a){this.window=a};p.Object.defineProperties(Bd.prototype,{ya:{configurable:!0,enumerable:!0,get:function(){var a=String;var b=this.url.C.get("cloudshell");return"true"===a(b).toLowerCase()},set:function(a){a=J(this.url,"cloudshell",String(a));var b=void 0;try{b=this.window.history.state}catch(c){}try{this.window.history.replaceState(b,"",a.toString())}catch(c){}}},url:{configurable:!0,enumerable:!0,get:function(){return new G(this.window.location.href)}}});var Cd=function(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||x,e=d.document,f;if(!(f=a.nonce))a:{f=(d||x).document;if(f.querySelector&&(f=f.querySelector("script[nonce]"))&&(f=f.nonce||f.getAttribute("nonce"))&&$a.test(f))break a;f=""}f&&!a.nonce&&(a.nonce=f);if("help"==a.flow){a:{var g=["document","location","href"];for(var h=d||x,k=0;k<g.length;k++)if(h=h[g[k]],null==h){g=null;break a}g=h}!a.helpCenterContext&&g&&(a.helpCenterContext=g.substring(0,1200));g=!0;b&&JSON&&JSON.stringify&&
(h=JSON.stringify(b),(g=1200>=h.length)&&(a.psdJson=h));g||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.serverUri||"//www.google.com/tools/feedback";if(g=d.GOOGLE_FEEDBACK_START)g.apply(d,b);else{d=c+"/load.js?";for(var l in a)b=a[l],null==b||Aa(b)||(d+=encodeURIComponent(l)+"="+encodeURIComponent(b)+"&");a=(e?new ic(hc(e)):Ga||(Ga=new ic)).createElement("SCRIPT");f&&a.setAttribute("nonce",f);l=Va(d);a.src=Ua(l);cc(a);e.body.appendChild(a)}};
wa("userfeedback.api.startFeedback",Cd);function Dd(a,b){var c={Qb:b.location.href};Ob(a,2,void 0,null).forEach(function(d,e){c[e]=d});return c};var Ed=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};m=Ed.prototype;m.clone=function(){return new Ed(this.left,this.top,this.width,this.height)};m.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};m.contains=function(a){return a instanceof V?a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height:this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height};
m.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};m.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};m.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
m.translate=function(a,b){a instanceof V?(this.left+=a.x,this.top+=a.y):(this.left+=D(a),"number"===typeof b&&(this.top+=b));return this};m.scale=function(a,b){b="number"===typeof b?b:a;this.left*=a;this.width*=a;this.top*=b;this.height*=b;return this};var Fd=function(a){try{return a.getBoundingClientRect()}catch(b){return{left:0,top:0,right:0,bottom:0}}},Gd=function(a,b){a:{var c=hc(b);if(c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(b,null))){c=c.display||c.getPropertyValue("display")||"";break a}c=""}c||(c=b.currentStyle?b.currentStyle.display:null);if("none"!=(c||b.style&&b.style.display))return a(b);c=b.style;var d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display=
"inline";a=a(b);c.display=d;c.position=f;c.visibility=e;return a},Hd=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=rb&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=Fd(a),new dc(a.right-a.left,a.bottom-a.top)):new dc(b,c)};var Id=[].concat(ea(Object.values(yd)),["authuser","disableOnBeforeUnload","jsmode","cloudshellsafemode","mendelDebugInput"]),Z=function(a,b,c){var d=this;b=void 0===b?window:b;c=void 0===c?Wc:c;this.options=a;this.La=b;this.lb=c;this.iframe=new this.lb({url:this.ab,where:this.options.element,waitForOnload:!1,attributes:Object.assign(Object.assign({"class":"cloudshell-frame"},this.options.disableIframeTitle?{}:{title:"Cloud Shell Window"}),{style:{height:"100%"},allow:"clipboard-read *; clipboard-write *;"})});
id.l(this,function(){return d.close()});kd.l(this,function(){return d.options.projectIdProvider?d.options.projectIdProvider():""});ld.l(this,function(e){d.options.resizer&&d.options.resizer(e)});ud.l(this,function(){var e;null===(e=d.options.maximization)||void 0===e?void 0:e.maximize()});vd.l(this,function(){var e;return!(null===(e=d.options.maximization)||void 0===e||!e.isMaximized())});md.l(this,function(e){var f=d.La;f=void 0===f?window:f;var g=Pb(e,bc,1);e=Dd(e,f);g&&Cd({productId:Ub(g,1),locale:Ub(g,
2),authuser:Ub(g,3),bucket:Ub(g,4),productVersion:Ub(g,5)},e);return new cd});rd.l(this,function(){Jd(d.options.onEditorLoad)});qd.l(this,function(){var e;null===(e=d.yb)||void 0===e?void 0:e.clearSpotlights()});sd.l(this,function(){var e,f;null===(f=(e=d.options).onTerminalReady)||void 0===f?void 0:f.call(e)});a.parseQueryParams&&(this.ia=new Bd(b),Kd(this),Ld(this)&&this.open())},Md=function(a){return A(a,function c(){var d=this,e,f,g,h,k;return v(c,function(l){switch(l.g){case 1:e=d,f=30,g=500,
h=0;case 2:if(!(h<f)){l.g=4;break}l.xa=5;k=new Promise(function(n,y){e.La.setTimeout(function(){return void y()},g)});return u(l,Promise.race([d.iframe.ping(),k]),7);case 7:return l.return();case 5:oa(l);l.g=3;break;case 3:h++;l.g=2;break;case 4:throw Error("Not transport ready");}})})};m=Z.prototype;m.setWalkthroughController=function(a){for(var b=r(xd),c=b.next();!c.done;c=b.next())c.value.Ba(a,this);this.yb=a};
m.focusElement=function(a){var b=this.options.element.querySelector("iframe");b&&b.contentWindow&&!decodeURIComponent(a).startsWith("theia::")&&b.contentWindow.focus();pd.send(this,a)};m.boundsForElement=function(a){return A(this,function c(){var d=this,e;return v(c,function(f){if(1==f.g)return u(f,od.send(d,(new ad).Xa(a)),2);e=f.o;return f.return(Qb(e,gd,1).map(function(g){return new Ed(Tb(g,1),Tb(g,2),Tb(g,3),Tb(g,4))}))})})};
m.open=function(){return A(this,function b(){var c=this;return v(b,function(d){if(1==d.g)return u(d,c.iframe.open(),2);Jd(c.options.onOpen);c.ia&&(c.ia.ya=!0);d.g=0})})};m.close=function(){return A(this,function b(){var c=this;return v(b,function(d){if(1==d.g)return u(d,c.iframe.close(),2);Jd(c.options.onClose);c.ia&&(c.ia.ya=!1);d.g=0})})};m.sendCommand=function(a){return A(this,function c(){var d=this;return v(c,function(e){return 1==e.g?u(e,Md(d),2):u(e,jd.send(d,a),0)})})};
m.expectRegExp=function(a){return A(this,function c(){var d=this;return v(c,function(e){return 1==e.g?u(e,Md(d),2):u(e,nd.send(d,a),0)})})};m.getWebPreviewAddress=function(a){return A(this,function c(){var d=this,e;return v(c,function(f){if(1==f.g){if(2E3>a||65E3<a)throw Error("Invalid port specified. Please use a port between 2000 and 65000");return u(f,Md(d),2)}if(3!=f.g)return u(f,td.send(d,a),3);e=f.o;return f.return(e)})})};
m.setProjectId=function(a){return A(this,function c(){var d=this;return v(c,function(e){return 1==e.g?u(e,Md(d),2):u(e,wd.send(d,a),0)})})};
var Ld=function(a){return a.options.parseQueryParams?a.ia&&a.ia.ya?!0:Object.values(yd).map(function(b){return a.Ra.get(b)}).some(function(b){return b}):!1},Kd=function(a){var b=[].concat(ea(Id));a.options.language||b.push("hl");var c=new G(a.ab);b=r(b);for(var d=b.next();!d.done;d=b.next()){d=d.value;var e=a.Ra.get(d);e&&J(c,d,e)}a=a.iframe;c={url:c.toString()};a.Ea=Object.assign(Object.assign({},a.Ea),c)};
p.Object.defineProperties(Z.prototype,{ab:{configurable:!0,enumerable:!0,get:function(){var a,b=new G("EditorShell"===this.options.mode?"https://shell.cloud.google.com/cloudshell/editor":"https://shell.cloud.google.com/embeddedcloudshell");this.options.language&&J(b,"hl",this.options.language);this.options.environmentDeployment&&J(b,"environment_deployment",this.options.environmentDeployment);(null===(a=this.options.experiments)||void 0===a?0:a.useEmptyWorkspace)||J(b,"cloudshell_workspace","~");
J(b,"hostappurl",String(window.location));J(b,"embedded","true");var c=new Vb;c=R(c,1,this.options.concordWindowId||"","");c=R(c,2,!!this.options.maximization,!1);c=R(c,3,!!this.options.hatsSurvey,!1);J(b,"embedding_options",S(c));return b.toString()}},boundingBox:{configurable:!0,enumerable:!0,get:function(){var a=this.options.element;C(a);if(1==a.nodeType){var b=Fd(a);b=new V(b.left,b.top)}else b=a.changedTouches?a.changedTouches[0]:a,b=new V(b.clientX,b.clientY);if(a.getBoundingClientRect){var c=
Gd(Fd,a);c=new dc(c.right-c.left,c.bottom-c.top)}else c=null;a=c||Gd(Hd,a);return new Ed(b.x,b.y,a.width,a.height)}},isOpen:{configurable:!0,enumerable:!0,get:function(){return this.iframe.isOpen}},Ra:{configurable:!0,enumerable:!0,get:function(){return new I(this.La.location.search.slice(1))}}});Z.prototype.close=Z.prototype.close;Z.prototype.open=Z.prototype.open;function Jd(a){try{(void 0===a?function(){}:a)()}catch(b){console.error(b)}}
function Nd(a){0===Ad(a).length||console.error("Cloud Shell options could not be validated"+Ad(a).join("\n"));return new Z(a)}wa("google.devops.tools.cloudshell.configure",Nd);wa("google.devops.tools.cloudshell.createController",Nd);}).call(this);
