(function(_ds){var window=this;'use strict';var x2=function(a){return!a.classList.contains("material-icons")},y2=function(){var a=_ds.fi.call(this)||this;a.ya=new _ds.qm;a.Aa=new _ds.qm;a.oa=new Set;a.ea=null;"IntersectionObserver"in window&&(a.ea=new IntersectionObserver(function(b){b=_ds.v(b);for(var c=b.next();!c.done;c=b.next())c=c.value,c.isIntersecting&&(c=c.target,_ds.WM(new _ds.UM,c,x2),a.oa.delete(c),a.ea.unobserve(c))},{rootMargin:"100%"}));return a},bla=function(a){Array.from(a.getElementsByTagName("table")).forEach(function(b){if(!b.parentNode.classList.contains("devsite-table-wrapper")){var c=
document.createElement("div");c.classList.add("devsite-table-wrapper");b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));_ds.rj(c,b);c.appendChild(b)}})},jla=function(a,b){var c,d,e,g,h,k,l;return _ds.Xa(function(m){if(1==m.$)return _ds.x(m,DevsiteApp.whenReady(),2);c=_ds.Mk();d=DevsiteApp.getInsecureHost();e=b.hb;if(e.origin!==c.origin&&d&&e.origin!==d)return m.return();try{g=_ds.rf(_ds.tn,e.data)}catch(n){return m.return()}h=_ds.We(g,
1,0);if(4===h)return cla(a,e),m.return();k=g.getName();if(!k)return m.return();if(l=a.querySelector('devsite-iframe iframe[name="'+k+'"]'))switch(h){case 5:dla(g,l);break;case 8:ela(e,g,c);break;case 1:fla(e,g,c);break;case 6:case 7:gla(h,c,g);break;case 9:hla(a,g);break;case 10:ila(g,c)}_ds.y(m)})},dla=function(a,b){var c,d,e,g;_ds.Xa(function(h){c=_ds.dj().y;d=a.Vd();e=_ds.xf(a,3);g=_ds.Dj(b);d&&g.setAttribute("width",d+"px");e&&g.setAttribute("height",e+"px");window.requestAnimationFrame(function(){window.scrollTo(_ds.dj().x,
c)});_ds.y(h)})},cla=function(a,b){var c,d,e;_ds.Xa(function(g){if(c=kla(a,b.source)){d="goog_"+_ds.En++;c.setAttribute("name",d);var h=_ds.un(3);e=_ds.Cf(h,2,d);(h=b.source)&&h.postMessage(_ds.qf(e),"*")}_ds.y(g)})},ela=function(a,b,c){var d;_ds.Xa(function(e){var g=_ds.vn(_ds.un(8),_ds.M(b,8));d=_ds.Cf(g,6,c.toString());(g=a.source)&&g.postMessage(_ds.qf(d),"*");_ds.y(e)})},fla=function(a,b,c){var d;_ds.Xa(function(e){var g=_ds.vn(_ds.un(2),_ds.M(b,8));d=_ds.Cf(g,7,c.search+c.hash);(g=a.source)&&
g.postMessage(_ds.qf(d),"*");_ds.y(e)})},gla=function(a,b,c){var d,e,g;_ds.Xa(function(h){d=c.Rb();e=new URL(c.getUrl(),b.origin);g=window.location.origin+window.location.pathname+e.search+e.hash;6===a?window.history.pushState({},d,g):window.history.replaceState({},d,g);_ds.y(h)})},hla=function(a,b){var c,d,e,g;_ds.Xa(function(h){c=_ds.M(b,9);d=JSON.parse(_ds.M(b,10));"cloudtrackEvent"===c&&d?(e=d,g={eventData:e},a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:g,
bubbles:!0}))):"devsite-apix"===c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",{detail:d,bubbles:!0}));_ds.y(h)})},ila=function(a,b){var c,d;_ds.Xa(function(e){if(c=a.getUrl())d=new URL(c,b.origin),c.startsWith("#")||b.origin===d.origin&&b.pathname===d.pathname&&b.search===d.search?DevsiteApp.scrollToAnchor(d.hash,!0):DevsiteApp.fetchPage(d.href);_ds.y(e)})},kla=function(a,b){var c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(function(d){_ds.Hj(d)===b&&(c=d)});return c},
z2=function(a){a.ra=a.querySelector(".devsite-article-body");a.ra&&lla(a);a.ea&&a.ea.disconnect();a.oa.clear();bla(a);var b=Array.from(a.querySelectorAll(".devsite-nav-title, .devsite-page-title, td > code, th > code"));if("docs"===document.body.getAttribute("layout")&&a.ra){var c=Array.from(a.ra.querySelectorAll("h1, h2, h3, h4, h5, h6"));b.push.apply(b,_ds.ta(c))}a.oa.clear();a.oa=new Set(b);if(_ds.Mk().hash){b=new _ds.UM;c=_ds.v(a.oa);for(var d=c.next();!d.done;d=c.next())_ds.WM(b,d.value,x2)}else mla(a,
a.oa);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},lla=function(a){"full"===document.body.getAttribute("layout")&&(a=a.ra.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&Array.from(a).forEach(function(b){b.removeAttribute("tabindex")})},mla=function(a,b){a.ea&&b.forEach(function(c){a.ea.observe(c)})};_ds.w(y2,_ds.fi);
y2.prototype.connectedCallback=function(){var a=this;this.ya.listen(window,"message",function(b){return jla(a,b)});z2(this)};y2.prototype.disconnectedCallback=function(){this.ea&&this.ea.disconnect();this.oa.clear();_ds.vm(this.ya);_ds.vm(this.Aa)};y2.prototype.zc=function(a){var b=this;a&&([".devsite-article",".devsite-content-data","devsite-content-footer","devsite-google-survey"].forEach(function(c){_ds.hi(b,b.querySelector(c),a.querySelector(c))}),z2(this))};y2.prototype.updateContent=y2.prototype.zc;
y2.prototype.disconnectedCallback=y2.prototype.disconnectedCallback;y2.prototype.connectedCallback=y2.prototype.connectedCallback;try{window.customElements.define("devsite-content",y2)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
