(function(_ds){var window=this;'use strict';var pqa=function(a){var b=a.position,c=a.eK;a=a.fK;b='<div class="devsite-thumb-rating" role="form" aria-labelledby="devsite-thumb-label-'+_ds.U(b)+'" tabindex="0"><div class="devsite-thumb-label" id="devsite-thumb-label-'+_ds.U(b)+'">';b=b+"Was this helpful?"+('</div><div class="devsite-thumbs">'+E8(a.label,a.qq,a.type)+E8(c.label,c.qq,c.type)+"</div></div>");return(0,_ds.S)(b)},E8=function(a,b,c){var d;"thumb-down-filled"==c?d=(0,_ds.S)('<path d="M3,17h6.31l-0.95,4.57l-0.03,0.32c0,0.41,0.17,0.79,0.44,1.06L9.83,24c0,0,7.09-6.85,7.17-7V4H6C5.17,4,4.46,4.5,4.16,5.22 l-3.02,7.05C1.05,12.5,1,12.74,1,13v2C1,16.1,1.9,17,3,17z"></path><path d="M19,17h4V4h-4V17L19,17z"></path>'):
"thumb-down-outline"==c?d=(0,_ds.S)('<path d="M3,17h6.31l-0.95,4.57l-0.03,0.32c0,0.41,0.17,0.79,0.44,1.06L9.83,24c0,0,7.09-6.85,7.17-7h5V4H6 C5.17,4,4.46,4.5,4.16,5.22l-3.02,7.05C1.05,12.5,1,12.74,1,13v2C1,16.1,1.9,17,3,17z M17,6h3v9h-3V6z M3,13l3-7h9v10l-4.34,4.34 L12,15H3V13z"></path>'):"thumb-up-filled"==c?d=(0,_ds.S)('<path d="M21,7h-6.31l0.95-4.57l0.03-0.32c0-0.41-0.17-0.79-0.44-1.06L14.17,0c0,0-7.09,6.85-7.17,7v13h11c0.83,0,1.54-0.5,1.84-1.22 l3.02-7.05C22.95,11.5,23,11.26,23,11V9C23,7.9,22.1,7,21,7z"></path><path d="M5,7H1v13h4V7L5,7z"></path>'):
"thumb-up-outline"==c?d=(0,_ds.S)('<path d="M21,7h-6.31l0.95-4.57l0.03-0.32c0-0.41-0.17-0.79-0.44-1.06L14.17,0c0,0-7.09,6.85-7.17,7H2v13h16 c0.83,0,1.54-0.5,1.84-1.22l3.02-7.05C22.95,11.5,23,11.26,23,11V9C23,7.9,22.1,7,21,7z M7,18H4V9h3V18z M21,11l-3,7H9V8l4.34-4.34 L12,9h9V11z"></path>'):d="";return(0,_ds.S)('<button class="devsite-thumb '+_ds.U(b)+'" data-title="'+_ds.U(a)+'" aria-label="'+_ds.U(a)+'"><svg class="devsite-thumb-icon" viewBox="0 0 24 24" aria-hidden="true">'+d+"</svg></button>")},
qqa=function(a){var b=a.Cj;a='<devsite-dialog class="devsite-thumb-rating-dialog" id="'+_ds.U(a.Bq)+'"><div class="devsite-dialog-contents"><h3 class="no-link" tabindex="-1">';a+='What is the reason for your feedback?</h3><form class="devsite-thumb-rating-categories">';for(var c=b.length,d=0;d<c;d++){var e=b[d];a+='<div class="devsite-thumb-rating-category"><input type="radio" name="'+_ds.U(e.type)+'" id="'+_ds.U(e.id)+'"><label for="'+_ds.U(e.id)+'">'+_ds.T(e.label)+"</label></div>"}return(0,_ds.S)(a+
'</form></div><div class="devsite-dialog-buttons"><button type="submit" class="button button-primary devsite-thumb-rating-submit" disabled>Submit</button><button type="button" class="button devsite-dialog-close">Cancel</button></div></devsite-dialog>')},rqa=function(a){var b=a.isSignedIn;a=a.sE;var c='<devsite-dialog class="devsite-thumb-rating-dialog" id="devsite-thumb-thank-you-dialog"><div class="devsite-dialog-contents"><h3 class="no-link">Thank you for your feedback.</h3>';b?a&&(c+='<p class="create-profile-prompt">Save your frequently visited pages with a Google Developer Profile.</p>'):
c+='<p class="sign-in-prompt">You need to be signed in to save your frequently visited pages with a Google Developer Profile.</p>';c+='</div><div class="devsite-dialog-buttons">';return(0,_ds.S)((b?a?c+'<button type="button" class="button button-primary create-profile">Create profile':c+'<button type="button" class="button button-primary devsite-dialog-close">Dismiss':c+'<button class="button button-primary sign-in-button">Sign in')+"</button></div></devsite-dialog>")},sqa=function(){return(0,_ds.S)('<svg class="material-icons devsite-feedback-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 2H4c-1.1 0-1.99.9-1.99 2L2 22l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm0 14H5.17l-.59.59-.58.58V4h16v12zm-9-4h2v2h-2zm0-6h2v4h-2z"></path></svg>')},
tqa=function(a){var b=a.Rd;a=a.Xd;var c='<devsite-dialog class="devsite-thumb-rating-dialog" id="devsite-thumb-create-profile-dialog"><div class="create-profile-spinner"><devsite-spinner size="48"></devsite-spinner></div><div class="devsite-dialog-contents"><h3 class="no-link">Create Google Developer Profile</h3>';a?(c+='<p>Would you like to receive emails from Google Developer Profile about developer events, new features and content?</p><input type="checkbox" id="devsite-thumb-create-profile-email-opt-in"><label for="devsite-thumb-create-profile-email-opt-in">Sure, I\'d love to!</label><p class="account-note">',
b='By creating a Developer Profile, you agree to the <a href="'+(_ds.U(_ds.Mp(b))+'">Content Policy</a>. Google\'s <a href="https://policies.google.com/terms">Terms of Service</a> and <a href="https://policies.google.com/privacy">Privacy Policy</a> apply to your use of this service. The name on your Google Account will be used in your Google Developer Profile. It may appear where you contribute and can be changed at any time.'),c+=b):c+='<p class="not-eligible-prompt">This account is not eligible for Developer Profiles. <a href="https://developers.google.com#i%E2%80%99m_unable_to_create_a_profile_with_my_g_suite_account_why_is_that" target="_blank">Learn more</a>';
c+='</p></div><div class="devsite-dialog-buttons">';return(0,_ds.S)((a?c+'<button class="button-primary create-profile">Create Profile':c+'<button class="button button-primary change-account-button">Change account')+'</button><button class="button devsite-dialog-close">Dismiss</button></div></devsite-dialog>')},uqa=function(a){a='<devsite-dialog class="devsite-thumb-rating-dialog" id="devsite-thumb-error-dialog"><div class="devsite-dialog-contents"><h3 class="no-link">Something went wrong</h3><p>'+
(_ds.T(a.error)+'</p></div><div class="devsite-dialog-buttons"><button class="button devsite-dialog-close">');return(0,_ds.S)(a+"Dismiss</button></div></devsite-dialog>")},F8=function(){var a=_ds.fi.call(this,["devsite-snackbar","devsite-dialog","devsite-feedback"])||this;a.eventHandler=new _ds.qm;a.qd=null;a.ea=null;a.oa=null;a.ra=null;a.Ba=[];a.ya=null;a.Ca=[];a.Aa=null;a.Tb="";return a},vqa=function(a,b){var c,d;_ds.R(a,function g(){var h,k=this;return _ds.D(g,function(l){switch(l.$){case 1:h=
b.target;if(null===h||void 0===h?0:h.classList.contains("devsite-thumb-up")){if("up"===k.Tb){k.removeAttribute("rating");G8(k,"Page rating removed.");l.Ea(10);break}k.setAttribute("rating","up");if(0<k.Ca.length){k.Aa=H8(k,k.Ca,"devsite-thumb-up-dialog");k.Aa.setAttribute("open","");l.Ea(11);break}null===(c=k.qd)||void 0===c?void 0:c.setAttribute("rating-type","thumbsUp");return _ds.x(l,I8(k),12)}if(null===h||void 0===h||!h.classList.contains("devsite-thumb-down")){l.Ea(0);break}if("down"===k.Tb){k.removeAttribute("rating");
G8(k,"Page rating removed.");l.Ea(5);break}k.setAttribute("rating","down");if(0<k.Ba.length){k.ya=H8(k,k.Ba,"devsite-thumb-down-dialog");k.ya.setAttribute("open","");l.Ea(6);break}null===(d=k.qd)||void 0===d?void 0:d.setAttribute("rating-type","thumbsDown");return _ds.x(l,I8(k),7);case 7:k.ra=l.ea,k.ra.setAttribute("open","");case 6:return G8(k,"Page rated not helpful."),_ds.x(l,k.wi(),5);case 5:return _ds.x(l,J8(k),0);case 12:k.ra=l.ea,k.ra.setAttribute("open","");case 11:return G8(k,"Page rated helpful."),
_ds.x(l,k.wi(),10);case 10:return _ds.x(l,J8(k),0)}})})},G8=function(a,b){a.dispatchEvent(new CustomEvent("devsite-show-custom-snackbar-msg",{detail:{msg:b,showClose:!1},bubbles:!0}))},K8=function(a){var b="thumb-down-outline",c="thumb-up-outline";"down"===a.Tb?b="thumb-down-filled":"up"===a.Tb&&(c="thumb-up-filled");var d=a.getAttribute("position")||"";_ds.$p(a,pqa,{position:d,eK:{qq:"devsite-thumb-down",label:"Not helpful",type:b},fK:{qq:"devsite-thumb-up",label:"Helpful",type:c}})},H8=function(a,
b,c){var d=document.body.querySelector("#"+c);if(d)return d;d=_ds.bq(qqa,{Bq:c,Cj:b});document.body.appendChild(d);a.eventHandler.listen(d,"change",function(){var e,g,h,k;"down"===a.Tb?null===(g=null===(e=a.ya)||void 0===e?void 0:e.querySelector(".devsite-thumb-rating-submit"))||void 0===g?void 0:g.removeAttribute("disabled"):"up"===a.Tb&&(null===(k=null===(h=a.Aa)||void 0===h?void 0:h.querySelector(".devsite-thumb-rating-submit"))||void 0===k?void 0:k.removeAttribute("disabled"))});a.eventHandler.listen(d.querySelector(".devsite-thumb-rating-submit"),
"click",function(){return _ds.R(a,function g(){var h=this;return _ds.D(g,function(k){return _ds.x(k,wqa(h),0)})})});return d},xqa=function(a){return _ds.R(a,function c(){var d=this,e,g,h,k,l,m,n,q;return _ds.D(c,function(r){if(1==r.$)return e=d,_ds.x(r,d.Xd(),2);if(3!=r.$)return g=r.ea,L8(d,"Callout Profile displayed"),(h=document.body.querySelector("#devsite-thumb-create-profile-dialog"))?r.return(h):_ds.x(r,(0,_ds.PG)(),3);k=r.ea.href;h=_ds.bq(tqa,{Rd:k,Xd:g});document.body.appendChild(h);if(l=
h.querySelector(".devsite-dialog-buttons"))(m=l.querySelector(".create-profile"))&&d.eventHandler.listen(m,"click",function(){e.createProfile()}),(n=l.querySelector(".change-account-button"))&&d.eventHandler.listen(n,"click",function(u){return _ds.R(e,function E(){var L,P=this,O;return _ds.D(E,function(da){if(1==da.$)return u.preventDefault(),u.stopPropagation(),L=new _ds.ok(_ds.Mk().href),L.$.add("thumb",P.Tb),_ds.Ok(L.toString(),!0,!1),_ds.x(da,(0,_ds.Lo)(),2);O=da.ea;return _ds.x(da,O.changeAccount(),
0)})})}),q=l.querySelector(".devsite-dialog-close"),d.eventHandler.listen(q,"click",function(){L8(e,"Callout Profile dismissed")});return r.return(h)})})},I8=function(a){return _ds.R(a,function c(){var d=this,e,g,h,k,l,m,n,q,r,u;return _ds.D(c,function(z){switch(z.$){case 1:return e=d,(g=document.body.querySelector("#devsite-thumb-thank-you-dialog"))?z.return(g):_ds.x(z,(0,_ds.Lo)(),2);case 2:return h=z.ea,_ds.x(z,h.isSignedIn(),3);case 3:l=k=z.ea;if(!k){z.Ea(4);break}return _ds.x(z,d.Ib(),5);case 5:m=
z.ea,l=M8()&&!m;case 4:return g=_ds.bq(rqa,{isSignedIn:k,sE:l}),document.body.appendChild(g),n=g.querySelector(".devsite-dialog-buttons"),d.qd&&(null===n||void 0===n?void 0:n.appendChild(d.qd),q=d.qd.querySelector("button"),d.eventHandler.listen(q,"click",function(){null===g||void 0===g?void 0:g.removeAttribute("open")})),l&&n&&(r=n.querySelector(".create-profile"),d.eventHandler.listen(r,"click",function(){return _ds.R(e,function L(){var P=this;return _ds.D(L,function(O){if(1==O.$)return null===
g||void 0===g?void 0:g.removeAttribute("open"),_ds.x(O,xqa(P),2);P.ea=O.ea;P.ea.setAttribute("open","");_ds.y(O)})})})),!k&&n&&(u=g.querySelector(".sign-in-button"))&&d.eventHandler.listen(u,"click",function(E){return _ds.R(e,function P(){var O,da=this;return _ds.D(P,function(ia){E.preventDefault();E.stopPropagation();O=new _ds.ok(_ds.Mk().href);O.$.add("thumb",da.Tb);_ds.Ok(O.toString(),!0,!1);return _ds.x(ia,h.signIn(),0)})})}),z.return(g)}})})},N8=function(a,b){L8(a,"Callout Profile error");if(a=
document.body.querySelector("#devsite-thumb-error-dialog"))return a;a=_ds.bq(uqa,{error:b});document.body.appendChild(a);return a},wqa=function(a){var b,c,d,e,g,h,k,l,m,n;return _ds.R(a,function r(){var u=this,z,E;return _ds.D(r,function(L){if(1==L.$)return"down"===u.Tb?(z=(null===(c=null===(b=u.ya)||void 0===b?void 0:b.querySelector("input[type=radio]:checked"))||void 0===c?void 0:c.id)||"",u.Pm(z),null===(d=u.qd)||void 0===d?void 0:d.setAttribute("rating-type","thumbsDown"),null===(e=u.qd)||void 0===
e?void 0:e.setAttribute("rating-category",z),null===(g=u.ya)||void 0===g?void 0:g.removeAttribute("open")):"up"===u.Tb&&(E=(null===(k=null===(h=u.Aa)||void 0===h?void 0:h.querySelector("input[type=radio]:checked"))||void 0===k?void 0:k.id)||"",u.Pm(E),null===(l=u.qd)||void 0===l?void 0:l.setAttribute("rating-type","thumbsUp"),null===(m=u.qd)||void 0===m?void 0:m.setAttribute("rating-category",E),null===(n=u.Aa)||void 0===n?void 0:n.removeAttribute("open")),_ds.x(L,I8(u),2);u.ra=L.ea;u.ra.setAttribute("open",
"");_ds.y(L)})})},L8=function(a,b){var c=null;"down"===a.Tb?c={category:"Site-Wide Custom Events",action:b,label:"Rating Widget Callout",value:-1}:"up"===a.Tb&&(c={category:"Site-Wide Custom Events",action:b,label:"Rating Widget Callout",value:1});a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:c,bubbles:!0}))},J8=function(a){var b;return _ds.R(a,function d(){var e,g,h=this,k,l,m,n,q;return _ds.D(d,function(r){switch(r.$){case 1:return _ds.x(r,(0,_ds.Lo)(),2);case 2:e=r.ea;
if(!e.hasFlagAccess(117))return r.return();g="RATING_STATE_UNKNOWN";"down"===h.Tb?g="THUMBS_DOWN":"up"===h.Tb&&(g="THUMBS_UP");return _ds.x(r,h.Ib(),3);case 3:k=r.ea;if(null===k||void 0===k||!k.profileId)return r.return();l=_ds.Mk().href;_ds.A(r,4);return _ds.x(r,(0,_ds.YG)(l),6);case 6:l=r.ea;_ds.B(r,5);break;case 4:_ds.C(r);case 5:return m=new _ds.GG,_ds.A(r,7),_ds.x(r,m.vh({path:l,status:g,profileId:null===k||void 0===k?void 0:k.profileId}),9);case 9:_ds.B(r,8);break;case 7:return _ds.C(r),null===
(b=h.ea)||void 0===b?void 0:b.removeAttribute("open"),h.oa=N8(h,"There was an issue saving the page rating."),h.oa.setAttribute("open",""),r.return();case 8:if(!h.Tb){r.Ea(0);break}n=document.querySelector("devsite-user#devsite-user");return _ds.x(r,(0,_ds.RG)("/saved-pages",null===k||void 0===k?void 0:k.profileId,null===k||void 0===k?void 0:k.vanityId),11);case 11:return q=r.ea,_ds.x(r,null===n||void 0===n?void 0:n.Rk("view-rated-pages",q),0)}})})},M8=function(){var a=document.querySelector("devsite-user#devsite-user");
return null!=a&&a.hasAttribute("enable-profiles")},yqa=function(a){return _ds.R(a,function c(){var d,e,g,h=this,k,l,m,n,q;return _ds.D(c,function(r){switch(r.$){case 1:return _ds.x(r,(0,_ds.Lo)(),2);case 2:d=r.ea;if(!d.hasFlagAccess(117))return r.return();e=new _ds.ok(_ds.Mk().href);if(!_ds.Ik(e.$,"thumb")){r.Ea(3);break}g=e.$.get("thumb");if("up"!==g&&"down"!==g){r.Ea(4);break}h.setAttribute("rating",g);return _ds.x(r,J8(h),4);case 4:return e.$.remove("thumb"),_ds.Ok(e.toString(),!0,!1),r.return();
case 3:return _ds.x(r,h.Ib(),6);case 6:k=r.ea;if(null===k||void 0===k||!k.profileId)return r.return();l=_ds.Mk().href;_ds.A(r,7);return _ds.x(r,(0,_ds.YG)(l),9);case 9:l=r.ea;_ds.B(r,8);break;case 7:_ds.C(r);case 8:return m=(null===k||void 0===k?void 0:k.profileId)||"",n=new _ds.GG,_ds.A(r,10),_ds.x(r,n.jc({path:l,profileId:m}),12);case 12:q=r.ea;"THUMBS_UP"===(null===q||void 0===q?void 0:q.ratingStatus)&&h.setAttribute("rating","up");"THUMBS_DOWN"===(null===q||void 0===q?void 0:q.ratingStatus)&&
h.setAttribute("rating","down");_ds.B(r,0);break;case 10:_ds.C(r),_ds.y(r)}})})},O8=function(){return F8.apply(this,arguments)||this};_ds.w(F8,_ds.fi);_ds.f=F8.prototype;
_ds.f.connectedCallback=function(){var a;return _ds.R(this,function c(){var d,e=this,g,h,k,l;return _ds.D(c,function(m){if(1==m.$){if(d=document.querySelector(".devsite-thumb-rating-feedback"))e.qd=null===(a=d.content.firstElementChild)||void 0===a?void 0:a.cloneNode(!0),e.qd&&(g=e.qd.querySelector("button"),null===g||void 0===g?void 0:g.classList.add("button-with-icon"),g&&g.firstChild&&(h=_ds.bq(sqa),g.insertBefore(h,g.firstChild)));if((k=document.querySelector(".devsite-thumb-rating-down-categories"))&&k.content)try{e.Ba=
JSON.parse(k.content.textContent||"")}catch(n){e.Ba=[]}if((l=document.querySelector(".devsite-thumb-rating-up-categories"))&&l.content)try{e.Ca=JSON.parse(l.content.textContent||"")}catch(n){e.Ca=[]}return _ds.x(m,yqa(e),2)}K8(e);e.ib();_ds.y(m)})})};_ds.f.disconnectedCallback=function(){_ds.vm(this.eventHandler);_ds.uj(this.ya);_ds.uj(this.Aa);_ds.uj(this.ra);_ds.uj(this.ea);_ds.uj(this.oa)};_ds.f.attributeChangedCallback=function(a,b,c){switch(a){case "rating":this.Tb=c||"",K8(this)}};
_ds.f.ib=function(){var a=this;this.eventHandler.listen(this,"click",function(b){vqa(a,b)})};
_ds.f.wi=function(){return _ds.R(this,function b(){var c,d=this;return _ds.D(b,function(e){c=null;"down"===d.Tb?c={category:"Site-Wide Custom Events",action:"devsite-rating thumb",label:"Thumb Down Rating",value:-1}:"up"===d.Tb&&(c={category:"Site-Wide Custom Events",action:"devsite-rating thumb",label:"Thumb Up Rating",value:1});d.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:c,bubbles:!0}));_ds.y(e)})})};
_ds.f.Pm=function(a){var b=null;"down"===this.Tb?b={category:"Site-Wide Custom Events",action:"devsite-rating category",label:"Rating Category: "+a,value:-1}:"up"===this.Tb&&(b={category:"Site-Wide Custom Events",action:"devsite-rating category",label:"Rating Category: "+a,value:1});this.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:b,bubbles:!0}))};
_ds.f.Xd=function(){var a;return _ds.R(this,function c(){var d,e,g,h;return _ds.D(c,function(k){switch(k.$){case 1:return _ds.x(k,(0,_ds.Lo)(),2);case 2:return d=k.ea,_ds.x(k,d.isSignedIn(),3);case 3:e=k.ea;if(!e)return k.return(!1);g=new _ds.EG;h=null;_ds.A(k,4);return _ds.x(k,g.$c(),6);case 6:h=k.ea;_ds.B(k,5);break;case 4:_ds.C(k);case 5:return k.return("ELIGIBILITY_ELIGIBLE"===(null===(a=null===h||void 0===h?void 0:h.createProfile)||void 0===a?void 0:a.status))}})})};
_ds.f.Ib=function(){return _ds.R(this,function b(){var c=this,d,e,g,h,k;return _ds.D(b,function(l){switch(l.$){case 1:return M8()?_ds.x(l,(0,_ds.Lo)(),2):l.return(null);case 2:return d=l.ea,_ds.x(l,d.isSignedIn(),3);case 3:return(e=l.ea)?_ds.x(l,c.Xd(),4):l.return(null);case 4:g=l.ea;if(!g)return l.return(null);h=new _ds.IG;k=null;_ds.A(l,5);return _ds.x(l,h.Ib(),7);case 7:k=l.ea;_ds.B(l,6);break;case 5:_ds.C(l);case 6:return l.return(k)}})})};
_ds.f.createProfile=function(){var a,b,c,d,e,g;return _ds.R(this,function k(){var l,m,n=this,q,r,u,z;return _ds.D(k,function(E){switch(E.$){case 1:return l=document.querySelector("devsite-user#devsite-user"),_ds.x(E,null===l||void 0===l?void 0:l.getAccountName(),2);case 2:if(m=E.ea){E.Ea(3);break}return _ds.x(E,null===l||void 0===l?void 0:l.getAccountEmail(),4);case 4:(m=E.ea)&&(m=m.charAt(0));case 3:if(!m)return null===(a=n.ea)||void 0===a?void 0:a.removeAttribute("open"),n.oa=N8(n,"There was an issue getting your account information."),
n.oa.setAttribute("open",""),E.return();q=null===(b=n.ea)||void 0===b?void 0:b.querySelector("#devsite-thumb-create-profile-email-opt-in");r=!(!q||!q.checked);null===(c=n.ea)||void 0===c?void 0:c.classList.add("loading");u=new _ds.IG;_ds.A(E,5);return _ds.x(E,_ds.KG(u,m,r,!0),7);case 7:return L8(n,"Callout Profile created"),null===(d=n.ea)||void 0===d?void 0:d.removeAttribute("open"),_ds.x(E,J8(n),8);case 8:_ds.B(E,6);break;case 5:z=_ds.C(E),null===(e=n.ea)||void 0===e?void 0:e.removeAttribute("open"),
n.oa=N8(n,""+z),n.oa.setAttribute("open","");case 6:null===(g=n.ea)||void 0===g?void 0:g.classList.remove("loading"),_ds.y(E)}})})};_ds.p.Object.defineProperties(F8,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["rating"]}}});_ds.w(O8,F8);
O8.prototype.wi=function(){var a=Object.create(null,{wi:{get:function(){return F8.prototype.wi}}});return _ds.R(this,function c(){var d=this,e,g,h;return _ds.D(c,function(k){if(1==k.$)return _ds.x(k,a.wi.call(d),2);e=d.getAttribute("position")||"";g=null;"down"===d.Tb?g={type:"feedback",name:"rating",metadata:{score:1,ratingType:"thumbsDown",position:e}}:"up"===d.Tb?g={type:"feedback",name:"rating",metadata:{score:5,ratingType:"thumbsUp",position:e}}:console.error("Unknown rating: "+d.Tb);g&&(h={eventData:JSON.stringify(g)},
d.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:h,bubbles:!0})));_ds.y(k)})})};O8.prototype.Pm=function(a){F8.prototype.Pm.call(this,a);var b=this.getAttribute("position")||"";a={eventData:JSON.stringify({type:"feedback",name:"ratingCategory",metadata:{ratingCategory:a,position:b}})};this.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:a,bubbles:!0}))};try{window.customElements.define("devsite-thumb-rating",O8)}catch(a){console.warn("Unrecognized DevSite custom element - CloudThumbRating",a)};})(_ds_www);
