(function(_ds){var window=this;'use strict';var Fja=function(a){var b=a.Nv,c=a.iE,d=a.Og,e=a.badgeServePath,g=a.Aj,h=a.Lv,k=a.isNewTier,l=a.nextPlaylistUrl,m=a.Ux,n=a.zy,q=a.sA,r=a.ow,u=a.dismissBtn,z=a.redeemAnotherBtn,E=a.hideButtons,L=a.yy,P=a.II,O=a.sharing,da=a.Ld,ia=a.iI,aa=a.Rd,la=a.Zg;a='<div class="card"><div class="spinner-container"><devsite-spinner size="64"></devsite-spinner></div><div class="card-content"><div class="content-container"><div class="text-container"><div class="badge-earned-title">';d?k?(d='You\'ve unlocked a new milestone: <span class="badge-name">'+
_ds.T(d)+"</span>!",a+=d):h?(d='You earned the <span class="badge-name">'+_ds.T(d)+"</span> badge!",a+=d):(d='You\'re on your way to get the <span class="badge-name">'+_ds.T(d)+"</span> badge!",a+=d):a=k?a+"Congratulations! You've unlocked a new milestone!":h?a+"Congratulations! You earned a new badge!":a+"You're on your way to get a new badge!";a+="</div>";m?a+='<div class="claim-badge-text">Claim your badge on Google Developer Profile.':n?a+='<div class="sign-in-text">Sign in to claim your badge.':
r?a+='<div class="create-profile-text">Create a profile to claim your badge.':L?(a+='<div class="not-eligible-text">',k='This account is not eligible for Developer Profiles. <a href="'+(_ds.U(_ds.Mp(la))+'#i%E2%80%99m_unable_to_create_a_profile_with_my_g_suite_account_why_is_that" target="_blank">Learn more</a>'),a+=k):(a+='<div class="badge-added-text">',a=k?a+"The milestone has been added to your profile.":h?a+"The badge has been added to your profile.":a+"You can track the progress of this badge on your profile.");
a=a+'</div></div><div class="illustration-container"><img alt="Icon representing the granted badge" class="badge-icon '+((h?"":"incomplete")+'" src="'+_ds.U(_ds.Op(b))+'">'+(c?'<img alt="Badge animation background" class="badge-animation" src="'+_ds.U(_ds.Op(c))+'">':"")+"</div></div>");P&&(a+='<div class="profile-creation-container"><p>One last thing, would you like to receive emails from Google Developer Profile about developer events, new features and content?</p><div class="profile-creation-container-email-options"><div class="profile-creation-container-email-option"><input type="checkbox" id="profile-creation-emails-googledev"><label for="profile-creation-emails-googledev">Sure, I\'d love to!</label></div></div><p>',
b='By creating a Developer Profile, you agree to the <a href="'+(_ds.U(_ds.Mp(aa))+'">Content Policy</a>. Google\'s <a href="https://policies.google.com/terms">Terms of Service</a> and <a href="https://policies.google.com/privacy">Privacy Policy</a> apply to your use of this service. The name on your Google Account will be used in your Google Developer Profile. It may appear where you contribute and can be changed at any time.'),a=a+b+"</p></div>");E||(a+='<div class="buttons-container"><div class="buttons sharing">',
O&&(a=a+'<span>Share</span><div class="share-buttons-container"><button class="share-twitter gc-analytics-event" data-category="share badge" data-action="twitter" data-label="'+(_ds.U(e)+'"><img src="'+_ds.U(_ds.Op(da))+'/images/share_twitter.svg" alt="Twitter"></button><button class="share-facebook gc-analytics-event" data-category="share badge" data-action="facebook" data-label="'+_ds.U(e)+'"><img src="'+_ds.U(_ds.Op(da))+'/images/share_facebook.svg" alt="Facebook"></button><button class="share-linkedin gc-analytics-event" data-category="share badge" data-action="linkedin" data-label="'+
_ds.U(e)+'"><img src="'+_ds.U(_ds.Op(da))+'/images/share_linkedin.svg" alt="LinkedIn"></button>'+(g?'<a href="'+_ds.U(_ds.Mp(g))+'" class="share-link gc-analytics-event" data-category="share badge" data-action="link" data-label="'+_ds.U(g)+'" target="_blank"><i class="material-icons">link</i></a>':"")+"</div>")),a+='</div><div class="buttons actions">',l&&(a+='<a href="'+_ds.U(_ds.Mp(l))+'" class="button return-to-playlist-button gc-analytics-event" data-category="next_pathway" data-action="badge card click" data-label="'+
_ds.U(l)+'">',a+="Next Pathway</a>"),m?a+='<a class="button button-primary claim-badge-button">Claim my badge</a>':n?a+='<a class="button button-primary sign-in-button" href="#">Sign in</a>':r?(a=P?a+'<button class="button button-primary finish-creating-profile-button">Create Profile':a+'<button class="button button-primary create-profile-button">Create profile',a+="</button>"):(L?a+='<a class="button button-primary change-account-button" href="#">Change account':(a+='<a class="button button-primary view-profile-button" href="'+
_ds.U(_ds.Mp(q))+'"'+(ia?' target="_blank"':"")+">",a+="View profile"),a+="</a>"),u&&(a+='<button class="button dismiss"><div class="dismiss-text">Dismiss</div><div class="next-badge-text" hidden>Next badge</div><div class="more-badges-marker" hidden></div></button>'),z&&(a+='<button class="button redeem-another">Redeem another badge</button>'),a+="</div></div>");return(0,_ds.S)(a+"</div></div>")},Gja=function(a){var b=a.Og;a='<devsite-dialog class="devsite-claim-badge-dialog"><div class="qr-code-container"></div><div class="redeem-code-section"><div class="redeem-code-title">Badge code</div><div class="redeem-code">'+
(_ds.T(a.redeemCode)+'</div></div><div class="text-container"><div class="badge-earned-title">');b='Claim the <span class="badge-name">'+_ds.T(b)+"</span> badge.";a=a+b+"</div>Scan the QR code with your phone and redeem your badge on Google Developer Profile.";a+='</div><div class="buttons-container"><button class="close-dialog-button">Close</button></div></devsite-dialog>';return(0,_ds.S)(a)},Hja=function(a){a=a.reason;var b='<div class="card"><div class="card-content"><div class="content-container"><div class="text-container"><div class="badge-earned-title">';
b=a?b+_ds.T(a):b+"There was an error displaying your badge award.";return(0,_ds.S)(b+'</div></div></div><div class="buttons-container"><div class="buttons"></div><div class="buttons actions"><button class="button button-primary error-try-again-button">Try Again.</button></div></div></div></div>')},C1=function(){var a=_ds.fi.call(this,["devsite-dialog"])||this;a.eventHandler=new _ds.qm(a);a.ea=null;a.ib();return a},Ija=function(a){return _ds.R(a,function c(){var d,e=this,g;return _ds.D(c,function(h){switch(h.$){case 1:return _ds.x(h,
(0,_ds.Lo)(),2);case 2:return d=h.ea,_ds.x(h,(0,_ds.MG)(e.getAttribute("badge-icon-url")||""+d.getStaticPath(!0)+"/images/quiz-icon.png"),3);case 3:return g=h.ea,_ds.x(h,(0,_ds.QG)(g),4);case 4:return h.return(h.ea.href)}})})},D1=function(a,b){_ds.$p(a,Hja,{reason:void 0===b?"":b})},Jja=function(a){return _ds.R(a,function c(){var d=this,e,g,h,k,l;return _ds.D(c,function(m){if(1==m.$)return e=d.querySelector(".badge-icon"),g=d.querySelector(".badge-animation"),h=[],e&&e.src&&(k=new _ds.wm,null===e||
void 0===e?void 0:e.addEventListener("load",function(){k.resolve()}),null===e||void 0===e?void 0:e.addEventListener("error",function(){k.reject()}),h.push(k.promise)),g&&g.src&&(l=new _ds.wm,null===g||void 0===g?void 0:g.addEventListener("load",function(){l.resolve()}),null===g||void 0===g?void 0:g.addEventListener("error",function(){l.reject()}),h.push(l.promise)),_ds.A(m,2),_ds.x(m,Promise.all(h),4);if(2!=m.$)return _ds.B(m,0);_ds.C(m);_ds.y(m)})})},Kja=function(a){var b,c,d=a.getAttribute("redeem-code");
a.ea=_ds.bq(Gja,{Og:null!==(b=a.getAttribute("badge-name"))&&void 0!==b?b:"",redeemCode:null!==d&&void 0!==d?d:""});var e=_ds.Uk("/redeem");d&&e.searchParams.set("code",d);(d=a.ea.querySelector(".qr-code-container"))&&new _ds.RM(d,{text:e.toString(),width:300,height:300,Fj:"#000000",di:"#ffffff",uq:0});e=a.ea.querySelector(".close-dialog-button");null===e||void 0===e?void 0:e.addEventListener("click",function(){var g;null===(g=a.ea)||void 0===g?void 0:g.removeAttribute("open")});a.appendChild(a.ea);
null===(c=a.ea)||void 0===c?void 0:c.setAttribute("open","")};_ds.w(C1,_ds.fi);_ds.f=C1.prototype;_ds.f.connectedCallback=function(){this.render()};_ds.f.disconnectedCallback=function(){_ds.vm(this.eventHandler)};
_ds.f.ib=function(){return _ds.R(this,function b(){var c=this,d,e;return _ds.D(b,function(g){if(1==g.$)return d=c,_ds.x(g,(0,_ds.Lo)(),2);if(3!=g.$)return _ds.x(g,window.customElements.whenDefined("devsite-user"),3);e=document.querySelector("devsite-user#devsite-user");c.eventHandler.listen(c,"click",function(h){var k,l,m,n=h.target;if(null===n||void 0===n?0:n.matches(".sign-in-button"))h.preventDefault(),h.stopPropagation(),null===e||void 0===e?void 0:e.signIn();else if(null===n||void 0===n?0:n.matches(".change-account-button"))h.preventDefault(),
h.stopPropagation(),null===e||void 0===e?void 0:e.changeAccount();else if(null===n||void 0===n?0:n.matches(".claim-badge-button"))h.preventDefault(),h.stopPropagation(),Kja(d);else if(null===n||void 0===n?0:n.matches(".redeem-another"))h.preventDefault(),h.stopPropagation(),document.location.reload();else if(null===n||void 0===n?0:n.matches(".create-profile-button"))h.preventDefault(),h.stopPropagation(),d.setAttribute("profile-creation-step","1"),d.render(!0);else if(null===n||void 0===n?0:n.matches(".finish-creating-profile-button"))h.preventDefault(),
h.stopPropagation(),d.createProfile();else if((null===n||void 0===n?0:n.matches(".share-twitter"))||(null===(k=null===n||void 0===n?void 0:n.parentElement)||void 0===k?0:k.matches(".share-twitter"))){var q,r,u=(new URL(null!==(q=d.getAttribute("badge-url"))&&void 0!==q?q:"","https://google.dev")).href,z=null!==(r=d.getAttribute("badge-share-title"))&&void 0!==r?r:"";_ds.ZK(u,z)}else if((null===n||void 0===n?0:n.matches(".share-linkedin"))||(null===(l=null===n||void 0===n?void 0:n.parentElement)||
void 0===l?0:l.matches(".share-linkedin"))){var E;r=(new URL(null!==(E=d.getAttribute("badge-url"))&&void 0!==E?E:"","https://google.dev")).href;q=null!==(z=d.getAttribute("badge-share-title"))&&void 0!==z?z:"";z=null!==(u=d.getAttribute("badge-share-title"))&&void 0!==u?u:"";_ds.$K(r,q,z)}else if((null===n||void 0===n?0:n.matches(".share-facebook"))||(null===(m=null===n||void 0===n?void 0:n.parentElement)||void 0===m?0:m.matches(".share-facebook"))){var L;u=(new URL(null!==(L=d.getAttribute("badge-url"))&&
void 0!==L?L:"","https://google.dev")).href;_ds.aL(u)}else if(null===n||void 0===n?0:n.matches(".error-try-again-button"))h.preventDefault(),h.stopPropagation(),d.render(!0)});_ds.y(g)})})};_ds.f.Os=function(){if(_ds.eo(_ds.SM)){var a=this.getAttribute("badge-path");if(a){var b=_ds.TM();b&&(b=b.filter(function(c){return c.servePath!==a}),0<b.length?_ds.SM.set("temp_badges",JSON.stringify(b)):_ds.SM.remove("temp_badges"))}}};
_ds.f.render=function(a){a=void 0===a?!1:a;var b,c,d,e,g,h,k,l;return _ds.R(this,function n(){var q=this,r,u,z,E,L,P,O,da,ia,aa,la,ja,za,na,Ha,mb,hb,Ma,Ua,oa,ea,ra,Ea,xa,eb,ib,wa,bb,jb,ba,nb,Pa,Wa,Ia,zb,Oa;return _ds.D(n,function(Ca){switch(Ca.$){case 1:return r=q,_ds.x(Ca,(0,_ds.Lo)(),2);case 2:return u=Ca.ea,_ds.x(Ca,window.customElements.whenDefined("devsite-user"),3);case 3:return(z=document.querySelector("devsite-user#devsite-user"))?_ds.x(Ca,(0,_ds.MG)(null!==(b=q.getAttribute("badge-url"))&&
void 0!==b?b:""),4):Ca.return();case 4:return E=Ca.ea,_ds.x(Ca,Ija(q),5);case 5:return L=null!==(c=Ca.ea)&&void 0!==c?c:"",P=null!==(d=q.getAttribute("badge-path"))&&void 0!==d?d:"",O="false"!==q.getAttribute("badge-complete"),da="true"===q.getAttribute("is-new-tier"),ia=null!==(e=q.getAttribute("badge-name"))&&void 0!==e?e:"",aa=q.getAttribute("badge-share-title"),la=null!==(g=q.getAttribute("badge-share-description"))&&void 0!==g?g:"",ja=null!==(h=q.getAttribute("next-playlist-url"))&&void 0!==
h?h:"",za=q.hasAttribute("dismiss"),na=q.hasAttribute("redeem-another"),Ha=q.hasAttribute("hide-buttons"),mb=_ds.Mk().href,_ds.x(Ca,(0,_ds.RG)("/",void 0,void 0),6);case 6:hb=Ca.ea;Ma="";try{Ma=(new URL(""+u.getStaticPath(!1)+"/images/badge-award-animation.gif")).href}catch(Sa){}return _ds.x(Ca,(0,_ds.OG)(),7);case 7:return Ua=Ca.ea.href,_ds.x(Ca,(0,_ds.PG)(),8);case 8:oa=Ca.ea.href;ea={zy:!1,Ux:!1,ow:!1,yy:!1,Og:ia,Aj:E,Nv:L,iE:Ma,badgeServePath:P,Lv:O,isNewTier:da,sharing:q.hasAttribute("badge-share-title"),
jq:la,nextPlaylistUrl:ja,dismissBtn:za,redeemAnotherBtn:na,hideButtons:Ha,url:mb,sA:hb.href,II:null!==(k=q.getAttribute("profile-creation-step"))&&void 0!==k?k:"",Ld:u.getStaticPath(!1),iI:document.location.host!==hb.host,Rd:oa,Zg:Ua};if(_ds.cl()){ea.Ux=!0;ra=q.getAttribute("redeem-code");if(!ra)return D1(q,"In Kiosk mode: No redeem code has been provided. Make sure you pass it using the redeem-code attribute."),Ca.return();Ca.Ea(9);break}return _ds.x(Ca,u.isSignedIn(),10);case 10:Ea=Ca.ea;if(!Ea){_ds.eo(_ds.SM)&&
(xa=_ds.TM()||[],(eb=xa.find(function(Sa){return Sa.servePath===P}))?eb.displayCount=(eb.displayCount||0)+1:(ib=_ds.Mk(),eb={awardedBy:ib.origin+ib.pathname,servePath:P,title:ea.Og,url:ea.Aj,imageUrl:ea.Nv,complete:ea.Lv,isNewTier:ea.isNewTier,nextPlaylistUrl:ea.nextPlaylistUrl||"",dismissBtn:ea.dismissBtn,redeemAnotherBtn:ea.redeemAnotherBtn,hideButtons:ea.hideButtons,awardUrl:mb,displayCount:0,badgeServePath:P,shareTitle:aa||"",shareDescription:ea.sharing?la:""},xa.push(eb)),_ds.SM.set("temp_badges",
JSON.stringify(xa)));ea.zy=!0;Ca.Ea(9);break}wa=!1;if(!Ea){Ca.Ea(12);break}bb=new _ds.EG;jb=null;_ds.A(Ca,13);return _ds.x(Ca,bb.$c(),15);case 15:jb=Ca.ea;_ds.B(Ca,14);break;case 13:_ds.C(Ca);case 14:wa="ELIGIBILITY_ELIGIBLE"===(null===(l=null===jb||void 0===jb?void 0:jb.createProfile)||void 0===l?void 0:l.status);case 12:if(!wa){ea.yy=!0;Ca.Ea(9);break}ba=null;nb=new _ds.IG;_ds.A(Ca,17);return _ds.x(Ca,nb.Ib(),19);case 19:ba=Ca.ea;_ds.B(Ca,18);break;case 17:_ds.C(Ca);case 18:if(!ba||null===ba||void 0===
ba||!ba.profileId){ea.ow=!0;Ca.Ea(9);break}q.Os();return _ds.x(Ca,(0,_ds.RG)("/",null===ba||void 0===ba?void 0:ba.profileId,null===ba||void 0===ba?void 0:ba.vanityId),21);case 21:Pa=Ca.ea,ea.sA=Pa.href;case 9:Wa={category:"badge",action:"awarded",label:ia||""};q.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:Wa,bubbles:!0}));_ds.$p(q,Fja,ea);if(a){Ca.Ea(22);break}return _ds.x(Ca,Jja(q),22);case 22:Ia=q.querySelector(".dismiss");null===Ia||void 0===Ia?void 0:Ia.addEventListener("click",
function(){r.dispatchEvent(new CustomEvent("devsite-badge-awarded-dismissed",{bubbles:!0}))});q.eventHandler.listen(q,"devsite-badge-awarded-stack-num-changed",function(Sa){var Lb;Sa=Sa.hb;Sa=(null===(Lb=null===Sa||void 0===Sa?void 0:Sa.detail)||void 0===Lb?void 0:Lb.vH)||0;var Ub=r.querySelector(".dismiss"),Ae=r.querySelector(".view-profile-button"),Lf=null===Ub||void 0===Ub?void 0:Ub.querySelector(".next-badge-text"),Se=null===Ub||void 0===Ub?void 0:Ub.querySelector(".dismiss-text");Ub=null===Ub||
void 0===Ub?void 0:Ub.querySelector(".more-badges-marker");Ae&&(Ae.hidden=0!==Sa);Se&&(Se.hidden=0!==Sa,Se.classList.toggle("button-primary",!!Sa));Lf&&(Lf.hidden=0===Sa);Ub&&(Ub.innerText=""+Sa,Ub.hidden=0===Sa)});q.dispatchEvent(new CustomEvent("running",{bubbles:!0}));q.removeAttribute("loading");if(zb=q.querySelector(".badge-animation"))zb.src=zb.getAttribute("src");Oa=q.querySelector(".badge-icon");null===Oa||void 0===Oa?void 0:Oa.classList.add("animate");_ds.y(Ca)}})})};
_ds.f.createProfile=function(){return _ds.R(this,function b(){var c,d=this,e,g,h,k,l;return _ds.D(b,function(m){switch(m.$){case 1:return _ds.x(m,(0,_ds.Lo)(),2);case 2:return _ds.x(m,window.customElements.whenDefined("devsite-user"),3);case 3:return c=document.querySelector("devsite-user#devsite-user"),c?_ds.x(m,c.getAccountName(),4):(D1(d),m.return());case 4:if(e=m.ea){m.Ea(5);break}return _ds.x(m,c.getAccountEmail(),6);case 6:e=m.ea;case 5:if(null===e||void 0===e?0:e.indexOf("@"))e=e.charAt(0);
e||D1(d,"There was an issue getting your account information");d.removeAttribute("profile-creation-step");g=d.querySelector("#profile-creation-emails-googledev");h=!(null===g||void 0===g||!g.checked);k=new _ds.IG;_ds.A(m,7);d.setAttribute("loading","");return _ds.x(m,_ds.KG(k,e,h,!1),9);case 9:return l=new _ds.fo,_ds.eo(l)&&l.remove("temp_badges"),_ds.x(m,d.render(!0),10);case 10:_ds.B(m,0);break;case 7:_ds.C(m),D1(d,"There was an error creating your profile."),_ds.y(m)}})})};
try{window.customElements.define("devsite-badge-awarded",C1)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBadgeAwarded",a)};})(_ds_www);
