(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var w4=function(){var a=_ds.fi.call(this)||this;a.oa=_ds.sn();a.ea=new _ds.qm;Vma().then(function(){v4(a)});return a},v4=function(a){var b;return _ds.Xa(function(c){return(b=_ds.UO.get("django_language"))?_ds.x(c,a.oa.set("language_preference",b),0):c.Ea(0)})},x4=function(a){_ds.vm(a.ea);var b=a.querySelector(".devsite-language-selector-select");b&&a.ea.listen(b,"change",function(c){Wma(a,c)})},Wma=function(a,b){var c,d;_ds.Xa(function(e){switch(e.$){case 1:return _ds.x(e,DevsiteApp.whenReady(),
2);case 2:return _ds.UO.remove("django_language"),c=b.target,_ds.UO.set("django_language",c.value,{Bd:15552E3,path:"/"}),d=document.documentElement.getAttribute("lang"),_ds.x(e,Xma(a,d,c.value),3);case 3:return _ds.x(e,v4(a),4);case 4:var g=_ds.Tn(_ds.Dk(new _ds.ok(_ds.hj().location.href),"hl").toString());_ds.hj().location.assign(_ds.Zh(g));_ds.y(e)}})},Xma=function(a,b,c){var d,e;return _ds.Xa(function(g){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",
label:"Language Selector",action:b+" to "+c},bubbles:!0}));d={name:"change",type:"languageSelector",metadata:{"selected-language":c,"original-language":b}};e={eventData:JSON.stringify(d)};a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:e,bubbles:!0}));_ds.y(g)})},Vma=function(){return _ds.Xa(function(a){if(1==a.$)return _ds.UO.get("django_language")?a.Ea(0):_ds.x(a,DevsiteApp.whenReady(),3);_ds.UO.set("django_language",DevsiteApp.getLocale()||"en",{Bd:15552E3,path:"/"});
_ds.y(a)})};_ds.w(w4,_ds.fi);w4.prototype.connectedCallback=function(){x4(this)};w4.prototype.disconnectedCallback=function(){_ds.vm(this.ea)};w4.prototype.zc=function(a){a&&(_ds.hi(this,this.querySelector(".devsite-language-selector-menu"),a.querySelector(".devsite-language-selector-menu")),x4(this))};w4.prototype.updateContent=w4.prototype.zc;w4.prototype.disconnectedCallback=w4.prototype.disconnectedCallback;w4.prototype.connectedCallback=w4.prototype.connectedCallback;try{window.customElements.define("devsite-language-selector",w4)}catch(a){console.warn("devsite.app.customElement.DevsiteLanguageSelector",a)};})(_ds_www);
