(function(_ds){var window=this;'use strict';var J7=function(a){var b=arguments.length;if(1==b&&Array.isArray(arguments[0]))return J7.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c},qpa=function(a,b,c,d,e,g,h,k,l,m){this.$=a;this.ya=b;this.Da=c;this.oa=d;this.ra=e;this.Aa=g;this.Ba=h;this.Ca=k;this.ea=l;this.Ga=m},rpa=function(a){return new qpa(a.oa,a.ra,a.Ca,a.$,a.ea,a.ya,a.Ga,a.Ba,a.Aa,a.Da)},spa=function(a,b){a.Da=b;return a},tpa=function(a,b){a.Aa=b;return a},upa=function(a,b){a.Ba=b;return a},
K7=function(){this.oa=null;this.ra="";this.Da=this.Aa=this.Ba=this.Ga=this.ya=this.ea=this.$=this.Ca=null},L7=function(a){var b=a.hb;b=(b=b&&"composed"in b&&b&&"composedPath"in b&&b.composed&&b.composedPath())&&0<b.length?b[0]:a.target;return rpa(spa(tpa(upa((new K7).keyCode(a.keyCode||0).key(a.key||"").shiftKey(!!a.shiftKey).altKey(!!a.altKey).ctrlKey(!!a.ctrlKey).metaKey(!!a.metaKey).target(a.target),b),function(){return a.preventDefault()}),function(){return a.stopPropagation()}))},M7=function(a,
b,c){_ds.Sf.call(this,a,c);this.$=b},N7=function(a){this.$=a||null;this.next=a?null:{}},O7=function(a,b){b.shift().forEach(function(c){var d=a[c];d&&(0==b.length?d.$&&delete a[c]:d.next&&(O7(d.next,b.slice(0)),_ds.qc(d.next)&&delete a[c]))})},vpa=function(a){a=a.replace(/[ +]*\+[ +]*/g,"+").replace(/[ ]+/g," ").toLowerCase();a=a.split(" ");for(var b=[],c,d=0;c=a[d];d++){var e=c.split("+"),g=null,h=null;c=0;for(var k,l=0;k=e[l];l++){switch(k){case "shift":c|=1;continue;case "ctrl":c|=2;continue;case "alt":c|=
4;continue;case "meta":c|=8;continue}e=void 0;g=k;if(!P7){h={};for(e in _ds.MQ)h[_ds.MQ[e]]=_ds.cB(parseInt(e,10));P7=h}h=P7[g];g=k;break}b.push({key:g,keyCode:h,modifiers:c})}return b},Q7=function(a,b,c){c=c||0;b=["c_"+b+"_"+c];""!=a&&b.push("n_"+a+"_"+c);return b},R7=function(a,b){if("string"===typeof b[a])a=vpa(b[a]).map(function(e){return Q7(e.key||"",e.keyCode,e.modifiers)});else{var c=b,d=a;Array.isArray(b[a])&&(c=b[a],d=0);for(a=[];d<c.length;d+=2)a.push(Q7("",c[d],c[d+1]))}return a},S7=function(a,
b){32==a.Aa&&32==b.$&&(0,b.ea)();a.Aa=null},T7=function(a){return _ds.hO&&a.ra&&a.oa},U7=function(a,b,c){var d=b.shift();d.forEach(function(e){if((e=a[e])&&(0==b.length||e.$))throw Error("Keyboard shortcut conflicts with existing shortcut: "+e.$);});b.length?d.forEach(function(e){e=e.toString();var g=new N7;e=e in a?a[e]:a[e]=g;U7(e.next,b.slice(0),c)}):d.forEach(function(e){a[e]=new N7(c)})},V7=function(a,b){for(var c=0;c<b.length;c++){var d=a[b[c]];if(d)return d}},W7=function(a,b,c){a:{var d=b.$;
if(""!=b.ya){var e=b.ya;if("Control"==e||"Shift"==e||"Meta"==e||"AltGraph"==e){d=!1;break a}}else if(16==d||17==d||18==d){d=!1;break a}e=b.Ca;var g="TEXTAREA"==e.tagName||"INPUT"==e.tagName||"BUTTON"==e.tagName||"SELECT"==e.tagName,h=!g&&(e.isContentEditable||e.ownerDocument&&"on"==e.ownerDocument.designMode);d=!g&&!h||a.Ga[d]||a.Ba?!0:h?!1:a.Ha&&(b.oa||b.ra||b.Aa)?!0:"INPUT"==e.tagName&&a.Sa[e.type]?13==d:"INPUT"==e.tagName||"BUTTON"==e.tagName?a.Ia?!0:32!=d:!1}d&&(!c&&T7(b)?a.ra=!1:(c=_ds.cB(b.$),
d=Q7(b.ya,c,(b.Da?1:0)|(b.ra?2:0)|(b.oa?4:0)|(b.Aa?8:0)),(e=V7(a.oa,d))&&(e=!(1500<=Date.now()-a.ya)),e||(a.oa=a.ea,a.ya=Date.now()),(e=V7(a.oa,d))&&e.next&&(a.oa=e.next,a.ya=Date.now()),e&&(e.next?(0,b.ea)():(a.oa=a.ea,a.ya=Date.now(),a.Ca&&(0,b.ea)(),a.Da&&(0,b.Ga)(),d=e.$,e=a.dispatchEvent(new M7("shortcut",d,b.Ba)),(e&=a.dispatchEvent(new M7("shortcut_"+d,d,b.Ba)))||(0,b.ea)(),_ds.Cm&&(a.Aa=c)))))},X7=function(a,b,c){for(;0<c.length&&b;){var d=c.shift();if((d=V7(b,d))&&(0==c.length&&d.$||X7(a,
d.next,c.slice(0))))return!0}return!1},Y7=function(a){_ds.xl.call(this);this.oa=this.ea={};this.ya=0;this.Ga=J7(wpa);this.Sa=J7(xpa);this.Ca=!0;this.Ba=this.Da=!1;this.Ha=!0;this.Ia=!1;this.Aa=null;this.$=a;_ds.fg(this.$,"keydown",this.tx,void 0,this);_ds.fg(this.$,"synthetic-keydown",this.Bx,void 0,this);_ds.hO&&(_ds.fg(this.$,"keypress",this.Ex,void 0,this),_ds.fg(this.$,"synthetic-keypress",this.Fx,void 0,this));_ds.fg(this.$,"keyup",this.ux,void 0,this);_ds.fg(this.$,"synthetic-keyup",this.Cx,
void 0,this)},ypa=function(a,b){return _ds.$e(a,10,b)},zpa=function(a){return(0,_ds.S)('<div class="devsite-popout" id="'+_ds.U(a.id)+'"><div class="devsite-popout-result devsite-suggest-results-container" devsite-hide></div></div>')},Z7=function(a){var b='<button type="submit" class="button button-white devsite-search-project-scope">';a="All results in "+_ds.T(a);return(0,_ds.S)(b+a+"</button>")},$7=function(a,b,c){var d='<button type="submit" class="button button-white devsite-suggest-all-results">';
b?(a="All results across "+_ds.T(c),d+=a):(a='All results for "'+_ds.T(a)+'"',d+=a);return(0,_ds.S)(d+"</button>")},a8=function(a,b,c,d,e,g,h,k){a=(c?"":'<devsite-analytics-scope action="'+_ds.U(_ds.Mp("Restricted "+d))+'">')+'<a class="devsite-result-item-link" href="'+_ds.U(_ds.Mp(a))+'"><span class="devsite-suggestion-fragment">'+_ds.T(b)+"</span>"+(k?'<span class="devsite-suggestion-fragment">'+_ds.T(k)+"</span>":"")+(e?'<span class="devsite-suggestion-fragment">'+_ds.T(e)+"</span>":"")+(_ds.mp(g)&&
!h?'<span class="devsite-suggestion-fragment">'+_ds.T(g)+"</span>":"");c||(a+='<span class="devsite-result-item-confidential">Confidential</span>');return(0,_ds.S)(a+("</a>"+(c?"":"</devsite-analytics-scope>")))},Apa=function(a){var b=a.projectName,c=a.lz,d=a.query,e=a.Kz;a=a.Zn;b='<div class="devsite-suggest-wrapper '+(e?"":"devsite-search-disabled")+'"><div class="devsite-suggest-section"><div class="devsite-result-label">There are no suggestions for your query</div></div>'+((e?'<div class="devsite-suggest-footer">'+
(c?Z7(b):"")+$7(d,c,a)+"</div>":"")+"</div>");return(0,_ds.S)(b)},Bpa=function(a){var b=a.pages,c=a.EI,d=a.YI,e=a.projectName,g=a.lz,h=a.query,k=a.dJ,l=a.Kz;a=a.Zn;var m='<div class="devsite-suggest-wrapper '+(l?"":"devsite-search-disabled")+'" tabindex="0" role="list"><div class="devsite-suggest-section">';if(0<d.length){m=m+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-partial-query" role="heading" aria-level="2">Suggested searches'+
((g?'<span class="devsite-suggest-project">'+_ds.T(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-partial-query" action="Query Suggestion Click">');for(var n=d.length,q=0;q<n;q++){var r=d[q];m+='<div class="devsite-result-item devsite-nav-label" id="suggestion-partial-query-'+_ds.U(q)+'" role="listitem" index=":'+_ds.U(q)+'">'+a8(r.jc(),r.Rb(),_ds.Xe(r,14),"Query Suggestion Click")+"</div>"}m+=
"</devsite-analytics-scope></div>"}m+=0<d.length&&0<b.length?'<hr role="none">':"";if(0<b.length){m=m+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-product" role="heading" aria-level="2">Pages'+((g?'<span class="devsite-suggest-project">'+_ds.T(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-product" action="Page Suggestion Click">');
n=b.length;for(q=0;q<n;q++)r=b[q],m+='<div class="devsite-result-item devsite-nav-label" id="suggestion-product-'+_ds.U(q)+'" role="listitem" index=":'+_ds.U(q)+'">'+a8(r.jc(),r.Rb(),_ds.Xe(r,14),"Page Suggestion Click",void 0,_ds.M(r,4),g)+"</div>";m+="</devsite-analytics-scope></div>"}m+=0<k.length&&0<b.length+d.length?'<hr role="none">':"";if(0<k.length){m=m+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-reference" role="heading" aria-level="2">Reference'+
((g?'<span class="devsite-suggest-project">'+_ds.T(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-reference" action="Reference Suggestion Click">');n=k.length;for(q=0;q<n;q++)r=k[q],m+='<div class="devsite-result-item devsite-nav-label" id="suggestion-reference-'+_ds.U(q)+'" role="listitem" index=":'+_ds.U(q)+'">'+a8(r.jc(),r.Rb(),_ds.Xe(r,14),"Reference Suggestion Click",_ds.M(r,3),_ds.M(r,4),
g,_ds.Te(r,10)[0])+"</div>";m+="</devsite-analytics-scope></div>"}m+=0<c.length&&0<b.length+d.length+k.length?'<hr role="none">':"";if(0<c.length){m+='<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-other-products" role="heading" aria-level="2"><span role="columnheader">Products</span></div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-other-products" action="Product Suggestion Click">';
b=c.length;for(d=0;d<b;d++)k=c[d],m+='<div class="devsite-result-item devsite-nav-label" id="suggestion-other-products-'+_ds.U(d)+'" role="listitem" index=":'+_ds.U(d)+'">'+a8(k.jc(),k.Rb(),_ds.Xe(k,14),"Product Suggestion Click")+"</div>";m+="</devsite-analytics-scope></div>"}m+="</div>"+(l?'<div class="devsite-suggest-footer">'+(g?Z7(e):"")+$7(h,g,a)+"</div>":"")+"</div>";return(0,_ds.S)(m)},b8=function(){var a=_ds.fi.call(this)||this;a.Sa=!1;a.Da={};a.Ga="";a.Ba=null;a.oa=new _ds.qm;a.ea=null;
a.Ia=!1;return a},Epa=function(a){a.ea&&(a.oa.listen(a.ea,"suggest-service-search",function(b){a:{var c=a.Aa.querySelector(".highlight");if(c&&(c=c.querySelector(".devsite-result-item-link"))){c.click();break a}c8(a,b.detail.originalEvent,!!a.Ba)}}),a.oa.listen(a.ea,"suggest-service-suggestions-received",function(b){return void Cpa(a,b)}),a.oa.listen(a.ea,"suggest-service-focus",function(){d8(a,"cloud-track-search-focus",null);a.Ia=!0;e8(a,!0)}),a.oa.listen(a.ea,"suggest-service-blur",function(){e8(a,
!1)}),a.oa.listen(a.ea,"suggest-service-input",function(){!a.Da["Text Entered Into Search Bar"]&&a.ea.query.trim()&&(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Text Entered Into Search Bar"},bubbles:!0})),a.Da["Text Entered Into Search Bar"]=!0);a.Ia&&(d8(a,"cloud-track-search-input",null),a.Ia=!1)}),a.oa.listen(a.ea,"suggest-service-navigate",function(b){return void Dpa(a,b)}),a.oa.listen(document.body,"devsite-page-changed",
function(){return a.Da={}}),a.ea.Tz("SLASH",191));a.ra&&a.oa.listen(a.ra,"submit",function(b){c8(a,b)});a.Aa&&a.oa.listen(a.Aa,"click",function(b){var c=b.target,d=c.closest(".devsite-result-item-link");d&&(e8(a,!1),d="suggestion: "+d.getAttribute("href"),d8(a,"cloud-track-search-submit",d));c.classList.contains("devsite-search-project-scope")&&c8(a,b,!0)});a.Xa&&a.oa.listen(a.Xa,"click",function(){return void e8(a,!0)});a.$a&&a.oa.listen(a.$a,"click",function(){return void e8(a,!1)})},c8=function(a,
b,c){c=void 0===c?!1:c;var d,e;_ds.Xa(function(g){if(1==g.$){b.preventDefault();b.stopPropagation();if(!a.hasAttribute("enable-search"))return g.Ea(0);a.Da["Full Site Search"]||(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Full Site Search"},bubbles:!0})),a.Da["Full Site Search"]=!0);d8(a,"cloud-track-search-submit",a.Ha?"contains: "+a.Ha:"no match");d=c&&a.Ba?_ds.Uk(a.Ba):_ds.Uk(a.ra.getAttribute("action"));e=new _ds.ok(d.href);
_ds.Bk(e,"q",a.ea.query);d.search=e.$.toString();return _ds.x(g,DevsiteApp.fetchPage(d.href),3)}e8(a,!1);_ds.y(g)})},Dpa=function(a,b){var c=b.detail;b=a.ya.querySelector(".highlight");var d,e=Array.from(a.ya.querySelectorAll(".devsite-result-item")),g=[],h=-1;if(b){var k=_ds.Tj(b,function(m){return m.classList.contains("devsite-suggest-section")});g=Array.from(k.querySelectorAll(".devsite-result-item"));k=_ds.zj(b.parentNode.parentNode);var l=_ds.Aj(b.parentNode.parentNode);h=e.indexOf(b)}switch(c.keyCode){case 37:if(!k&&
!l)return;b&&(c=b.getAttribute("index"),l?(d=l.querySelector('[index="'+c+'"]'))||(d=_ds.Xb(Array.from(l.querySelectorAll("[index]")))):k&&((d=k.querySelector('[index="'+c+'"]'))||(d=_ds.Xb(Array.from(k.querySelectorAll("[index]"))))));break;case 39:if(!k&&!l)return;b&&(c=b.getAttribute("index"),k?(d=k.querySelector('[index="'+c+'"]'))||(d=_ds.Xb(Array.from(k.querySelectorAll("[index]")))):l&&((d=l.querySelector('[index="'+c+'"]'))||(d=_ds.Xb(Array.from(l.querySelectorAll("[index]"))))));break;case 38:b?
(d=e[h-1])||(d=_ds.Xb(g)):d=_ds.Xb(e);break;case 40:b?(d=e[h+1])||(d=g[0]):d=e[0]}b&&(b.classList.remove("highlight"),b.removeAttribute("aria-selected"));d&&(a.Ca.setAttribute("aria-activedescendant",d.id),d.setAttribute("aria-selected","true"),d.classList.add("highlight"),d.scrollIntoViewIfNeeded&&d.scrollIntoViewIfNeeded()||d.scrollIntoView())},d8=function(a,b,c){a.dispatchEvent(new CustomEvent(b,{detail:{type:"search",name:b,position:"nav",metadata:{eventDetail:c}},bubbles:!0}))},e8=function(a,
b){if(a.Sa!==b){_ds.MK(a.ea,b);if(a.Sa=b)a.setAttribute("search-active","");else{var c=a.Aa.querySelector(".highlight");c&&c.classList.remove("highlight");a.removeAttribute("search-active");a.setAttribute("aria-expanded","false");_ds.qj(a.ya)}a.hasAttribute("capture")||a.dispatchEvent(new CustomEvent("devsite-search-toggle",{detail:{active:b},bubbles:!0}))}},Cpa=function(a,b){a.Ha=null;b=b.detail;var c=b.suggestions,d=b.query;if(a.ea.query.toLowerCase().startsWith(d.toLowerCase()))if(c){var e=c.Gd();
0<e.length&&(b=e.filter(function(r){return r.Rb().includes(d)}),0<b.length&&(a.Ha=b[0].Rb()));b=e.filter(function(r){return 2===r.Ai()});c=e.filter(function(r){return 3===r.Ai()});var g=e.filter(function(r){return 4===r.Ai()}).slice(0,5),h=e.filter(function(r){return 1===r.Ai()});e=b.length+g.length+h.length;for(var k=_ds.v(g),l=k.next();!l.done;l=k.next())l=l.value,l.uh(_ds.Uk((a.Ba||"/s/results")+"/?q="+l.Rb()).toString());var m=d.split(Fpa);c.forEach(function(r){return ypa(r,_ds.Te(r,10).filter(function(u){return m.some(function(z){return u.includes(z)})}))});
k=a.getAttribute("project-name")||"";l=a.hasAttribute("project-scope");var n=a.hasAttribute("enable-search"),q=a.getAttribute("tenant-name")||"";b={pages:b,projectName:k,lz:l,EI:h,YI:g,query:d,dJ:c,Kz:n,Zn:q};0===e?_ds.$p(a.ya,Apa,b):(_ds.$p(a.ya,Bpa,b),Gpa(a,d));a.setAttribute("aria-expanded","true");a.ya.removeAttribute("hidden")}else a.ya.setAttribute("hidden",""),a.setAttribute("aria-expanded","false")},Gpa=function(a,b){b=new RegExp("("+_ds.Ki(b)+")","ig");a=_ds.v(a.ya.querySelectorAll(".devsite-suggestion-fragment"));
for(var c=a.next();!c.done;c=a.next()){c=c.value;var d=c.innerHTML;d=d.replace(b,"<b>$1</b>");_ds.kn.ct(c,_ds.To(d))}};_ds.f=K7.prototype;_ds.f.keyCode=function(a){this.oa=a;return this};_ds.f.key=function(a){this.ra=a;return this};_ds.f.shiftKey=function(a){this.Ca=a;return this};_ds.f.altKey=function(a){this.$=a;return this};_ds.f.ctrlKey=function(a){this.ea=a;return this};_ds.f.metaKey=function(a){this.ya=a;return this};_ds.f.target=function(a){this.Ga=a;return this};_ds.Ab(M7,_ds.Sf);
var wpa=[27,112,113,114,115,116,117,118,119,120,121,122,123,19],xpa="color date datetime datetime-local email month number password search tel text time url week".split(" "),P7;_ds.Ab(Y7,_ds.xl);_ds.f=Y7.prototype;_ds.f.Oma=function(){return this.Ca};_ds.f.zIa=function(a){this.Da=a};_ds.f.Pma=function(){return this.Da};_ds.f.vIa=function(a){this.Ba=a};_ds.f.Hma=function(){return this.Ba};_ds.f.nNa=function(a){this.Ha=a};_ds.f.xra=function(){return this.Ha};_ds.f.yIa=function(a){this.Ia=a};
_ds.f.zz=_ds.fa(10);_ds.f.YRa=function(a){O7(this.ea,R7(0,arguments))};_ds.f.UDa=function(a){return X7(this,this.ea,R7(0,arguments))};_ds.f.sLa=function(a){this.Ga=J7(a)};_ds.f.Npa=function(){return _ds.pc(this.Ga)};
_ds.f.kb=function(){Y7.Ua.kb.call(this);this.ea={};_ds.pg(this.$,"keydown",this.tx,!1,this);_ds.pg(this.$,"synthetic-keydown",this.Bx,!1,this);_ds.hO&&(_ds.pg(this.$,"keypress",this.Ex,!1,this),_ds.pg(this.$,"synthetic-keypress",this.Fx,!1,this));_ds.pg(this.$,"keyup",this.ux,!1,this);_ds.pg(this.$,"synthetic-keyup",this.Cx,!1,this);this.$=null};_ds.f.x4=function(a){return"shortcut_"+a};_ds.f.ux=function(a){a=L7(a);_ds.Cm&&S7(this,a);_ds.hO&&!this.ra&&T7(a)&&W7(this,a,!0)};
_ds.f.Cx=function(a){a=a.$();_ds.Cm&&S7(this,a);_ds.hO&&!this.ra&&T7(a)&&W7(this,a,!0)};_ds.f.Ex=function(a){a=L7(a);32<a.$&&T7(a)&&(this.ra=!0)};_ds.f.Fx=function(a){a=a.$();32<a.$&&T7(a)&&(this.ra=!0)};_ds.f.tx=function(a){W7(this,L7(a))};_ds.f.Bx=function(a){W7(this,a.$())};
_ds.NK.prototype.Tz=_ds.ha(11,function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];var e=this;this.$&&this.$.dispose();a&&(this.$=new Y7(document),this.$.Ca=!1,this.$.zz.apply(this.$,[a].concat(_ds.ta(c))),this.eventHandler.listen(this.$,"shortcut",function(g){var h=document;h.activeElement&&h.activeElement===h.body&&(g.preventDefault(),_ds.MK(e,!0))}))});Y7.prototype.zz=_ds.ha(10,function(a,b){U7(this.ea,R7(1,arguments),a)});var Fpa=/[ .()<>{}\[\]\/:,]+/,Hpa=0;_ds.w(b8,_ds.fi);b8.prototype.disconnectedCallback=function(){_ds.vm(this.oa);this.ea&&(this.ea.dispose(),this.ea=null)};b8.prototype.attributeChangedCallback=function(a,b,c){switch(a){case "project-scope":this.Ga=c||"";this.ea&&(this.ea.Ga=this.Ga);break;case "url-scoped":this.Ba=c;break;case "disabled":this.Ca&&(this.Ca.disabled=null!==c)}};
b8.prototype.connectedCallback=function(){if(this.ra=this.querySelector("form")){this.Ca=this.ra.querySelector(".devsite-search-query");this.Xa=this.ra.querySelector(".devsite-search-button[search-open]");this.$a=this.querySelector(".devsite-search-button[search-close]");var a="devsite-search-popout-container-id-"+ ++Hpa;this.Ca.setAttribute("aria-controls",a);this.Aa=_ds.bq(zpa,{id:a});this.ya=this.Aa.querySelector(".devsite-suggest-results-container");this.ra.appendChild(this.Aa);this.hasAttribute("project-scope")&&
(this.Ga=this.getAttribute("project-scope"));this.hasAttribute("url-scoped")&&(this.Ba=this.getAttribute("url-scoped"));this.ra&&this.Ca&&(this.ea=new _ds.NK(this,this.ra,this.Ca),this.ea.oa=!0,this.ea.Lq=this.hasAttribute("enable-query-completion"),this.ea.Im=!0,this.ea.Kq=!0,this.ea.Mq=!0,this.ea.Ga=this.Ga,this.ea.oa=this.hasAttribute("enable-suggestions"));Epa(this)}};b8.prototype.cb=function(a){var b=this;_ds.Tj(a.target,function(c){return c===b})||e8(this,!1)};
_ds.p.Object.defineProperties(b8,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["project-scope","url-scoped","disabled"]}}});b8.prototype.connectedCallback=b8.prototype.connectedCallback;b8.prototype.attributeChangedCallback=b8.prototype.attributeChangedCallback;b8.prototype.disconnectedCallback=b8.prototype.disconnectedCallback;try{window.customElements.define("devsite-search",b8)}catch(a){console.warn("devsite.app.customElement.DevsiteSearch",a)};})(_ds_www);
