(function(_ds){var window=this;'use strict';var J1=function(){_ds.nG.apply(this,arguments);this.ra=null},K1=function(a){return _ds.R(a,function c(){var d=this,e;return _ds.D(c,function(g){if(1==g.$)return _ds.x(g,_ds.pG(d),2);if(3!=g.$)return d.ra?g.return(d.ra):_ds.x(g,d.getConfig(),3);e=g.ea;d.ra=new _ds.TE(e);return g.return(d.ra)})})},Vja=function(a){a=a.uc;return(0,_ds.S)('<div class="devsite-badger-award-inner"><devsite-badge-awarded badge-name="'+_ds.U(a.title)+'" badge-icon-url="'+_ds.U(_ds.Mp(a.imageUrl))+'" badge-url="'+
_ds.U(_ds.Mp(a.url))+'"'+(null!=a.complete?' badge-complete="'+_ds.U(a.complete)+'"':"")+(null!=a.isNewTier?' is-new-tier="'+_ds.U(a.isNewTier)+'"':"")+(a.servePath?' badge-path="'+_ds.U(a.servePath)+'"':"")+(a.shareTitle?' badge-share-title="'+_ds.U(a.shareTitle)+'"':"")+(a.shareDescription?' badge-share-description="'+_ds.U(a.shareDescription)+'"':"")+(a.nextPlaylistUrl?' next-playlist-url="'+_ds.U(_ds.Mp(a.nextPlaylistUrl))+'"':"")+(a.redeemAnotherBtn?" redeem-another":"")+(a.hideButtons?" hide-buttons":
"")+" dismiss></devsite-badge-awarded></div>")},Wja=function(){return(0,_ds.S)('<div class="devsite-badger-award"></div>')},L1=function(){var a=_ds.Zv.call(this,["devsite-badge-awarded"])||this;a.eventHandler=new _ds.qm(a);a.oa=new _ds.fo;a.ea=null;return a},M1=function(a){return _ds.R(a,function c(){var d=this,e,g,h;return _ds.D(c,function(k){if(1==k.$){if(!d.ea)return k.return();e=d.ea.querySelectorAll(".devsite-badger-award-inner");g=e[0];if(!g)return k.Ea(0);h=g.querySelector("devsite-badge-awarded");
if(null===h||void 0===h?0:h.Os)null===h||void 0===h?void 0:h.Os();g.removeAttribute("show");return _ds.x(k,_ds.kl(200),3)}_ds.uj(g);1===e.length&&(_ds.uj(d.ea),d.ea=null);_ds.y(k)})})},Xja=function(a){if(_ds.eo(a.oa)){var b=_ds.TM();if(b){b=b.filter(function(g){return 3>g.displayCount});0<b.length?a.oa.set("temp_badges",JSON.stringify(b)):a.oa.remove("temp_badges");b=_ds.v(b);for(var c=b.next();!c.done;c=b.next()){c=c.value;var d=new URL(c.awardedBy,document.location.origin),e=_ds.Mk();(!c.awardedBy||
d.origin===e.origin&&d.pathname===e.pathname)&&c.complete&&N1(a,c)}}}},N1=function(a,b){_ds.R(a,function d(){var e=this,g,h,k;return _ds.D(d,function(l){switch(l.$){case 1:g=e;if(!b||"error"===document.body.getAttribute("type")||Yja.exec(document.location.pathname))return l.return();e.ea||(e.ea=_ds.bq(Wja),document.body.appendChild(e.ea));_ds.A(l,2);return _ds.x(l,window.customElements.whenDefined("devsite-badge-awarded"),4);case 4:_ds.B(l,3);break;case 2:_ds.C(l);case 3:h=_ds.bq(Vja,{uc:b});if(!h)return l.return();
e.eventHandler.listen(h,"devsite-badge-awarded-dismissed",function(){M1(g)});if(k=h.querySelector("devsite-badge-awarded"))e.ea.appendChild(h),_ds.um(e.eventHandler,k,"running",function(){null===h||void 0===h?void 0:h.setAttribute("show","");var m,n,q=null===(m=g.ea)||void 0===m?void 0:m.querySelectorAll("devsite-badge-awarded");if(q)for(m=0;m<q.length;m++)null===(n=q[m])||void 0===n?void 0:n.dispatchEvent(new CustomEvent("devsite-badge-awarded-stack-num-changed",{bubbles:!0,detail:{vH:q.length-1-
m}}))});_ds.y(l)}})})};_ds.w(J1,_ds.nG);_ds.f=J1.prototype;_ds.f.vf=function(){return _ds.R(this,function b(){var c=this,d;return _ds.D(b,function(e){if(1==e.$)return _ds.x(e,K1(c),2);d=e.ea;return e.return(d.vf())})})};
_ds.f.Di=function(a){a=void 0===a?!1:a;return _ds.R(this,function c(){var d=this,e,g,h,k,l;return _ds.D(c,function(m){switch(m.$){case 1:return _ds.x(m,K1(d),2);case 2:return e=m.ea,g=_ds.wG(d,"getWalletId",a),h=_ds.xG(d,g),h||(h=e.Di(a),_ds.zG(d,g,h)),k=null,_ds.A(m,3,4),_ds.x(m,h,6);case 6:k=m.ea;case 4:_ds.Ga(m);_ds.yG(d,g);_ds.Ja(m,5);break;case 3:throw l=_ds.C(m),l;case 5:return m.return(k)}})})};
_ds.f.nk=function(){return _ds.R(this,function b(){var c=this,d;return _ds.D(b,function(e){if(1==e.$)return _ds.x(e,K1(c),2);d=e.ea;return e.return(d.nk())})})};_ds.f.Vi=function(){return _ds.R(this,function b(){var c=this,d,e,g,h;return _ds.D(b,function(k){switch(k.$){case 1:return _ds.x(k,K1(c),2);case 2:return d=k.ea,e=_ds.wG(c,"syncWallet"),g=_ds.xG(c,e),g||(g=d.Vi(),_ds.zG(c,e,g)),_ds.A(k,3,4),_ds.x(k,g,4);case 4:_ds.Ga(k);_ds.yG(c,e);_ds.Ja(k,0);break;case 3:throw h=_ds.C(k),h;}})})};
_ds.f.Mj=function(){return _ds.R(this,function b(){var c=this,d;return _ds.D(b,function(e){if(1==e.$)return _ds.x(e,K1(c),2);d=e.ea;d.Mj();_ds.y(e)})})};var Yja=/\/redeem.*|\/u[\/]?.*|\/settings[\/]?.*?/;_ds.w(L1,_ds.Zv);L1.prototype.connectedCallback=function(){this.ib()};L1.prototype.disconnectedCallback=function(){_ds.vm(this.eventHandler);M1(this)};
L1.prototype.Vi=function(){return _ds.R(this,function b(){var c,d,e,g,h;return _ds.D(b,function(k){switch(k.$){case 1:return _ds.x(k,(0,_ds.Lo)(),2);case 2:return _ds.x(k,window.customElements.whenDefined("devsite-user"),3);case 3:c=document.querySelector("devsite-user#devsite-user");if(!c)return k.return();d=!1;_ds.A(k,4);return _ds.x(k,c.isSignedIn(),6);case 6:d=k.ea;_ds.B(k,5);break;case 4:_ds.C(k);case 5:if(!d)return k.return();e=new J1;return _ds.x(k,e.vf(),7);case 7:g=k.ea;if(!g)return k.return();
h=new _ds.IG;_ds.A(k,8);return _ds.x(k,h.Ib(),10);case 10:_ds.B(k,0);break;case 8:_ds.C(k),_ds.y(k)}})})};L1.prototype.ib=function(){var a=this;this.eventHandler.listen(document.body,"devsite-before-page-change",function(){return void M1(a)});this.eventHandler.listen(document.body,"devsite-award-granted",function(b){(b=b.hb)&&b.detail&&(b=b.detail.award,b.complete&&N1(a,b))});this.eventHandler.listen(document.body,["devsite-page-loaded","devsite-page-changed"],function(){a.Vi();Xja(a)})};try{window.customElements.define("devsite-badger",L1)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBadger",a)};})(_ds_www);
