(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var Z3=function(a,b){W3()&&(b=X3()?"translate3d("+b+"px,0px,0px)":"translate("+b+"px,0px)",_ds.Am(a,Y3(),b))},b4=function(){var a=_ds.fi.apply(this,arguments)||this;a.eventHandler=new _ds.qm;a.pb=-1;a.Xa=new _ds.qm;a.Sa=0;a.rc=new MutationObserver(function(){return $3(a)});a.wd=new _ds.nm(function(){$3(a);a4(a)},15);a.im=void 0;a.ya=0;a.ea=0;a.Aa=0;a.offset=0;a.updated=!1;return a},c4=function(a){window.requestAnimationFrame(function(){return a.wd.Gb()})},d4=function(a,b){return(a=a.querySelector(b))?
a.getBoundingClientRect().height:0},$3=function(a){a.ya=d4(a,".devsite-top-logo-row-wrapper-wrapper");a.ea=d4(a,".devsite-collapsible-section");a.Aa=d4(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",""+a.ya);a.setAttribute("bottom-row--height",""+a.ea);a.setAttribute("bottom-tabs--height",""+a.Aa);document.body.style.setProperty("--devsite-js-header-top-row-height",a.ya+"px");document.body.style.setProperty("--devsite-js-header-lower-section-height",a.ea+"px");document.body.style.setProperty("--devsite-js-header-lower-tabs-height",
a.Aa+"px");document.body.style.setProperty("--devsite-js-header-height",a.Vq()+"px");e4(a)},f4=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){var b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},e4=function(a){var b=a.querySelector(".devsite-collapsible-section");a.offset>=a.ea&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<
a.ea-a.Aa&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.pb&&(document.body.style.setProperty("--devsite-js-header-lower-tabs-offset",a.offset+"px"),_ds.Am(b,"transform","translate3d(0, -"+a.offset+"px, 0)"),a4(a),a.pb=a.offset)},Bma=function(a){var b=a.querySelector(".devsite-top-logo-row-middle"),c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.vm(a.Xa);a.Sa&&window.cancelAnimationFrame(a.Sa);c.removeAttribute("transition");
a.removeAttribute("search-expanded");var e=new _ds.Ei(b.offsetWidth,b.offsetHeight);b=new _ds.Ei(c.offsetWidth,c.offsetHeight);var g=_ds.Zm(c,"margin"),h="rtl"===document.documentElement.getAttribute("dir")?1:-1,k=(e.width-g.left-g.right)/b.width;e=(e.width-(b.width+g.left+g.right))*h;var l=(g=a.hasAttribute("search-active"))?e:0,m=g?k:1;_ds.Am(d,{opacity:1,width:b.width+"px",height:b.height+"px"});Z3(c,a.hasAttribute("search-active")?0:e);_ds.um(a.Xa,d,_ds.MI,function(){var n=a.querySelector("devsite-search"),
q=a.querySelector(".devsite-search-background");q&&(q.style.opacity="0");n&&(n.removeAttribute("transition"),Z3(n,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.Sa=window.requestAnimationFrame(function(){c.setAttribute("transition","");if(W3()){var n=X3()?"scale3d("+m+",1,1)":"scale("+m+",1)";_ds.Am(d,Y3(),n)}Z3(c,l)})}},Cma=function(a,b){_ds.R(a,function d(){var e=this,g,h,k,l;return _ds.D(d,function(m){if(1==m.$){if(!e.hasAttribute("billboard"))return m.return();
g=e.querySelector("devsite-search");h=e.querySelector("devsite-search input.devsite-search-query");k=e.querySelector(".devsite-header-billboard-search devsite-search");l=null===k||void 0===k?void 0:k.querySelector("input.devsite-search-query");if(!(g&&h&&k&&l))return m.return();if(!b)return k.removeAttribute("disabled"),document.activeElement===h&&l.focus(),g.setAttribute("disabled",""),m.Ea(0);g.removeAttribute("disabled");return document.activeElement!==l?m.Ea(3):_ds.x(m,_ds.fl(),4)}3!=m.$&&h.focus();
k.setAttribute("disabled","");_ds.y(m)})})},a4=function(a){0===a.ea?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},g4=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},h4=function(a,b,c){b=b.querySelector(c);
c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.hi(a,c,b))},l4=function(){var a=b4.call(this)||this;a.cb=null;a.Ba=null;a.xe=[];a.Ca=null;a.vb=!1;a.oa=!1;a.Ha=!1;a.Cb=null;a.Kb=null;a.ra=null;a.fc=null;a.Ia=null;a.Da=null;a.Gc=null;a.$a=null;a.Ga=null;a.eventHandler=new _ds.qm;a.Ed=function(b){b.matches?i4(a):j4(a)};a.jb=function(b){b.matches&&k4(a)};return a},m4=function(a){_ds.R(a,function c(){var d=this,e,g;return _ds.D(c,function(h){if(1==h.$)return _ds.A(h,2),_ds.x(h,Dma(d),4);if(2!=h.$){(e=d.querySelector(".right-overflow"))&&
e.remove();if(!d.Ga||d.fc)return h.return();if(!d.Ha){var k=document.createElement("tab");k.classList.add("left-overflow","cta");var l=document.createElement("div");l.classList.add("right-overflow");d.Ga.appendChild(k);d.Kb.appendChild(l);d.Cb=d.querySelector(".left-overflow");d.Gc=d.querySelector(".right-overflow");d.Ha=!0}d.oa||(864>=window.innerWidth?d.oa||(d.Da=window.matchMedia("(min-width: 864px)"),d.Da.addListener(d.jb)):k4(d));return _ds.B(h,0)}g=_ds.C(h);console.error("Error: ",g);_ds.y(h)})})},
Dma=function(a){return _ds.R(a,function c(){var d=this;return _ds.D(c,function(e){if(1==e.$)return _ds.x(e,Ema(d),2);d.$a=e.ea;var g;a:{if(g=d.querySelector(".devsite-doc-set-nav-row .devsite-breadcrumb-item")){var h=g.querySelector(".devsite-breadcrumb-link");if(h&&"none"!==window.getComputedStyle(h).display)break a}g=null}d.fc=g;d.cb=d.querySelector(".devsite-product-button-row");d.Ga=d.querySelector(".devsite-tabs-wrapper");d.Kb=d.querySelector(".devsite-top-logo-row");d.Ca=d.querySelectorAll(".devsite-product-button-row a");
d.ra=d.querySelector(".devsite-collapsible-section");_ds.y(e)})})},k4=function(a){if(!document.querySelector(".devsite-doc-set-nav-row cloudx-tabs-nav"))try{j4(a);var b=a.$a.querySelector(".left-overflow").getBoundingClientRect().right,c=a.$a.querySelector(".right-overflow").getBoundingClientRect().left,d=window.innerWidth-c,e=Fma(a.querySelectorAll(".devsite-tabs-wrapper tab"));a.Ia=b+e+d+60;a.Ia>=window.innerWidth&&i4(a);a.Ba=window.matchMedia("(max-width: "+a.Ia+"px)");a.Ba.addListener(a.Ed);a.oa=
!0}catch(g){a.oa=!1,console.error("Failed to initialize overflow media query: ",g)}},Gma=function(a){var b;null===(b=a.Ca)||void 0===b?void 0:b.forEach(function(c){c.className&&(c.dataset.defaultClass=c.className)})},Ema=function(a){return _ds.R(a,function c(){var d=this,e;return _ds.D(c,function(g){e=d;return g.return(new Promise(function(h){var k=e.querySelector("cloudx-tabs-nav").shadowRoot;k&&k.innerHTML?h(k):(new MutationObserver(function(){k=e.querySelector("cloudx-tabs-nav").shadowRoot;h(k)})).observe(k,
{childList:!0})}))})})},j4=function(a){var b=[].slice.call(a.querySelectorAll(".devsite-product-button-row a"));Array.isArray(b)&&b.length&&(Gma(a),Hma(a),b.forEach(function(c){"left"===c.getAttribute("data-overflow-container")?a.Cb.appendChild(c):a.Gc.appendChild(c)}),a.ra&&a.ra.setAttribute("hidden",""))},i4=function(a){a.ra&&a.ra.removeAttribute("hidden");Ima(a)},Ima=function(a){var b;null===(b=a.Ca)||void 0===b?void 0:b.forEach(function(c){c.dataset.defaultClass&&(c.className=c.dataset.defaultClass);
a.cb.appendChild(c)})},Hma=function(a){a=_ds.v(a.Ca);for(var b=a.next();!b.done;b=a.next()){b=b.value;var c=b.getAttribute("data-overflow-class");b.className=c||""}},Fma=function(a){return Array.from(a).reduce(function(b,c){return b+(c?c.offsetWidth:0)},0)};var W3=_ds.pi(function(){return!_ds.fj||0<=_ds.Wb(_ds.ty,9)}),X3=_ds.pi(function(){return _ds.gj||_ds.dB||_ds.Cm&&0<=_ds.Wb(_ds.ty,10)||_ds.fj&&0<=_ds.Wb(_ds.ty,10)}),Y3=_ds.pi(function(){return _ds.fj&&9==_ds.Im?"-ms-transform":"transform"});_ds.w(b4,_ds.fi);_ds.f=b4.prototype;_ds.f.attributeChangedCallback=function(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;e4(this);break;case "search-active":Bma(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),Cma(this,a)}};
_ds.f.connectedCallback=function(){this.ib();f4(this);a4(this);$3(this);this.rc.observe(this,{childList:!0,subtree:!0});e4(this);var a=_ds.Mk();this.im=_ds.Ck(_ds.Ek(a.href),"authuser")};_ds.f.disconnectedCallback=function(){_ds.vm(this.eventHandler);this.rc.disconnect()};
_ds.f.ib=function(){var a=this;this.eventHandler.listen(this,"devsite-search-toggle",function(b){b=b.hb;_ds.Vj(b.target,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});this.eventHandler.listen(document.body,"devsite-sitemask-hidden",function(){return document.body.removeAttribute("devsite-book-nav--open")});this.eventHandler.listen(window,"resize",function(){return c4(a)});this.eventHandler.listen(document.body,["devsite-page-loaded",
"devsite-content-updated"],function(){c4(a)});this.eventHandler.listen(this,"click",function(b){b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})))})};_ds.f.Vq=function(){return this.ya+this.ea-this.offset};_ds.f.RF=function(){return this.ya+this.ea};
_ds.f.zc=function(a){this.updated=!1;if(a){h4(this,a,".devsite-header-upper-tabs");h4(this,a,".devsite-collapsible-section");h4(this,a,".devsite-product-name-wrapper");h4(this,a,"devsite-language-selector");h4(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&g4(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(g4(c,b),c=_ds.Mk(),c=_ds.Ck(_ds.Ek(c.href),"authuser"),c!==this.im&&(this.im=c,b.refresh()));
_ds.hi(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));_ds.hi(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&a&&(_ds.qj(this),this.appendChild(a));f4(this);c4(this)};_ds.p.Object.defineProperties(b4,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["offset","search-active","bottom-row--hidden"]}}});_ds.w(l4,b4);l4.prototype.connectedCallback=function(){var a=this;b4.prototype.connectedCallback.call(this);this.eventHandler.listen(document.body,"cloud-tabs-loaded",function(){a.vb||(a.vb=!0,m4(a))})};l4.prototype.disconnectedCallback=function(){b4.prototype.disconnectedCallback.call(this);this.Ba&&this.Ba.removeListener(this.Ed);this.Da&&this.Da.removeListener(this.jb)};l4.prototype.zc=function(a){b4.prototype.zc.call(this,a);this.Ha=this.oa=!1;m4(this)};try{window.customElements.define("devsite-header",l4)}catch(a){console.warn("devsite.app.tenants.cloud.static.components.CloudxHeader",a)};})(_ds_www);
