(function(_ds){var window=this;'use strict';var Tla=function(){var a=void 0===a?_ds.vR.length:a;return _ds.vR.slice(0,a)},Ula=function(a){var b=a.projectName,c=a.OI,d=a.QI,e=a.IF,g=a.oF,h=a.RJ;a='<devsite-dialog class="devsite-feedback"><div class="devsite-dialog-contents"><h3 class="no-link">Send feedback about...</h3><div class="devsite-feedback-items"><a href="#" class="devsite-feedback-item" feedback-type="documentation" data-label="Docs Feedback Image" track-type="feedback" track-name="feedbackDocIcon"><div class="devsite-feedback-item-icon-container devsite-feedback-item-icon-color"><div class="devsite-feedback-item-icon material-icons" aria-hidden="true">description</div></div><div>This page</div><div class="devsite-feedback-item-type">Documentation feedback</div></a>';
g||(c=d?'<div class="devsite-feedback-item-icon material-icons" aria-hidden="true">'+_ds.T(d)+"</div>":c?'<img src="'+_ds.U(_ds.Op(c))+'" loading="lazy" alt="">':"",a+="<a"+(e?' href="'+_ds.U(_ds.Mp(e))+'"':' href="#"')+' class="devsite-feedback-item" feedback-type="product" data-label="Product Feedback Image" track-type="feedback" track-name="feedbackProductIcon"><div class="devsite-feedback-item-icon-container '+(d?"devsite-feedback-item-icon-color devsite-theme-primary":"devsite-feedback-item-icon-img")+
'">'+c+"</div><div>"+_ds.T(b)+'</div><div class="devsite-feedback-item-type">',a+="Product feedback</div></a>");a+='</div><div class="devsite-feedback-notice">We appreciate your feedback! Please note that we cannot respond.</div>';h&&(a+='<div class="devsite-feedback-support"><span class="devsite-feedback-support-icon material-icons" aria-hidden="true">help</span><span>',b='Need help? Visit our <a href="'+(_ds.U(_ds.Mp(h))+'">support page</a>.'),a=a+b+"</span></div>");return(0,_ds.S)(a+'<div class="devsite-feedback-buttons"><button class="button-white" tabindex="1" data-label="Cancel Feedback Button" track-type="feedback" track-name="cancelFeedbackButton" feedback-cancel>Close</button></div></div></devsite-dialog>')},
f3=function(){var a=_ds.fi.call(this,["devsite-dialog"])||this;a.eventHandler=new _ds.qm;a.ea=null;a.oa=!1;a.Pe(_ds.zg(Vla),_ds.zg(Wla),_ds.zg(Xla),_ds.zg(Yla),_ds.zg(Zla),_ds.zg($la),_ds.zg(ama),_ds.zg(bma),_ds.zg(cma));return a},ema=function(a,b){_ds.R(a,function d(){var e=this,g,h,k,l,m,n,q,r,u;return _ds.D(d,function(z){if(1==z.$)return g=e,h=b.Ve,k=h.getAttribute("feedback-type"),l="#"===h.getAttribute("href"),m={context:e.getAttribute("context"),type:k},n=Tla(),n.length&&(m.errorStack=n),e.hasAttribute("rating-type")&&
(m.ratingType=e.getAttribute("rating-type")),e.hasAttribute("rating-category")&&(m.ratingCategory=e.getAttribute("rating-category")),_ds.x(z,(0,_ds.Lo)(),2);q=z.ea;r={productId:e.getAttribute("product-id"),locale:q.getLocale(),bucket:e.getAttribute("bucket"),productVersion:e.getAttribute("version"),callback:function(){return void dma()},onLoadCallback:function(){return void g3(g)}};u={action:"click",label:h.getAttribute("data-label"),category:h.getAttribute("data-category")||"Site-Wide Custom Events"};
h3(e,u);l&&(b.preventDefault(),b.stopPropagation(),_ds.WK(r,m));_ds.y(z)})})},g3=function(a){var b;null===(b=a.ea)||void 0===b?void 0:b.removeAttribute("open");_ds.uj(a.ea)},dma=function(){Array.from(document.querySelectorAll('script[src*="www.google.com/tools/feedback/"]')).forEach(function(a){return _ds.uj(a)})},h3=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:b,bubbles:!0}))};var Vla=_ds.t(["bucket"]),Wla=_ds.t(["context"]),Xla=_ds.t(["product-id"]),Yla=_ds.t(["data-label"]),Zla=_ds.t(["track-metadata-position"]),$la=_ds.t(["track-name"]),ama=_ds.t(["track-type"]),bma=_ds.t(["disable"]),cma=_ds.t(["project-"]),fma=_ds.t(["open"]);_ds.w(f3,_ds.fi);
f3.prototype.connectedCallback=function(){if(!this.oa){var a=this.querySelector(".google-feedback"),b=new Map([["data-b","bucket"],["data-context","context"],["data-p","product-id"]]),c=new Map([["data-label","Send Feedback Button"],["track-metadata-position","content"],["track-name","sendFeedbackLink"],["track-type","feedback"]]);if(a){b=_ds.v(b.entries());for(var d=b.next();!d.done;d=b.next()){var e=_ds.v(d.value);d=e.next().value;e=e.next().value;if(a.hasAttribute(d)){var g=a.getAttribute(d)||
"";_ds.gi(this,e,g);a.removeAttribute(d)}}c=_ds.v(c.entries());for(b=c.next();!b.done;b=c.next())d=_ds.v(b.value),b=d.next().value,d=d.next().value,a.hasAttribute(b)?(d=a.getAttribute(b)||"",_ds.gi(this,b,d),a.removeAttribute(b)):_ds.gi(this,b,d);a.classList.remove("google-feedback")}!this.hasAttribute("project-name")&&(a=document.querySelector('meta[property="og:site_name"]'))&&(a=a.getAttribute("content")||"",_ds.gi(this,"project-name",a));this.hasAttribute("project-icon")?_ds.gi(this,"project-icon",
_ds.Uk(this.getAttribute("project-icon")||"").href||""):(a=document.querySelector('link[rel="apple-touch-icon"]'))&&_ds.gi(this,"project-icon",a.getAttribute("href")||"");this.ea=_ds.bq(Ula,{oF:this.hasAttribute("disable-product-feedback"),IF:this.getAttribute("project-feedback-url"),OI:this.getAttribute("project-icon"),QI:this.getAttribute("project-icon-name"),projectName:this.getAttribute("project-name")||"",RJ:this.getAttribute("project-support-url")});this.oa=!0}this.ib()};
f3.prototype.disconnectedCallback=function(){_ds.vm(this.eventHandler)};
f3.prototype.ib=function(){var a=this,b;this.eventHandler.listen(this,"click",function(e){if("A"===e.target.tagName||"BUTTON"===e.target.tagName)e.preventDefault(),e.stopPropagation(),a.ea&&(document.body.appendChild(a.ea),_ds.kn.oe([_ds.zg(fma)],a.ea,"open",""),e={action:"click",category:a.getAttribute("data-category")||"Site-Wide Custom Events",label:a.getAttribute("data-label")},h3(a,e))});if(this.ea){var c=Array.from(this.ea.querySelectorAll("[feedback-type]"));c=_ds.v(c);for(var d=c.next();!d.done;d=
c.next())this.eventHandler.listen(d.value,"click",function(e){ema(a,e)});(c=null===(b=this.ea)||void 0===b?void 0:b.querySelector("button[feedback-cancel]"))&&this.eventHandler.listen(c,"click",function(){g3(a);var e,g=null===(e=a.ea)||void 0===e?void 0:e.querySelector("button[feedback-cancel]");e={action:"click",label:null===g||void 0===g?void 0:g.getAttribute("data-label"),category:(null===g||void 0===g?void 0:g.getAttribute("data-category"))||"Site-Wide Custom Events"};h3(a,e)});this.eventHandler.listen(this.ea,
"devsite-dialog-hide",function(){_ds.uj(a.ea)})}};f3.prototype.disconnectedCallback=f3.prototype.disconnectedCallback;f3.prototype.connectedCallback=f3.prototype.connectedCallback;try{window.customElements.define("devsite-feedback",f3)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteFeedback",a)};})(_ds_www);
