(function(_ds){var window=this;'use strict';var zqa=function(a){var b=a.ZJ,c=a.Yd,d=a.TE;a=a.pH;var e='<ul class="devsite-nav-list"><li class="devsite-nav-item devsite-nav-heading devsite-toc-toggle" role="heading" aria-level="2"><span class="devsite-nav-title"><span class="devsite-nav-text">On this page</span></span>';c&&(e=e+'<button type="button" title="'+_ds.qp("Expand/collapse contents"),e+='" class="devsite-nav-show-all button-transparent material-icons"></button>');e+="</li>";for(var g=b.length,h=0;h<g;h++){var k=b[h];e+=
'<li class="devsite-nav-item"'+(c&&k.index<a?" visible":"")+'><a href="#'+_ds.U(k.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.U(h)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.U(h)+'" track-metadata-link-destination="#'+_ds.U(k.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.T(k.text)+"</span></a>";if(_ds.kp(k.children).length){e+=
'<ul class="devsite-nav-list">';k=k.children;for(var l=k.length,m=0;m<l;m++){var n=k[m];e+='<li class="devsite-nav-item"'+(c&&n.index<a?" visible":"")+'><a href="#'+_ds.U(n.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.U(h)+"."+_ds.U(m)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.U(h)+"."+_ds.U(m)+'" track-metadata-link-destination="#'+
_ds.U(n.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.T(n.text)+"</span></a></li>"}e+="</ul>"}e+="</li>"}d&&(e=c?e+'<li class="devsite-nav-item devsite-apix-link"><a href="#try-it" class="devsite-nav-title"><span class="devsite-nav-text" tooltip>Try it</span></a></li>':e+'<button type="button" class="devsite-show-apix button-primary">Try it!</button>');c&&(e=e+'<li class="devsite-toc-toggle"><button type="button" class="button-flat devsite-nav-more-items material-icons" track-type="navigation" track-name="embeddedNavExpand" title="'+
_ds.qp("Expand/collapse contents"),e+='"></button></li>');return(0,_ds.S)(e+"</ul>")},Q8=function(){var a=_ds.fi.call(this)||this;a.eventHandler=new _ds.qm;a.Ga=new _ds.wm;a.Aa=new Set;a.Ba=new Map;a.Ia=new _ds.nm(function(){return void P8(a)},16);a.Ha=new _ds.nm(function(){return void Aqa(a)},33);a.ra=null;a.oa=null;a.ea=[];a.Ca=!1;a.ya=null;a.Yd=!1;a.Da=[];a.Pe(_ds.zg(Bqa),_ds.zg(Cqa),_ds.zg(Dqa),_ds.zg(Eqa),_ds.zg(Fqa),_ds.zg(Gqa));return a},Hqa=function(a){_ds.R(a,function c(){var d=this,e,g,
h,k;return _ds.D(c,function(l){switch(l.$){case 1:e=d;if(!("IntersectionObserver"in _ds.hj())){l.Ea(2);break}d.ya&&d.ya.disconnect();g=document.querySelector("devsite-header");h=152;if(!g){l.Ea(3);break}return _ds.x(l,window.customElements.whenDefined("devsite-header"),4);case 4:(k=Number(g.getAttribute("top-row--height"))+Number(g.getAttribute("bottom-row--height")))&&(h=k);case 3:d.ya=new IntersectionObserver(function(m){m=_ds.v(m);for(var n=m.next();!n.done;n=m.next())n=n.value,n.isIntersecting?
e.Aa.add(n.target):e.Aa.delete(n.target);e.Ha.Gb()},{rootMargin:h+"px 0px 0px 0px",threshold:[0,1]});case 2:d.Ga.resolve(),_ds.y(l)}})})},Aqa=function(a){return _ds.R(a,function c(){var d=this;return _ds.D(c,function(e){if(1==e.$)return _ds.x(e,Iqa(d),2);if(d.oa){var g="#"+d.oa.id,h=encodeURI(g);g=d.Ba.get(g)||d.Ba.get(h);d.ra!==g&&(d.ra&&d.ra.classList.remove("devsite-nav-active"),g&&(g.classList.add("devsite-nav-active"),d.ra=g))}_ds.y(e)})})},P8=function(a){if(!a.hasAttribute("disabled")){var b=
document.querySelector("devsite-content .devsite-article-body");b?(a.Yd?a.classList.add("devsite-toc-embedded"):a.classList.add("devsite-toc"),Jqa(a,b),a.Ca=!0):a.Rc()}},Jqa=function(a,b){var c=[],d=!1,e="";switch(a.getAttribute("depth")){case "1":e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents)";break;default:e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents), h3:not(.hide-from-toc):not(#contents):not(#table-of-contents)"}a.ea=[].concat(_ds.ta(b.querySelectorAll(e))).filter(function(h){return h.id&&
h.dataset.text}).filter(function(h){return Kqa(h)});b=_ds.v(a.ea.entries());for(e=b.next();!e.done;e=b.next()){var g=_ds.v(e.value);e=g.next().value;g=g.next().value;e={id:g.id,level:g.tagName.toLowerCase(),text:g.dataset.text,children:[],index:e};"h2"===e.level?(c.push(e),d=!0):d?c[c.length-1].children.push(e):c.push(e)}_ds.fc(a.Da,c,a.dw.bind(a))&&a.Ca||(c.length?(Lqa(a,c),a.show(),a.Yd||Mqa(a)):a.Rc(),a.Da=c)},Iqa=function(a){return _ds.R(a,function c(){var d=this,e,g,h,k,l,m,n,q;return _ds.D(c,
function(r){switch(r.$){case 1:e=d;g=0;h=document.querySelector("devsite-header");if(!h){r.Ea(2);break}return _ds.x(r,window.customElements.whenDefined("devsite-header"),3);case 3:g=h.Vq();case 2:k=d.ea.findIndex(function(u){return e.Aa.has(u)&&u.getBoundingClientRect().top>=g});l=d.ea[k];if(!l){d.oa&&d.oa.getBoundingClientRect().top>window.innerHeight&&(m=d.ea.indexOf(d.oa),0<m&&(d.oa=d.ea[m-1]));r.Ea(0);break}return _ds.x(r,Nqa(d),5);case 5:n=r.ea,q=l.getBoundingClientRect().top-g,d.oa=q>n&&0<k?
d.ea[k-1]:l,_ds.y(r)}})})},Nqa=function(a){return _ds.R(a,function c(){var d,e,g,h;return _ds.D(c,function(k){if(1==k.$)return e=d=0,(g=document.querySelector("devsite-header"))?_ds.x(k,window.customElements.whenDefined("devsite-header"),3):k.Ea(2);2!=k.$&&(d=g.Vq(),e=g.RF());h=window.innerHeight-d;return k.return(Math.max(e-d,Math.floor(h/5)))})})},Mqa=function(a){_ds.R(a,function c(){var d=this,e,g,h;return _ds.D(c,function(k){if(1==k.$)return _ds.x(k,d.Ga.promise,2);if(!d.ya)return k.return();
d.ya.disconnect();d.Aa.clear();d.ra&&d.ra.classList.remove("devsite-nav-active");d.ra=null;e=_ds.v(d.ea);for(g=e.next();!g.done;g=e.next())h=g.value,d.ya.observe(h);_ds.y(k)})})},Kqa=function(a){return _ds.OO.find(function(b){return!!_ds.Vj(a,b,6)})||_ds.Uj(a,"devsite-selector",null,6)||_ds.Vj(a,"devsite-dialog",3)?!1:!0},Lqa=function(a,b){var c=_ds.bq(zqa,{ZJ:b,Yd:a.Yd,TE:!!document.body.querySelector("devsite-apix, .devsite-apix"),pH:5});b=_ds.v(c.querySelectorAll("a.devsite-nav-title"));for(var d=
b.next();!d.done;d=b.next()){d=d.value;var e=d.hash,g=encodeURI(d.hash);a.Ba.set(e,d);a.Ba.set(g,d)}_ds.qj(a);a.Yd&&_ds.gi(a,"hidden","",c);a.appendChild(c);if(a.Yd){if(8<=a.getElementsByClassName("devsite-nav-item").length){b=_ds.v(a.querySelectorAll(".devsite-nav-show-all, .devsite-nav-more-items"));for(d=b.next();!d.done;d=b.next())a.eventHandler.listen(d.value,"click",function(){a.hasAttribute("expanded")?a.removeAttribute("expanded"):_ds.gi(a,"expanded","")});_ds.gi(a,"expandable","")}setTimeout(function(){c.removeAttribute("hidden")},
0)}};var Bqa=_ds.t(["disabled"]),Cqa=_ds.t(["has-sidebar"]),Dqa=_ds.t(["hidden"]),Eqa=_ds.t(["expandable"]),Fqa=_ds.t(["expanded"]),Gqa=_ds.t(["visible"]);_ds.w(Q8,_ds.fi);_ds.f=Q8.prototype;_ds.f.connectedCallback=function(){this.Yd=this.hasAttribute("devsite-toc-embedded");P8(this);this.ib()};_ds.f.disconnectedCallback=function(){this.Rc();this.Ca=!1;_ds.vm(this.eventHandler)};
_ds.f.ib=function(){var a=this;this.Yd||this.eventHandler.listen(document.body,"devsite-content-updated devsite-element-hidden devsite-element-visible devsite-page-loaded devsite-sticky-resize devsite-sticky-scroll".split(" "),function(){a.Ha.Gb()});this.eventHandler.listen(document.body,"devsite-content-updated",function(){P8(a)})};_ds.f.Ss=function(a){a=a&&"false"===a.toLowerCase();this.Da=[];_ds.qj(this);a?(_ds.gi(this,"disabled",""),this.Rc()):(this.removeAttribute("disabled"),this.show(),this.Ia.Gb())};
_ds.f.Rc=function(){_ds.qj(this);this.dispatchEvent(new CustomEvent("devsite-element-hidden",{bubbles:!0}));this.removeAttribute("visible");_ds.gi(this,"hidden","");if(!this.Yd){var a=document.querySelector(".devsite-main-content");a&&a.removeAttribute("has-sidebar")}};
_ds.f.show=function(){this.dispatchEvent(new CustomEvent("devsite-element-visible",{bubbles:!0}));this.removeAttribute("hidden");_ds.gi(this,"visible","");if(!this.Yd){var a=document.querySelector(".devsite-main-content");a&&_ds.gi(this,"has-sidebar","",a);Hqa(this)}};_ds.f.dw=function(a,b){var c=!0;if(a.children.length||b.children.length)c=_ds.fc(a.children,b.children,this.dw.bind(this));return c&&a.id===b.id&&a.text===b.text};
_ds.p.Object.defineProperties(Q8,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["max-height","offset"]}}});Q8.prototype.renderUpdatedContent=Q8.prototype.Ss;Q8.prototype.disconnectedCallback=Q8.prototype.disconnectedCallback;Q8.prototype.connectedCallback=Q8.prototype.connectedCallback;try{window.customElements.define("devsite-toc",Q8)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteToc",a)};})(_ds_www);
