(function(_ds){var window=this;'use strict';var Zja=function(){return(0,_ds.S)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},$ja=function(){return(0,_ds.S)('<div class="devsite-book-nav-blur"></div>')},P1=function(){var a=_ds.fi.call(this)||this;a.ra=!1;a.oa=null;a.eventHandler=new _ds.qm;a.Ca=function(){};a.ya=new Set;a.Da=!1;a.background=document.createElement("div");a.background.classList.add("devsite-book-nav-bg");a.ea=_ds.bq(Zja);
a.Aa=_ds.bq($ja);a.Ga=new Promise(function(b){a.Ca=b});a.Ba=new _ds.nm(function(){a.ra&&O1(a)},20);return a},Q1=function(a,b,c){c=void 0===c?!0:c;b=Array.from((void 0===b?a:b).querySelectorAll(".devsite-nav-title"));a.ya=new Set(b);if(!_ds.Mk().hash&&c)aka(a,a.ya);else for(c=new _ds.UM,a=_ds.v(a.ya),b=a.next();!b.done;b=a.next())_ds.WM(c,b.value)},aka=function(a,b){_ds.R(a,function d(){var e=this,g,h,k,l,m,n,q;return _ds.D(d,function(r){if(1==r.$)return g=e,e.ra?_ds.x(r,(0,_ds.Lo)(),2):r.return();
h=r.ea;k=new _ds.UM;l=function(u){u=u.target;_ds.WM(k,u);g.ya.delete(u);h.unregisterIntersectionForElement(u)};m=_ds.v(b);for(n=m.next();!n.done;n=m.next()){q=n.value;try{h.registerIntersectionForElement(q,l)}catch(u){l({target:q})}}_ds.y(r)})})},O1=function(a){var b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.gi(a,"visually-hidden","",c))},R1=function(a,b){var c=!1;if(a.oa)for(var d=_ds.v(a.oa.querySelectorAll("[menu]")),
e=d.next();!e.done;e=d.next())e=e.value,e.getAttribute("menu")===b?(e.removeAttribute("hidden"),c=!0):_ds.gi(a,"hidden","",e);return c},bka=function(a,b){b.defaultPrevented||(b=_ds.Tj(b.target,function(c){return c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a},!0),b!==a&&_ds.$h(b,_ds.Tn(_ds.Uk(b.href).href)))},cka=function(a){return _ds.R(a,function c(){var d=this;return _ds.D(c,function(e){switch(e.$){case 1:if(!d.ra)return e.return();d.removeAttribute("user-scrolled");return _ds.x(e,
_ds.fl(),2);case 2:return _ds.x(e,S1(d),3);case 3:return _ds.x(e,d.Ga,4);case 4:return _ds.x(e,(0,_ds.Lo)(),5);case 5:return _ds.x(e,_ds.fl(),6);case 6:return _ds.x(e,S1(d),0)}})})},T1=function(a,b){(b=void 0===b?a:b)||(b=a);var c=_ds.v(b.querySelectorAll(".devsite-nav-active"));for(a=c.next();!a.done;a=c.next())a.value.classList.remove("devsite-nav-active");a=_ds.ll(_ds.Mk().pathname);a='[href="'+_ds.Uk(a).href+'"], [href="'+a+'"],\n        [alt-paths~="'+a+'"]';b=_ds.v(b.querySelectorAll(a));for(a=
b.next();!a.done;a=b.next())a.value.classList.add("devsite-nav-active")},U1=function(a,b){(b=void 0===b?a:b)||(b=a);var c=b.querySelector(".devsite-mobile-nav-bottom");if(c)for(var d=c.querySelector(".devsite-nav-active");d&&d.parentElement&&d.parentElement!==b;)d.hasAttribute("collapsed")&&(d.removeAttribute("animatable"),_ds.um(a.eventHandler,d,"devsite-expandable-nav-transition-end",function(){d&&_ds.gi(a,"animatable","",d)}),d.removeAttribute("collapsed")),d=d.parentElement},S1=function(a){return _ds.R(a,
function c(){var d=this,e;return _ds.D(c,function(g){if(1==g.$)return d.ra&&d.oa?_ds.x(g,(0,_ds.Lo)(),2):g.return();if(4!=g.$)return(e=d.oa.querySelector(".devsite-nav-active"))?d.hasAttribute("user-scrolled")?g.Ea(4):_ds.x(g,dka(d,e),4):g.Ea(0);_ds.gi(d,"animatable","");_ds.y(g)})})},dka=function(a,b){return _ds.R(a,function d(){var e=this,g,h;return _ds.D(d,function(k){if(1==k.$){if(!e.ra)return k.return();g=e.hasAttribute("user-scrolled");h=_ds.Om(b,e,!0);e.scrollTop=h.y;return _ds.x(k,_ds.fl(),
2)}g&&_ds.gi(e,"user-scrolled","");_ds.y(k)})})},V1=function(a){return _ds.R(a,function c(){var d,e=this,g,h,k;return _ds.D(c,function(l){if(1==l.$)return _ds.x(l,(0,_ds.Lo)(),2);d=l.ea;g=_ds.v(e.ya);for(h=g.next();!h.done;h=g.next())k=h.value,d.unregisterIntersectionForElement(k);_ds.y(l)})})},eka=function(a){_ds.R(a,function c(){var d,e,g=this;return _ds.D(c,function(h){if(1==h.$)return e=(d=document.documentElement.scrollHeight-document.documentElement.clientHeight)?document.documentElement.scrollTop/
d:0,g.hasAttribute("collapsed")?(_ds.gi(g,"aria-expanded","true",g.ea),_ds.gi(g,"aria-label","Hide side navigation",g.ea),_ds.gi(g,"data-title","Hide side navigation",g.ea),g.removeAttribute("collapsed"),W1(g,"Expanded book nav")):(g.ea.removeAttribute("aria-expanded"),_ds.gi(g,"aria-label","Show side navigation",g.ea),_ds.gi(g,"data-title","Show side navigation",g.ea),_ds.gi(g,"collapsed",""),W1(g,"Collapsed book nav")),_ds.x(h,_ds.fl(),2);d=document.documentElement.scrollHeight-document.documentElement.clientHeight;
document.documentElement.scrollTop=Math.round(e*d);_ds.y(h)})})},W1=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))};var fka=_ds.t(["animatable"]),gka=_ds.t(["aria-expanded"]),hka=_ds.t(["aria-label"]),ika=_ds.t(["collapsed"]),jka=_ds.t(["data-title"]),kka=_ds.t(["fixed"]),lka=_ds.t(["has-book-nav"]),mka=_ds.t(["hidden"]),nka=_ds.t(["role"]),oka=_ds.t(["top-level-nav"]),pka=_ds.t(["user-scrolled"]),qka=_ds.t(["visually-hidden"]),rka="onpointerover"in window?"pointerover":"mouseover";_ds.w(P1,_ds.fi);_ds.f=P1.prototype;
_ds.f.connectedCallback=function(){var a,b;return _ds.R(this,function d(){var e=this,g;return _ds.D(d,function(h){if(1==h.$)return e.ra=!0,e.Pe(e.$(fka),e.$(gka),e.$(hka),e.$(ika),e.$(jka),e.$(kka),e.$(lka),e.$(mka),e.$(nka),e.$(oka),e.$(pka),e.$(qka)),_ds.gi(e,"role","menu"),_ds.rj(e.background,e),e.hasAttribute("hidden")&&(_ds.gi(e,"hidden","",e.ea),_ds.gi(e,"hidden","",e.Aa)),_ds.x(h,(0,_ds.Lo)(),2);if(3!=h.$)return g=h.ea,e.Da=g.hasFlagAccess(150),e.Da&&(null===(a=e.parentElement)||void 0===a?
void 0:a.insertBefore(e.ea,e.nextSibling),_ds.gi(e,"aria-label","Hide side navigation",e.ea),_ds.gi(e,"data-title","Hide side navigation",e.ea),_ds.gi(e,"aria-expanded","true",e.ea),null===(b=e.parentElement)||void 0===b?void 0:b.insertBefore(e.Aa,e.nextSibling)),O1(e),e.ib(),_ds.x(h,e.init(),3);Q1(e);_ds.y(h)})})};
_ds.f.disconnectedCallback=function(){this.ra=!1;_ds.vm(this.eventHandler);V1(this);this.ya.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.gi(this,"visually-hidden","",a);a=_ds.v([this.background,this.ea,this.Aa]);for(var b=a.next();!b.done;b=a.next())(b=b.value)&&_ds.uj(b);this.removeAttribute("animatable");document.body.style.removeProperty("--devsite-js-book-nav-scrollbar-width")};
_ds.f.attributeChangedCallback=function(a){"hidden"===a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.gi(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);for(var c=_ds.v([this.background,
this.ea,this.Aa]),d=c.next();!d.done;d=c.next())(d=d.value)&&(b?_ds.gi(this,a,"",d):d.removeAttribute(a))}"fixed"===a&&this.Ca()};
_ds.f.ib=function(){var a=this;this.eventHandler.listen(this,"click",function(b){var c;if(!b.defaultPrevented){var d=b.target;"devsite-close-nav"===d.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.gi(a,"top-level-nav",""));if(d.hasAttribute("menu")){var e=d.getAttribute("menu");e&&R1(a,e)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}if(!(d.classList.contains("devsite-nav-toggle")||
d.classList.contains("devsite-nav-title-no-path")||(null===(c=d.parentElement)||void 0===c?0:c.classList.contains("devsite-nav-title-no-path")))){a.oa&&(b=a.oa.querySelector("[menu=_book]"))&&b.contains(d)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}));var g;d instanceof Element&&d.matches("a.devsite-nav-title")?g=d:g=_ds.Uj(d,"a","devsite-nav-title");g&&!g.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}))}}});
this.eventHandler.listen(this,[rka,"focusin"],function(b){return void bka(a,b)});this.eventHandler.listen(document.body,"devsite-sitemask-hidden",function(){a.oa&&(R1(a,"_book")?a.removeAttribute("top-level-nav"):_ds.gi(a,"top-level-nav",""))});this.eventHandler.listen(document.body,"devsite-page-loaded",function(){return void a.Ba.Gb()});this.eventHandler.listen(this,"devsite-content-updated",function(){a.Ba.Gb()});this.eventHandler.listen(this,"scroll",function(){_ds.gi(a,"user-scrolled","")});
this.eventHandler.listen(this.ea,"click",function(){eka(a)})};
_ds.f.init=function(a){a=void 0===a?!0:a;return _ds.R(this,function c(){var d=this,e,g,h;return _ds.D(c,function(k){if(1==k.$){if(!d.ra)return k.return();document.body.style.setProperty("--devsite-js-book-nav-scrollbar-width",d.offsetWidth-d.clientWidth+"px");d.oa=d.querySelector(".devsite-mobile-nav-bottom");!d.hasAttribute("hidden")&&d.oa&&d.oa.querySelector(".devsite-nav-active")||_ds.gi(d,"animatable","");_ds.gi(d,"top-level-nav","");d.oa&&d.oa.querySelector("[menu=_book]")&&d.removeAttribute("top-level-nav");
0===d.children.length&&_ds.gi(d,"hidden","");if(d.background)for(e=_ds.v(["hidden","fixed","animatable"]),g=e.next();!g.done;g=e.next())h=g.value,d.hasAttribute(h)&&_ds.gi(d,h,"",d.background);return!d.hasAttribute("hidden")&&a?(T1(d),U1(d),_ds.x(k,cka(d),0)):_ds.x(k,_ds.fl(),4)}return _ds.x(k,S1(d),0)})})};
_ds.f.zc=function(a){return _ds.R(this,function c(){var d=this,e;return _ds.D(c,function(g){switch(g.$){case 1:if(!a){_ds.qj(d);g.Ea(2);break}d.removeAttribute("animatable");e=a.querySelector("nav")||null;T1(d,e);U1(d,e);if(!e){g.Ea(3);break}return _ds.x(g,V1(d),4);case 4:d.ya.clear(),Q1(d,e,!1);case 3:_ds.hi(d,d.querySelector("nav"),e);case 2:return _ds.x(g,_ds.fl(),5);case 5:return _ds.x(g,d.init(!1),0)}})})};
_ds.p.Object.defineProperties(P1,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["collapsed","fixed","hidden"]}}});P1.prototype.updateContent=P1.prototype.zc;P1.prototype.attributeChangedCallback=P1.prototype.attributeChangedCallback;P1.prototype.disconnectedCallback=P1.prototype.disconnectedCallback;P1.prototype.connectedCallback=P1.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",P1)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
