(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var n=ca(this);function p(a,b){if(b)a:{var c=n;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
p("Symbol",function(a){function b(k){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(k||"")+"_"+e++,k)}function c(k,g){this.g=k;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
p("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=n[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});function da(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function r(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ea="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var ka=fa;function la(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.I=b.prototype}function ma(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function na(){this.m=!1;this.j=null;this.s=void 0;this.g=1;this.l=this.i=0;this.o=this.h=null}
function oa(a){if(a.m)throw new TypeError("Generator is already running");a.m=!0}f=na.prototype;f.K=function(a){this.s=a};function pa(a,b){a.h={R:b,S:!0};a.g=a.i||a.l}f.return=function(a){this.h={return:a};this.g=this.l};f.Id=function(a){this.h={D:a};this.g=this.l};function qa(a,b,c){a.g=c;return{value:b}}f.vf=function(a,b){a=r(a);var c=a.next();ma(c);if(c.done)this.s=c.value,this.g=b;else return this.j=a,qa(this,c.value,b)};f.D=function(a){this.g=a};f.Jd=function(){this.g=0};
f.Xd=function(a){this.i=0;this.l=a||0};function ra(a,b){a.g=b;a.i=0}function sa(a){a.i=0;var b=a.h.R;a.h=null;return b}f.Mc=function(a,b,c){c?this.o[c]=this.h:this.o=[this.h];this.i=a||0;this.l=b||0};f.Kd=function(a,b){b=this.o.splice(b||0)[0];(b=this.h=this.h||b)?b.S?this.g=this.i||this.l:void 0!=b.D&&this.l<b.D?(this.g=b.D,this.h=null):this.g=this.l:this.g=a};f.Pc=function(a){return new ta(a)};function ta(a){this.h=a;this.g=[];for(var b in a)this.g.push(b);this.g.reverse()}
ta.prototype.i=function(){for(;0<this.g.length;){var a=this.g.pop();if(a in this.h)return a}return null};function ua(a){this.g=new na;this.h=a}function va(a,b){oa(a.g);var c=a.g.j;if(c)return wa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return xa(a)}function wa(a,b,c,d){try{var e=b.call(a.g.j,c);ma(e);if(!e.done)return a.g.m=!1,e;var k=e.value}catch(g){return a.g.j=null,pa(a.g,g),xa(a)}a.g.j=null;d.call(a.g,k);return xa(a)}
function xa(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.m=!1,{value:b.value,done:!1}}catch(c){a.g.s=void 0,pa(a.g,c)}a.g.m=!1;if(a.g.h){b=a.g.h;a.g.h=null;if(b.S)throw b.R;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ya(a){this.next=function(b){oa(a.g);a.g.j?b=wa(a,a.g.j.next,b,a.g.K):(a.g.K(b),b=xa(a));return b};this.throw=function(b){oa(a.g);a.g.j?b=wa(a,a.g.j["throw"],b,a.g.K):(pa(a.g,b),b=xa(a));return b};this.return=function(b){return va(a,b)};this[Symbol.iterator]=function(){return this}}function za(a,b){b=new ya(new ua(b));ka&&a.prototype&&ka(b,a.prototype);return b}function t(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
p("WeakMap",function(a){function b(l){this.g=(h+=Math.random()+1).toString();if(l){l=r(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function e(l){if(!t(l,g)){var m=new c;ba(l,g,{value:m})}}function k(l){var m=Object[l];m&&(Object[l]=function(q){if(q instanceof c)return q;Object.isExtensible(q)&&e(q);return m(q)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),
q=new a([[l,2],[m,3]]);if(2!=q.get(l)||3!=q.get(m))return!1;q.delete(l);q.set(m,4);return!q.has(l)&&4==q.get(m)}catch(u){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();k("freeze");k("preventExtensions");k("seal");var h=0;b.prototype.set=function(l,m){if(!d(l))throw Error("Invalid WeakMap key");e(l);if(!t(l,g))throw Error("WeakMap key fail: "+l);l[g][this.g]=m;return this};b.prototype.get=function(l){return d(l)&&t(l,g)?l[g][this.g]:void 0};b.prototype.has=function(l){return d(l)&&t(l,
g)&&t(l[g],this.g)};b.prototype.delete=function(l){return d(l)&&t(l,g)&&t(l[g],this.g)?delete l[g][this.g]:!1};return b});
p("Map",function(a){function b(){var h={};return h.B=h.next=h.head=h}function c(h,l){var m=h.g;return da(function(){if(m){for(;m.head!=h.g;)m=m.B;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})}function d(h,l){var m=l&&typeof l;"object"==m||"function"==m?k.has(l)?m=k.get(l):(m=""+ ++g,k.set(l,m)):m="p_"+l;var q=h.h[m];if(q&&t(h.h,m))for(h=0;h<q.length;h++){var u=q[h];if(l!==l&&u.key!==u.key||l===u.key)return{id:m,list:q,index:h,v:u}}return{id:m,list:q,
index:-1,v:void 0}}function e(h){this.h={};this.g=b();this.size=0;if(h){h=r(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),l=new a(r([[h,"s"]]));if("s"!=l.get(h)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),q=m.next();if(q.done||q.value[0]!=h||"s"!=q.value[1])return!1;q=m.next();return q.done||4!=q.value[0].x||
"t"!=q.value[1]||!m.next().done?!1:!0}catch(u){return!1}}())return a;var k=new WeakMap;e.prototype.set=function(h,l){h=0===h?0:h;var m=d(this,h);m.list||(m.list=this.h[m.id]=[]);m.v?m.v.value=l:(m.v={next:this.g,B:this.g.B,head:this.g,key:h,value:l},m.list.push(m.v),this.g.B.next=m.v,this.g.B=m.v,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.v&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.h[h.id],h.v.B.next=h.v.next,h.v.next.B=h.v.B,h.v.head=null,this.size--,
!0):!1};e.prototype.clear=function(){this.h={};this.g=this.g.B=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).v};e.prototype.get=function(h){return(h=d(this,h).v)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,l){for(var m=this.entries(),q;!(q=m.next()).done;)q=q.value,
h.call(l,q[1],q[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});function Aa(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
p("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=Aa(this,b,"endsWith");void 0===c&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;0<e&&0<c;)if(d[--c]!=b[--e])return!1;return 0>=e}});function Ba(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var k=c++;return{value:b(k,a[k]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}
p("Array.prototype.entries",function(a){return a?a:function(){return Ba(this,function(b,c){return[b,c]})}});
p("Promise",function(a){function b(g){this.h=0;this.i=void 0;this.g=[];this.o=!1;var h=this.j();try{g(h.resolve,h.reject)}catch(l){h.reject(l)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.h=function(g){if(null==this.g){this.g=[];var h=this;this.i(function(){h.l()})}this.g.push(g)};var e=n.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var l=
g[h];g[h]=null;try{l()}catch(m){this.j(m)}}}this.g=null};c.prototype.j=function(g){this.i(function(){throw g;})};b.prototype.j=function(){function g(m){return function(q){l||(l=!0,m.call(h,q))}}var h=this,l=!1;return{resolve:g(this.O),reject:g(this.l)}};b.prototype.O=function(g){if(g===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.T(g);else{a:switch(typeof g){case "object":var h=null!=g;break a;case "function":h=!0;break a;default:h=!1}h?this.J(g):this.m(g)}};
b.prototype.J=function(g){var h=void 0;try{h=g.then}catch(l){this.l(l);return}"function"==typeof h?this.U(h,g):this.m(g)};b.prototype.l=function(g){this.s(2,g)};b.prototype.m=function(g){this.s(1,g)};b.prototype.s=function(g,h){if(0!=this.h)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.h);this.h=g;this.i=h;2===this.h&&this.P();this.F()};b.prototype.P=function(){var g=this;e(function(){if(g.N()){var h=n.console;"undefined"!==typeof h&&h.error(g.i)}},1)};b.prototype.N=
function(){if(this.o)return!1;var g=n.CustomEvent,h=n.Event,l=n.dispatchEvent;if("undefined"===typeof l)return!0;"function"===typeof g?g=new g("unhandledrejection",{cancelable:!0}):"function"===typeof h?g=new h("unhandledrejection",{cancelable:!0}):(g=n.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return l(g)};b.prototype.F=function(){if(null!=this.g){for(var g=0;g<this.g.length;++g)k.h(this.g[g]);this.g=null}};var k=new c;b.prototype.T=
function(g){var h=this.j();g.H(h.resolve,h.reject)};b.prototype.U=function(g,h){var l=this.j();try{g.call(h,l.resolve,l.reject)}catch(m){l.reject(m)}};b.prototype.then=function(g,h){function l(H,K){return"function"==typeof H?function(ab){try{m(H(ab))}catch(bb){q(bb)}}:K}var m,q,u=new b(function(H,K){m=H;q=K});this.H(l(g,m),l(h,q));return u};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.H=function(g,h){function l(){switch(m.h){case 1:g(m.i);break;case 2:h(m.i);break;default:throw Error("Unexpected state: "+
m.h);}}var m=this;null==this.g?k.h(l):this.g.push(l);this.o=!0};b.resolve=d;b.reject=function(g){return new b(function(h,l){l(g)})};b.race=function(g){return new b(function(h,l){for(var m=r(g),q=m.next();!q.done;q=m.next())d(q.value).H(h,l)})};b.all=function(g){var h=r(g),l=h.next();return l.done?d([]):new b(function(m,q){function u(ab){return function(bb){H[ab]=bb;K--;0==K&&m(H)}}var H=[],K=0;do H.push(void 0),K++,d(l.value).H(u(H.length-1),q),l=h.next();while(!l.done)})};return b});
p("Array.prototype.keys",function(a){return a?a:function(){return Ba(this,function(b){return b})}});p("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],k="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof k){b=k.call(b);for(var g=0;!(k=b.next()).done;)e.push(c.call(d,k.value,g++))}else for(k=b.length,g=0;g<k;g++)e.push(c.call(d,b[g],g));return e}});
p("Array.prototype.values",function(a){return a?a:function(){return Ba(this,function(b,c){return c})}});p("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});p("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var k=d[c];if(k===b||Object.is(k,b))return!0}return!1}});
p("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==Aa(this,b,"includes").indexOf(b,c||0)}});var v=this||self;function Ca(){}function Da(a){var b=typeof a;b="object"!=b?b:a?Array.isArray(a)?"array":b:"null";return"array"==b||"object"==b&&"number"==typeof a.length}function Ea(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}
function w(a,b){a=a.split(".");var c=v;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}function Fa(a,b){function c(){}c.prototype=b.prototype;a.I=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Dc=function(d,e,k){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}}function Ga(a){return a};var x=new Map([]);x.set("devsite-a11y-announce",{src:"/js/devsite_devsite_a11y_announce_module.js"});x.set("devsite-analytics",{src:"/js/devsite_devsite_analytics_module.js"});x.set("devsite-analytics-scope",{src:"/js/devsite_devsite_analytics_scope_module.js"});x.set("devsite-anselm",{src:"/js/devsite_devsite_anselm_module.js"});x.set("devsite-api-getstarted",{src:"/js/devsite_devsite_api_getstarted_module.js"});x.set("devsite-apix",{src:"/js/devsite_devsite_apix_module.js"});
x.set("devsite-apix-index",{src:"/js/devsite_devsite_apix_index_module.js"});x.set("devsite-apix-snippets",{src:"/js/devsite_devsite_apix_snippets_module.js"});x.set("devsite-badger",{src:"/js/devsite_devsite_badger_module.js"});x.set("devsite-badge-awarded",{src:"/js/devsite_devsite_badge_awarded_module.js"});x.set("devsite-badge-awarder",{src:"/js/devsite_devsite_badge_awarder_module.js"});x.set("devsite-badge-redeemer",{src:"/js/devsite_devsite_badge_redeemer_module.js"});
x.set("devsite-book-nav",{src:"/js/devsite_devsite_book_nav_module.js"});x.set("devsite-bookmark",{src:"/js/devsite_devsite_bookmark_module.js"});x.set("devsite-chart",{src:"/js/devsite_devsite_chart_module.js"});x.set("devsite-catalog",{src:"/js/devsite_devsite_catalog_module.js"});x.set("devsite-code",{src:"/js/devsite_devsite_code_module.js"});x.set("devsite-content",{src:"/js/devsite_devsite_content_module.js"});x.set("devsite-codelab-catalog",{src:"/js/devsite_devsite_codelab_catalog_module.js"});
x.set("devsite-product-catalog",{src:"/js/devsite_devsite_product_catalog_module.js"});x.set("devsite-credentials-dialog",{src:"/js/devsite_devsite_credentials_dialog_module.js"});x.set("devsite-cse",{src:"/js/devsite_devsite_cse_module.js"});x.set("devsite-panel",{src:"/js/devsite_devsite_panel_module.js"});x.set("devsite-device",{src:"/js/devsite_devsite_device_module.js"});x.set("devsite-devprofile",{src:"/js/devsite_devsite_devprofile_module.js"});x.set("devsite-dialog",{src:"/js/devsite_devsite_dialog_module.js"});
x.set("devsite-dynamic-content",{src:"/js/devsite_devsite_dynamic_content_module.js"});x.set("devsite-expandable",{src:"/js/devsite_devsite_expandable_module.js"});x.set("devsite-expandable-nav",{src:"/js/devsite_devsite_expandable_nav_module.js"});x.set("devsite-extradory",{src:"/js/devsite_devsite_extradory_module.js"});x.set("devsite-feedback",{src:"/js/devsite_devsite_feedback_module.js"});x.set("devsite-filter",{src:"/js/devsite_devsite_filter_module.js"});x.set("devsite-footer-linkboxes",{src:"/js/devsite_devsite_footer_linkboxes_module.js"});
x.set("devsite-footer-promos",{src:"/js/devsite_devsite_footer_promos_module.js"});x.set("devsite-footer-utility",{src:"/js/devsite_devsite_footer_utility_module.js"});x.set("devsite-google-survey",{src:"/js/devsite_devsite_google_survey_module.js"});x.set("devsite-googler-buttons",{src:"/js/devsite_devsite_googler_buttons_module.js"});x.set("devsite-hats-survey",{src:"/js/devsite_devsite_hats_survey_module.js"});x.set("devsite-header",{src:"/js/devsite_devsite_header_module.js"});
x.set("devsite-heading-link",{src:"/js/devsite_devsite_heading_link_module.js"});x.set("devsite-iframe",{src:"/js/devsite_devsite_iframe_module.js"});x.set("devsite-info-popout",{src:"/js/devsite_devsite_info_popout_module.js"});x.set("devsite-jump-to",{src:"/js/devsite_devsite_jump_to_module.js"});x.set("devsite-jsfiddle-button",{src:"/js/devsite_devsite_jsfiddle_button_module.js"});x.set("devsite-language-selector",{src:"/js/devsite_devsite_language_selector_module.js"});
x.set("devsite-lightbox",{src:"/js/devsite_devsite_lightbox_module.js"});x.set("devsite-mathjax",{src:"/js/devsite_devsite_mathjax_module.js"});x.set("devsite-mdc",{src:"/js/devsite_devsite_mdc_module.js"});x.set("devsite-multiple-choice",{src:"/js/devsite_devsite_multiple_choice_module.js"});x.set("devsite-nav-buttons",{src:"/js/devsite_devsite_nav_buttons_module.js"});x.set("devsite-playlist",{src:"/js/devsite_devsite_playlist_module.js"});x.set("devsite-playlist-earnable-badges",{src:"/js/devsite_devsite_playlist_earnable_badges_module.js"});
x.set("devsite-playlist-summary",{src:"/js/devsite_devsite_playlist_summary_module.js"});x.set("devsite-pagination",{src:"/js/devsite_devsite_pagination_module.js"});x.set("devsite-profile-card",{src:"/js/devsite_devsite_profile_card_module.js"});x.set("devsite-progress",{src:"/js/devsite_devsite_progress_module.js"});x.set("devsite-quiz",{src:"/js/devsite_devsite_quiz_module.js"});x.set("devsite-recommendations",{src:"/js/devsite_devsite_recommendations_module.js"});
x.set("devsite-recommendations-dropdown",{src:"/js/devsite_devsite_recommendations_dropdown_module.js"});x.set("devsite-recommendations-sidebar",{src:"/js/devsite_devsite_recommendations_sidebar_module.js"});x.set("devsite-reference-results",{src:"/js/devsite_devsite_reference_results_module.js"});x.set("devsite-search",{src:"/js/devsite_devsite_search_module.js"});x.set("devsite-select",{src:"/js/devsite_devsite_select_module.js"});x.set("devsite-selector",{src:"/js/devsite_devsite_selector_module.js"});
x.set("devsite-shell",{src:"/js/devsite_devsite_shell_module.js"});x.set("devsite-shell-activate-button",{src:"/js/devsite_devsite_shell_activate_button_module.js"});x.set("devsite-sitemask",{src:"/js/devsite_devsite_sitemask_module.js"});x.set("devsite-snackbar",{src:"/js/devsite_devsite_snackbar_module.js"});x.set("devsite-sort",{src:"/js/devsite_devsite_sort_module.js"});x.set("devsite-spinner",{src:"/js/devsite_devsite_spinner_module.js"});x.set("devsite-support-form",{src:"/js/devsite_devsite_support_form_module.js"});
x.set("devsite-tabs",{src:"/js/devsite_devsite_tabs_module.js"});x.set("devsite-theme-selector",{src:"/js/devsite_devsite_theme_selector_module.js"});x.set("devsite-thumb-rating",{src:"/js/devsite_devsite_thumb_rating_module.js"});x.set("devsite-toc",{src:"/js/devsite_devsite_toc_module.js"});x.set("devsite-topic",{src:"/js/devsite_devsite_topic_module.js"});x.set("devsite-tooltip",{src:"/js/devsite_devsite_tooltip_module.js"});x.set("devsite-tracking-question",{src:"/js/devsite_devsite_tracking_question_module.js"});
x.set("devsite-user",{src:"/js/devsite_devsite_user_module.js"});x.set("devsite-var",{src:"/js/devsite_devsite_var_module.js"});x.set("devsite-version-selector",{src:"/js/devsite_devsite_version_selector_module.js"});x.set("devsite-visibility-analytics",{src:"/js/devsite_devsite_visibility_analytics_module.js"});x.set("devsite-vplus",{src:"/js/devsite_devsite_vplus_module.js"});x.set("devsite-wall-acknowledgement",{src:"/js/devsite_devsite_wall_acknowledgement_module.js"});
x.set("devsite-youtube",{src:"/js/devsite_devsite_youtube_module.js"});x.set("google-codelab",{src:"/js/devsite_google_codelab_module.js"});x.set("google-codelab-about",{src:"/js/devsite_google_codelab_about_module.js"});x.set("google-codelab-analytics",{src:"/js/devsite_google_codelab_analytics_module.js"});x.set("google-codelab-step",{src:"/js/devsite_google_codelab_step_module.js"});x.set("google-codelab-survey",{src:"/js/devsite_google_codelab_survey_module.js"});
w("DevsiteAppAuthorizedElements",x);w("DevsiteAppTenantCustomized",!1);var Ha={yc:0,xc:1,cc:6,ac:8,ic:12,jc:14,kc:17,nc:18,pc:21,rc:25,za:37,sc:38,Ja:40,hb:45,na:47,Z:50,ha:52,ea:62,Va:63,Bb:66,sb:70,$:73,mb:74,pa:75,yb:76,Ra:77,Ta:80,fa:81,eb:82,Pa:83,rb:85,sa:87,La:89,ub:90,Ma:91,Sa:92,la:93,vc:94,Oa:95,ka:96,Cb:97,aa:98,ca:99,qc:100,Ia:101,Qa:102,xb:103,uc:104,ua:105,ma:106,Ga:107,xa:108,qb:109,ta:110,Fa:111,tc:112,zb:113,ya:114,ja:115,Aa:116,fb:117,cb:118,Na:119,tb:120,fc:121,Ab:122,lc:123,bc:124,$a:125,nb:126,Ha:127,hc:128,jb:129,kb:130,Da:131,Za:132,ba:133,Wa:134,
Ka:135,gb:136,da:137,wc:138,ob:139,dc:140,$b:141,ib:142,bb:143,pb:144,ia:145,lb:146,Xa:147,ab:148,vb:149,wa:150,ra:151,Ya:152,Ea:153,Ca:154,oa:155,oc:156,mc:157,Ua:158,Ba:159,ga:160,qa:161,va:162,ec:163,wb:164};var Ia,Ja="undefined"!==typeof TextEncoder;var Ka=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},La=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,k=0;k<c;k++)k in e&&(d[k]=b.call(void 0,e[k],k,a));return d};function Ma(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};var Na;function Oa(a,b){this.g=b===Pa?a:""}f=Oa.prototype;f.ed=!0;f.ad=function(){return this.g.toString()};f.dd=!0;f.Tc=function(){return 1};f.Jc=function(a,b){var c=Qa.exec(Ra(this).toString()),d=c[3]||"";return Sa(c[1]+Ta("?",c[2]||"",a)+Ta("#",d,b))};f.toString=function(){return this.g+""};function Ra(a){return a instanceof Oa&&a.constructor===Oa?a.g:"type_error:TrustedResourceUrl"}var Qa=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,Pa={};
function Sa(a){if(void 0===Na){var b=null;var c=v.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:Ga,createScript:Ga,createScriptURL:Ga})}catch(d){v.console&&v.console.error(d.message)}Na=b}else Na=b}a=(b=Na)?b.createScriptURL(a):a;return new Oa(a,Pa)}
function Ta(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c)if(Object.prototype.hasOwnProperty.call(c,d)){var e=c[d];e=Array.isArray(e)?e:[e];for(var k=0;k<e.length;k++){var g=e[k];null!=g&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(g)))}}return b};var Ua;a:{var Va=v.navigator;if(Va){var Wa=Va.userAgent;if(Wa){Ua=Wa;break a}}Ua=""}function y(a){return-1!=Ua.indexOf(a)};function Xa(){}function Ya(){return(y("Chrome")||y("CriOS"))&&!y("Edge")};var Za="function"===typeof Uint8Array.prototype.slice,$a,z=0,A=0;function cb(a){var b=a>>>0;a=Math.floor((a-b)/4294967296)>>>0;z=b;A=a}function B(a){var b=0>a;a=Math.abs(a);var c=a>>>0;a=Math.floor((a-c)/4294967296);a>>>=0;b&&(a=~a>>>0,c=(~c>>>0)+1,4294967295<c&&(c=0,a++,4294967295<a&&(a=0)));z=c;A=a}function db(a){var b=0>a;a=2*Math.abs(a);cb(a);a=z;var c=A;b&&(0==a?0==c?c=a=4294967295:(c--,a=4294967295):a--);z=a;A=c}
function eb(a){var b=0>a?1:0;a=b?-a:a;if(0===a)0<1/a?z=A=0:(A=0,z=2147483648);else if(isNaN(a))A=0,z=2147483647;else if(3.4028234663852886E38<a)A=0,z=(b<<31|2139095040)>>>0;else if(1.1754943508222875E-38>a)a=Math.round(a/Math.pow(2,-149)),A=0,z=(b<<31|a)>>>0;else{var c=Math.floor(Math.log(a)/Math.LN2);a*=Math.pow(2,-c);a=Math.round(8388608*a)&8388607;A=0;z=(b<<31|c+127<<23|a)>>>0}}
function fb(a){var b=r(a);a=b.next().value;var c=b.next().value,d=b.next().value,e=b.next().value,k=b.next().value,g=b.next().value,h=b.next().value;b=b.next().value;z=a+(c<<8)+(d<<16)+(e<<24)>>>0;A=k+(g<<8)+(h<<16)+(b<<24)>>>0}function gb(a,b,c){var d=b>>31;c(a<<1^d,(b<<1|a>>>31)^d)}
function hb(a){function b(g,h){for(var l=0;8>l&&(1!==g||0<h);l++)h=g*e[l]+h,e[l]=h&255,h>>>=8}function c(){for(var g=0;8>g;g++)e[g]=~e[g]&255}var d=!1;"-"===a[0]&&(d=!0,a=a.slice(1));for(var e=[0,0,0,0,0,0,0,0],k=0;k<a.length;k++)b(10,a.charCodeAt(k)-48);d&&(c(),b(1,1));return e}
function ib(a){return a.constructor===Uint8Array?a:a.constructor===ArrayBuffer?new Uint8Array(a):a.constructor===Array?new Uint8Array(a):a.constructor===String?jb(a):a instanceof Uint8Array?new Uint8Array(a.buffer,a.byteOffset,a.byteLength):new Uint8Array(0)};function C(a,b){this.g=a;this.h=b}function kb(a){return new C((a.g>>>1|(a.h&1)<<31)>>>0,a.h>>>1>>>0)}function lb(a){return new C(a.g<<1>>>0,(a.h<<1|a.g>>>31)>>>0)}f=C.prototype;f.Ld=function(){return!!(this.g&1)};f.add=function(a){return new C((this.g+a.g&4294967295)>>>0>>>0,((this.h+a.h&4294967295)>>>0)+(4294967296<=this.g+a.g?1:0)>>>0)};f.sub=function(a){return new C((this.g-a.g&4294967295)>>>0>>>0,((this.h-a.h&4294967295)>>>0)-(0>this.g-a.g?1:0)>>>0)};
function mb(a){var b=a&65535,c=a>>>16;a=10*b+65536*(0*b&65535)+65536*(10*c&65535);for(b=0*c+(0*b>>>16)+(10*c>>>16);4294967296<=a;)a-=4294967296,b+=1;return new C(a>>>0,b>>>0)}f.toString=function(){for(var a="",b=this;0!=b.g||0!=b.h;){var c=new C(0,0);b=new C(b.g,b.h);for(var d=new C(10,0),e=new C(1,0);!(d.h&2147483648);)d=lb(d),e=lb(e);for(;0!=e.g||0!=e.h;)0>=(d.h<b.h||d.h==b.h&&d.g<b.g?-1:d.h==b.h&&d.g==b.g?0:1)&&(c=c.add(e),b=b.sub(d)),d=kb(d),e=kb(e);c=[c,b];b=c[0];a=c[1].g+a}""==a&&(a="0");return a};
function nb(a){for(var b=new C(0,0),c=new C(0,0),d=0;d<a.length;d++){if("0">a[d]||"9"<a[d])return null;c.g=parseInt(a[d],10);var e=mb(b.g);b=mb(b.h);b.h=b.g;b.g=0;b=e.add(b).add(c)}return b}f.Db=function(){return new C(this.g,this.h)};function D(a,b){this.g=a;this.h=b}D.prototype.add=function(a){return new D((this.g+a.g&4294967295)>>>0>>>0,((this.h+a.h&4294967295)>>>0)+(4294967296<=this.g+a.g?1:0)>>>0)};
D.prototype.sub=function(a){return new D((this.g-a.g&4294967295)>>>0>>>0,((this.h-a.h&4294967295)>>>0)-(0>this.g-a.g?1:0)>>>0)};D.prototype.i=function(){return new D(this.g,this.h)};D.prototype.toString=function(){var a=0!=(this.h&2147483648),b=new C(this.g,this.h);a&&(b=(new C(0,0)).sub(b));return(a?"-":"")+b.toString()};function ob(a){var b=0<a.length&&"-"==a[0];b&&(a=a.substring(1));a=nb(a);if(null===a)return null;b&&(a=(new C(0,0)).sub(a));return new D(a.g,a.h)};function pb(){this.h=new Uint8Array(64);this.g=0}function qb(a,b){if(!(a.g+b<a.h.length)){var c=a.h;a.h=new Uint8Array(Math.ceil(b+2*a.h.length));a.h.set(c)}}f=pb.prototype;f.push=function(a){qb(this,1);this.h[this.g++]=a};f.Eb=function(a){qb(this,a.length);this.h.set(a,this.g);this.g+=a.length};f.length=function(){return this.g};f.end=function(){var a=this.h,b=this.g;this.g=0;return 0===b?$a||($a=new Uint8Array(0)):Za?a.slice(0,b):new Uint8Array(a.subarray(0,b))};
function E(a,b,c){for(;0<c||127<b;)a.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.push(b)}function F(a,b,c){G(a,b);G(a,c)}function rb(a,b,c){gb(b,c,function(d,e){E(a,d>>>0,e>>>0)})}function I(a,b){for(;127<b;)a.push(b&127|128),b>>>=7;a.push(b)}function sb(a,b){if(0<=b)I(a,b);else{for(var c=0;9>c;c++)a.push(b&127|128),b>>=7;a.push(1)}}function tb(a,b){I(a,(b<<1^b>>31)>>>0)}function ub(a,b){fb(hb(b));gb(z,A,function(c,d){E(a,c>>>0,d>>>0)})}f.uf=function(a){this.push(a>>>0&255)};
f.tf=function(a){this.push(a>>>0&255);this.push(a>>>8&255)};function G(a,b){a.push(b>>>0&255);a.push(b>>>8&255);a.push(b>>>16&255);a.push(b>>>24&255)}function vb(a,b){cb(b);G(a,z);G(a,A)}f.te=function(a){this.push(a>>>0&255)};f.se=function(a){this.push(a>>>0&255);this.push(a>>>8&255)};function wb(a,b){a.push(b>>>0&255);a.push(b>>>8&255);a.push(b>>>16&255);a.push(b>>>24&255)}
function xb(a,b){var c=b;c=(b=0>c?1:0)?-c:c;if(0===c)A=0<1/c?0:2147483648,z=0;else if(isNaN(c))A=2147483647,z=4294967295;else if(1.7976931348623157E308<c)A=(b<<31|2146435072)>>>0,z=0;else if(2.2250738585072014E-308>c){var d=c/Math.pow(2,-1074);A=(b<<31|d/4294967296)>>>0;z=d>>>0}else{var e=c;d=0;if(2<=e)for(;2<=e&&1023>d;)d++,e/=2;else for(;1>e&&-1022<d;)e*=2,d--;c*=Math.pow(2,-d);A=(b<<31|d+1023<<20|1048576*c&1048575)>>>0;z=4503599627370496*c>>>0}G(a,z);G(a,A)};function yb(a){yb[" "](a);return a}yb[" "]=Ca;var zb=y("Gecko")&&!(-1!=Ua.toLowerCase().indexOf("webkit")&&!y("Edge"))&&!(y("Trident")||y("MSIE"))&&!y("Edge"),Ab=-1!=Ua.toLowerCase().indexOf("webkit")&&!y("Edge"),Bb=y("Macintosh");Xa();!y("Android")||Ya()||Xa();Ya();!y("Safari")||Ya()||y("Coast")||y("Opera")||y("Edge")||y("Edg/")||y("OPR")||Xa();var Cb={},Db=null;function Eb(a,b){void 0===b&&(b=0);Fb();b=Cb[b];for(var c=Array(Math.floor(a.length/3)),d=b[64]||"",e=0,k=0;e<a.length-2;e+=3){var g=a[e],h=a[e+1],l=a[e+2],m=b[g>>2];g=b[(g&3)<<4|h>>4];h=b[(h&15)<<2|l>>6];l=b[l&63];c[k++]=m+g+h+l}m=0;l=d;switch(a.length-e){case 2:m=a[e+1],l=b[(m&15)<<2]||d;case 1:a=a[e],c[k]=b[a>>2]+b[(a&3)<<4|m>>4]+l+d}return c.join("")}
function jb(a){var b=a.length,c=3*b/4;c%3?c=Math.floor(c):-1!="=.".indexOf(a[b-1])&&(c=-1!="=.".indexOf(a[b-2])?c-2:c-1);var d=new Uint8Array(c),e=0;Gb(a,function(k){d[e++]=k});return d.subarray(0,e)}
function Gb(a,b){function c(l){for(;d<a.length;){var m=a.charAt(d++),q=Db[m];if(null!=q)return q;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return l}Fb();for(var d=0;;){var e=c(-1),k=c(0),g=c(64),h=c(64);if(64===h&&-1===e)break;b(e<<2|k>>4);64!=g&&(b(k<<4&240|g>>2),64!=h&&b(g<<6&192|h))}}
function Fb(){if(!Db){Db={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));Cb[c]=d;for(var e=0;e<d.length;e++){var k=d[e];void 0===Db[k]&&(Db[k]=e)}}}};function Hb(){this.i=[];this.h=0;this.g=new pb}function Ib(a,b){0!==b.length&&(a.i.push(b),a.h+=b.length)}function Jb(a){Ib(a,a.g.end())}function J(a,b){L(a,b,2);Jb(a);return{X:a.h,V:a.i.length-1}}function M(a,b){Jb(a);I(a.g,a.h+a.g.length()-b.X);var c=a.g.end();a.h+=c.length;a.i.splice(1+b.V,0,c)}f=Hb.prototype;f.Od=function(a,b,c){null!=a&&null!=b&&null!=c&&(a=a.subarray(b,c),Jb(this),Ib(this,a))};
function Kb(a){var b=a.h+a.g.length();if(0===b)return new Uint8Array(0);b=new Uint8Array(b);for(var c=a.i,d=c.length,e=0,k=0;k<d;k++){var g=c[k];0!==g.length&&(b.set(g,e),e+=g.length)}c=a.g;d=c.g;0!==d&&(b.set(c.h.subarray(0,d),e),c.g=0);a.i=[b];return b}f.$c=function(a){return Eb(Kb(this),a)};function L(a,b,c){I(a.g,8*b+c)}
f.qe=function(a,b,c){switch(a){case 1:null!=c&&(L(this,b,1),xb(this.g,c));break;case 2:null!=c&&(L(this,b,5),a=this.g,eb(c),G(a,z));break;case 3:null!=c&&null!=c&&(L(this,b,0),a=this.g,B(c),E(a,z,A));break;case 4:null!=c&&null!=c&&(L(this,b,0),a=this.g,B(c),E(a,z,A));break;case 5:null!=c&&null!=c&&(L(this,b,0),sb(this.g,c));break;case 6:null!=c&&(L(this,b,1),vb(this.g,c));break;case 7:null!=c&&(L(this,b,5),G(this.g,c));break;case 8:Lb(this,b,c);break;case 9:N(this,b,c);break;case 12:null!=c&&Mb(this,
b,ib(c));break;case 13:null!=c&&null!=c&&(L(this,b,0),I(this.g,c));break;case 14:Nb(this,b,c);break;case 15:null!=c&&(L(this,b,5),wb(this.g,c));break;case 16:null!=c&&(L(this,b,1),a=this.g,B(c),F(a,z,A));break;case 17:null!=c&&null!=c&&(L(this,b,0),tb(this.g,c));break;case 18:null!=c&&null!=c&&(L(this,b,0),a=this.g,db(c),E(a,z,A))}};f.sf=function(a,b){null!=b&&null!=b&&(L(this,a,0),ub(this.g,b))};function Lb(a,b,c){null!=c&&(L(a,b,0),a.g.push(c?1:0))}
function Nb(a,b,c){null!=c&&(c=parseInt(c,10),L(a,b,0),sb(a.g,c))}
function N(a,b,c){if(null!=c){if(Ja)c=(Ia||(Ia=new TextEncoder)).encode(c);else{var d=void 0;d=void 0===d?!1:d;for(var e=0,k=new Uint8Array(3*c.length),g=0;g<c.length;g++){var h=c.charCodeAt(g);if(128>h)k[e++]=h;else{if(2048>h)k[e++]=h>>6|192;else{if(55296<=h&&57343>=h){if(56319>=h&&g<c.length){var l=c.charCodeAt(++g);if(56320<=l&&57343>=l){h=1024*(h-55296)+l-56320+65536;k[e++]=h>>18|240;k[e++]=h>>12&63|128;k[e++]=h>>6&63|128;k[e++]=h&63|128;continue}else g--}if(d)throw Error("Found an unpaired surrogate");
h=65533}k[e++]=h>>12|224;k[e++]=h>>6&63|128}k[e++]=h&63|128}}c=k.subarray(0,e)}Mb(a,b,c)}}function Mb(a,b,c){L(a,b,2);I(a.g,c.length);Jb(a);Ib(a,c)}f.ue=function(a,b,c){null!=b&&(a=J(this,a),c(b,this),M(this,a))};f.ve=function(a,b,c){null!=b&&(L(this,1,3),L(this,2,0),sb(this.g,a),a=J(this,3),c(b,this),M(this,a),L(this,1,4))};f.re=function(a,b,c){null!=b&&(L(this,a,3),c(b,this),L(this,a,4))};f.af=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,0),sb(this.g,d))}};
f.bf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){L(this,a,0);var e=this.g;B(d);E(e,z,A)}}};f.lf=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var k=c(b[e]),g=d(b[e]);L(this,a,1);F(this.g,k,g)}};f.mf=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var k=c(b[e]),g=d(b[e]);L(this,a,0);E(this.g,k,g)}};f.nf=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var k=c(b[e]),g=d(b[e]);L(this,a,0);rb(this.g,k>>>0,g>>>0)}};
f.cf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=ob(e),L(this,d,0),E(this.g,e.g,e.h))}};f.pf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,0),I(this.g,d))}};f.qf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){L(this,a,0);var e=this.g;B(d);E(e,z,A)}}};f.rf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=nb(e),L(this,d,0),E(this.g,e.g,e.h))}};
f.hf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,0),tb(this.g,d))}};f.jf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){L(this,a,0);var e=this.g;db(d);E(e,z,A)}}};f.kf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,0),ub(this.g,d))}};f.We=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,5),G(this.g,d))}};
f.Xe=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,1),vb(this.g,d))}};f.Ye=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=nb(e),L(this,d,1),F(this.g,e.g,e.h))}};f.ef=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,5),wb(this.g,d))}};f.ff=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){L(this,a,1);var e=this.g;B(d);F(e,z,A)}}};
f.gf=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=ob(e),L(this,d,1),F(this.g,e.g,e.h))}};f.Ze=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){L(this,a,5);var e=this.g;eb(d);G(e,z)}}};f.Ue=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(L(this,a,1),xb(this.g,d))}};f.Se=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Lb(this,a,b[c])};f.Ve=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Nb(this,a,b[c])};
function Ob(a,b,c){if(null!=c)for(var d=0;d<c.length;d++)N(a,b,c[d])}f.Te=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Mb(this,a,ib(d))}};f.df=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++){var e=J(this,a);c(b[d],this);M(this,e)}};f.$e=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++)L(this,a,3),c(b[d],this),L(this,a,4)};f.Ce=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)sb(this.g,b[c]);M(this,a)}};
f.De=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)sb(this.g,parseInt(b[c],10));M(this,a)}};f.Ee=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++){var d=this.g;B(b[c]);E(d,z,A)}M(this,a)}};f.Me=function(a,b,c,d){if(null!=b){a=J(this,a);for(var e=0;e<b.length;e++)F(this.g,c(b[e]),d(b[e]));M(this,a)}};f.Ne=function(a,b,c,d){if(null!=b){a=J(this,a);for(var e=0;e<b.length;e++)E(this.g,c(b[e]),d(b[e]));M(this,a)}};
f.Oe=function(a,b,c,d){if(null!=b){a=J(this,a);for(var e=this.g,k=0;k<b.length;k++)rb(e,c(b[k]),d(b[k]));M(this,a)}};f.Fe=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++){var d=ob(b[c]);E(this.g,d.g,d.h)}M(this,a)}};f.Pe=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)I(this.g,b[c]);M(this,a)}};f.Qe=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++){var d=this.g;B(b[c]);E(d,z,A)}M(this,a)}};
f.Re=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++){var d=nb(b[c]);E(this.g,d.g,d.h)}M(this,a)}};f.Je=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)tb(this.g,b[c]);M(this,a)}};f.Ke=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++){var d=this.g;db(b[c]);E(d,z,A)}M(this,a)}};f.Le=function(a,b){if(null!=b&&b.length){a=J(this,a);for(var c=0;c<b.length;c++)ub(this.g,b[c]);M(this,a)}};
f.ye=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,4*b.length),a=0;a<b.length;a++)G(this.g,b[a])};f.ze=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,8*b.length),a=0;a<b.length;a++)vb(this.g,b[a])};f.Ae=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,8*b.length),a=0;a<b.length;a++){var c=nb(b[a]);F(this.g,c.g,c.h)}};f.Ge=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,4*b.length),a=0;a<b.length;a++)wb(this.g,b[a])};
f.He=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,8*b.length),a=0;a<b.length;a++){var c=this.g;B(b[a]);F(c,z,A)}};f.Ie=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,8*b.length),a=0;a<b.length;a++){var c=this.g;fb(hb(b[a]));F(c,z,A)}};f.Be=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,4*b.length),a=0;a<b.length;a++){var c=this.g;eb(b[a]);G(c,z)}};f.xe=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,8*b.length),a=0;a<b.length;a++)xb(this.g,b[a])};
f.we=function(a,b){if(null!=b&&b.length)for(L(this,a,2),I(this.g,b.length),a=0;a<b.length;a++)this.g.push(b[a]?1:0)};var Pb="function"===typeof Uint8Array;function Qb(a){return Rb(a,function(b){return b},function(b){return new Uint8Array(b)})}function Sb(a,b,c){return"object"===typeof a?Pb&&!Array.isArray(a)&&a instanceof Uint8Array?c(a):Rb(a,b,c):b(a)}function Rb(a,b,c){if(Array.isArray(a)){for(var d=Array(a.length),e=0;e<a.length;e++){var k=a[e];null!=k&&(d[e]=Sb(k,b,c))}Array.isArray(a)&&a.W&&O(d);return d}d={};for(e in a)k=a[e],null!=k&&(d[e]=Sb(k,b,c));return d}
function Tb(a){return Rb(a,function(b){return"number"===typeof b?isFinite(b)?b:String(b):b},function(b){return Eb(b)})}function Ub(a){return Rb(a,function(b){return b},function(b){return new Uint8Array(b)})}var Vb={W:{value:!0,configurable:!0}};function O(a){Array.isArray(a)&&!Object.isFrozen(a)&&Object.defineProperties(a,Vb);return a}var Wb;function Xb(a,b){this.i=a;this.j=b;this.g={};this.h=!0;this.l=null;if(0<this.i.length){for(a=0;a<this.i.length;a++){b=this.i[a];var c=b[0];this.g[c.toString()]=new Yb(c,b[1])}this.h=!0}}f=Xb.prototype;f.isFrozen=function(){return!1};f.Fc=function(){};f.toJSON=function(){var a=this.u(!1);return Wb?a:Tb(a)};f.Gb=function(){return this.toJSON()};
f.u=function(a){if(this.h){if(this.j){var b=this.g,c;for(c in b)if(Object.prototype.hasOwnProperty.call(b,c)){var d=b[c].g;d&&d.u(a)}}}else{this.i.length=0;b=Zb(this);b.sort();for(c=0;c<b.length;c++){d=this.g[b[c]];var e=d.g;e&&e.u(a);this.i.push([d.key,d.value])}this.h=!0}return this.i};f.Wc=function(){return Zb(this).length};f.Fb=function(){this.g={};this.h=!1};f.Kc=function(a){a=a.toString();var b=this.g.hasOwnProperty(a);delete this.g[a];this.h=!1;return b};
f.Uc=function(){var a=[],b=Zb(this);b.sort();for(var c=0;c<b.length;c++){var d=this.g[b[c]];a.push([d.key,d.value])}return a};f.entries=function(){var a=[],b=Zb(this);b.sort();for(var c=0;c<b.length;c++){var d=this.g[b[c]];a.push([d.key,$b(this,d)])}return new ac(a)};f.keys=function(){var a=[],b=Zb(this);b.sort();for(var c=0;c<b.length;c++)a.push(this.g[b[c]].key);return new ac(a)};f.values=function(){var a=[],b=Zb(this);b.sort();for(var c=0;c<b.length;c++)a.push($b(this,this.g[b[c]]));return new ac(a)};
f.forEach=function(a,b){var c=Zb(this);c.sort();for(var d=0;d<c.length;d++){var e=this.g[c[d]];a.call(b,$b(this,e),e.key,this)}};f.set=function(a,b){var c=new Yb(a);this.j?(c.g=b,c.value=b.u(!1)):c.value=b;this.g[a.toString()]=c;this.h=!1;return this};f.fe=function(a,b){this.g[a.toString()]=new Yb(a,b);this.h=!1};function $b(a,b){return a.j?(b.g||(b.g=new a.j(b.value),a.isFrozen()&&null(b.g)),b.g):b.value}f.get=function(a){if(a=this.g[a.toString()])return $b(this,a)};
f.has=function(a){return a.toString()in this.g};function Zb(a){a=a.g;var b=[],c;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b}Xb.prototype[Symbol.iterator]=function(){return this.entries()};function Yb(a,b){this.key=a;this.value=b;this.g=void 0}function ac(a){this.i=0;this.h=a}ac.prototype.next=function(){return this.i<this.h.length?{done:!1,value:this.h[this.i++]}:{done:!0,value:void 0}};ac.prototype[Symbol.iterator]=function(){return this};var bc;function cc(a,b){bc=b;a=new a(b);bc=null;return a};function dc(a,b,c){var d=bc;bc=null;a||(a=d);d=this.constructor.Pd;a||(a=d?[d]:[]);this.l=d?0:-1;this.j=this.g=null;this.i=a;a:{d=this.i.length;a=d-1;if(d&&(d=this.i[a],!(null===d||"object"!=typeof d||Array.isArray(d)||Pb&&d instanceof Uint8Array))){this.m=a-this.l;this.h=d;break a}void 0!==b&&-1<b?(this.m=Math.max(b,a+1-this.l),this.h=null):this.m=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)a=c[b],a<this.m?(a+=this.l,(d=this.i[a])?O(d):this.i[a]=ec):(fc(this),(d=this.h[a])?O(d):this.h[a]=ec)}
var ec=Object.freeze(O([]));function fc(a){var b=a.m+a.l;a.i[b]||(a.h=a.i[b]={})}function P(a,b){if(-1===b)return null;if(b<a.m){b+=a.l;var c=a.i[b];return c!==ec?c:a.i[b]=O([])}if(a.h)return c=a.h[b],c!==ec?c:a.h[b]=O([])}f=dc.prototype;f.xd=function(a){return null!=P(this,a)};f.yd=function(a,b){return gc(this,b)===a};function hc(a,b){a=P(a,b);return null==a?a:+a}function ic(a,b){a=P(a,b);return null==a?a:!!a}
f.wd=function(a){var b=P(this,a);this.j||(this.j={});if(!this.j[a]){for(var c=0;c<b.length;c++)b[c]=+b[c];this.j[a]=!0}return b};f.vd=function(a){var b=P(this,a);this.j||(this.j={});if(!this.j[a]){for(var c=0;c<b.length;c++)b[c]=!!b[c];this.j[a]=!0}return b};function jc(a,b,c){a=P(a,b);return null==a?c:a}function kc(a,b,c){c=void 0===c?!1:c;a=ic(a,b);return null==a?c:a}
f.kd=function(a,b,c){this.g||(this.g={});if(a in this.g)return this.g[a];var d=P(this,a);if(!d){if(b)return;d=O([]);Q(this,a,d)}b=new Xb(d,c);return this.g[a]=b};function Q(a,b,c){b<a.m?a.i[b+a.l]=c:(fc(a),a.h[b]=c);return a}f.jd=function(a){this.g||(this.g={});this.g[a]=void 0;return Q(this,a,void 0)};f.hd=function(a){var b=[];this.g||(this.g={});b=b||[];for(var c=O([]),d=0;d<b.length;d++)c[d]=b[d].u(!1);this.g[a]=b;return Q(this,a,c)};function R(a,b,c,d){c!==d?Q(a,b,c):Q(a,b,void 0);return a}
function lc(a,b,c,d){b=P(a,b);void 0!=d?b.splice(d,0,c):b.push(c);return a}function gc(a,b){for(var c=0,d=0;d<b.length;d++){var e=b[d];null!=P(a,e)&&(0!==c&&Q(a,c,void 0),c=e)}return c}f.zd=function(a,b,c){this.g||(this.g={});var d=c?c.u(!1):c;this.g[a]=c;(b=gc(this,b))&&b!==a&&null!=d&&(this.g&&b in this.g&&(this.g[b]=void 0),Q(this,b,void 0));return Q(this,a,d)};
f.gd=function(a,b,c,d){this.g||(this.g={});if(!this.g[a]){var e=P(this,a);for(var k=[],g=0;g<e.length;g++)k[g]=new c(e[g]);this.g[a]=k}e=this.g[a];b=b?b:new c;a=P(this,a);void 0!=d?(e.splice(d,0,b),a.splice(d,0,b.u(!1))):(e.push(b),a.push(b.u(!1)));return b};f.Ib=function(){return this.toJSON()};f.ne=function(){return this.toJSON()};f.toJSON=function(){var a=this.u(!1);return Wb?a:Tb(a)};f.oe=function(){return Ub(this.u(!1))};
f.u=function(a){if(this.g)for(var b in this.g){var c=this.g[b];if(Array.isArray(c))for(var d=0;d<c.length;d++)c[d]&&c[d].u(a);else c&&c.u(a)}return this.i};function mc(){var a=S.g;Wb=!0;try{return JSON.stringify(a.toJSON(),nc)}finally{Wb=!1}}function nc(a,b){switch(typeof b){case "number":return isFinite(b)?b:String(b);case "object":if(Pb&&null!=b&&b instanceof Uint8Array)return Eb(b)}return b}f.toString=function(){return this.u(!1).toString()};
f.Vd=function(a,b){this.g||(this.g={});fc(this);var c=a.h;a.i?(b=b||[],a.g()?(this.g[c]=b,this.h[c]=O(La(b,function(d){return d.u(!1)}))):this.h[c]=O(b)):a.g()?(this.g[c]=b,this.h[c]=b?b.u(!1):b):this.h[c]=b;return this};f.Hb=function(){var a=this.constructor,b=Qb(this.u(!1));return cc(a,b)};function T(a,b,c){return gc(a,b)===c?c:-1}function U(a,b,c){return jc(a,b,void 0===c?"":c)}f.od=function(a,b,c){return jc(this,T(this,b,a),c)};f.md=function(a,b,c){return kc(this,T(this,b,a),c)};
f.rd=function(a,b,c){a=T(this,b,a);return jc(this,a,void 0===c?0:c)};f.sd=function(a,b,c){a=T(this,b,a);return jc(this,a,void 0===c?"0":c)};f.qd=function(a,b,c){a=T(this,b,a);c=void 0===c?0:c;a=hc(this,a);return null==a?c:a};f.td=function(a,b,c){return U(this,T(this,b,a),c)};f.nd=function(a,b){return P(this,T(this,b,a))};f.ld=function(a,b){return ic(this,T(this,b,a))};f.pd=function(a,b){return hc(this,T(this,b,a))};
f.ud=function(a,b,c){b=T(this,c,b);-1===b?a=null:(this.g||(this.g={}),this.g[b]||(c=P(this,b))&&(this.g[b]=new a(c)),a=this.g[b]);return a};f.Cd=function(a,b){return R(this,a,b,0)};f.Bd=function(a,b){return R(this,a,b,0)};f.Dd=function(a,b){null!=b&&0!==+b?Q(this,a,b):Q(this,a,void 0);return this};f.Ad=function(a,b){null!=b&&0!==b.length?Q(this,a,b):Q(this,a,void 0);return this};function oc(a){dc.call(this,a,-1,pc)}la(oc,dc);f=oc.prototype;f.getTenantId=function(){return jc(this,1,0)};f.ie=function(a){return R(this,1,a,0)};f.getLocale=function(){return U(this,2)};f.Sd=function(a){return R(this,4,a,"")};f.Yd=function(a){return R(this,5,a,"")};f.je=function(a){return R(this,6,a,"")};f.getInsecureHost=function(){return U(this,7)};f.Zd=function(a){return R(this,7,a,"")};f.Vc=function(){return kc(this,8)};f.ae=function(a){return R(this,8,a,!1)};
f.$d=function(a){return R(this,9,a,!1)};f.Qc=function(){return P(this,10)};f.Td=function(a){return Q(this,10,O(a||[]))};f.zc=function(a,b){return lc(this,10,a,b)};f.Gc=function(){return Q(this,10,O([]))};f.be=function(a){return R(this,11,a,!1)};f.he=function(a){return Q(this,12,O(a||[]))};f.Bc=function(a,b){return lc(this,12,a,b)};f.Ic=function(){return Q(this,12,O([]))};f.Wd=function(a){return Q(this,13,O(a||[]))};f.Ac=function(a,b){return lc(this,13,a,b)};f.Hc=function(){return Q(this,13,O([]))};
f.Sc=function(){return U(this,14)};f.Ud=function(a){return R(this,14,a,"")};f.Yc=function(){return U(this,15)};f.ce=function(a){return R(this,15,a,"")};
f.Rd=function(){var a=new Hb;Nb(a,1,P(this,1));N(a,2,P(this,2));N(a,4,P(this,4));N(a,5,P(this,5));N(a,6,P(this,6));N(a,7,P(this,7));Lb(a,8,P(this,8));Lb(a,9,P(this,9));Ob(a,10,P(this,10));Lb(a,11,P(this,11));Ob(a,12,P(this,12));var b=P(this,13);if(null!=b&&b.length){for(var c=J(a,13),d=0;d<b.length;d++)sb(a.g,b[d]);M(a,c)}N(a,14,P(this,14));N(a,15,P(this,15));if(b=this.s)for(Jb(a),c=0;c<b.length;c++)Ib(a,b[c]);return Kb(a)};
function qc(){var a=GoogleDevelopersObject;return cc(oc,a?JSON.parse(a):null)}var pc=[10,12,13];oc.prototype.o=function(a){if(null!=this){var b,c={le:jc(this,1,0),locale:U(this,2),Cc:U(this,4),bd:U(this,5),me:U(this,6),fd:U(this,7),Fd:kc(this,8),Ed:kc(this,9),Ec:null==(b=P(this,10))?void 0:b,Gd:kc(this,11),ke:null==(b=P(this,12))?void 0:b,Nc:null==(b=P(this,13))?void 0:b,Lc:U(this,14),Nd:U(this,15)};a&&(c.Y=this);a=c}else a=void 0;return a};function rc(a){var b=sc,c=void 0;return new (c||(c=Promise))(function(d,e){function k(l){try{h(a.next(l))}catch(m){e(m)}}function g(l){try{h(a["throw"](l))}catch(m){e(m)}}function h(l){l.done?d(l.value):(new c(function(m){m(l.value)})).then(k,g)}h((a=a.apply(b,void 0)).next())})};function tc(a,b){this.h=a[v.Symbol.iterator]();this.i=b;this.j=0}tc.prototype[Symbol.iterator]=function(){return this};tc.prototype.next=function(){var a=this.h.next();return{value:a.done?void 0:this.i.call(void 0,a.value,this.j++),done:a.done}};function uc(a,b){return new tc(a,b)};var vc="StopIteration"in v?v.StopIteration:{message:"StopIteration",stack:""};function wc(){}wc.prototype.next=function(){return wc.prototype.g.call(this)};wc.prototype.g=function(){throw vc;};wc.prototype.G=function(){return this};function xc(a){if(a instanceof V||a instanceof W||a instanceof yc)return a;if("function"==typeof a.next)return new V(function(){return zc(a)});if("function"==typeof a[Symbol.iterator])return new V(function(){return a[Symbol.iterator]()});if("function"==typeof a.G)return new V(function(){return zc(a.G())});throw Error("Not an iterator or iterable.");}
function zc(a){if(!(a instanceof wc))return a;var b=!1;return{next:function(){for(var c;!b;)try{c=a.g();break}catch(d){if(d!==vc)throw d;b=!0}return{value:c,done:b}}}}function V(a){this.h=a}V.prototype.G=function(){return new W(this.h())};V.prototype.l=function(){return new W(this.h())};V.prototype[Symbol.iterator]=function(){return new yc(this.h())};V.prototype.i=function(){return new yc(this.h())};function W(a){this.h=a}la(W,wc);W.prototype.g=function(){var a=this.h.next();if(a.done)throw vc;return a.value};
W.prototype.next=function(){return W.prototype.g.call(this)};W.prototype.l=function(){return this};W.prototype[Symbol.iterator]=function(){return new yc(this.h)};W.prototype.i=function(){return new yc(this.h)};function yc(a){V.call(this,function(){return a});this.j=a}la(yc,V);yc.prototype.next=function(){return this.j.next()};function Ac(a,b){this.h={};this.g=[];this.i=this.size=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof Ac)for(c=a.C(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}f=Ac.prototype;f.A=function(){Bc(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.h[this.g[b]]);return a};f.C=function(){Bc(this);return this.g.concat()};
f.has=function(a){return Cc(this.h,a)};f.Kb=function(a){for(var b=0;b<this.g.length;b++){var c=this.g[b];if(Cc(this.h,c)&&this.h[c]==a)return!0}return!1};f.Lb=function(a,b){if(this===a)return!0;if(this.size!=a.size)return!1;b=b||Dc;Bc(this);for(var c,d=0;c=this.g[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function Dc(a,b){return a===b}f.Mb=function(){return 0==this.size};f.Jb=function(){this.h={};this.i=this.size=this.g.length=0};
function Bc(a){if(a.size!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];Cc(a.h,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.size!=a.g.length){var e={};for(c=b=0;b<a.g.length;)d=a.g[b],Cc(e,d)||(a.g[c++]=d,e[d]=1),b++;a.g.length=c}}f.get=function(a,b){return Cc(this.h,a)?this.h[a]:b};f.set=function(a,b){Cc(this.h,a)||(this.size+=1,this.g.push(a),this.i++);this.h[a]=b};f.forEach=function(a,b){for(var c=this.C(),d=0;d<c.length;d++){var e=c[d],k=this.get(e);a.call(b,k,e,this)}};
f.pe=function(){for(var a=new Ac,b=0;b<this.g.length;b++){var c=this.g[b];a.set(this.h[c],c)}return a};f.Nb=function(){Bc(this);for(var a={},b=0;b<this.g.length;b++){var c=this.g[b];a[c]=this.h[c]}return a};f.keys=function(){return xc(this.G(!0)).i()};f.values=function(){return xc(this.G(!1)).i()};f.entries=function(){var a=this;return uc(this.keys(),function(b){return[b,a.get(b)]})};
f.G=function(a){Bc(this);var b=0,c=this.i,d=this,e=new wc;e.g=function(){if(c!=d.i)throw Error("The map has changed since the iterator was created");if(b>=d.g.length)throw vc;var k=d.g[b++];return a?k:d.h[k]};e.next=e.g.bind(e);return e};function Cc(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Ec(a){if(a.A&&"function"==typeof a.A)return a.A();if("undefined"!==typeof Map&&a instanceof Map||"undefined"!==typeof Set&&a instanceof Set)return Array.from(a.values());if("string"===typeof a)return a.split("");if(Da(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function Fc(a){if(a.C&&"function"==typeof a.C)return a.C();if(!a.A||"function"!=typeof a.A){if("undefined"!==typeof Map&&a instanceof Map)return Array.from(a.keys());if(!("undefined"!==typeof Set&&a instanceof Set)){if(Da(a)||"string"===typeof a){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}b=[];c=0;for(var d in a)b[c++]=d;return b}}}
function Gc(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(Da(a)||"string"===typeof a)Array.prototype.forEach.call(a,b,c);else for(var d=Fc(a),e=Ec(a),k=e.length,g=0;g<k;g++)b.call(c,e[g],d&&d[g],a)};var Hc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Ic(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var k=a[c].substring(0,d);e=a[c].substring(d+1)}else k=a[c];b(k,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function Jc(a,b){this.h=this.s=this.m="";this.j=null;this.o=this.i="";this.l=this.F=!1;if(a instanceof Jc){this.l=void 0!==b?b:a.l;Kc(this,a.m);var c=a.s;X(this);this.s=c;c=a.h;X(this);this.h=c;Lc(this,a.j);c=a.i;X(this);this.i=c;Mc(this,Nc(a.g));a=a.o;X(this);this.o=a}else a&&(c=String(a).match(Hc))?(this.l=!!b,Kc(this,c[1]||"",!0),a=c[2]||"",X(this),this.s=Oc(a),a=c[3]||"",X(this),this.h=Oc(a,!0),Lc(this,c[4]),a=c[5]||"",X(this),this.i=Oc(a,!0),Mc(this,c[6]||"",!0),a=c[7]||"",X(this),this.o=Oc(a)):
(this.l=!!b,this.g=new Pc(null,this.l))}f=Jc.prototype;f.toString=function(){var a=[],b=this.m;b&&a.push(Qc(b,Rc,!0),":");var c=this.h;if(c||"file"==b)a.push("//"),(b=this.s)&&a.push(Qc(b,Rc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.j,null!=c&&a.push(":",String(c));if(c=this.i)this.h&&"/"!=c.charAt(0)&&a.push("/"),a.push(Qc(c,"/"==c.charAt(0)?Sc:Tc,!0));(c=this.g.toString())&&a.push("?",c);(c=this.o)&&a.push("#",Qc(c,Uc));return a.join("")};
f.resolve=function(a){var b=new Jc(this),c=!!a.m;c?Kc(b,a.m):c=!!a.s;if(c){var d=a.s;X(b);b.s=d}else c=!!a.h;c?(d=a.h,X(b),b.h=d):c=null!=a.j;d=a.i;if(c)Lc(b,a.j);else if(c=!!a.i){if("/"!=d.charAt(0))if(this.h&&!this.i)d="/"+d;else{var e=b.i.lastIndexOf("/");-1!=e&&(d=b.i.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var k=[],g=0;g<e.length;){var h=e[g++];"."==h?d&&g==e.length&&k.push(""):".."==h?((1<k.length||
1==k.length&&""!=k[0])&&k.pop(),d&&g==e.length&&k.push("")):(k.push(h),d=!0)}d=k.join("/")}else d=e}c?(X(b),b.i=d):c=""!==a.g.toString();c?Mc(b,Nc(a.g)):c=!!a.o;c&&(a=a.o,X(b),b.o=a);return b};function Kc(a,b,c){X(a);a.m=c?Oc(b,!0):b;a.m&&(a.m=a.m.replace(/:$/,""))}function Lc(a,b){X(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.j=b}else a.j=null}function Mc(a,b,c){X(a);b instanceof Pc?(a.g=b,Vc(a.g,a.l)):(c||(b=Qc(b,Wc)),a.g=new Pc(b,a.l));return a}
f.ee=function(a,b){return Mc(this,a,b)};f.Rc=function(){return Oc(this.g.toString())};f.Ob=function(){return this.g.toString()};f.de=function(a,b){X(this);Array.isArray(b)||(b=[String(b)]);Xc(this.g,a,b);return this};f.Zc=function(a){return this.g.A(a)};f.cd=function(a){return(!this.h&&!a.h||this.h==a.h)&&(null==this.j&&null==a.j||this.j==a.j)};
f.Md=function(){X(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Date.now()).toString(36);X(this);this.g.set("zx",a);return this};f.Pb=function(a){X(this);Yc(this.g,a);return this};f.ge=function(a){this.F=a;return this};f.Hd=function(){return this.F};function X(a){if(a.F)throw Error("Tried to modify a read-only Uri");}f.Qb=function(a){this.l=a;this.g&&Vc(this.g,a);return this};
function Zc(a){return a instanceof Jc?new Jc(a):new Jc(a,void 0)}function Oc(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function Qc(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,$c),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function $c(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Rc=/[#\/\?@]/g,Tc=/[#\?:]/g,Sc=/[#\?]/g,Wc=/[#\?@]/g,Uc=/#/g;function Pc(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b}
function Y(a){a.g||(a.g=new Ac,a.h=0,a.i&&Ic(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}f=Pc.prototype;f.Ub=function(){Y(this);return this.h};f.add=function(a,b){Y(this);this.i=null;a=ad(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};function Yc(a,b){Y(a);b=ad(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a=a.g,Cc(a.h,b)&&(delete a.h[b],--a.size,a.i++,a.g.length>2*a.size&&Bc(a)))}f.Rb=function(){this.g=this.i=null;this.h=0};
f.Vb=function(){Y(this);return 0==this.h};function bd(a,b){Y(a);b=ad(a,b);return a.g.has(b)}f.Sb=function(a){var b=this.A();return 0<=Ka(b,a)};f.forEach=function(a,b){Y(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};f.C=function(){Y(this);for(var a=this.g.A(),b=this.g.C(),c=[],d=0;d<b.length;d++)for(var e=a[d],k=0;k<e.length;k++)c.push(b[d]);return c};
f.A=function(a){Y(this);var b=[];if("string"===typeof a)bd(this,a)&&(b=b.concat(this.g.get(ad(this,a))));else{a=this.g.A();for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};f.set=function(a,b){Y(this);this.i=null;a=ad(this,a);bd(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};f.get=function(a,b){if(!a)return b;a=this.A(a);return 0<a.length?String(a[0]):b};
function Xc(a,b,c){Yc(a,b);if(0<c.length){a.i=null;var d=a.g,e=d.set;b=ad(a,b);var k=c.length;if(0<k){for(var g=Array(k),h=0;h<k;h++)g[h]=c[h];k=g}else k=[];e.call(d,b,k);a.h+=c.length}}f.toString=function(){if(this.i)return this.i;if(!this.g)return"";for(var a=[],b=this.g.C(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.A(d);for(var k=0;k<d.length;k++){var g=e;""!==d[k]&&(g+="="+encodeURIComponent(String(d[k])));a.push(g)}}return this.i=a.join("&")};
f.Oc=function(a){Y(this);this.g.forEach(function(b,c){0<=Ka(a,c)||Yc(this,c)},this);return this};function Nc(a){var b=new Pc;b.i=a.i;a.g&&(b.g=new Ac(a.g),b.h=a.h);return b}function ad(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b}function Vc(a,b){b&&!a.j&&(Y(a),a.i=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Yc(this,d),Xc(this,e,c))},a));a.j=b}f.Tb=function(a){for(var b=0;b<arguments.length;b++)Gc(arguments[b],function(c,d){this.add(d,c)},this)};var cd={};function dd(a,b){var c=cd[a];if(void 0!==c&&(!c.M||Date.now()<=c.M+3E5))return c.p;c=new Promise(function(e,k){b.onload=function(){return e(b)};b.onerror=function(g){b.parentNode&&b.parentNode.removeChild(b);k(g)};document.head.appendChild(b)});var d={M:0,p:c};c.catch(function(){return d.M=+new Date});cd[a]=d;return c}
function ed(a){var b=void 0===b?null:b;a=Zc(a);var c=document.createElement("script"),d=Sa(a.toString());c.src=Ra(d);var e;d=(c.ownerDocument&&c.ownerDocument.defaultView||window).document;var k=null===(e=d.querySelector)||void 0===e?void 0:e.call(d,"script[nonce]");(e=k?k.nonce||k.getAttribute("nonce")||"":"")&&c.setAttribute("nonce",e);b&&(c.type=b);return dd(a.toString(),c)};function fd(a,b){this.type=a;this.i=this.target=b;this.m=this.l=!1}fd.prototype.O=function(){return this.l};fd.prototype.j=function(){this.l=!0};fd.prototype.h=function(){this.m=!0};var gd=function(){if(!v.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{v.addEventListener("test",Ca,b),v.removeEventListener("test",Ca,b)}catch(c){}return a}();function Z(a,b){fd.call(this,a?a.type:"");this.relatedTarget=this.i=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.N=this.F=0;this.key="";this.o=this.s=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.J=!1;this.pointerId=0;this.pointerType="";this.g=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.i=b;if(b=a.relatedTarget){if(zb){a:{try{yb(b.nodeName);
var e=!0;break a}catch(k){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.F=Ab||void 0!==a.offsetX?a.offsetX:a.layerX,this.N=Ab||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.s=a.keyCode||0;this.key=a.key||"";this.o=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.J=Bb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:hd[a.pointerType]||"";this.state=a.state;this.g=a;a.defaultPrevented&&Z.I.h.call(this)}}Fa(Z,fd);var hd={2:"touch",3:"pen",4:"mouse"};
Z.prototype.P=function(){return 0==this.g.button&&!(Bb&&this.ctrlKey)};Z.prototype.j=function(){Z.I.j.call(this);this.g.stopPropagation?this.g.stopPropagation():this.g.cancelBubble=!0};Z.prototype.h=function(){Z.I.h.call(this);var a=this.g;a.preventDefault?a.preventDefault():a.returnValue=!1};var id="closure_listenable_"+(1E6*Math.random()|0);var jd=0;function kd(a,b,c,d,e){this.listener=a;this.g=null;this.src=b;this.type=c;this.capture=!!d;this.i=e;this.key=++jd;this.h=this.L=!1}function ld(a){a.h=!0;a.listener=null;a.g=null;a.src=null;a.i=null};function md(a){this.src=a;this.g={};this.h=0}f=md.prototype;f.Xc=function(){var a=0,b;for(b in this.g)a+=this.g[b].length;return a};f.add=function(a,b,c,d,e){var k=a.toString();a=this.g[k];a||(a=this.g[k]=[],this.h++);var g=nd(a,b,d,e);-1<g?(b=a[g],c||(b.L=!1)):(b=new kd(b,this.src,k,!!d,e),b.L=c,a.push(b));return b};
f.Zb=function(a,b,c,d){a=a.toString();if(!(a in this.g))return!1;var e=this.g[a];b=nd(e,b,c,d);return-1<b?(ld(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.g[a],this.h--),!0):!1};f.Qd=function(a){a=a&&a.toString();var b=0,c;for(c in this.g)if(!a||c==a){for(var d=this.g[c],e=0;e<d.length;e++)++b,ld(d[e]);delete this.g[c];this.h--}return b};f.Xb=function(a,b){a=this.g[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
f.Wb=function(a,b,c,d){a=this.g[a.toString()];var e=-1;a&&(e=nd(a,b,c,d));return-1<e?a[e]:null};f.Yb=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Ma(this.g,function(k){for(var g=0;g<k.length;++g)if(!(c&&k[g].type!=d||e&&k[g].capture!=b))return!0;return!1})};function nd(a,b,c,d){for(var e=0;e<a.length;++e){var k=a[e];if(!k.h&&k.listener==b&&k.capture==!!c&&k.i==d)return e}return-1};var od="closure_lm_"+(1E6*Math.random()|0),pd={},qd=0;function rd(a,b,c,d,e){if(d&&d.once)return sd(a,b,c,d,e);if(Array.isArray(b)){for(var k=0;k<b.length;k++)rd(a,b[k],c,d,e);return null}c=td(c);return a&&a[id]?a.g(b,c,Ea(d)?!!d.capture:!!d,e):ud(a,b,c,!1,d,e)}
function ud(a,b,c,d,e,k){if(!b)throw Error("Invalid event type");var g=Ea(e)?!!e.capture:!!e,h=vd(a);h||(a[od]=h=new md(a));c=h.add(b,c,d,g,k);if(c.g)return c;d=wd();c.g=d;d.src=a;d.listener=c;if(a.addEventListener)gd||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(xd(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");qd++;return c}
function wd(){function a(c){return b.call(a.src,a.listener,c)}var b=yd;return a}function sd(a,b,c,d,e){if(Array.isArray(b)){for(var k=0;k<b.length;k++)sd(a,b[k],c,d,e);return null}c=td(c);return a&&a[id]?a.h(b,c,Ea(d)?!!d.capture:!!d,e):ud(a,b,c,!0,d,e)}
function zd(a){if("number"!==typeof a&&a&&!a.h){var b=a.src;if(b&&b[id])b.i(a);else{var c=a.type,d=a.g;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(xd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);qd--;if(c=vd(b)){d=a.type;if(d in c.g){var e=c.g[d],k=Ka(e,a),g;(g=0<=k)&&Array.prototype.splice.call(e,k,1);g&&(ld(a),0==c.g[d].length&&(delete c.g[d],c.h--))}0==c.h&&(c.src=null,b[od]=null)}else ld(a)}}}
function xd(a){return a in pd?pd[a]:pd[a]="on"+a}function yd(a,b){if(a.h)a=!0;else{b=new Z(b,this);var c=a.listener,d=a.i||a.src;a.L&&zd(a);a=c.call(d,b)}return a}function vd(a){a=a[od];return a instanceof md?a:null}var Ad="__closure_events_fn_"+(1E9*Math.random()>>>0);function td(a){if("function"===typeof a)return a;a[Ad]||(a[Ad]=function(b){return a.handleEvent(b)});return a[Ad]};function Bd(){var a=this;this.promise=new Promise(function(b,c){a.resolve=b;a.reject=c})};function Cd(){var a=this;this.h=null;this.g=new oc;this.j=[];this.l=this.i=null;if(v.__globalAppLoader)return v.__globalAppLoader;try{this.g=qc()}catch(b){Dd("GoogleDevelopersObject missing or invalid")}GoogleDevelopersObject=null;w("__globalAppLoader",this);w("DevsiteApp.hasFlagAccess",function(b){return a.hasFlagAccess(b)})}Cd.prototype.m=function(){v.__globalAppLoader=null;zd(this.i);zd(this.l)};
function Ed(a){var b=[];b.push(ed("https://www.gstatic.com/external_hosted/polymer/v2/webcomponents-lite.js"));"fetch"in window&&"URL"in window||b.push(ed(U(a.g,5)+"/js/polyfills.js"));return Promise.all(b)}function Fd(a){var b=a.g.getLocale();a=U(a.g,4);return b&&"en"!==b?a.replace(/\.js$/,"__"+b.toLowerCase().replace("-","_")+".js"):a}
Cd.prototype.getEnv=function(){if(kc(this.g,11))return"PROD";var a=document.location.hostname;return a.endsWith("test.devsite.corp.google.com")||a.endsWith("test.devsite-v2-staging.googleplex.com")?"TEST":a.endsWith(".devsite.corp.google.com")||a.endsWith("devsite-v2-staging.googleplex.com")?"STAGE":"DEV"};
Cd.prototype.hasFlagAccess=function(a){a:{var b=this.getEnv(),c=P(this.g,13),d=new URL(document.location.toString());d=new Jc(d.href);var e=Object.keys(Ha);if("PROD"!==b)for(b=r(e),e=b.next();!e.done;e=b.next())if(e=e.value,Ha[e]===a&&(e=d.g.get(e),void 0!==e)){if("true"===e){a=!0;break a}if("false"===e){a=!1;break a}}a=Array.from(c).includes(a)}return a};
function Gd(){return rc(function b(){var c=this,d,e,k,g,h,l,m,q;return za(b,function(u){switch(u.g){case 1:return u.i=2,qa(u,Ed(c),4);case 4:ra(u,3);break;case 2:d=sa(u),Dd("Failed to load Devsite App dependencies: "+d.message);case 3:e=new Bd;w("__devsiteAppReadyResolver",e.resolve);w("__devsiteAppReadyPromise",e.promise);w("DevsiteApp.whenReady",function(){return e.promise});if(!P(c.g,12).length){u.D(5);break}u.i=6;return qa(u,Promise.all(P(c.g,12).map(function(H){H=Zc(H);var K=document.createElement("link");
K.setAttribute("rel","stylesheet");K.setAttribute("type","text/css");K.setAttribute("href",H.toString());return dd(H.toString(),K)})),8);case 8:ra(u,5);break;case 6:k=sa(u),Dd("Failed to load Devsite App dependencies: "+k.message);case 5:return g=v.DevsiteAppTenantCustomized?U(c.g,6):U(c.g,5),u.i=9,qa(u,ed(g+Fd(c)),11);case 11:ra(u,10);break;case 9:h=sa(u);if("en"===c.g.getLocale()){Dd("Failed to load Devsite App binary: "+h.message);u.D(10);break}R(c.g,2,"en","");u.i=13;return qa(u,ed(g+U(c.g,4)),
15);case 15:ra(u,10);break;case 13:l=sa(u),Dd("Failed to load Devsite App binary: "+l.message);case 10:if(m=document,"complete"===m.readyState||"interactive"===m.readyState)u.D(0);else return q=new Bd,m.addEventListener("readystatechange",function(){"interactive"!==m.readyState&&"complete"!==m.readyState||q.resolve()}),qa(u,q.promise,0)}})})}function Dd(a){throw Error(void 0===a?"Devsite has failed to load.":a);};var S=new Cd;(function(){var a=document.querySelector("devsite-content");a&&(S.i=rd(window,"message",function(b){S.j.push(b)}),S.l=sd(a,"devsite-content-updated",function(){zd(S.i);for(var b=r(S.j),c=b.next();!c.done;c=b.next())(c=c.value.g)&&window.dispatchEvent(c);S.j=[];zd(S.l)}))})();var Hd;var sc=S,Id=window;"WeakMap"in Id&&"performance"in Id&&"now"in Id.performance?(sc.h||(sc.h=Gd()),Hd=sc.h):Hd=Promise.resolve();
Hd.then(function(){v.DevsiteAppInit||Dd("Failed to load Devsite App binary");kc(S.g,9)?DevsiteAppFrameboxInit(mc(),v.DevsiteAppAuthorizedElements):DevsiteAppInit(mc(),v.DevsiteAppAuthorizedElements)});}).call(this);
