(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var FX=function(a,b){CX()&&(b=DX()?"translate3d("+b+"px,0px,0px)":"translate("+b+"px,0px)",_ds.Wn(a,EX(),b))},IX=function(){var a=_ds.R.call(this)||this;a.M=-1;a.o=new _ds.Ll;a.J=new _ds.Ll;a.F=0;a.K=new MutationObserver(function(){return GX(a)});a.V=new _ds.Qn(function(){GX(a);HX(a)},15);a.C=0;a.j=0;a.D=0;a.m=0;a.G=!1;return a},KX=function(a){a.o.listen(a,"devsite-search-toggle",function(b){b=b.ma;_ds.ul(b.target,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",
""):a.removeAttribute("search-active"))});a.o.listen(document.body,"devsite-sitemask-hidden",function(){return document.body.removeAttribute("devsite-book-nav--open")});a.o.listen(window,"resize",function(){return JX(a)});a.o.listen(document.body,["devsite-page-loaded","devsite-content-updated"],function(){JX(a)});a.o.listen(a,"click",function(b){b.defaultPrevented||"devsite-hamburger-menu"!=b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",
""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})))})},JX=function(a){window.requestAnimationFrame(function(){return a.V.Aa()})},LX=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},GX=function(a){a.C=LX(a,".devsite-top-logo-row-wrapper-wrapper");a.j=LX(a,".devsite-collapsible-section");a.D=LX(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",a.C);a.setAttribute("bottom-row--height",a.j);a.setAttribute("bottom-tabs--height",a.D);document.body.style.setProperty("--devsite-js-header-top-row-height",
a.C+"px");document.body.style.setProperty("--devsite-js-header-lower-section-height",a.j+"px");document.body.style.setProperty("--devsite-js-header-lower-tabs-height",a.D+"px");document.body.style.setProperty("--devsite-js-header-height",a.Hh()+"px");MX(a)},NX=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){var b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity=1;a.appendChild(b)}},MX=function(a){var b=
a.querySelector(".devsite-collapsible-section");a.m>=a.j&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.m<a.j-a.D&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.m!==a.M&&(document.body.style.setProperty("--devsite-js-header-lower-tabs-offset",a.m+"px"),_ds.Wn(b,"transform","translate3d(0, -"+a.m+"px, 0)"),HX(a),a.M=a.m)},OX=function(a){var b=a.querySelector(".devsite-top-logo-row-middle"),c=a.querySelector("devsite-search"),d=
a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.Rl(a.J);a.F&&window.cancelAnimationFrame(a.F);c.removeAttribute("transition");a.removeAttribute("search-expanded");var e=new _ds.mk(b.offsetWidth,b.offsetHeight);b=new _ds.mk(c.offsetWidth,c.offsetHeight);var g=_ds.no(c,"margin"),h="rtl"===document.documentElement.getAttribute("dir")?1:-1,k=(e.width-g.left-g.right)/b.width;e=(e.width-(b.width+g.left+g.right))*h;var l=(g=a.hasAttribute("search-active"))?e:0,m=g?k:1;_ds.Wn(d,{opacity:1,width:b.width+
"px",height:b.height+"px"});FX(c,a.hasAttribute("search-active")?0:e);_ds.Pl(a.J,d,_ds.hm,function(){var p=a.querySelector("devsite-search"),q=a.querySelector(".devsite-search-background");q&&(q.style.opacity=0);p&&(p.removeAttribute("transition"),FX(p,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.F=window.requestAnimationFrame(function(){c.setAttribute("transition","");if(CX()){var p=DX()?"scale3d("+m+",1,1)":"scale("+m+",1)";_ds.Wn(d,
EX(),p)}FX(c,l)})}},PX=function(a,b){var c,d,e,g;_ds.cb(function(h){if(1==h.h){if(!a.hasAttribute("billboard"))return h.return();c=a.querySelector("devsite-search");d=a.querySelector("devsite-search input.devsite-search-query");e=a.querySelector(".devsite-header-billboard-search devsite-search");g=e.querySelector("input.devsite-search-query");if(!b)return e.removeAttribute("disabled"),document.activeElement===d&&g.focus(),c.setAttribute("disabled",""),h.H(0);c.removeAttribute("disabled");return document.activeElement!==
g?h.H(3):_ds.y(h,_ds.Jm(),4)}3!=h.h&&d.focus();e.setAttribute("disabled","");_ds.z(h)})},HX=function(a){0===a.j?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},QX=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},
RX=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.G=!0,_ds.ii(a,c,b))};var CX=_ds.Hb(function(){return!_ds.Dk||0<=_ds.Jc(_ds.pN,9)}),DX=_ds.Hb(function(){return _ds.Fk||_ds.YB||_ds.Yn&&0<=_ds.Jc(_ds.pN,10)||_ds.Dk&&0<=_ds.Jc(_ds.pN,10)}),EX=_ds.Hb(function(){return _ds.Dk&&9==_ds.eo?"-ms-transform":"transform"});_ds.w(IX,_ds.R);_ds.f=IX.prototype;_ds.f.attributeChangedCallback=function(a,b,c){switch(a){case "offset":this.m=parseFloat(this.getAttribute("offset"))||0;MX(this);break;case "search-active":OX(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),PX(this,a)}};
_ds.f.connectedCallback=function(){KX(this);NX(this);HX(this);GX(this);this.K.observe(this,{childList:!0,subtree:!0});MX(this);var a=_ds.qm();this.L=_ds.hj(_ds.jj(a.href),"authuser")};_ds.f.disconnectedCallback=function(){_ds.Rl(this.o);this.K.disconnect()};_ds.f.Hh=function(){return this.C+this.j-this.m};_ds.f.Zp=function(){return this.C+this.j};
_ds.f.Ya=function(a){this.G=!1;if(a){RX(this,a,".devsite-header-upper-tabs");RX(this,a,".devsite-collapsible-section");RX(this,a,".devsite-product-name-wrapper");RX(this,a,"devsite-language-selector");RX(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&QX(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(QX(c,b),c=_ds.qm(),c=_ds.hj(_ds.jj(c.href),"authuser"),c!==this.L&&(this.L=c,b.refresh()));
_ds.ii(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));_ds.ii(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.G&&a&&(_ds.Nk(this),this.appendChild(a));NX(this);JX(this)};_ds.n.Object.defineProperties(IX,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["offset","search-active","bottom-row--hidden"]}}});
IX.prototype.updateContent=IX.prototype.Ya;IX.prototype.disconnectedCallback=IX.prototype.disconnectedCallback;IX.prototype.connectedCallback=IX.prototype.connectedCallback;IX.prototype.attributeChangedCallback=IX.prototype.attributeChangedCallback;try{window.customElements.define("devsite-header",IX)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
