(function(_ds){var window=this;'use strict';var cR=function(a,b){a.href=_ds.bi(b)},dR=function(){return(0,_ds.T)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},eR=function(){return(0,_ds.T)('<div class="devsite-book-nav-blur"></div>')},gR=function(){var a=_ds.R.call(this)||this;a.o=!1;a.m=null;a.eventHandler=new _ds.Ll;a.G=function(){};a.C=new Set;a.J=!1;a.background=document.createElement("div");a.background.classList.add("devsite-book-nav-bg");
a.j=_ds.Al(dR);a.D=_ds.Al(eR);a.K=new Promise(function(b){a.G=b});a.F=new _ds.Qn(function(){a.o&&fR(a)},20);return a},iR=function(a,b,c){c=void 0===c?!0:c;b=Array.from((void 0===b?a:b).querySelectorAll(".devsite-nav-title"));a.C=new Set(b);if(!_ds.qm().hash&&c)hR(a,a.C);else for(c=new _ds.VE,a=_ds.r(a.C),b=a.next();!b.done;b=a.next())_ds.XE(c,b.value)},hR=function(a,b){_ds.Q(a,function d(){var e=this,g,h,k,l,m,p,q;return _ds.D(d,function(t){if(1==t.h)return g=e,e.o?_ds.y(t,(0,_ds.Kp)(),2):t.return();
h=t.j;k=new _ds.VE;l=function(u){u=u.target;_ds.XE(k,u);g.C.delete(u);h.unregisterIntersectionForElement(u)};m=_ds.r(b);for(p=m.next();!p.done;p=m.next()){q=p.value;try{h.registerIntersectionForElement(q,l)}catch(u){l({target:q})}}_ds.z(t)})})},fR=function(a){var b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.hi(a,"visually-hidden","",c))},nR=function(a){a.eventHandler.listen(a,"click",function(b){var c;
if(!b.defaultPrevented){var d=b.target;"devsite-close-nav"===d.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.hi(a,"top-level-nav",""));if(d.hasAttribute("menu")){var e=d.getAttribute("menu");e&&jR(a,e)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}if(!(d.classList.contains("devsite-nav-toggle")||d.classList.contains("devsite-nav-title-no-path")||
(null===(c=d.parentElement)||void 0===c?0:c.classList.contains("devsite-nav-title-no-path")))){a.m&&(b=a.m.querySelector("[menu=_book]"))&&b.contains(d)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}));var g;d instanceof Element&&d.matches("a.devsite-nav-title")?g=d:g=_ds.tl(d,"a","devsite-nav-title");g&&!g.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}))}}});a.eventHandler.listen(a,[kR,"focusin"],function(b){return void lR(a,
b)});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",function(){a.m&&(jR(a,"_book")?a.removeAttribute("top-level-nav"):_ds.hi(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",function(){return void a.F.Aa()});a.eventHandler.listen(a,"devsite-content-updated",function(){a.F.Aa()});a.eventHandler.listen(a,"scroll",function(){_ds.hi(a,"user-scrolled","")});a.eventHandler.listen(a.j,"click",function(){mR(a)})},jR=function(a,b){var c=!1;if(a.m)for(var d=
_ds.r(a.m.querySelectorAll("[menu]")),e=d.next();!e.done;e=d.next())e=e.value,e.getAttribute("menu")===b?(e.removeAttribute("hidden"),c=!0):_ds.hi(a,"hidden","",e);return c},lR=function(a,b){b.defaultPrevented||(b=_ds.sl(b.target,function(c){return c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a},!0),b!==a&&cR(b,_ds.ip(_ds.ym(b.href).href)))},pR=function(a){return _ds.Q(a,function c(){var d=this;return _ds.D(c,function(e){switch(e.h){case 1:if(!d.o)return e.return();d.removeAttribute("user-scrolled");
return _ds.y(e,_ds.Jm(),2);case 2:return _ds.y(e,oR(d),3);case 3:return _ds.y(e,d.K,4);case 4:return _ds.y(e,(0,_ds.Kp)(),5);case 5:return _ds.y(e,_ds.Jm(),6);case 6:return _ds.y(e,oR(d),0)}})})},qR=function(a,b){(b=void 0===b?a:b)||(b=a);var c=_ds.r(b.querySelectorAll(".devsite-nav-active"));for(a=c.next();!a.done;a=c.next())a.value.classList.remove("devsite-nav-active");a=_ds.Om(_ds.qm().pathname);a='[href="'+_ds.ym(a).href+'"], [href="'+a+'"],\n        [alt-paths~="'+a+'"]';b=_ds.r(b.querySelectorAll(a));
for(a=b.next();!a.done;a=b.next())a.value.classList.add("devsite-nav-active")},rR=function(a,b){(b=void 0===b?a:b)||(b=a);var c=b.querySelector(".devsite-mobile-nav-bottom");if(c)for(var d=c.querySelector(".devsite-nav-active");d&&d.parentElement&&d.parentElement!==b;)d.hasAttribute("collapsed")&&(d.removeAttribute("animatable"),_ds.Pl(a.eventHandler,d,"devsite-expandable-nav-transition-end",function(){d&&_ds.hi(a,"animatable","",d)}),d.removeAttribute("collapsed")),d=d.parentElement},oR=function(a){return _ds.Q(a,
function c(){var d=this,e;return _ds.D(c,function(g){if(1==g.h)return d.o&&d.m?_ds.y(g,(0,_ds.Kp)(),2):g.return();if(4!=g.h)return(e=d.m.querySelector(".devsite-nav-active"))?d.hasAttribute("user-scrolled")?g.H(4):_ds.y(g,sR(d,e),4):g.H(0);_ds.hi(d,"animatable","");_ds.z(g)})})},sR=function(a,b){return _ds.Q(a,function d(){var e=this,g,h;return _ds.D(d,function(k){if(1==k.h){if(!e.o)return k.return();g=e.hasAttribute("user-scrolled");h=_ds.go(b,e,!0);e.scrollTop=h.y;return _ds.y(k,_ds.Jm(),2)}g&&
_ds.hi(e,"user-scrolled","");_ds.z(k)})})},tR=function(a){return _ds.Q(a,function c(){var d,e=this,g,h,k;return _ds.D(c,function(l){if(1==l.h)return _ds.y(l,(0,_ds.Kp)(),2);d=l.j;g=_ds.r(e.C);for(h=g.next();!h.done;h=g.next())k=h.value,d.unregisterIntersectionForElement(k);_ds.z(l)})})},mR=function(a){_ds.Q(a,function c(){var d,e,g=this;return _ds.D(c,function(h){if(1==h.h)return e=(d=document.documentElement.scrollHeight-document.documentElement.clientHeight)?document.documentElement.scrollTop/d:
0,g.hasAttribute("collapsed")?(_ds.hi(g,"aria-expanded","true",g.j),_ds.hi(g,"aria-label","Hide side navigation",g.j),_ds.hi(g,"data-title","Hide side navigation",g.j),g.removeAttribute("collapsed"),uR(g,"Expanded book nav")):(g.j.removeAttribute("aria-expanded"),_ds.hi(g,"aria-label","Show side navigation",g.j),_ds.hi(g,"data-title","Show side navigation",g.j),_ds.hi(g,"collapsed",""),uR(g,"Collapsed book nav")),_ds.y(h,_ds.Jm(),2);d=document.documentElement.scrollHeight-document.documentElement.clientHeight;
document.documentElement.scrollTop=Math.round(e*d);_ds.z(h)})})},uR=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))};var vR=_ds.xa(["animatable"]),wR=_ds.xa(["aria-expanded"]),xR=_ds.xa(["aria-label"]),yR=_ds.xa(["collapsed"]),zR=_ds.xa(["data-title"]),AR=_ds.xa(["fixed"]),BR=_ds.xa(["has-book-nav"]),CR=_ds.xa(["hidden"]),DR=_ds.xa(["role"]),ER=_ds.xa(["top-level-nav"]),FR=_ds.xa(["user-scrolled"]),GR=_ds.xa(["visually-hidden"]),kR="onpointerover"in window?"pointerover":"mouseover";_ds.w(gR,_ds.R);_ds.f=gR.prototype;
_ds.f.connectedCallback=function(){var a,b;return _ds.Q(this,function d(){var e=this,g;return _ds.D(d,function(h){if(1==h.h)return e.o=!0,e.O(e.h(vR),e.h(wR),e.h(xR),e.h(yR),e.h(zR),e.h(AR),e.h(BR),e.h(CR),e.h(DR),e.h(ER),e.h(FR),e.h(GR)),_ds.hi(e,"role","menu"),_ds.Ok(e.background,e),e.hasAttribute("hidden")&&(_ds.hi(e,"hidden","",e.j),_ds.hi(e,"hidden","",e.D)),_ds.y(h,(0,_ds.Kp)(),2);if(3!=h.h)return g=h.j,e.J=g.hasFlagAccess(150),e.J&&(null===(a=e.parentElement)||void 0===a?void 0:a.insertBefore(e.j,
e.nextSibling),_ds.hi(e,"aria-label","Hide side navigation",e.j),_ds.hi(e,"data-title","Hide side navigation",e.j),_ds.hi(e,"aria-expanded","true",e.j),null===(b=e.parentElement)||void 0===b?void 0:b.insertBefore(e.D,e.nextSibling)),fR(e),nR(e),_ds.y(h,e.init(),3);iR(e);_ds.z(h)})})};
_ds.f.disconnectedCallback=function(){this.o=!1;_ds.Rl(this.eventHandler);tR(this);this.C.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.hi(this,"visually-hidden","",a);a=_ds.r([this.background,this.j,this.D]);for(var b=a.next();!b.done;b=a.next())(b=b.value)&&_ds.Rk(b);this.removeAttribute("animatable");document.body.style.removeProperty("--devsite-js-book-nav-scrollbar-width")};
_ds.f.attributeChangedCallback=function(a){"hidden"===a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.hi(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);for(var c=_ds.r([this.background,
this.j,this.D]),d=c.next();!d.done;d=c.next())(d=d.value)&&(b?_ds.hi(this,a,"",d):d.removeAttribute(a))}"fixed"===a&&this.G()};
_ds.f.init=function(a){a=void 0===a?!0:a;return _ds.Q(this,function c(){var d=this,e,g,h;return _ds.D(c,function(k){if(1==k.h){if(!d.o)return k.return();document.body.style.setProperty("--devsite-js-book-nav-scrollbar-width",d.offsetWidth-d.clientWidth+"px");d.m=d.querySelector(".devsite-mobile-nav-bottom");!d.hasAttribute("hidden")&&d.m&&d.m.querySelector(".devsite-nav-active")||_ds.hi(d,"animatable","");_ds.hi(d,"top-level-nav","");d.m&&d.m.querySelector("[menu=_book]")&&d.removeAttribute("top-level-nav");
0===d.children.length&&_ds.hi(d,"hidden","");if(d.background)for(e=_ds.r(["hidden","fixed","animatable"]),g=e.next();!g.done;g=e.next())h=g.value,d.hasAttribute(h)&&_ds.hi(d,h,"",d.background);return!d.hasAttribute("hidden")&&a?(qR(d),rR(d),_ds.y(k,pR(d),0)):_ds.y(k,_ds.Jm(),4)}return _ds.y(k,oR(d),0)})})};
_ds.f.Ya=function(a){return _ds.Q(this,function c(){var d=this,e;return _ds.D(c,function(g){switch(g.h){case 1:if(!a){_ds.Nk(d);g.H(2);break}d.removeAttribute("animatable");e=a.querySelector("nav")||null;qR(d,e);rR(d,e);if(!e){g.H(3);break}return _ds.y(g,tR(d),4);case 4:d.C.clear(),iR(d,e,!1);case 3:_ds.ii(d,d.querySelector("nav"),e);case 2:return _ds.y(g,_ds.Jm(),5);case 5:return _ds.y(g,d.init(!1),0)}})})};
_ds.n.Object.defineProperties(gR,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["collapsed","fixed","hidden"]}}});gR.prototype.updateContent=gR.prototype.Ya;gR.prototype.attributeChangedCallback=gR.prototype.attributeChangedCallback;gR.prototype.disconnectedCallback=gR.prototype.disconnectedCallback;gR.prototype.connectedCallback=gR.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",gR)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
