(function(_ds){var window=this;'use strict';var wS=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_ds.mb(d)){var e=a.length||0,g=d.length||0;a.length=e+g;for(var h=0;h<g;h++)a[e+h]=d[h]}else a.push(d)}},xS=function(){var a=new _ds.xE;wS(a.L,"data-devsite-credential-type data-modal-dialog-id data-scope data-terminal-prefix data-title data-type".split(" "));return a},yS=function(){var a=xS();["devsite-var"].forEach(function(b){this.K.push(b)},a);return a},zS=function(){var a='<div class="devsite-code-buttons-container" role="group" aria-label="'+
_ds.Dj("Action buttons");return(0,_ds.T)(a+'"></div>')},AS=function(a){a=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" aria-label="'+_ds.X(a)+'" data-title="'+_ds.X(a)+'"></button>')},BS=function(a){a=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" aria-label="'+
_ds.X(a)+'" data-title="'+_ds.X(a)+'"></button>')},CS=function(a){var b=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-copy" data-category="Site-Wide Custom Events" data-label="'+_ds.X(a.sp)+'" track-type="exampleCode" track-name="clickToCopy" aria-label="'+_ds.X(b)+'" data-title="'+_ds.X(b)+'"></button>')},DS=function(a){a=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code" data-category="jsfiddle" data-label="" track-type="exampleCode" track-name="jsfiddle" aria-label="'+
_ds.X(a)+'" data-title="'+_ds.X(a)+'"></button>')},ES=function(){var a=_ds.R.call(this,["devsite-snackbar"])||this;a.j=null;a.o=null;a.K="";a.D=null;a.m=new _ds.Ll;a.L=!1;a.C=null;a.F=null;a.M=new _ds.Tn;a.V=new _ds.BE(_ds.HE(yS()));a.G=null;a.J=new _ds.Wl;return a},FS=function(a){Array.from(a.getElementsByClassName("prettyprint")).forEach(function(b){b.classList.remove("prettyprint");var c=(c=b.className.match(/\blang(?:uage)?-([\w.]+)(?!\S)/))?c[1]:void 0;c=window.prettyPrintOne(b.innerHTML,c);
c=a.V.h(c);_ds.Hd(b,c);b.getElementsByTagName("strong").length&&b.classList.add("devsite-code-highlight")})},GS=function(a){var b=a.getElementsByTagName("pre")[0];if(b){if(b.classList.contains("devsite-disable-click-to-copy")||b.hasAttribute("no-copy")||!b.classList.contains("devsite-click-to-copy")&&!b.classList.contains("prettyprint")&&!b.classList.contains("devsite-terminal"))a.setAttribute("no-copy",""),b.classList.remove("devsite-disable-click-to-copy"),b.removeAttribute("no-copy");a.setAttribute("data-copy-event-label",
b.getAttribute("data-copy-event-label")||"");b.classList.remove("devsite-click-to-copy");b=b.getAttribute("data-label");a.K=b?"Copy code sample: "+b:"Copy code sample"}var c=a.querySelector(".devsite-enable-open-in-jsfiddle,.devsite-jsfiddle-code-sample");c&&(a.setAttribute("js-fiddle",""),c.classList.remove("devsite-enable-open-in-jsfiddle"),c.classList.add("devsite-jsfiddle-code-sample"));a.hasAttribute("js-fiddle")&&c&&["scope","jsfiddle-title","jsfiddle-wrap","jsfiddle-label"].forEach(function(d){c.hasAttribute("data-"+
d)&&(a.setAttribute(d,c.getAttribute("data-"+d)),c.removeAttribute("data-"+d))})},HS=function(a){var b,c;return _ds.cb(function(d){if(1==d.h){b=Array.from(a.querySelector("pre:not(.devsite-copy-hide)").childNodes);_ds.mI(document.body,b);if(!a.G)return d.H(0);c=new _ds.Tn;a.o.setAttribute("aria-label","Code sample copied to clipboard");_ds.Pl(a.m,a.G,_ds.hm,function(){c.resolve()});return _ds.y(d,c.promise,3)}_ds.Pl(a.m,a.G,_ds.hm,function(){a.o.setAttribute("aria-label",a.K)});_ds.z(d)})},IS=function(a){a.D&&
a.m.listen(a.D,"click",function(){return void a.setAttribute("dark-code","")});a.F&&a.m.listen(a.F,"click",function(){return void a.removeAttribute("dark-code")});a.o&&a.m.listen(a.o,"click",function(){return void HS(a)});a.C&&a.m.listen(a.C,"click",function(){var b={title:a.getAttribute("jsfiddle-title")||"Code sample",wrap:a.getAttribute("jsfiddle-wrap")||"b",description:""},c=a.getAttribute("scope");c?_ds.zI(c,b):_ds.yI([a],b)})};/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(da){return da.replace(t,"&amp;").replace(u,"&lt;").replace(v,"&gt;")}function b(da,ea,ja){switch(da.nodeType){case 1:var fa=da.tagName.toLowerCase();ea.push("<",fa);var ta=da.attributes,La=ta.length;if(La){if(ja){for(var Ha=[],ha=La;0<=--ha;)Ha[ha]=ta[ha];Ha.sort(function(ua,Sa){return ua.name<Sa.name?-1:ua.name===Sa.name?0:1});ta=Ha}for(ha=0;ha<La;++ha)Ha=ta[ha],Ha.specified&&ea.push(" ",Ha.name.toLowerCase(),'="',Ha.value.replace(t,"&amp;").replace(u,"&lt;").replace(v,"&gt;").replace(x,
"&quot;"),'"')}ea.push(">");for(ta=da.firstChild;ta;ta=ta.nextSibling)b(ta,ea,ja);!da.firstChild&&/^(?:br|link|img)$/.test(fa)||ea.push("</",fa,">");break;case 3:case 4:ea.push(a(da.nodeValue))}}function c(da){function ea(Da){if("\\"!==Da.charAt(0))return Da.charCodeAt(0);switch(Da.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(Da.substring(2),16)||Da.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(Da.substring(1),
8);default:return Da.charCodeAt(1)}}function ja(Da){if(32>Da)return(16>Da?"\\x0":"\\x")+Da.toString(16);Da=String.fromCharCode(Da);if("\\"===Da||"-"===Da||"["===Da||"]"===Da)Da="\\"+Da;return Da}function fa(Da){var Ia=Da.substring(1,Da.length-1).match(RegExp("\\\\u[0-9A-Fa-f]{4}|\\\\x[0-9A-Fa-f]{2}|\\\\[0-3][0-7]{0,2}|\\\\[0-7]{1,2}|\\\\[\\s\\S]|-|[^-\\\\]","g"));Da=[];for(var wa=[],va="^"===Ia[0],Ba=va?1:0,db=Ia.length;Ba<db;++Ba){var Ta=Ia[Ba];switch(Ta){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":Da.push(Ta);
continue}Ta=ea(Ta);if(Ba+2<db&&"-"===Ia[Ba+1]){var ob=ea(Ia[Ba+2]);Ba+=2}else ob=Ta;wa.push([Ta,ob]);65>ob||122<Ta||(65>ob||90<Ta||wa.push([Math.max(65,Ta)|32,Math.min(ob,90)|32]),97>ob||122<Ta||wa.push([Math.max(97,Ta)&-33,Math.min(ob,122)&-33]))}wa.sort(function(Ub,Md){return Ub[0]-Md[0]||Md[1]-Ub[1]});Ia=[];Ta=[NaN,NaN];for(Ba=0;Ba<wa.length;++Ba)db=wa[Ba],db[0]<=Ta[1]+1?Ta[1]=Math.max(Ta[1],db[1]):Ia.push(Ta=db);wa=["["];va&&wa.push("^");wa.push.apply(wa,Da);for(Ba=0;Ba<Ia.length;++Ba)db=Ia[Ba],
wa.push(ja(db[0])),db[1]>db[0]&&(db[1]+1>db[0]&&wa.push("-"),wa.push(ja(db[1])));wa.push("]");return wa.join("")}function ta(Da){for(var Ia=Da.source.match(RegExp("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)","g")),wa=Ia.length,va=[],Ba=0,db=0;Ba<wa;++Ba){var Ta=Ia[Ba];"("===Ta?++db:"\\"===Ta.charAt(0)&&(Ta=+Ta.substring(1))&&Ta<=db&&(va[Ta]=-1)}for(Ba=1;Ba<va.length;++Ba)-1===va[Ba]&&(va[Ba]=
++La);for(db=Ba=0;Ba<wa;++Ba)Ta=Ia[Ba],"("===Ta?(++db,void 0===va[db]&&(Ia[Ba]="(?:")):"\\"===Ta.charAt(0)&&(Ta=+Ta.substring(1))&&Ta<=db&&(Ia[Ba]="\\"+va[db]);for(db=Ba=0;Ba<wa;++Ba)"^"===Ia[Ba]&&"^"!==Ia[Ba+1]&&(Ia[Ba]="");if(Da.ignoreCase&&Ha)for(Ba=0;Ba<wa;++Ba)Ta=Ia[Ba],Da=Ta.charAt(0),2<=Ta.length&&"["===Da?Ia[Ba]=fa(Ta):"\\"!==Da&&(Ia[Ba]=Ta.replace(/[a-zA-Z]/g,function(ob){ob=ob.charCodeAt(0);return"["+String.fromCharCode(ob&-33,ob|32)+"]"}));return Ia.join("")}for(var La=0,Ha=!1,ha=!1,ua=
0,Sa=da.length;ua<Sa;++ua){var U=da[ua];if(U.ignoreCase)ha=!0;else if(/[a-z]/i.test(U.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){Ha=!0;ha=!1;break}}var bb=[];ua=0;for(Sa=da.length;ua<Sa;++ua){U=da[ua];if(U.global||U.multiline)throw Error(""+U);bb.push("(?:"+ta(U)+")")}return new RegExp(bb.join("|"),ha?"gi":"g")}function d(da){var ea=0;return function(ja){for(var fa=null,ta=0,La=0,Ha=ja.length;La<Ha;++La)switch(ja.charAt(La)){case "\t":fa||(fa=[]);fa.push(ja.substring(ta,La));ta=
da-ea%da;for(ea+=ta;0<=ta;ta-=16)fa.push("                ".substring(0,ta));ta=La+1;break;case "\n":ea=0;break;default:++ea}if(!fa)return ja;fa.push(ja.substring(ta));return fa.join("")}}function e(da,ea,ja,fa){ea&&(da={source:ea,Zj:da},ja(da),fa.push.apply(fa,da.xk))}function g(da,ea){function ja(Ha){for(var ha=Ha.Zj,ua=[ha,"pln"],Sa=0,U=Ha.source.match(ta)||[],bb={},Da=0,Ia=U.length;Da<Ia;++Da){var wa=U[Da],va=bb[wa],Ba=void 0;if("string"===typeof va)var db=!1;else{var Ta=fa[wa.charAt(0)];if(Ta)Ba=
wa.match(Ta[1]),va=Ta[0];else{for(db=0;db<La;++db)if(Ta=ea[db],Ba=wa.match(Ta[1])){va=Ta[0];break}Ba||(va="pln")}!(db=5<=va.length&&"lang-"===va.substring(0,5))||Ba&&"string"===typeof Ba[1]||(db=!1,va="src");db||(bb[wa]=va)}Ta=Sa;Sa+=wa.length;if(db){db=Ba[1];var ob=wa.indexOf(db),Ub=ob+db.length;Ba[2]&&(Ub=wa.length-Ba[2].length,ob=Ub-db.length);va=va.substring(5);e(ha+Ta,wa.substring(0,ob),ja,ua);e(ha+Ta+ob,db,m(va,db),ua);e(ha+Ta+Ub,wa.substring(Ub),ja,ua)}else ua.push(ha+Ta,va)}Ha.xk=ua}var fa=
{},ta;(function(){for(var Ha=da.concat(ea),ha=[],ua={},Sa=0,U=Ha.length;Sa<U;++Sa){var bb=Ha[Sa],Da=bb[3];if(Da)for(var Ia=Da.length;0<=--Ia;)fa[Da.charAt(Ia)]=bb;bb=bb[1];Da=""+bb;ua.hasOwnProperty(Da)||(ha.push(bb),ua[Da]=null)}ha.push(/[\0-\uffff]/);ta=c(ha)})();var La=ea.length;return ja}function h(da){var ea=[],ja=[];da.tripleQuotedStrings?ea.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,
null,"'\""]):da.multiLineStrings?ea.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,null,"'\"`"]):ea.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);da.verbatimStrings&&ja.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var fa=da.hashComments;fa&&(da.cStyleComments?(1<fa?ea.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):ea.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,
null,"#"]),ja.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,null])):ea.push(["com",/^#[^\r\n]*/,null,"#"]));da.cStyleComments&&(ja.push(["com",/^\/\/[^\r\n]*/,null]),ja.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));da.regexLiterals&&ja.push(["lang-regex",new RegExp("^"+q+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);da=da.keywords.replace(/^\s+|\s+$/g,"");da.length&&ja.push(["kwd",new RegExp("^(?:"+da.replace(/\s+/g,
"|")+")\\b"),null]);ea.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);ja.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",RegExp("^(?:0x[a-f0-9]+|(?:\\d(?:_\\d+)*\\d*(?:\\.\\d*)?|\\.\\d\\+)(?:e[+\\-]?\\d+)?)[a-z]*","i"),null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return g(ea,ja)}function k(da){function ea(xe){if(xe>ua){Sa&&Sa!==U&&(ha.push("</span>"),Sa=null);!Sa&&U&&(Sa=U,ha.push('<span class="',Sa,'">'));var jf=
a(Ia(ja.substring(ua,xe))).replace(Ta?va:wa,"$1&#160;");Ta=db.test(jf);ha.push(jf.replace(Ba,hf));ua=xe}}var ja=da.source,fa=da.Rp,ta=da.xk,La=da.zl,Ha=da.xm,ha=[],ua=0,Sa=null,U=null,bb=0,Da=0,Ia=d(window.PR_TAB_WIDTH),wa=/([\r\n ]) /g,va=/(^| ) /gm,Ba=/\r\n?|\n/g,db=/[ \r\n]$/,Ta=!0,ob=window._pr_isIE6();Ha=ob?Ha&&"PRE"===Ha.tagName?6===ob?"&#160;\r\n":7===ob?"&#160;<br />\r":8===ob?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if(La){var Ub=[];for(ob=0;10>ob;++ob)Ub[ob]=Ha+'</li><li class="L'+
ob+'">';var Md="number"===typeof La?La-1:0;ha.push('<ol class="linenums"><li class="L',Md%10,'"');Md&&ha.push(' value="',Md+1,'"');ha.push(">");var hf=function(){var xe=Ub[++Md%10];return Sa?"</span>"+xe+'<span class="'+Sa+'">':xe}}else hf=Ha;for(;;)if(bb<fa.length&&(Da<ta.length?fa[bb]<=ta[Da]:1))ea(fa[bb]),Sa&&(ha.push("</span>"),Sa=null),ha.push(fa[bb+1]),bb+=2;else if(Da<ta.length)ea(ta[Da]),U=ta[Da+1],Da+=2;else break;ea(ja.length);Sa&&ha.push("</span>");La&&ha.push("</li></ol>");da.ri=ha.join("")}
function l(da,ea){for(var ja=ea.length;0<=--ja;){var fa=ea[ja];Va.hasOwnProperty(fa)?"console"in window&&console.warn("cannot override language handler %s",fa):Va[fa]=da}}function m(da,ea){da&&Va.hasOwnProperty(da)||(da=/^\s*</.test(ea)?"default-markup":"default-code");return Va[da]}function p(da){var ea=da.wm,ja=da.jl;da.ri=ea;try{var fa=ea.match(pa);ea=[];var ta=0,La=[];if(fa)for(var Ha=0,ha=fa.length;Ha<ha;++Ha){var ua=fa[Ha];if(1<ua.length&&"<"===ua.charAt(0)){if(!ba.test(ua))if(Ga.test(ua))ea.push(ua.substring(9,
ua.length-3)),ta+=ua.length-12;else if($a.test(ua))ea.push("\n"),++ta;else if(0<=ua.indexOf("nocode")&&ua.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var Sa=ua.match(Fa)[2],U=1;var bb=Ha+1;a:for(;bb<ha;++bb){var Da=fa[bb].match(Fa);if(Da&&Da[2]===Sa)if("/"===Da[1]){if(0===--U)break a}else++U}bb<ha?(La.push(ta,fa.slice(Ha,bb+1).join("")),Ha=bb):La.push(ta,ua)}else La.push(ta,ua)}else{U=ua;var Ia=U.indexOf("&");if(0>Ia)var wa=
U;else{for(--Ia;0<=(Ia=U.indexOf("&#",Ia+1));){var va=U.indexOf(";",Ia);if(0<=va){var Ba=U.substring(Ia+3,va),db=10;Ba&&"x"===Ba.charAt(0)&&(Ba=Ba.substring(1),db=16);var Ta=parseInt(Ba,db);isNaN(Ta)||(U=U.substring(0,Ia)+String.fromCharCode(Ta)+U.substring(va+1))}}wa=U.replace(G,"<").replace(I,">").replace(M,"'").replace(W,'"').replace(ca," ").replace(S,"&")}ea.push(wa);ta+=wa.length}}var ob=ea.join("");da.source=ob;da.Zj=0;da.Rp=La;m(ja,ob)(da);k(da)}catch(Ub){"console"in window&&console.log(Ub&&
Ub.stack?Ub.stack:Ub)}}var q=function(){for(var da="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),ea="(?:^^|[+-]",ja=0;ja<da.length;++ja)ea+="|"+da[ja].replace(/([^=<>:&a-z])/g,"\\$1");return ea+")\\s*"}(),t=/&/g,u=/</g,v=/>/g,x=/"/g,G=/&lt;/g,I=/&gt;/g,M=/&apos;/g,W=/&quot;/g,S=/&amp;/g,ca=/&nbsp;/g,ia=/[\r\n]/g,aa=null,
pa=RegExp("[^<]+|\x3c!--[\\s\\S]*?--\x3e|<!\\[CDATA\\[[\\s\\S]*?\\]\\]>|</?[a-zA-Z](?:[^>\"']|'[^']*'|\"[^\"]*\")*>|<","g"),ba=/^\x3c!--/,Ga=/^<!\[CDATA\[/,$a=/^<br\b/i,Fa=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,Qa=h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),Va={};l(Qa,["default-code"]);l(g([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));l(g([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);l(g([],[["atv",/^[\s\S]+/]]),["uq.val"]);l(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));l(h({keywords:"null true false"}),["json"]);l(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);l(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);l(h({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);l(h({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);l(h({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);l(h({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);l(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);l(h({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);l(g([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=function(da,ea,ja){da={wm:da,jl:ea,zl:ja};p(da);return da.ri};window.prettyPrint=function(da){function ea(){for(var U=
window.PR_SHOULD_USE_CONTINUATION?ha.now()+250:Infinity;ua<fa.length&&ha.now()<U;ua++){var bb=fa[ua];if(bb.className&&0<=bb.className.indexOf("prettyprint")){var Da=bb.className.match(/\blang-(\w+)\b/);Da&&(Da=Da[1]);for(var Ia=!1,wa=bb.parentNode;wa;wa=wa.parentNode)if(("pre"===wa.tagName||"code"===wa.tagName||"xmp"===wa.tagName)&&wa.className&&0<=wa.className.indexOf("prettyprint")){Ia=!0;break}if(!Ia){wa=bb;null===aa&&(Ia=document.createElement("PRE"),Ia.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),
aa=!/</.test(Ia.innerHTML));if(aa)if(Ia=wa.innerHTML,"XMP"===wa.tagName)Ia=a(Ia);else{if("PRE"!==wa.tagName&&ia.test(Ia)){var va="";wa.currentStyle?va=wa.currentStyle.whiteSpace:window.getComputedStyle&&(va=window.getComputedStyle(wa,null).whiteSpace);wa=!va||"pre"===va}else wa=!0;wa||(Ia=Ia.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{Ia=[];for(wa=wa.firstChild;wa;wa=wa.nextSibling)b(wa,Ia);Ia=Ia.join("")}Ia=Ia.replace(/(?:\r\n?|\n)$/,"");wa=bb.className.match(/\blinenums\b(?::(\d+))?/);
Sa={wm:Ia,jl:Da,xm:bb,zl:wa?wa[1]&&wa[1].length?+wa[1]:!0:!1};p(Sa);if(bb=Sa.ri)if(Da=Sa.xm,"XMP"===Da.tagName){Ia=document.createElement("PRE");for(wa=0;wa<Da.attributes.length;++wa)va=Da.attributes[wa],va.specified&&("class"===va.name.toLowerCase()?Ia.className=va.value:Ia.setAttribute(va.name,va.value));Ia.innerHTML=bb;Da.parentNode.replaceChild(Ia,Da)}else Da.innerHTML=bb}}}ua<fa.length?setTimeout(ea,250):da&&da()}for(var ja=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),
document.getElementsByTagName("xmp")],fa=[],ta=0;ta<ja.length;++ta)for(var La=0,Ha=ja[ta].length;La<Ha;++La)fa.push(ja[ta][La]);ja=null;var ha=Date;ha.now||(ha={now:function(){return(new Date).getTime()}});var ua=0,Sa;ea()};window.PR={combinePrefixPatterns:c,createSimpleLexer:g,registerLangHandler:l,sourceDecorator:h,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",
PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],[PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],
[PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\x0B\f\r "],[PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*

 Copyright (C) 2017 Micha? B?czkowski

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PUNCTUATION,/^[.!%&()*+,\-;<=>?\[\\\]^{|}:]+/,null,".!%&()*+,-;<=>?[\\]^{|}:"]],[[PR.PR_KEYWORD,/^\b(package|public|protected|private|open|abstract|constructor|final|override|import|for|while|as|typealias|get|set|((data|enum|annotation|sealed) )?class|this|super|val|var|fun|is|in|throw|return|break|continue|(companion )?object|if|try|else|do|when|init|interface|typeof|suspend)\b/],[PR.PR_LITERAL,
/^(?:true|false|null)\b/],[PR.PR_LITERAL,/^(0[xX][0-9a-fA-F_]+L?|0[bB][0-1]+L?|[0-9_.]+([eE]-?[0-9]+)?[fFL]?)/],[PR.PR_TYPE,/^(\b[A-Z]+[a-z][a-zA-Z0-9_$@]*|`.*`)/,null],[PR.PR_COMMENT,/^\/\/.*/],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/],[PR.PR_STRING,/'.'/],[PR.PR_STRING,/^"([^"\\]|\\[\s\S])*"/],[PR.PR_STRING,/^"{3}[\s\S]*?[^\\]"{3}/],[PR.PR_LITERAL,/^@([a-zA-Z0-9_$@]*|`.*`)/],[PR.PR_LITERAL,/^[a-zA-Z0-9_]+@/]]),["kotlin"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],
[PR.PR_PLAIN,/^[a-z_]\w*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);PR.registerLangHandler(PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[PR.PR_KEYWORD,/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],
[PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[PR.PR_PLAIN,/^[$a-zA-Z_][\w$]*/],[PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^[a-z_][\w-]*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[PR.PR_LITERAL,/^(?:true|false|nil)\b/,null],[PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[PR.PR_PUNCTUATION,/^(?:\[|\])/]]),["vb","vbs"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[PR.PR_COMMENT,/^--[^\r\n]*/],[PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[PR.PR_LITERAL,/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],
[PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[PR.PR_PLAIN,/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[PR.PR_TYPE,/^[&]\S+/,null,"&"],[PR.PR_TYPE,/^!\S*/,null,"!"],[PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],[PR.PR_PUNCTUATION,/^-/],[PR.PR_KEYWORD,/^\w+:[ \r\n]/],[PR.PR_PLAIN,/^\w+/]]),
["yaml","yml"]);_ds.w(ES,_ds.R);ES.prototype.whenReady=function(){return this.M.promise};
ES.prototype.connectedCallback=function(){var a=this,b;return _ds.cb(function(c){switch(c.h){case 1:return _ds.y(c,DevsiteApp.whenReady(),2);case 2:return a.L||(GS(a),FS(a),a.L=!0),a.J.get("pref_dark-code")&&a.setAttribute("dark-code",""),a.M.resolve(),_ds.A(c,3),_ds.y(c,DevsiteApp.intersectionEnterForElement(a),5);case 5:_ds.B(c,4);break;case 3:if(b=_ds.C(c),"IntersectionObserver not supported"!==b.message)return c.return();case 4:var d=a.querySelector(".devsite-code-buttons-container");if(d)a.j=
d;else{a.j=_ds.Al(zS);a.hasAttribute("scope")&&(a.C=_ds.Al(DS,{label:"Open code sample in JSFiddle"}),(a.hasAttribute("jsfiddle-label")||a.hasAttribute("jsfiddle-title"))&&a.C.setAttribute("data-label",a.getAttribute("jsfiddle-label")||a.getAttribute("jsfiddle-title")),a.j.appendChild(a.C));a.D=_ds.Al(AS,{label:"Dark code theme"});a.j.appendChild(a.D);a.F=_ds.Al(BS,{label:"Light code theme"});a.j.appendChild(a.F);if(!a.hasAttribute("no-copy")){d=a.getAttribute("data-copy-event-label");var e="Click To Copy";
d&&(e+=": "+d);a.o=_ds.Al(CS,{label:a.K,sp:e});a.j.appendChild(a.o)}a.prepend(a.j)}IS(a);a.G=document.querySelector("devsite-snackbar");_ds.z(c)}})};ES.prototype.disconnectedCallback=function(){var a=this;return _ds.cb(function(b){if(1==b.h)return _ds.y(b,DevsiteApp.whenReady(),2);DevsiteApp.unregisterIntersectionForElement(a);a.j&&a.removeChild(a.j);_ds.Rl(a.m);_ds.z(b)})};
ES.prototype.attributeChangedCallback=function(a,b,c){var d=this;return _ds.cb(function(e){if(1==e.h){if("dark-code"!==a||b===c)return e.H(0);if(d.hasAttribute("dark-code"))return d.J.set("pref_dark-code","1"),_ds.y(e,_ds.Jm(),6);d.J.remove("pref_dark-code");return _ds.y(e,_ds.Jm(),5)}if(6!=e.h)return Array.from(document.querySelectorAll("devsite-code[dark-code]")).forEach(function(g){g.removeAttribute("dark-code")}),e.H(0);Array.from(document.querySelectorAll("devsite-code:not([dark-code])")).filter(function(g){return g!==
d}).forEach(function(g){g.setAttribute("dark-code","")});_ds.z(e)})};_ds.n.Object.defineProperties(ES,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["dark-code"]}}});ES.prototype.attributeChangedCallback=ES.prototype.attributeChangedCallback;ES.prototype.disconnectedCallback=ES.prototype.disconnectedCallback;ES.prototype.connectedCallback=ES.prototype.connectedCallback;ES.prototype.whenReady=ES.prototype.whenReady;try{window.customElements.define("devsite-code",ES)}catch(a){console.warn("devsite.app.customElement.DevsiteCode",a)};})(_ds_www);
