(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var oY=function(){var a=_ds.R.call(this)||this;a.m=_ds.Ho();a.j=new _ds.Ll;mY().then(function(){nY(a)});return a},nY=function(a){var b;return _ds.cb(function(c){return(b=_ds.hM.get("django_language"))?_ds.y(c,a.m.set("language_preference",b),0):c.H(0)})},qY=function(a){_ds.Rl(a.j);var b=a.querySelector(".devsite-language-selector-select");b&&a.j.listen(b,"change",function(c){pY(a,c)})},pY=function(a,b){var c,d;_ds.cb(function(e){switch(e.h){case 1:return _ds.y(e,DevsiteApp.whenReady(),
2);case 2:return _ds.hM.remove("django_language"),c=b.target,_ds.hM.set("django_language",c.value,{Lb:15552E3,path:"/"}),d=document.documentElement.getAttribute("lang"),_ds.y(e,rY(a,d,c.value),3);case 3:return _ds.y(e,nY(a),4);case 4:var g=_ds.ip(_ds.ij(new _ds.Oi(_ds.Gk().location.href),"hl").toString());_ds.Gk().location.assign(_ds.bi(g));_ds.z(e)}})},rY=function(a,b,c){var d,e;return _ds.cb(function(g){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",
label:"Language Selector",action:b+" to "+c},bubbles:!0}));d={name:"change",type:"languageSelector",metadata:{"selected-language":c,"original-language":b}};e={eventData:JSON.stringify(d)};a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:e,bubbles:!0}));_ds.z(g)})},mY=function(){return _ds.cb(function(a){if(1==a.h)return _ds.hM.get("django_language")?a.H(0):_ds.y(a,DevsiteApp.whenReady(),3);_ds.hM.set("django_language",DevsiteApp.getLocale()||"en",{Lb:15552E3,path:"/"});
_ds.z(a)})};_ds.w(oY,_ds.R);oY.prototype.connectedCallback=function(){qY(this)};oY.prototype.disconnectedCallback=function(){_ds.Rl(this.j)};oY.prototype.Ya=function(a){a&&(_ds.ii(this,this.querySelector(".devsite-language-selector-menu"),a.querySelector(".devsite-language-selector-menu")),qY(this))};oY.prototype.updateContent=oY.prototype.Ya;oY.prototype.disconnectedCallback=oY.prototype.disconnectedCallback;oY.prototype.connectedCallback=oY.prototype.connectedCallback;try{window.customElements.define("devsite-language-selector",oY)}catch(a){console.warn("devsite.app.customElement.DevsiteLanguageSelector",a)};})(_ds_www);
