(function(_ds){var window=this;'use strict';var $2=function(a){var b=a.Ti;a=a.op;for(var c='<div class="dropdown-tabbed-menu"><ul class="dropdown-tabbed-menu-list">',d=a.length,e=0;e<d;e++){var g=a[e];c+='<li class="dropdown-tabbed-menu-list-item"><a href="#" column-id="'+_ds.X(g.np)+'" tabindex="0" track-type="nav" track-name="'+_ds.X(g.text)+'" track-metadata-eventdetail="#" track-metadata-position="nav - '+_ds.X(b)+'" track-metadata-module="secondary nav">'+_ds.V(g.text)+"</a></li>"}return(0,_ds.T)(c+"</ul></div>")},a3=function(a){var b=
a.Ti,c=a.href;a=a.text;return(0,_ds.T)('<div class="dropdown-tabbed-menu-button"><a href="'+_ds.X(_ds.Zj(c))+'" track-type="nav" track-name="'+_ds.X(a)+'" track-metadata-eventdetail="'+_ds.X(c)+'" track-metadata-position="nav - '+_ds.X(b)+'" track-metadata-module="secondary nav">'+_ds.V(a)+"</a></div>")},s3=function(){var a=_ds.R.call(this)||this;a.V=20;a.eventHandler=new _ds.Ll;a.m=new _ds.Ll;a.K=new _ds.Qn(function(){b3(a)},a.V);a.L=null;a.D=null;a.J=!1;a.G=0;a.j=null;a.F=null;a.M=0;a.o=[];a.C=
null;a.O(a.h(c3),a.h(d3),a.h(e3),a.h(f3),a.h(g3),a.h(h3),a.h(i3),a.h(j3),a.h(k3),a.h(l3),a.h(m3),a.h(n3),a.h(o3),a.h(p3),a.h(q3),a.h(r3));return a},B3=function(a){a.eventHandler.listen(document.body,"devsite-sticky-resize",function(){return a.K.Aa()});a.eventHandler.listen(a,"click",function(e){if(!(e.shiftKey||e.ctrlKey||e.metaKey||e.altKey)){var g=e.target,h=t3(a,g);if(h)if(a.D&&a.D(e))e.preventDefault(),e.stopPropagation();else if(h===a.j)u3(a,e);else if(v3(a),g.classList.contains("devsite-tabs-dropdown-toggle"))e.preventDefault(),
e.stopPropagation(),h.hasAttribute("dropdown--open")?w3(a):x3(a,h);else{var k;"A"===g.tagName?k=g:k=_ds.tl(g,"A");var l=h.querySelector(".devsite-tabs-dropdown");if(l&&l.contains(g))k&&k.hasAttribute("href")||(e.preventDefault(),e.stopPropagation());else{if(e=a.L||a.querySelector("[active]"))e.removeAttribute("active"),_ds.hi(a,"aria-selected","false",e);_ds.hi(a,"active","",h);_ds.hi(a,"aria-selected","true",h);a.L=h;k&&k&&"#"!==k.href||a.K.Aa()}}}});if(a.querySelector("tab[dropdown]")||a.querySelector("tab[overflow-tab]")){var b=
"onpointermove"in window?"pointerover":"mouseover",c="onpointermove"in window?"pointerleave":"mouseleave",d=a.querySelectorAll("tab[clickable]");if(d.length){b=_ds.r(d);for(c=b.next();!c.done;c=b.next())a.eventHandler.listen(c.value,"click",function(e){var g,h=e.target,k=t3(a,h),l=null===k||void 0===k?void 0:k.querySelector(".devsite-tabs-dropdown");!l||(null===(g=a.j)||void 0===g?0:g.contains(h))||l.contains(h)||(e.preventDefault(),e.stopPropagation(),(null===k||void 0===k?0:k.hasAttribute("dropdown--open"))?
w3(a):y3(a,e))});a.eventHandler.listen(document.body,"click",function(e){a.C&&!a.C.contains(e.target)&&w3(a)})}else a.eventHandler.listen(a,b,function(e){return void z3(a,e)}),a.eventHandler.listen(a,c,function(){return void A3(a)})}b=[].concat(_ds.ya(a.querySelectorAll(".devsite-tabs-close-button")));b=_ds.r(b);for(c=b.next();!c.done;c=b.next())a.eventHandler.listen(c.value,"click",function(){return w3(a)})},A3=function(a){return _ds.Q(a,function c(){var d,e=this;return _ds.D(c,function(g){if(1==
g.h)return _ds.y(g,(0,_ds.Kp)(),2);d=g.j;if(d.isTouchEnabled())return g.return();w3(e,300);_ds.z(g)})})},z3=function(a,b){return _ds.Q(a,function d(){var e,g=this;return _ds.D(d,function(h){if(1==h.h)return _ds.y(h,(0,_ds.Kp)(),2);e=h.j;if(e.isTouchEnabled())return h.return();y3(g,b);_ds.z(h)})})},y3=function(a,b){var c,d=b.target,e=t3(a,d);e&&(e===a.j||(null===(c=a.j)||void 0===c?0:c.contains(d))?u3(a,b):x3(a,e))},w3=function(a,b){b=void 0===b?0:b;_ds.Rl(a.m);window.clearTimeout(a.G);var c=a.querySelector("tab[dropdown--open]");
if(c){var d=c.querySelector(".devsite-tabs-dropdown");_ds.hi(a,"dropdown-transition","",d);_ds.Pl(a.m,d,_ds.hm,function(){null===d||void 0===d?void 0:d.removeAttribute("dropdown-transition");a.removeAttribute("dropdown--open");_ds.hi(a,"hidden","",d)});a.G=window.setTimeout(function(){c.removeAttribute("dropdown--open");C3(a,c)},b)}else a.removeAttribute("dropdown--open");v3(a)},x3=function(a,b){_ds.Q(a,function d(){var e=this,g,h,k,l,m,p,q,t,u,v,x,G;return _ds.D(d,function(I){if(1==I.h){g=e;v3(e);
if(!b.hasAttribute("dropdown"))return w3(e),I.return();_ds.Rl(e.m);window.clearTimeout(e.G);return b.hasAttribute("dropdown--open")?I.return():_ds.y(I,(0,_ds.Kp)(),2)}h=I.j;h.isTouchEnabled()&&_ds.Pl(e.m,document.body,"click",function(M){g.contains(M.target)||w3(g)});k=e.querySelector("tab[dropdown--open]");l=b.querySelector(".devsite-tabs-dropdown");if(!l)return k&&(k.removeAttribute("dropdown--open"),C3(e,k)),I.return();l.removeAttribute("hidden");_ds.Wn(l,"left","");m=_ds.Bk(window||window);p=
Array.from(l.querySelectorAll(".devsite-tabs-dropdown-column"));!b.hasAttribute("dropdown-full")&&1<p.length&&(q=[],p.forEach(function(M){q.push(M.scrollWidth)}),t=Math.max.apply(null,q),u=t*p.length,u<m.width?p.forEach(function(M){_ds.Wn(M,"width",t+"px")}):_ds.hi(e,"dropdown-full","",b));v=l.getBoundingClientRect();b.hasAttribute("dropdown-full")?_ds.Wn(l,"left","-"+v.left+"px"):(x=Math.min(v.left,v.left+v.width-m.width),0<x&&_ds.Wn(l,"left","-"+x+"px"));k?(k.removeAttribute("dropdown--open"),C3(e,
k),G=k.querySelector(".devsite-tabs-dropdown"),null===G||void 0===G?void 0:G.removeAttribute("dropdown-transition"),_ds.hi(e,"hidden","",G)):(_ds.hi(e,"dropdown-transition","",l),_ds.Pl(e.m,l,_ds.hm,function(){return l.removeAttribute("dropdown-transition")}));window.requestAnimationFrame(function(){_ds.hi(g,"dropdown--open","");_ds.hi(g,"dropdown--open","",b);C3(g,b)});_ds.z(I)})})},t3=function(a,b){for(;b&&b!==a;){if("TAB"===b.tagName.toUpperCase())return b;b=b.parentElement}return null},u3=function(a,
b){var c;_ds.Q(a,function e(){var g=this,h,k,l;return _ds.D(e,function(m){switch(m.h){case 1:return h=g,b.preventDefault(),b.stopPropagation(),document.body.dispatchEvent(new CustomEvent("devsite-close-overflow-tabs")),_ds.y(m,_ds.Jm(),2);case 2:return g.hasAttribute("overflow-menu--open")?m.return():_ds.y(m,(0,_ds.Kp)(),3);case 3:return k=m.j,_ds.y(m,k.whenReady(),4);case 4:k.isTouchEnabled()&&(l=function(p){h.contains(p.target)||v3(h);_ds.Ql(h.m,document.body,["devsite-close-overflow-tabs","click"],
l)},g.m.listen(document.body,["devsite-close-overflow-tabs","click"],l)),null===(c=g.F)||void 0===c?void 0:c.removeAttribute("hidden"),_ds.hi(g,"overflow-menu--open",""),_ds.z(m)}})})},v3=function(a){_ds.hi(a,"hidden","",a.F);a.removeAttribute("overflow-menu--open")},b3=function(a){var b,c,d;_ds.hi(a,"hidden","",a.j);if(!(a.o&&3>a.o.length)){var e=D3(a,a);if(0!==e){var g=(null===(b=a.o)||void 0===b?void 0:b.slice())||[],h=0,k;g.forEach(function(t){t.parentNode!==a.C&&(k?_ds.Pk(t,k):_ds.Qk(a.C,t,0));
k=t;h+=D3(a,t)});if(!(h<=e)){var l=a.M;null===(c=a.j)||void 0===c?void 0:c.removeAttribute("hidden");var m=a.querySelector("[active]");for(m&&(l+=D3(a,m));null===g||void 0===g?0:g.length;){var p=g.shift();if(p!==m){var q=D3(a,p||null);l+q<=e?l+=q:null===(d=a.F)||void 0===d?void 0:d.appendChild(p)}}}}}},E3=function(a){var b;a.o=Array.from(a.querySelectorAll("tab"));var c=a.querySelector(".devsite-tabs-wrapper");c||(c=a.ownerDocument.createElement("div"),c.classList.add("devsite-tabs-wrapper"),a.appendChild(c),
null===(b=a.o)||void 0===b?void 0:b.forEach(function(g){return null===c||void 0===c?void 0:c.appendChild(g)}));a.C=c;a.appendChild(c);if(!a.hasAttribute("no-overflow")){var d=a.ownerDocument.createElement("tab");_ds.hi(a,"overflow-tab","",d);var e=a.ownerDocument.createElement("a");_ds.Jd(e,"#");e.textContent="More";e.classList.add("devsite-icon");e.classList.add("devsite-icon-arrow-drop-down");d.appendChild(e);a.j=d;e=a.ownerDocument.createElement("div");e.classList.add("devsite-tabs-overflow-menu");
_ds.hi(a,"scrollbars","",e);_ds.hi(a,"hidden","",e);a.F=e;d.appendChild(e);c.appendChild(d)}},D3=function(a,b){if(!b)return 0;for(var c=[],d=b;d.parentElement&&0===d.offsetWidth;)c.push(d),_ds.hi(a,"render-hidden","",d),d=d.parentElement;a=_ds.ho(b).width;c=_ds.r(c);for(b=c.next();!b.done;b=c.next())b.value.removeAttribute("render-hidden");return a},C3=function(a,b){_ds.hi(a,"aria-expanded",""+b.hasAttribute("dropdown--open"),b.querySelector(".devsite-tabs-dropdown-toggle"))},F3=function(a,b){return _ds.Q(a,
function d(){var e;return _ds.D(d,function(g){if(1==g.h)return _ds.y(g,(0,_ds.Kp)(),2);e=g.j;return e.isTouchEnabled()||!b.hasAttribute("generated-tab-menu")?g.return(!1):g.return(!0)})})},I3=function(a){var b;null===(b=a.o)||void 0===b?void 0:b.forEach(function(c,d){return _ds.Q(a,function g(){var h=this,k,l,m,p,q,t,u,v,x;return _ds.D(g,function(G){if(1==G.h)return k=h,_ds.y(G,F3(h,c),2);l=G.j;if(!l)return G.return();m=Array.from(c.querySelectorAll(".devsite-tabs-dropdown-column"));p=c.querySelector(".devsite-tabs-dropdown");
q=c.querySelector("a");m.forEach(function(I,M){_ds.hi(k,"column-id","tab-"+d+"-column-"+M,I)});t=m.map(function(I){var M=I.querySelector(".devsite-nav-title")||I.querySelector(".devsite-nav-item-title");return{np:I.getAttribute("column-id"),text:null===M||void 0===M?void 0:M.textContent}});q&&(u=_ds.Al($2,{Ti:(q.textContent||"").toLowerCase().trim(),op:t}),p&&(v=c.querySelector(".devsite-tabs-dropdown-content")))&&(p.insertBefore(u,v),x=c.querySelector(".dropdown-tabbed-menu a"),G3(c),h.eventHandler.listen(u,
"click",function(I){I.preventDefault();var M=c.querySelector(".dropdown-tabbed-menu-button");I=I.target;M&&I.tagName&&"a"===I.tagName.toLowerCase()&&!M.contains(I)&&H3(k,c,(null===I||void 0===I?void 0:I.getAttribute("column-id"))||"")}),x&&H3(h,c,x.getAttribute("column-id")||""));_ds.z(G)})})})},H3=function(a,b,c){var d=Array.from(b.querySelectorAll(".devsite-tabs-dropdown-column"));b=Array.from(b.querySelectorAll(".dropdown-tabbed-menu a"));b.forEach(function(e){return e.removeAttribute("active")});
d.forEach(function(e){return _ds.hi(a,"hidden","",e)});b=b.find(function(e){return e.getAttribute("column-id")===c});d=d.find(function(e){return e.getAttribute("column-id")===c});b&&d&&(_ds.hi(a,"active","",b),d.removeAttribute("hidden"))},G3=function(a){var b=a.querySelector(".dropdown-tabbed-menu-button-target");if(!a.querySelector(".dropdown-tabbed-menu-button")&&b){var c=a.querySelector("a");c&&(c=c.textContent,b=b.querySelector(".devsite-nav-item a"),a=a.querySelector(".dropdown-tabbed-menu"),
b&&(c=_ds.Al(a3,{Ti:(c||"").toLowerCase().trim(),href:b.getAttribute("href")||"",text:b.textContent||""}),null===a||void 0===a?void 0:a.appendChild(c)))}};var c3=_ds.xa(["active"]),d3=_ds.xa(["aria-expanded"]),e3=_ds.xa(["aria-selected"]),f3=_ds.xa(["collapsed"]),g3=_ds.xa(["column-id"]),h3=_ds.xa(["connected"]),i3=_ds.xa(["dropdown"]),j3=_ds.xa(["dropdown-full"]),k3=_ds.xa(["dropdown--open"]),l3=_ds.xa(["dropdown-transition"]),m3=_ds.xa(["hidden"]),n3=_ds.xa(["no-overflow"]),o3=_ds.xa(["overflow-menu--open"]),p3=_ds.xa(["overflow-tab"]),q3=_ds.xa(["render-hidden"]),r3=_ds.xa(["scrollbars"]);_ds.w(s3,_ds.R);
s3.prototype.disconnectedCallback=function(){_ds.Rl(this.eventHandler);_ds.Rl(this.m)};s3.prototype.connectedCallback=function(){this.J||(E3(this),this.J=!0);_ds.hi(this,"connected","");var a;this.hasAttribute("no-overflow")||(_ds.hi(this,"collapsed","",this.j),this.M=D3(this,this.j),null===(a=this.j)||void 0===a?void 0:a.removeAttribute("collapsed"),B3(this),b3(this));I3(this)};s3.prototype.R=function(a){this.D=a};s3.prototype.Y=function(){this.D=null};s3.prototype.connectedCallback=s3.prototype.connectedCallback;
s3.prototype.disconnectedCallback=s3.prototype.disconnectedCallback;try{window.customElements.define("devsite-tabs",s3)}catch(a){console.warn("devsite.app.customElement.DevsiteTabs",a)};})(_ds_www);
