(function(_ds){var window=this;'use strict';var m4=function(a){var b=a.Os,c=a.Zb,d=a.pp;a=a.Nq;var e='<ul class="devsite-nav-list"><li class="devsite-nav-item devsite-nav-heading devsite-toc-toggle" role="heading" aria-level="2"><span class="devsite-nav-title"><span class="devsite-nav-text">On this page</span></span>';c&&(e=e+'<button type="button" title="'+_ds.Dj("Expand/collapse contents"),e+='" class="devsite-nav-show-all button-transparent material-icons"></button>');e+="</li>";for(var g=b.length,h=0;h<g;h++){var k=b[h];e+=
'<li class="devsite-nav-item"'+(c&&k.index<a?" visible":"")+'><a href="#'+_ds.X(k.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.X(h)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.X(h)+'" track-metadata-link-destination="#'+_ds.X(k.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.V(k.text)+"</span></a>";if(_ds.xj(k.children).length){e+=
'<ul class="devsite-nav-list">';k=k.children;for(var l=k.length,m=0;m<l;m++){var p=k[m];e+='<li class="devsite-nav-item"'+(c&&p.index<a?" visible":"")+'><a href="#'+_ds.X(p.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.X(h)+"."+_ds.X(m)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.X(h)+"."+_ds.X(m)+'" track-metadata-link-destination="#'+
_ds.X(p.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.V(p.text)+"</span></a></li>"}e+="</ul>"}e+="</li>"}d&&(e=c?e+'<li class="devsite-nav-item devsite-apix-link"><a href="#try-it" class="devsite-nav-title"><span class="devsite-nav-text" tooltip>Try it</span></a></li>':e+'<button type="button" class="devsite-show-apix button-primary">Try it!</button>');c&&(e=e+'<li class="devsite-toc-toggle"><button type="button" class="button-flat devsite-nav-more-items material-icons" track-type="navigation" track-name="embeddedNavExpand" title="'+
_ds.Dj("Expand/collapse contents"),e+='"></button></li>');return(0,_ds.T)(e+"</ul>")},v4=function(){var a=_ds.R.call(this)||this;a.eventHandler=new _ds.Ll;a.K=new _ds.Tn;a.D=new Set;a.F=new Map;a.M=new _ds.Qn(function(){return void n4(a)},16);a.L=new _ds.Qn(function(){return void o4(a)},33);a.o=null;a.m=null;a.j=[];a.G=!1;a.C=null;a.Zb=!1;a.J=[];a.O(_ds.Qh(p4),_ds.Qh(q4),_ds.Qh(r4),_ds.Qh(s4),_ds.Qh(t4),_ds.Qh(u4));return a},w4=function(a){a.Zb||a.eventHandler.listen(document.body,"devsite-content-updated devsite-element-hidden devsite-element-visible devsite-page-loaded devsite-sticky-resize devsite-sticky-scroll".split(" "),
function(){a.L.Aa()});a.eventHandler.listen(document.body,"devsite-content-updated",function(){n4(a)})},x4=function(a){_ds.Q(a,function c(){var d=this,e,g,h,k;return _ds.D(c,function(l){switch(l.h){case 1:e=d;if(!("IntersectionObserver"in _ds.Gk())){l.H(2);break}d.C&&d.C.disconnect();g=document.querySelector("devsite-header");h=152;if(!g){l.H(3);break}return _ds.y(l,window.customElements.whenDefined("devsite-header"),4);case 4:(k=Number(g.getAttribute("top-row--height"))+Number(g.getAttribute("bottom-row--height")))&&
(h=k);case 3:d.C=new IntersectionObserver(function(m){m=_ds.r(m);for(var p=m.next();!p.done;p=m.next())p=p.value,p.isIntersecting?e.D.add(p.target):e.D.delete(p.target);e.L.Aa()},{rootMargin:h+"px 0px 0px 0px",threshold:[0,1]});case 2:d.K.resolve(),_ds.z(l)}})})},o4=function(a){return _ds.Q(a,function c(){var d=this;return _ds.D(c,function(e){if(1==e.h)return _ds.y(e,y4(d),2);if(d.m){var g="#"+d.m.id,h=encodeURI(g);g=d.F.get(g)||d.F.get(h);d.o!==g&&(d.o&&d.o.classList.remove("devsite-nav-active"),
g&&(g.classList.add("devsite-nav-active"),d.o=g))}_ds.z(e)})})},n4=function(a){if(!a.hasAttribute("disabled")){var b=document.querySelector("devsite-content .devsite-article-body");b?(a.Zb?a.classList.add("devsite-toc-embedded"):a.classList.add("devsite-toc"),z4(a,b),a.G=!0):a.hb()}},z4=function(a,b){var c=[],d=!1,e="";switch(a.getAttribute("depth")){case "1":e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents)";break;default:e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents), h3:not(.hide-from-toc):not(#contents):not(#table-of-contents)"}a.j=
[].concat(_ds.ya(b.querySelectorAll(e))).filter(function(h){return h.id&&h.dataset.text}).filter(function(h){return A4(h)});b=_ds.r(a.j.entries());for(e=b.next();!e.done;e=b.next()){var g=_ds.r(e.value);e=g.next().value;g=g.next().value;e={id:g.id,level:g.tagName.toLowerCase(),text:g.dataset.text,children:[],index:e};"h2"===e.level?(c.push(e),d=!0):d?c[c.length-1].children.push(e):c.push(e)}_ds.Sb(a.J,c,a.jk.bind(a))&&a.G||(c.length?(B4(a,c),a.show(),a.Zb||C4(a)):a.hb(),a.J=c)},y4=function(a){return _ds.Q(a,
function c(){var d=this,e,g,h,k,l,m,p,q;return _ds.D(c,function(t){switch(t.h){case 1:e=d;g=0;h=document.querySelector("devsite-header");if(!h){t.H(2);break}return _ds.y(t,window.customElements.whenDefined("devsite-header"),3);case 3:g=h.Hh();case 2:k=d.j.findIndex(function(u){return e.D.has(u)&&u.getBoundingClientRect().top>=g});l=d.j[k];if(!l){d.m&&d.m.getBoundingClientRect().top>window.innerHeight&&(m=d.j.indexOf(d.m),0<m&&(d.m=d.j[m-1]));t.H(0);break}return _ds.y(t,D4(d),5);case 5:p=t.j,q=l.getBoundingClientRect().top-
g,d.m=q>p&&0<k?d.j[k-1]:l,_ds.z(t)}})})},D4=function(a){return _ds.Q(a,function c(){var d,e,g,h;return _ds.D(c,function(k){if(1==k.h)return e=d=0,(g=document.querySelector("devsite-header"))?_ds.y(k,window.customElements.whenDefined("devsite-header"),3):k.H(2);2!=k.h&&(d=g.Hh(),e=g.Zp());h=window.innerHeight-d;return k.return(Math.max(e-d,Math.floor(h/5)))})})},C4=function(a){_ds.Q(a,function c(){var d=this,e,g,h;return _ds.D(c,function(k){if(1==k.h)return _ds.y(k,d.K.promise,2);if(!d.C)return k.return();
d.C.disconnect();d.D.clear();d.o&&d.o.classList.remove("devsite-nav-active");d.o=null;e=_ds.r(d.j);for(g=e.next();!g.done;g=e.next())h=g.value,d.C.observe(h);_ds.z(k)})})},A4=function(a){return _ds.bM.find(function(b){return!!_ds.ul(a,b,6)})||_ds.tl(a,"devsite-selector",null,6)||_ds.ul(a,"devsite-dialog",3)?!1:!0},B4=function(a,b){var c=_ds.Al(m4,{Os:b,Zb:a.Zb,pp:!!document.body.querySelector("devsite-apix, .devsite-apix"),Nq:5});b=_ds.r(c.querySelectorAll("a.devsite-nav-title"));for(var d=b.next();!d.done;d=
b.next()){d=d.value;var e=d.hash,g=encodeURI(d.hash);a.F.set(e,d);a.F.set(g,d)}_ds.Nk(a);a.Zb&&_ds.hi(a,"hidden","",c);a.appendChild(c);if(a.Zb){if(8<=a.getElementsByClassName("devsite-nav-item").length){b=_ds.r(a.querySelectorAll(".devsite-nav-show-all, .devsite-nav-more-items"));for(d=b.next();!d.done;d=b.next())a.eventHandler.listen(d.value,"click",function(){a.hasAttribute("expanded")?a.removeAttribute("expanded"):_ds.hi(a,"expanded","")});_ds.hi(a,"expandable","")}setTimeout(function(){c.removeAttribute("hidden")},
0)}};var p4=_ds.xa(["disabled"]),q4=_ds.xa(["has-toc"]),r4=_ds.xa(["hidden"]),s4=_ds.xa(["expandable"]),t4=_ds.xa(["expanded"]),u4=_ds.xa(["visible"]);_ds.w(v4,_ds.R);_ds.f=v4.prototype;_ds.f.connectedCallback=function(){this.Zb=this.hasAttribute("devsite-toc-embedded");n4(this);w4(this)};_ds.f.disconnectedCallback=function(){this.hb();this.G=!1;_ds.Rl(this.eventHandler)};
_ds.f.Hi=function(a){a=a&&"false"===a.toLowerCase();this.J=[];_ds.Nk(this);a?(_ds.hi(this,"disabled",""),this.hb()):(this.removeAttribute("disabled"),this.show(),this.M.Aa())};_ds.f.hb=function(){_ds.Nk(this);this.dispatchEvent(new CustomEvent("devsite-element-hidden",{bubbles:!0}));this.removeAttribute("visible");_ds.hi(this,"hidden","");if(!this.Zb){var a=document.querySelector(".devsite-main-content");a&&a.removeAttribute("has-toc")}};
_ds.f.show=function(){this.dispatchEvent(new CustomEvent("devsite-element-visible",{bubbles:!0}));this.removeAttribute("hidden");_ds.hi(this,"visible","");if(!this.Zb){var a=document.querySelector(".devsite-main-content");a&&_ds.hi(this,"has-toc","",a);x4(this)}};_ds.f.jk=function(a,b){var c=!0;if(a.children.length||b.children.length)c=_ds.Sb(a.children,b.children,this.jk.bind(this));return c&&a.id===b.id&&a.text===b.text};
_ds.n.Object.defineProperties(v4,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["max-height","offset"]}}});v4.prototype.renderUpdatedContent=v4.prototype.Hi;v4.prototype.disconnectedCallback=v4.prototype.disconnectedCallback;v4.prototype.connectedCallback=v4.prototype.connectedCallback;try{window.customElements.define("devsite-toc",v4)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteToc",a)};})(_ds_www);
