(function(_ds){var window=this;'use strict';var A7=function(a){a='<a href="//www.youtube.com/watch?v='+_ds.Sj(a.videoId)+'" class="devsite-video-placeholder"><img src="/_static/images/video-placeholder.svg" alt=""><span>';return(0,_ds.T)(a+"This resource may not be available in your region.</span></a>")},B7=function(a){return(0,_ds.T)('<video class="devsite-basic-video-player" controls><source src="//redirector.gvt1.com/edgedl/cn-devsite/'+_ds.X(a.videoId)+'.mp4" type="video/mp4"></video>')},C7=function(){var a=_ds.R.call(this)||
this;a.j=null;a.m=null;return a},D7=function(){C7.m=!1;var a=C7.j;delete C7.j;delete C7.h;a.forEach(function(b){return b.call()});delete window.onYouTubeIframeAPIReady},E7=function(){C7.m=!0;var a=C7.h;delete C7.j;delete C7.h;a&&a.forEach(function(b){return b.call()})},H7=function(a){a.parentNode.classList.contains("video-wrapper")&&a.setAttribute("inline-small","");var b=a.querySelector(".devsite-embedded-youtube-video");if(b){F7.forEach(function(d){b.hasAttribute("data-"+d)&&a.setAttribute(d,b.getAttribute("data-"+
d))});G7.forEach(function(d){b.hasAttribute("data-"+d)&&a.setAttribute(d,b.getAttribute("data-"+d))});if(b.src){var c=new _ds.Oi(b.src);G7.forEach(function(d){var e=_ds.hj(c,d);e&&a.setAttribute(d,e)})}a.removeChild(b)}};var F7="autohide autoplay controls embed_domain enablejsapi end hl rel showinfo start video-id".split(" "),G7=["listType","list"],I7=null,J7=!1;_ds.w(C7,_ds.R);_ds.f=C7.prototype;
_ds.f.connectedCallback=function(){if(DevsiteApp.hasFlagAccess(161)&&"cn"==_ds.qm().hostname.split(".").pop()){var a=_ds.Al(B7,{videoId:String(this.getAttribute("video-id"))});this.appendChild(a)}else{H7(this);C7.m&&this.wj();a=this.tm.bind(this);var b=this.wj.bind(this);void 0!==window.YT?a=!0:(C7.j||(C7.j=[]),C7.h||(C7.h=[]),C7.j.push(a),C7.h.push(b),I7||(_ds.xb("onYouTubeIframeAPIReady",D7),I7=_ds.um("//www.youtube.com/iframe_api"),I7.catch(E7)),a=!1);a&&this.tm()}};
_ds.f.tm=function(){var a=this,b=document.createElement("div");this.appendChild(b);var c={origin:_ds.qm().origin};F7.forEach(function(e){a.hasAttribute(e)&&(c[e]=a.getAttribute(e))});G7.forEach(function(e){a.hasAttribute(e)&&(c[e]=a.getAttribute(e))});var d={playerVars:c,events:{onReady:this.eq.bind(this),onStateChange:this.fq.bind(this),onError:this.bq.bind(this),onVideoProgress:this.gq.bind(this)}};this.hasAttribute("video-id")&&(d.videoId=this.getAttribute("video-id"));this.j=new YT.Player(b,d)};
_ds.f.attributeChangedCallback=function(a,b,c){if(this.j&&"action"===a)switch(c){case "play":this.j.playVideo();break;case "pause":this.j.pauseVideo();break;case "stop":this.j.stopVideo()}};
_ds.f.eq=function(a){if(void 0!==a&&void 0!==a.target){this.setAttribute("tabindex","0");a=a.target;var b=a.getVideoData().title;b&&this.setAttribute("aria-label","You are currently on an element that contains a YouTube video titled: "+b+". Continue tabbing to hear the contained options.");"play"===this.getAttribute("action")&&a.playVideo()}};
_ds.f.gq=function(a){if(void 0!==a&&void 0!==a.data&&void 0!==a.target){var b=a.data,c=a.target;a=c.getVideoData().video_id;var d=c.getDuration();c=c.getCurrentTime();this.dispatchEvent(new CustomEvent("devsite-youtube-progress",{detail:{videoId:a,progress:b,currentTime:c,duration:d},bubbles:!0}))}};
_ds.f.fq=function(a){if(void 0!==a&&void 0!==a.data&&void 0!==a.target){var b=a.data,c=a.target;a=c.getVideoData().video_id;var d=c.getCurrentTime();"number"===typeof d&&(d=Math.floor(d));c=c.getDuration();var e={videoId:a,currentTime:d,duration:c};switch(b){case YT.PlayerState.PLAYING:this.setAttribute("action","play");c=null===this.m?"Video Start":"Video Resume";this.dispatchEvent(new CustomEvent("devsite-youtube-playing",{detail:e,bubbles:!0}));break;case YT.PlayerState.PAUSED:this.setAttribute("action",
"pause");c="Video Paused";this.dispatchEvent(new CustomEvent("devsite-youtube-paused",{detail:e,bubbles:!0}));break;case YT.PlayerState.ENDED:this.removeAttribute("action");c="Video Finished";this.dispatchEvent(new CustomEvent("devsite-youtube-ended",{detail:e,bubbles:!0}));break;default:return}this.m=b;this.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:c,label:a,value:d},bubbles:!0}));b={eventData:JSON.stringify({name:c.replace(" ",
""),type:"youTubeVideo",metadata:{youTubeId:a,videoTime:d}})};this.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:b,bubbles:!0}))}};_ds.f.bq=function(){};_ds.f.wj=function(){var a=_ds.Al(A7,{videoId:String(this.getAttribute("video-id"))});this.appendChild(a)};_ds.f.disconnectedCallback=function(){this.j&&this.j.destroy()};
_ds.n.Object.defineProperties(C7,{m:{configurable:!0,enumerable:!0,get:function(){return J7},set:function(a){J7=a}},observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["action"]}}});C7.prototype.disconnectedCallback=C7.prototype.disconnectedCallback;C7.prototype.attributeChangedCallback=C7.prototype.attributeChangedCallback;C7.prototype.connectedCallback=C7.prototype.connectedCallback;try{window.customElements.define("devsite-youtube",C7)}catch(a){console.warn("devsite.app.customElement.DevsiteYouTube",a)};})(_ds_www);
